### ISSUE TITLE
`betti_number` for affine toric varieties

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1023]
The following code 
```julia
C = positive_hull([0 1; 1 1; 2 1])
X = AffineNormalToricVariety(C)
betti_number(X, 4)
```
produces the output `1`. But the output of 
```julia
toric_ideal(X)
```
says, that this variety is realized as the cone ``x*y-z^2=0``, which is contractible. 

These results suggest that the Betti numbers are not for singular homology, but for Borel-Moore homology, correct? I think that should be explained somewhere.

**Comment by HereAround** [comment]
@HechtiDerLachs:
 
I have just checked the computational results. All of the above is correct and there is no bug (to the best of my knowledge).

Our implementations follow the book by Cox-Little-Schenk. In stating from there, the Betti numbers are the dimension of the singular homology groups $H_i( X, Q)$, i.e. with rational coefficients.

I am very far from an expert about Borel-Moore homology, but judging from `appendix: Generalized Gysin Maps`, there is (often) a duality among the singular cohomology groups $H^i( X, Q)$ and Borel-Moore homology $H^BM_(2n-i)(X,Q)$.

Does this answer your question? If yes, I can make a PR to add this explanation to the documentation.

@lkastner: What do you think?

**Comment by lkastner** [comment]
Theorem 12.3.12 CLS only holds for complete and simplicial fans, but this example is not complete. Is this what you are using here?

**Comment by HereAround** [comment]
Thank you for spotting this Lars! This is indeed the result that I am using, but somehow I forgot about these conditions. I have prepared a corresponding PR (see below).

**Comment by HechtiDerLachs** [comment]
So the algorithms for the computation of Betti numbers in CLS are indeed only for complete toric varieties? 

On p. 582 in the section "Spectral Sequence of a Filtered Topological Space" they also consider non-compact varieties, but in that case, they switch to cohomology with compact support. That would have been my other guess apart from Borel-Moore homology since it behaves similar in many respects, see for example equation (12.3.4). 

I'm wondering: Can one make these spectral sequences with their boundary maps explicit from the cones/fans? In that case, it would be great to have that functionality also available for non-complete varieties! 

Btw: I first thought, this was an honest bug, but then, while filing this issue, I realized, that this might just be due to some faulty understanding of the material on my side. Anyway, I thought it might be worth to give you the feedback about the perception of an outsider.

**Comment by HereAround** [comment]
It is definitely good that you brought this up! For instance, it definitely improved the code (see the above PR). Thank you!

About the spectral sequences - I frankly don't know. I will (try to) read-up on the details at some point.

Is there an interesting application for the homologies of affine toric varieties that you would like to crack?

**Comment by HechtiDerLachs** [comment]
Indeed, there is. I've been working on singularities of functions on varieties with a finite decomposition into orbits via some algebraic group action. Toric varieties are a special case of the latter. If it was possible to trace the interplay of the (trivially computable) cohomology of the orbit throughout the process of taking unions of orbits, that would be amazing! With the techniques I had developed so far, this could be done only in special cases.

**Comment by fingolfin** [comment]
This was resolved:
```
julia> C = positive_hull([0 1; 1 1; 2 1])
Polyhedral cone in ambient dimension 2

julia> X = affine_normal_toric_variety(C)
Normal toric variety

julia> betti_number(X, 4)
ERROR: ArgumentError: Currently, the computation of Betti numbers is limited to complete and simplicial toric varieties
```
