### ISSUE TITLE
adjust doc for toric varieties to OSCAR standard

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#1039]
I suggest to change / add to the file [intro.md](https://github.com/oscar-system/Oscar.jl/blob/master/docs/src/ToricVarieties/intro.md).

(1) "Toric geometry in Julia" should be changed to "Toric Geometry" or "Toric Varieties".

(2) This page should comprise some basic defintions.  See [another intro.md](https://github.com/oscar-system/Oscar.jl/blob/master/docs/src/PolyhedralGeometry/intro.md) for comparison.

(3) The directory structure below `docs/src` should resemble the structure below `src`.

**Comment by lkastner** [comment]
> I suggest to change / add to the file [intro.md](https://github.com/oscar-system/Oscar.jl/blob/master/docs/src/ToricVarieties/intro.md).
> 
> (1) "Toric geometry in Julia" should be changed to "Toric Geometry" or "Toric Varieties".
> 
I removed this title as in the other intros

> (2) This page should comprise some basic defintions. See [another intro.md](https://github.com/oscar-system/Oscar.jl/blob/master/docs/src/PolyhedralGeometry/intro.md) for comparison.
> 
Done

> (3) The directory structure below `docs/src` should resemble the structure below `src`.

Unclear to me. Is this just about the `LineBundle`'s that are `ToricLineBundle`'s in the docs?

**Comment by micjoswig** [comment]
> > (3) The directory structure below `docs/src` should resemble the structure below `src`.
> 
> Unclear to me. Is this just about the `LineBundle`'s that are `ToricLineBundle`'s in the docs?

No, but I just realize that this is more confusing than I even thought.

```
$ ls src
Combinatorics  GAP  Geometry  Groups  imports.jl  Manifest.toml  Modules  NumberTheory  Oscar.jl  PolyhedralGeometry  printing.jl  Rings  ToricVarieties
$ ls docs/src
AlgebraicGeometry  CommutativeAlgebra      Experimental  General  index.md         LinearAlgebra   NumberTheory        references.md  ToricVarieties
Combinatorics      DeveloperDocumentation  Fields        Groups   InvariantTheory  manualindex.md  PolyhedralGeometry  Rings
```

There is a third hierarchy, namely the one shown in the docs.  there the toric varieties are below "Algebraic Geometry".  This is what I meant.  I guess this requires a major cleanup.  It is not specific to toric varieties.
