### ISSUE TITLE
msolve crashing for non-real solutions

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1040]
@ederc: Is the following behaviour normal? I wasn't expecting it from reading the docstring:
```julia
julia> Qx, (x,) = PolynomialRing(QQ, ["x"])
(Multivariate Polynomial Ring in x over Rational Field, fmpq_mpoly[x])

julia> I = ideal(Qx, [x^2 + 1])
ideal(x^2 + 1)

julia> msolve(I)
signal (11): Segmentation fault: 11
in expression starting at REPL[5]:1
msolve_julia at /Users/blurb/.julia/artifacts/bcee5c4d85a2eec4263cee38a2386ddf16f8b661/lib/libmsolve-0.1.7.dylib (unknown line)
```

Since someone else could not reproduce it:
```julia
julia> versioninfo(verbose = true)
Julia Version 1.8.0-DEV.1351
Commit 05d3e84821 (2022-01-20 05:22 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  uname: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64 arm
  CPU: Apple M1:
              speed         user         nice          sys         idle          irq
       #1    24 MHz     261704 s          0 s     172888 s    1867380 s          0 s
       #2    24 MHz     243514 s          0 s     153839 s    1904568 s          0 s
       #3    24 MHz     216658 s          0 s     130809 s    1954455 s          0 s
       #4    24 MHz     195624 s          0 s     115076 s    1991221 s          0 s
       #5    24 MHz     288530 s          0 s      71363 s    1942028 s          0 s
       #6    24 MHz     240423 s          0 s      54656 s    2006842 s          0 s
       #7    24 MHz     207576 s          0 s      41417 s    2052928 s          0 s
       #8    24 MHz     187701 s          0 s      34598 s    2079623 s          0 s
  Memory: 16.0 GB (424.0625 MB free)
  Uptime: 547871.0 sec
  Load Avg:  1.3701171875  1.517578125  1.4775390625
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, cyclone)
```
(Same error for julia 1.6.3 and x86 binaries for macOS.)

**Comment by ederc** [comment]
Yes, that's known and already fixed in the dev version of msolve. We plan a new release in the next 1-2 weeks with other features like saturation and elimination order which will then fix the above bug.

**Comment by thofma** [comment]
I could not reproduce it (obviously), but @FabianMaeurer reported that it did not return non-real solutions? Is this normal?

**Comment by ederc** [comment]
Yes, msolve is doing a real root isolation and returns only real roots. You can use the rational parametrization if you want to compute non-real roots. But this is stated explicitly in the docstring: 

> return a pair p,r where p is the rational parametrization of the solution set and r represents the real roots of I 

Still the above segfault is a bug and this is fixed in the next release of msolve.

**Comment by thofma** [comment]
Ah, oops, I missed that :)

Can you give a quick example on how to construct all the complex solutions? Or is it more involved?

**Comment by ederc** [comment]
This is a bit more involved. I still plan to add this to Oscar, but if you wish to have it right now take a look at the (a bit outdated, sorry) [msolve docu](https://msolve.lip6.fr/downloads/msolve-tutorial.pdf). In Chapter 2 we explain how to handle the rational parametrization to compute the solution set.

But maybe it is better to discuss this in more detail on gather.

**Comment by thofma** [comment]
Thanks, I see. I might play around with it a bit and will come back to you if I have questions.
