### ISSUE TITLE
ToricVarieties: Use properties of Oscar fans

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1055]
I am not sure if this is a problem (as in needs fixing) or if it is optimized and I need to understand it. Hence, this here aims towards a discussion and, if necessary/reasonable a possibly improved design.

Currently, if we have a toric_variety `v` and want to know if it is `smooth`, then we issue:

> pm_object(v).SMOOTH

Inspired from the theory, one might be tempted to replace this by

> issmooth(fan(v))::Bool

This pattern repeats for essentially all properties of toric varieties:
- `hastorusfactor(v::AbstractNormalToricVariety)`
- `isaffine(v::AbstractNormalToricVariety)`
- `iscomplete(v::AbstractNormalToricVariety)`
- `isfano(v::AbstractNormalToricVariety)`
- `isgorenstein(v::AbstractNormalToricVariety)`
- `issimplicial(v::AbstractNormalToricVariety)`
- `issmooth(v::AbstractNormalToricVariety)`
- `isnormal(v::AbstractNormalToricVariety)`
- `isorbifold(v::AbstractNormalToricVariety)`
- `isprojective(v::AbstractNormalToricVariety)`
- `is_q_gorenstein(v::AbstractNormalToricVariety)`

Some of these are currently supported for fans in `Oscar` (e.g. `issmooth`) and some others are not (e.g. `issimplicial`). Here are the questions that I have in this regard:
- Does it make sense to support all these properties for fans?
- Would the above change towards properties of fans seem superior to direct calls to `Polymake`? Or are direct calls to `Polymake` superior (e.g. because of caching issues, faster runtime etc.)?

cc @lkastner @benlorenz

**Comment by lkastner** [comment]
>     * Does it make sense to support all these properties for fans?

No. Polyhedral fans do not have all of these properties in polymake.

>     * Would the above change towards properties of fans seem superior to direct calls to `Polymake`? Or are direct calls to `Polymake` superior (e.g. because of caching issues, faster runtime etc.)?

Going via the `fan` messes with polymake's internal logic, as some properties might already be computed for the toric variety, but not for the fan. I also don't like caching the `:fan`, as usually it would duplicate all the information already stored in the toric variety. Luckily in this case it is only a pointer.

**Comment by HereAround** [comment]
I see. Thank you for elaborating.
