### ISSUE TITLE
Release Oscar 0.8.1

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1082]
I'd like to release Oscar 0.8.1 really soon (tomorrow? end of this week?), so we can verity that it now passes Julia's Nanosoldier tests (which would be good because it'd mean that if certain big changes in Julia master cause regressions in Oscar, they'll be noticed earlier).

If you have reasons to delay this, please comment here

CC @fieker @wdecker @thofma @micjoswig

**Comment by micjoswig** [comment]
I am all in favor!

**Comment by thofma** [comment]
Yes, sounds good!
