### ISSUE TITLE
Allow *(::Vector/Matrix{fmpq}, ::fmpq/fmpz), //(::Vector/Matrix{fmpq}, ::fmpq/fmpz) and *(::Vector/Matrix{fmpz}, ::fmpz)

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#1088]
I think the following operations should be implemented the sake of user-friendliness, especially if `fmpq` and `fmpz` are the go-to types for rational and integer numbers in OSCAR:

- `*(::Vector{fmpq}, ::fmpq)`, `*(::Vector{fmpq}, ::fmpz)`, `*(::Matrix{fmpq}, ::fmpq)`, `*(::Matrix{fmpq}, ::fmpz)`
-  `//(::Vector{fmpq}, ::fmpq)`, `//(::Vector{fmpq}, ::fmpz)`, `//(::Matrix{fmpq}, ::fmpq)`, `//(::Matrix{fmpq}, ::fmpz)` 
- `*(::Vector{fmpz}, ::fmpz)`, `*(::Matrix{fmpz}, ::fmpz)`

So that for example following operations are possible:

```
w = [fmpq(1), fmpq(0), fmpq(0)];
# the following operations do not work
w*fmpq(1)
fmpq(1)*w
w *= fmpq(1)
w//fmpq(1)
w //= fmpq(1) 
```

**Comment by thofma** [comment]
Not sure this will be implemented in the near future. Note that everything is already possible by doing `.*`, `.//`, `.*=` etc. The `.` is the broadcasting operator in julia. See for example `"a" * ["b", "c"]` versus `"a" .* ["b", "c"]`.

**Comment by YueRen** [comment]
I see, I also think it would be nice to have for the sake of consistency, since the following does work:

```
w = [fmpq(1), fmpq(0), fmpq(0)];
w*1
1*w
w *= 1
w//1
w //= 1 
```

**Comment by alexej-jordan** [comment]
The working methods you mentioned each are defined in `Base` for a combination of an `AbstractArray` and a `Number`, which actually refer to a special broadcasting function. Now `fmpq` is not derived from `Number`; its super-types are some algebraic abstract types. I am unsure about the (dis-)advantages arising from this implementation, I just want to point out why you experience this inconsistency.

**Comment by fingolfin** [comment]
All of this seems to work now:
```
julia> w = [fmpq(1), fmpq(0), fmpq(0)];

julia> w*fmpq(1)
3-element Vector{fmpq}:
 1
 0
 0

julia> fmpq(1)*w
3-element Vector{fmpq}:
 1
 0
 0

julia> w *= fmpq(1)
3-element Vector{fmpq}:
 1
 0
 0

julia> w//fmpq(1)
3-element Vector{fmpq}:
 1
 0
 0

julia> w //= fmpq(1)
3-element Vector{fmpq}:
 1
 0
 0

```
