### ISSUE TITLE
Group homomorphisms without checks

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1098]
It can be expensive to check if a group homomorphism defined by images of generators is well defined.
In many cases these checks are not necessary, for instance the inclusion of a subgroup, projections in a direct product, kernel, cokernel homomorphisms etc.
So we should provide `hom` with a keyword `check=true` and set it to false in a priori well defined homomorphisms.

**Comment by fieker** [comment]
On Wed, Feb 16, 2022 at 02:07:12PM -0800, simonbrandhorst wrote:
> It can be expensive to check if a group homomorphism defined by images of generators is well defined.
> In many cases these checks are not necessary, for instance the inclusion of a subgroup, projections in a direct product, kernel, cokernel homomorphisms etc.
> So we should provide `hom` with a keyword `check=true` and set it to false in a priori well defined homomorphisms.
> 
The "default" is to have the check argument and set it to true...

**Comment by ThomasBreuer** [comment]
As far as I understand, @simonbrandhorst suggests to change the method `hom(G::GAPGroup, H::GAPGroup, gensG::Vector, imgs::Vector)` such that `check = false` is supported (and has the effect to call `GAP.Globals.GroupHomomorphismByImagesNC` instead of `GAP.Globals.GroupHomomorphismByImages`).

**Comment by simonbrandhorst** [comment]
Indeed. That is what I mean. And further in certain situations, e.g. the creation of a subgroup, oscar provides the inclusion morphism. We know a priori that the inclusion is well defined, so in  the subgroup constructor `hom` should be called with `check=false`.

**Comment by ThomasBreuer** [comment]
Fine. I will provide a pull request for this change.

**Comment by simonbrandhorst** [comment]
Thank you Thomas.
