### ISSUE TITLE
Change the order of arguments in `MapFromFunc`

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1104]
Just a little heads-up. If no one objects I will change `MapFromFunc(f, [g], C, D)` to `MapFromFunc(C, D, f, [g])` . I don't expect this to be a controversial change. I will make sure to make the necessary adjustments.

CC: @fieker @ThomasBreuer

**Comment by fieker** [comment]
On Thu, Feb 17, 2022 at 11:39:41AM -0800, Tommy Hofmann wrote:
> Just a little heads-up. If no one objects I will change `MapFromFunc(f, [g], C, D)` to `MapFromFunc(C, D, f, [g])` . I don't expect this to be a controversial change. I will make sure to make the necessary adjustments.
> 
> CC: @fieker @ThomasBreuer 
> 
Makes more sense than the old convention

**Comment by ThomasBreuer** [comment]
Yes, the new syntax is nicer.
