### ISSUE TITLE
Graded module morphism inconsistency

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1112]
We are trying to make the maps enforce `parent(x) === domain(f)` whenever `f(x)` is called. There were some easy fixes in Oscar when this was violated, but the graded module have some internal inconsistency which makes it more complicated to fix.

If `f` is a `FreeModuleHom_dec`, then `f.f` (aka `forget_decoration(f)`) is *not* a `FreeModuleHom` morphism from `forget_decoration(domain(f))` to `forget_decoration(codomain(f))`, but it is a `FreeModuleHom` morphism from `domain(f)` to `codomain(f)`.

The inconsistency is exposed when `H, mH = hom(F, G)` for graded modules is computed respectively when `mH` is applied (or its preimage function via `module_elem(H, f)`, where `f` is a `FreeModuleHom_dec`). In this case, `hom(forget_decoration(F), forget_decoration(G))` is computed and the result is applied to `f.f`. But this is of course nonsense, since `f.f` has not domain `forget_decoration(F)` nor codomain `forget_decoration(G)`.

The obvious fix would be changing
https://github.com/oscar-system/Oscar.jl/blob/fc0adeec12b90c69195ceb7ce695b4c18c7c173b/src/Modules/ModuleTypes.jl#L544
to do
```julia
 f = FreeModuleHom(forget_decoration(F),forget_decoration(G),forget_decoration.(a)) 
```
but this does not work because `f.f` than has the wrong type.

I know a fix but it consists mainly of deleting some tests file. So it would be good if this could be fixed by some people familiar with the module code. CC: @AlexD97 @jankoboehm

**Comment by AlexD97** [comment]
I'm not quite sure, if I understood the problem completely, that is, if it's a general design flaw or just this problem in `hom(F, G)`. In the latter case, #1113 should fix this.

**Comment by thofma** [comment]
What I don't understand is why are there two incompatible ways used to work with the ungraded morphisms between `F` and `G`. Maybe more concretely:

1. Why are `FreeModuleHom_dec` between `F` and `G` represented internally by a `FreeModuleHom(F, G)` and not by `FreeModuleHom(forget_decoration(F), forget_decoration(G))`? The `hom` implementation assumes that and it also seems like a canonical choice?

Or

2. Why doesn't `hom(F, G)` determine (as a first step) the non-graded morphisms between `F` and `G` if this is how `FreeModuleHom_dec` are represented internally?

I will try your fix and if it works, this will be good enough for me.

**Comment by AlexD97** [comment]
I think you are right. I renamed `forget_decoration` to `forget_decoration_on_morphism` and `forget_decoration_completely` to `forget_decoration` (see  #1120).
