### ISSUE TITLE
Why is it called `MPolyRing_dec`?

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1119]
I'm almost afraid to ask, but why are all the "decorated" types called `..._dec` instead of `Dec`? For example `MPolyRing_dec`, `MPolyElem_dec`, etc.
Assuming we all agree that this conflicts with our naming conventions, I could open a pull request to change it.
What's the best practice for such changes? `const` the old types to the new ones? `@deprecate` them?

**Comment by wdecker** [comment]
I am not familiar with conventions. However, if this is to be discussed, we should at the same rethink the concept of decorated rings as such and may be change it to just graded rings.

**Comment by jankoboehm** [comment]
We will need the filtered case in various settings (singularities and lots more), so we should definitely keep it somehow. There also went quite some work into it in particular for modules. One could split into different types for graded and filtered. That will make things more transparent, but there is of course a lot of code overlap between the two cases. So one might again end up with some decorated type behind everything.

**Comment by wdecker** [comment]
Is there already some piece of code where I could see the use of the filtered case?

**Comment by thofma** [comment]
@joschmitt If it is not urgent, I would wait with the renaming PR.

**Comment by joschmitt** [comment]
> @joschmitt If it is not urgent, I would wait with the renaming PR.

No problem. I wasn't aware of a bigger issue behind this.

**Comment by fieker** [comment]
On Tue, Feb 22, 2022 at 06:00:16AM -0800, Johannes Schmitt wrote:
> I'm almost afraid to ask, but why are all the "decorated" types called `..._dec` instead of `Dec`? For example `MPolyRing_dec`, `MPolyElem_dec`, etc.
> Assuming we all agree that this conflicts with our naming conventions, I could open a pull request to change it.
> What's the best practice for such changes? `const` the old types to the new ones? ***@***.***` them?
> 
I felt like it when I did this. No reason at all. Feel free to change at
will

**Comment by joschmitt** [comment]
Closed via #1972 .
