### ISSUE TITLE
Inconsistent definition of irreducible secondary invariants

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1121]
For everyone interested in the invariant theory of finite groups: I'm confused as to how "irreducible secondary invariants" are defined. Kemper--Steel say that a secondary invariant is irreducible "if it cannot be written as a polynomial expression in the primary invariants and the other secondary invariants". But in their algorithm a secondary invariant is irreducible if it cannot be written as a power product of the other secondary invariants which is a stronger condition.

I realized now that I followed the first definition in the modular case and the second one in the non-modular one in my implementation.
I think the second one is the better one, when one wants to compute the relations between the invariants. However, if we also want to do it like this in the modular case, then the irreducible secondary invariants are (in general) either all the secondary ones besides 1 (that's what Magma does) or the computation of the secondary invariants will be somewhat slower.
As I am mostly interested in getting a presentation of the invariant ring as an affine algebra and for this a particularly small number of generators is always better, I would still prefer the last approach. Then again, I'm not really interested in the modular case...

In general, "irreducible secondary invariant" does not appear to be a strongly established term. In the book by Derksen and Kemper it is never mentioned and Magma only promises a subset of the secondary invariants which generate the invariant ring as an algebra over the algebra generated by the primary invariants.
Therefore I would like to discuss, what people most likely expect to get, before I start changing anything in my implementation.

**Comment by thofma** [comment]
@wdecker any ideas?

**Comment by joschmitt** [comment]
He already talked to me about it.
