### ISSUE TITLE
Polyhedron intersection performance

### ISSUE THREAD

**Issue by XLVII-47** [oscar-system/Oscar.jl#1129]
sagemath polyhedron intersection operation faster than oscar implementation, isn't it expected to be faster in julia?

**Comment by thofma** [comment]
Can you provide the specific example and the timings?

**Comment by XLVII-47** [comment]
![123](https://user-images.githubusercontent.com/58266985/156033472-1f1302a2-1794-4ea7-a7e7-ad71beb067c8.PNG)

**Comment by thofma** [comment]
Note that the first time includes compilation time and all subsequent calls will be faster:
```julia
julia> @time intersect(P, P) == P
  0.161580 seconds (512.19 k allocations: 30.823 MiB, 75.76% compilation time)
true

julia> @time intersect(P, P) == P
  0.024527 seconds (5.01 k allocations: 42.281 KiB)
```
To avoid this noise, it is best to benchmark using the `BenchmarkTools` package:
```julia
julia> using BenchmarkTools

julia> @btime intersect(P, P) == P
  16.313 ms (5015 allocations: 42.28 KiB)
true
```
In Sage I get
```python
sage: %time P.intersection(P) == P
CPU times: user 5.56 ms, sys: 378 µs, total: 5.94 ms
Wall time: 5.58 ms
```
So it is a factor 3 slower on my machine.
