### ISSUE TITLE
Implement `describe(::GrpAbFinGen)`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1132]
See also #987

**Comment by fingolfin** [comment]
@ThomasBreuer this is probably a one liner now: take the group, convert it to an isomorphic GAP group, and call `describe` on that.

If you can provide the code for that, I can add it to what I am writing right now for `describe` on general GAP groups. PR coming up

**Comment by ThomasBreuer** [comment]
@fingolfin  `describe(Oscar._isomorphic_gap_group(G)[1])` would work.
But this yields the description as a *multiplicative* group.
If we want the additive notation in the case of abelian groups, we can compute a nice output from what `GAP.Globals.AbelianInvariants` returns; or better, we use directly `elementary_divisors(G)`, without transfering the group to GAP.

**Comment by fingolfin** [comment]
OK, makes sense.
