### ISSUE TITLE
Something noisy in the groups code

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1141]
I was doing some isomorphism tests between matrix groups over Q and received:
```
#I  Forcing finiteness test
```
multiple times. Can this be suppressed? I don't know where this is coming from.

CC: @ThomasBreuer

**Comment by ThomasBreuer** [comment]
These messages can be suppressed by calling
```
GAP.Globals.SetInfoLevel(GAP.Globals.InfoWarning, 0)
```
The message is shown by GAP's isomorphism fest for two groups if at least one of the groups does not yet store whether it is finite, and if the info level of `InfoWarning` is at least 1 (which is the default).

**Comment by thofma** [comment]
Can we just do this when starting Oscar?

**Comment by fingolfin** [comment]
We could but I'd rather fix the cause not the symptom :-). Can you provide an example triggering this?

**Comment by thofma** [comment]
I think the cause is that GAP is allowed to print some info, which we don't want I think. At least we have this stance for the other parts of Oscar.

PS: I can't isolate the example triggering this right now.

**Comment by ThomasBreuer** [comment]
@fingolfin In GAP, just form a matrix group in characteristic zero, for example `Group( [[E(4)]] )`, and ask for `IsomorphismGroups(G, G)`.

The function first checks for finiteness, thus one can avoid the warning by computing the finiteness flag before calling the isomorphism test.
The warning just tells the user that something expensive is going on. Such warnings make sense mainly in an interactive GAP session.

If we decide to disable the `InfoWarning` messages in Oscar then I think we should set also the other info levels to zero.

**Comment by fingolfin** [comment]
Sure but I don't care about that pure GAP situation but rather triggers from Oscar

**Comment by ThomasBreuer** [comment]
@fingolfin Here is a translation to Oscar.
```
julia> K, z = CyclotomicField(4);

julia> G = matrix_group([matrix(K, 1, 1, [z])]);

julia> isisomorphic(G, G);
#I  Forcing finiteness test
```
