### ISSUE TITLE
Can we get the more of the small group database?

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1150]
At the moment I get:
```
ERROR: Error thrown by GAP: Error, the group identification for groups of size 1536 is not available at /Users/blub/.julia/packages/GAP/lK1LP/gaproot/v1.9/pkg/SmallGrp-1.4.2/gap/small.gi:314 called from
<function "IdGroup generic method for groups">( <arguments> )
 called from read-eval loop at *defin*:0
```
I think this does not happen with vanilla Magma or Sage. Can we also make this work here?

CC: @ThomasBreuer @fingolfin

**Comment by fingolfin** [comment]
Identification for order 3*512=1536 is simply not available in GAP.

There is no explicit limitation here, we export "everything" as far as it is available in GAP.

**Comment by ThomasBreuer** [comment]
In Magma V2.24-10, I get the following.
```
> G:= SmallGroup( 1536, 5 );
> IdentifyGroup( G );

>> IdentifyGroup( G );
                ^
Runtime error: Unable to identify groups of order 1536
```
Should we perhaps catch the GAP error, and give an Oscar error message?

**Comment by thofma** [comment]
Ah oops, my bad, I misread the error message.
