### ISSUE TITLE
Manual: start page has a link to "Introduction" which surprisingly links to "Groups: Introduction"

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1155]
I think this is an automatic feature, where each section has a link to the next; which is nice. But when one is on https://oscar-system.github.io/Oscar.jl/dev/ and sees this, I think one expects to be lead to an introduction to Oscar, not to Groups.

<img width="862" alt="Screenshot 2022-03-09 at 14 19 50" src="https://user-images.githubusercontent.com/241512/157449594-6eda117e-779d-47ae-a9ad-ae8018400040.png">

Some potential remedies:
- insert an actual Oscar intro (yay)
- get rid of this link somehow
- change the link to make it clearer that this is a link to the next section, which is about groups...

**Comment by lkastner** [comment]
I moved the `General` section to the top in #1223, so now the next page is the architecture. I think once an introduction is written it should go into the `General` section anyway, so this sounds like an ok compromise.
