### ISSUE TITLE
Add instructions to `README.md` for using development version

### ISSUE THREAD

**Issue by FriedrichRober** [oscar-system/Oscar.jl#1193]
We have information and installation instructions for using a released version of Oscar in Julia,
but I cannot find information on how to use the development version of Oscar in Julia.

**Comment by fingolfin** [comment]
Take a look at https://oscar-system.github.io/Oscar.jl/dev/DeveloperDocumentation/new_developers/, does that help? We could certainly link to it explicit in the README (it is quite new)

**Comment by FriedrichRober** [comment]
Yes, this is exactly what I was looking for. Then a link in the README would be quite helpful.

**Comment by FriedrichRober** [comment]
I have a suggestion for the documentation. Maybe we should mention `]status` and `Revise` in the documentation or provide a link to [Julia Pkg](https://pkgdocs.julialang.org/v1/managing-packages/)? This is how I figured out how to develop with Oscar.
