### ISSUE TITLE
Generators of fraction field

### ISSUE THREAD

**Issue by voggesbe** [oscar-system/Oscar.jl#1195]
I would like to be able to get the generators of a fraction field defined from a polynomial ring, e.g.
```julia
P,p=PolynomialRing(QQ,["x","y"])
F=FractionField(P)
```
I would like `gens(F)` to return x and y, and `F[1]` to return x, `F[2]` to return y

**Comment by tthsqe12** [comment]
I am not sure if we can put this into oscar, but you easily extend the definitions on your own:
```julia
function gen(R::AbstractAlgebra.Generic.Frac{T}) where T <: MPolyElem
    return map(R, gens(base_ring(R)))
end

function gens(R::AbstractAlgebra.Generic.Frac{T}, i::Int) where T <: MPolyElem
    return R(gen(base_ring(R), i)))
end
```

**Comment by thofma** [comment]
@tthsqe12 what would be the specific reason against adding it?

**Comment by tthsqe12** [comment]
No specific reason, just seems like an adhoc extension of the gen function.

**Comment by tthsqe12** [comment]
Also, `gen` seems like it should be a function for the `FunctionField` object. Since we don't have multivariate function fields, it looks like the fraction field is taking its place. So, if no one else objects, we could add the requested functions to oscar.
