### ISSUE TITLE
Groups: for conjugacy, have a function which only tests conjugacy, and one which tests conjugacy and returns a conjugator

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#120]
See here https://github.com/oscar-system/Oscar.jl/pull/114/files#r444881452 and here https://github.com/oscar-system/Oscar.jl/pull/114/files#r446875954

**Comment by fingolfin** [comment]
@ThomasBreuer I believe this is complete now, we have `is_conjugate` and `is_conjugate_with_data` ?

**Comment by ThomasBreuer** [comment]
Yes, I think so: We have the two functions for the cases of
- a group and two group elements,
- a group and two groups,
- a G-set and two elements of a G-set.
