### ISSUE TITLE
Wanted: discrete logarithm for finite field elements

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1205]
It'd be good to have a function `disc_log` or `discrete_logarithm` or whatever. For my purposes the inputs would be elements of a finite field. Of course the case where logarithm does not exist should be covered. E.g. by returning `nothing` or throwing an exception or returning two values (either `true, the_log` or `false, 0` or something like that).

Don't worry about doing the world best implementation. This is what you need to beat (for all finite fields):
```julia
# TODO very bold discrete log, waiting for a better one. Don't try with large fields!!
# return g such that a^g = b
function _disc_log(a,b)
   for g in 0:order(parent(a))
      if a^g==b
         return g
      end
   end
   error("Second element is not a power of the first one")
end
```

**Comment by thofma** [comment]
As a first step, we could just wrap `disc_log_bs_gs` or `disc_log_ph` from Hecke.

**Comment by fieker** [comment]
I'd inclined to 
 - wrap what we have (and use our news HiWi to include their FaPra)
 - rename to log and log(gen, elem)

**Comment by fingolfin** [comment]
@thofma That would be most helpful. You say "or", so which should be wrapped?

A naive implementation for finite field elements:
```julia
function disc_log(b::T, x::T) where {T <: FinFieldElem}
  @assert parent(b) === parent(x)
  return disc_log_bs_gs(b, x, order(parent(b)))
end
```
What do we want this to do if the discrete logarithm does not exist? Right now it throws an error:
```
julia> F = GF(3,4)
Finite field of degree 4 over F_3

julia> disc_log(gen(F), rand(F))
21

julia> disc_log(one(F), gen(F))
ERROR: "disc_log failed"
Stacktrace:
 [1] disc_log_bs_gs(a::fq_nmod, b::fq_nmod, o::fmpz)
   @ Hecke ~/.julia/packages/Hecke/96GT7/src/Misc/UnitsModM.jl:383
 [2] disc_log(b::fq_nmod, x::fq_nmod)
   @ Main ./REPL[62]:3
 [3] top-level scope
   @ REPL[68]:1
```

**Comment by thofma** [comment]
I would be happy with throwing an error.
