### ISSUE TITLE
Document mpoly stuff

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#123]
It would be nice if the MPoly code written by @fieker was hooked up in the Oscar.jl manual

**Comment by fingolfin** [comment]
at least I don't see anything about it on https://oscar-system.github.io/Oscar.jl/dev/ not even things like `eliminate` for which there are already docstrings

**Comment by fingolfin** [comment]
More broadly I also wonder what would be a good way to point to the documentation for all the stuff we import from Hecke...

**Comment by fieker** [comment]
On Wed, Jul 08, 2020 at 06:40:24AM -0700, Max Horn wrote:
> It would be nice if the MPoly code written by @fieker was hooked up in the Oscar.jl manual
> 

I fully agree....

**Comment by fieker** [comment]
On Wed, Jul 08, 2020 at 06:41:54AM -0700, Max Horn wrote:
> More broadly I also wonder what would be a good way to point to the documentation for all the stuff we import from Hecke...

THis are deficiencies in the Julia doc-system... I think it is difficult
to fully "include" foreign stuff, but maybe that is s.th. for Rafael to
look into (as th elocal Julia Guru?)

Of course, even Hecke could have more documentation...

**Comment by fingolfin** [comment]
@rfourquet do you have any idea whether/how one can include the manual of one package into another? Julia itself seems to do something like that for some of their "standard" packages? Or is that done via copy&paste?

**Comment by thofma** [comment]
I don't see where julia does this. And I don't think this is possible by default in Documenter.jl. They just include a ton of markdown files https://github.com/JuliaLang/julia/blob/master/doc/make.jl as usual.

Also, what is "the" manual of a package? Just the html files?

**Comment by rfourquet** [comment]
> include the manual of one package into another? 

I don't think it's possible, but am no expert (I asked on Julia's slack few days ago but got no answer).

**Comment by fingolfin** [comment]
I'd say this is covered nicely now, see https://oscar-system.github.io/Oscar.jl/dev/CommutativeAlgebra/intro and so on
