### ISSUE TITLE
conversino Oscar-> Gap incomplete...

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#1237]
```julia> elements(o)
3-element Vector{Any}:
 Set([2, 3, 1])
 Set([5, 4, 6])
 Set([7, 9, 8])

julia> map(GAP.GapObj, ans)
ERROR: UndefKeywordError: keyword argument recursive not assigned
Stacktrace:
 [1] julia_to_gap(obj::Set{Int64})
   @ GAP ~/.julia/dev/GAP/src/julia_to_gap.jl:88
 [2] julia_to_gap(obj::Set{Int64}, recursion_dict::IdDict{Any, Any}; recursive::Bool)
   @ GAP ~/.julia/dev/GAP/src/julia_to_gap.jl:89
```

**Comment by fingolfin** [comment]
It will always be incomplete. There are infinitely many types, and we won't ever be able to support all (for many, it is not even clear what "support" means).

There is no "set" type in GAP, but I can add a conversion function which will turn  sets into sorted lists. Of course that means it won't work correctly for all Julia set types, only for those where the elements support a total ordering. But I am guessing that might be sufficient for your needs, at least based on the example you give...
