### ISSUE TITLE
Make `G[:]` an alias for `gens(G)`?

### ISSUE THREAD

**Issue by mgkurtz** [oscar-system/Oscar.jl#1249]
In general, I expect `G[:]` to yield a vector of all `G[i]`. So I’m puzzled not to get `gens(G)` when typing `G[:]` for some group or ring `G`.

**Comment by fieker** [comment]
On Thu, Apr 07, 2022 at 04:07:55AM -0700, Markus Kurtz wrote:
> In general, I expect `G[:]` to yield a vector of all `G[i]`. So I’m puzzled not to get `gens(G)` when typing `G[:]` for some group or ring `G`.
> 
Actually this is tricky. You just (correctl! thanks!) implemented an
iterator for a certain finite ring. Thus one might also expect
R[i] to give the i-th element.
So for a group, which is also iterable, there is an ambiguity.

Note: this is actually independet of your question. G[:] is not there as
it was never missed.

**Comment by thofma** [comment]
Why is it suddenly tricky? The ambiguity was introduced a long time ago, since abelian groups have always been iteratable and we added `G[i]` for those at the same time.

**Comment by fieker** [comment]
On Fri, Apr 08, 2022 at 12:51:48AM -0700, Tommy Hofmann wrote:
> Why is it suddenly tricky? The ambiguity was introduced a long time ago, since abelian groups have always been iteratable and we added `G[i]` for those at the same time.
>
Its not sudden indeed. And abelian groups we even could implement an
i-th element...

**Comment by fingolfin** [comment]
A detour: 
TBH I never liked the "feature" of accessing the i-th generator as `G[i]`, precisely because I was wary that this would confuse people esp. for things that are "iterable" or even "enumerable". 

Of course one can do hacks, like "With `G[i]` one can enumerate the group, but we arrange things so that the first few such entries coincide with the generators". But this doesn't work for GAP groups in general, where generator lists may have duplicate entries (for similar reasons as to why @fieker would like us to distinguish, say, the trivial permutation group of degree 3 from one of degree 5, etc.). It also simply is not possible to efficiently "enumerate" all groups (though for permutation and pc groups, it is in principle possible, but it's nasty enough that I wouldn't want to compromise it by adding in codes to arbitrary sort a few elements differently than the "natural" order).

For this reason, I think it makes more sense to let the user explicitly ask for an "enumerator" if they want to do that with a group (that's how it is done in GAP), or even simply not allow this at all (instead, use iteration, or even better, an algorithm that gets what you want in reasonable asymptotic time, unlike enumeration which only scales with the group order).

**Comment by fingolfin** [comment]
Back to the original issue: 

If `G[i]` accesses the generators and nothing else, then I agree it would be kinda consistent to support `G[:]` as alias for `gens(G)`. Of course then one can also ask for `G[a:b]` or even `G[vec]` being supported. Maybe even more things would be "expected"?

Personally I'd wish `G[i]` as alias for `gen(G,i)` did not exist at all, for reasons already outlined *sigh*.

---

All that said, how do we want to deal with this?

**Comment by thofma** [comment]
I can live with the proposal to remove `G[i]` as an alias for `gen(G, i)`.

**Comment by mgkurtz** [comment]
That is fine for me. Though, I must admit, that I always love to play with whatever exotic feature, some language or library provides. So, I also sympathize with this (mis)usage of “indexing” a group. But sympathies aside, `gen(G, i)` looks cleaner to me, than `G[i]`.

Speaking of misusage of indexing. The alias `R["🐰"]` for `PolynomialRing(R, "🐰")` looks similar. It is cool, but rather inconsistent with how we create all kinds of other rings and groups. Thus, maybe we could remove this alias, too?

Happy Easter

**Comment by thofma** [comment]
> Speaking of misusage of indexing. About `R["🐰"]` as alias for `PolynomialRing(R, "🐰")`, I can say the same. It is cool, but rather inconsistent with how we create all kinds of other rings and groups. Thus, I would discourage and then purge this alias, too.

Can you elaborate why you consider this inconsistent? I cannot think of any other `getindex(R::Ring, s::String)` definition that would clash with this.

**Comment by mgkurtz** [comment]
> Can you elaborate why you consider this inconsistent? I cannot think of any other `getindex(R::Ring, s::String)` definition that would clash with this.

Sorry, I should have been more precise 😞 The point about the `R["x"]` syntax just came to my mind, while writing my comment. Maybe I should have used more question marks and less rabbit emojis?

Anyway, when I first saw the marvelous hack to use `getindex` to provide a constructor consistent with the mathematical syntax for polynomial rings, I was quite excited. I only fear, that hacks make for an interface inconsistent with usual expectations.

Usually, I expect indexing to return some element out of some larger structure. But here, we index a base ring with the sole intent to construct a more complicated ring. On the other hand, for constructing, we normally spell out some `CamelCaseConstructor` like `ResidueRing`, `PowerSeriesRing`, `FiniteField`, `FractionField`, etc. Other times, we construct with some function like `quo`, `sub` or `ideal`. But here, we construct an encompassing structure via indexing a base ring. So, while consistent with mathematical syntax, this seems weird from a Julia user point of view.

So, as I understand the previous discussion, for the `G[i]` case, we may ask: do we want to keep a notation which is concise, but Julia users could expect that notation, to mean something else? Now, for the `R["x"]` case, I ask: do we want to keep a notation, which is concise and coherent with mathematical notation, but Julia users could consider that notation, to be reserved for purposes, which here do not exist?

**Comment by fingolfin** [comment]
We are now uniformly support `X[i]` as alias for `gen(X,i)`.

That said, we still don't support `X[:]` as alias for `gens(X)`, and I think that's fine: e.g. dictionaries also support `d[i]` but not `d[:]`. The existence of `X[i]` does not mean that `X` should behave like a Vector in general. And I much rather have code write gens(X)`, which is at least explicit and easy to understand; `X[:]` is "cool" but only if you appreciate that kind of technicality...
