### ISSUE TITLE
Multivariate rational function fields

### ISSUE THREAD

**Issue by ulthiel** [oscar-system/Oscar.jl#1261]
Can we get multivariate rational function fields with a convenient function extending the existing one for univariate fields? E.g.
```
K,(X,Y) = RationalFunctionField(QQ, ["X","Y"])
```
? Of course, one could take the fraction field of the polynomial ring, but then one has to remap the variables, which is a bit inconvenient.

Edit: Maybe there should also be an own type for such things. I think FractionField of a polynomial ring is just a generic fraction field, isn't it?

Edit: Related is issue #1195 .

**Comment by thofma** [comment]
Will be addressed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1173.

**Comment by ulthiel** [comment]
> Will be addressed in [Nemocas/AbstractAlgebra.jl#1173](https://github.com/Nemocas/AbstractAlgebra.jl/pull/1173).

This is still work in progress, isn't it?

**Comment by thofma** [comment]
We just merged it. It will take a few days to bubble up to Oscar.

**Comment by ulthiel** [comment]
Terrific!

**Comment by thofma** [comment]
Here it is
```
julia> RationalFunctionField(QQ, ["x", "y"])
(Rational function field over Rational Field, AbstractAlgebra.Generic.Rat{fmpq, fmpq_mpoly}[x, y])
```
