### ISSUE TITLE
Matroid code error

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1284]
There is an error in the Matroid code: https://github.com/oscar-system/Oscar.jl/runs/6191061211?check_suite_focus=true#step:5:178

pinging @bschroter
since there is a polymake warning, pinging also @benlorenz

_Originally posted by @thofma in https://github.com/oscar-system/Oscar.jl/issues/1281#issuecomment-1110839907_

**Comment by benlorenz** [comment]
> The issue seems to be in the memory management. The parent object of `M.pm_matroid.DUAL` (line 404 in src/Combinatorics/Matroids/properties.jl) probably is removed.
> 
> Maybe @benlorenz knows how to fix this issue quickly.

@bschroter There is no reason for `M` to stay alive any longer, references to parent objects are always weak (to avoid loops). And polymake itself is perfectly happy with a `DUAL` object that only contains `RANK` and `N_ELEMENTS`, you will need to request some defining properties before `M` disappears, something like this should work (the list of properties might need adjusting):
```julia
function dual_matroid(M::Matroid)
  GC.@preserve M begin
    dual = Matroid(pm_object(M).DUAL, M.groundset, M.gs2num)
    Polymake.give(pm_object(dual), "BASES|CIRCUITS")
  end
  return dual
end
```

**Comment by bschroter** [comment]
I was hoping that this is a way to keep the parent (and its many properties). However, thank you Benjamin!
