### ISSUE TITLE
`hash` problem for `QabElem`

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#1287]
Currently there is no special method for `hash(x::QabElem, h::UInt)`, and the default method is based on `objectid(x)`.
On the other hand, `==` for `QabElem` objects regards two elements as equal if their normal forms are equal.
Thus the rule that objects with different `hash` values are different w.r.t. `==` does not hold.
```
julia> using Oscar

julia> x = QabElem(GAP.evalstr("E(5)"))
ζ(5)

julia> y = QabElem(GAP.evalstr("E(5)"))
ζ(5)

julia> x == y
true

julia> hash(x, zero(UInt)) == hash(y, zero(UInt))
false

julia> y = QabElem(GAP.evalstr("E(15)"))^3
ζ(15)^3

julia> x == y
true

```
What do we want? Shall we just add a very bad but cheap `hash` method?

**Comment by fieker** [comment]
On Wed, Apr 27, 2022 at 06:24:02AM -0700, Thomas Breuer wrote:
> Currently there is no special method for `hash(x::QabElem, h::UInt)`, and the default method is based on `objectid(x)`.
> On the other hand, `==` for `QabElem` objects regards two elements as equal if their normal forms are equal.
> Thus the rule that objects with different `hash` values are different w.r.t. `==` does not hold.
> ```
> julia> using Oscar
> 
> julia> x = QabElem(GAP.evalstr("E(5)"))
> ζ(5)
> 
> julia> y = QabElem(GAP.evalstr("E(5)"))
> ζ(5)
> 
> julia> x == y
> true
> 
> julia> hash(x, zero(UInt)) == hash(y, zero(UInt))
> false
> 
> julia> y = QabElem(GAP.evalstr("E(15)"))^3
> ζ(15)^3
> 
> julia> x == y
> true
> 
> ```
> What do we want? Shall we just add a very bad but cheap `hash` method?
No we should compute the normal form and a hash for it.

**Comment by ThomasBreuer** [comment]
O.k., I will create a pull request.
