### ISSUE TITLE
Oscar matrices over non-commutative rings?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1293]
I was just asked whether we support matrices over non-commutative rings. Experimentally, the answers seems to be no (?) but perhaps I am just doing it wrong? Here is what I tried with current OSCAR master:
```
julia> A = MatrixAlgebra(QQ, 3)
Matrix Algebra of degree 3 over Rational Field

julia> e = one(A)
[1   0   0]
[0   1   0]
[0   0   1]

julia> matrix(A, [ e ])
ERROR: MethodError: no method matching matrix(::AbstractAlgebra.Generic.MatAlgebra{fmpq}, ::Vector{AbstractAlgebra.Generic.MatAlgElem{fmpq}})
Stacktrace:
 [1] top-level scope
   @ REPL[20]:1
```

**Comment by tthsqe12** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1127
I should look over this pr

**Comment by thofma** [comment]
The PR is ready, we just need a breaking release.

**Comment by thofma** [comment]
P.S.: The syntax `matrix(A, [e])` would not work even with the PR. It should be `matrix(A, 1, 1, [e])`.

**Comment by thofma** [comment]
Will be working once we bump AA.
