### ISSUE TITLE
Computation of Galois groups for some polynomials raises UndefVarError

### ISSUE THREAD

**Issue by aelzenaar** [oscar-system/Oscar.jl#1323]
**Describe the bug**
Computing some Galois groups raises the error 

```
ERROR: UndefVarError: map_reduce not defined
Stacktrace:
 [1] Oscar.GaloisGrp.GaloisCtx(f::fmpq_poly, p::Int64)
   @ Oscar.GaloisGrp ~/src/Oscar.jl/experimental/GaloisGrp/GaloisGrp.jl:365
 [2] galois_group(f::fmpq_poly; prime::Int64, pStart::Int64)
   @ Oscar.GaloisGrp ~/src/Oscar.jl/experimental/GaloisGrp/GaloisGrp.jl:2274
 [3] galois_group(f::fmpq_poly)
   @ Oscar.GaloisGrp ~/src/Oscar.jl/experimental/GaloisGrp/GaloisGrp.jl:2256
 [4] top-level scope
   @ REPL[12]:1
```

**To Reproduce**

```
using Oscar
Qx, x = QQ["x"];
g = x^3-1;
G, C = galois_group(g)
```

**Expected behavior**
Return a group `G` such that `describe(G)` returns `"C3"`.

**Other remarks**

Some polynomials work fine. For example `G,C = galois_group(x^4 - 2)` returns the correct answer (`(Group([ (1,4), (2,3), (1,2)(3,4) ]), Galois Context for x^4 - 2 and prime 11)`).

On the other hand, the polynomial `x^4 - 4*x^3 + 9*x^2 - 4*x + 8` gives exactly the same error.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(jll=true,julia=true)` below. If
this does not work, please paste the output of Julia's `versioninfo()` and your
Oscar version.
```
OSCAR version 0.9.0-DEV
  combining:
    AbstractAlgebra.jl   v0.25.2
    GAP.jl               v0.7.7
    Hecke.jl             v0.13.4
    Nemo.jl              v0.30.0
    Polymake.jl          v0.7.2
    Singular.jl          v0.10.1
  building on:
    Antic_jll               v0.200.501+0
    Arb_jll                 v200.2200.0+0
    Calcium_jll             v0.400.102+0
    FLINT_jll               v200.800.401+1
    GAP_jll                 v400.1191.1+2
    Singular_jll            v403.1.200+0
    libpolymake_julia_jll   v0.8.0+1
    libsingular_julia_jll   v0.23.0+0
    msolve_jll              v0.2.3+1
    polymake_jll            v400.600.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.7.2
Commit bf53498635* (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)


```

**Comment by fieker** [comment]
On Thu, May 12, 2022 at 05:18:25AM -0700, Alex Elzenaar wrote:
Sorry, bad question: can you please update Oscar? The 0.9-DEV could be a
mount old (or not). In my dev version this error does not happen (any
more - I am aware of several fixes)
The offending line was last changed May 3rd...

Sorry

**Comment by aelzenaar** [comment]
I am up to date with master:
```
alex@xanthias ~/src/Oscar.jl (master)> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
And I check that Julia is indeed using the version of Oscar in that directory:

```
(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [c3fe647b] AbstractAlgebra v0.25.2
  [7073ff75] IJulia v1.23.3
  [f1435218] Oscar v0.9.0-DEV `~/src/Oscar.jl`
```
Should I be on a different branch to get the fix?

**Comment by aelzenaar** [comment]
Hang on, I have found the problem - my local version is cloned from my Github fork, not here. Thus it is entirely my fault!

**Comment by fieker** [comment]
On Thu, May 12, 2022 at 05:38:42AM -0700, Alex Elzenaar wrote:
> Hang on, I have found the problem - my local version is cloned from my Github fork, not here. Thus it is entirely my fault!
> 
No worries.
