### ISSUE TITLE
Reconcile `DEVELOPMENT.md` with dev docs

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1337]
We have https://github.com/oscar-system/Oscar.jl/blob/master/DEVELOPMENT.md and we have https://oscar-system.github.io/Oscar.jl/dev/DeveloperDocumentation/new_developers/   (off topic: annoyingly it seems one cannot link to chapters, i.e., https://oscar-system.github.io/Oscar.jl/dev/DeveloperDocumentation/  gives a 404 error. Anything we can do about that).

It would be good to reconcile those. E.g. replace the content of `DEVELOPMENT.md` with a link to the dev docs plus some surrounding words; of course only after seeing if any content in it should be transferred to the manual first.

I guess something similar should be done for https://github.com/oscar-system/Oscar.jl/blob/master/WhatIs.md

**Comment by CameronBraunstein** [comment]
I can work on this issue

**Comment by fingolfin** [comment]
Great!

**Comment by CameronBraunstein** [comment]
Is there a reason why we need to keep DEVELOPMENT.md at all? README.md also contains a link to the new developer instructions, so we can still have an easy way to jump to the new developer instructions

**Comment by CameronBraunstein** [comment]
I also think everything in WhatIs.md can just be moved into the README/new developers guide and that file can be deleted as well

**Comment by fingolfin** [comment]
I think this was resolved some time ago
