### ISSUE TITLE
`quo` method for `FPGroup`

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#1384]
**Describe the bug**
Currently the `quo(G::FPGroup, elements::Vector{FPGroupElem})` method works only if `G` is a *full* (free or) f.p. group.
If `G` is a *subgroup* of a free group then `quo` returns a result that is in general not valid.
If `G` is a *subgroup* of a f.p. group then `quo` throws a GAP error.

**To Reproduce**
```
using Oscar
f = free_group(2)
# `quo` for a subgroup of a free group
s = sub(f, [gen(f, 1)^2])[1]  # a subgroup of a free group
q, epi = quo(s, [gen(s, 1)^2])  # the function returns something
order(q)  # but here we get a GAP error
# `quo``for a subgroup of a f.p. group
x, y = gens(f)
frels = [x^2, y^2, comm(x, y)]
q, epi = quo(f, frels)  # a full f.p. group
s, emb = sub(q, [gen(q, 1)])  # a subgroup of a f.p. group
qq = quo( s, [gen(s, 1)])  # here we get a GAP error
```

**Expected behavior**
I think that if we want `quo` to delegate everything to GAP then we should catch the problematic cases on the Julia side.
Would that be sufficient?

**System:**
```
julia> Oscar.versioninfo(full=true)
julia> Oscar.versioninfo(full=true)
OSCAR version 0.9.0 - #TB_map_word, 1f158018 -- 2022-06-10 12:28:32 +0200
  combining:
    AbstractAlgebra.jl   v0.26.0
    GAP.jl               v0.8.0 - #TB_install_catch_errors, 5324a07 -- 2022-06-10 09:48:17 +0200
    Hecke.jl             v0.14.2 - #master, d9692752 -- 2022-05-24 14:23:05 +0200
    Nemo.jl              v0.31.1
    Polymake.jl          v0.7.2
    Singular.jl          v0.10.2
  building on:
    Antic_jll               v0.200.501+0
    Arb_jll                 v200.2200.0+0
    Calcium_jll             v0.400.102+0
    FLINT_jll               v200.800.500+0
    GAP_jll                 v400.1192.2+1
    Singular_jll            v403.1.300+0
    libpolymake_julia_jll   v0.8.0+2
    libsingular_julia_jll   v0.23.1+0
    msolve_jll              v0.2.3+1
    polymake_jll            v400.600.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver1)
Official https://julialang.org/ release
```

**Comment by ThomasBreuer** [comment]
Since PR #1404, we do not run into the (immediate or delayed) GAP errors anymore.
If the discussion of gap-system/gap/issues/4897 provides new ideas then we may adjust to them on the Oscar side.

**Comment by fingolfin** [comment]
Actually this still (or again?) runs into GAP errors for me, but now in a different spot, namely when using `quo`:

```
julia> f = free_group(2)
       # `quo` for a subgroup of a free group
Free group of rank 2

julia> s = sub(f, [gen(f, 1)^2])[1]  # a subgroup of a free group
Free group

julia> q, epi = quo(s, [gen(s, 1)^2])  # the function returns something
ERROR: Error thrown by GAP: Error, I don't know how to find a natural homomorphism for <N> in <G> at /Users/mhorn/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/factgrp.gi:1711 called from
oper( Parent( D ), D ) at /Users/mhorn/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/domain.gd:462 called from
attr( sub ) at /Users/mhorn/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/domain.gd:450 called from
NaturalHomomorphismByNormalSubgroupNCOrig( G, N ) at /Users/mhorn/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/ghom.gd:339 called from
NaturalHomomorphismByNormalSubgroupNC( G, N ) at /Users/mhorn/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/ghom.gi:1378 called from
<function "NaturalHomomorphismByNormalSubgroup">( <arguments> )
 called from read-eval loop at *defin*:0

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] ThrowObserver(depth::Int32)
   @ GAP ~/.julia/packages/GAP/fMeZB/src/GAP.jl:89
```


Anyway, I hope PR #3754 or a follow-up PR will fix it -- thoughts, @ThomasBreuer ?

**Comment by ThomasBreuer** [comment]
Funny. The error message is different from the one which we got when this issue got created.
And the situation is different.

My understanding is as follows: With #1404, we tried to forbid calling `quo` with a subgroup of a full free or f.p. group, and the problem/error was gone.
With  #1837, we tried to reintroduce `quo` for subgroups; the idea was that we can avoid the corrupted GAP objects by switching from the given elements list to the normal closure in the given group. Note that the text in the code says

> forming the quotient modulo a normal subgroup may work

Thus the new error "just" means that GAP gave up.
There are no corrupted objects involved, as in the situation when the issue had been created.

Situations where the current code works are when the given subgroup has small index in the full group.
The example here starts with a free group of rank 2 and then constructs subgroups involving just one generator, hence the index in the full group is infinite.

If we want to support `quo` for subgroups of full free or f.p groups then I do not see how we can check in advance whether GAP will be successful; thus we have to expect GAP error messages.
In particular, the new setup of `FPGroup` vs. `SubFPGroup` does not help here.

**Comment by fingolfin** [comment]
OK we discussed this on monday and in the end we are running in actual mathematical problems / impossibilities in the general case.

Of course the *specific* example here could (and eventually) should be handled better.

But in the end, in general we can't support forming quotients of `SubFpGroup` instances. It might be better to just generally forbid this, issuing a helpful error that suggests to first compute an isomorphism to a different group type. We could also add a `sub` method that uses a heuristic to compute such an iso, but in general this is impossible, hence why I think it might be better to just always print a helpful error explaining the issue.

**Comment by ThomasBreuer** [comment]
O.k., that makes sense:
We support the `quo(G, array_of_elements)` syntax only for `FPGroup` not for `SubFPGroup`; in order to form a quotient of a `SubFPGroup`, the *user* has to form the normal subgroup `N` generated by the elements, and call `quo(G, N)`. This way, the error messages will be better understandable.

**Comment by fingolfin** [comment]
@ThomasBreuer what's the status of this issue? Did your PR #3813 fully resolve it?

**Comment by ThomasBreuer** [comment]
Yes, I think that #3813 resolves this issue.
