### ISSUE TITLE
make some Singular functions accessible for Oscar objects

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#139]
The functions `Singular.substitute_variable`, `Singular.MaximalIdeal`, `Singular.satstd`, and `Singular.permute_variables` have no counterparts for wrapped Oscar objects, see the comments in oscar-system/GITFans/issues/8.
(I am not sure whether an issue for Singular.jl is the right place for this request, but I have been advised to open one.)

**Comment by fieker** [comment]
added to the issue in GitFan - all the functionality is there, but of course not in Singular names. Maybe not optimally wrapped or implemented, but all there

**Comment by ThomasBreuer** [comment]
Thanks for the hints. This is not an Oscar issue.
