### ISSUE TITLE
Test failure in QQAb conformance tests

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1392]
Earlier I merged PR #1388 by @thofma after it passed all tests. Unfortunately this now causes random failures on `master` and PRs, see e.g.
- https://github.com/oscar-system/Oscar.jl/actions/runs/2489073033
- https://github.com/oscar-system/Oscar.jl/actions/runs/2489883930

As an emergency workaround, I've pushed d18bb318a8cc30cfbbbb42512ba78bdc21eea89d to not run this conformance test. But of course we should figure out what is going wrong there and fix it properly. 

@fieker or @thofma might know quickly, so I won't dive into it right now.

**Comment by thofma** [comment]
I will have a look.

**Comment by fingolfin** [comment]
My workaround actually was not enough anyway, there are still random (?) CI failures coming from the tests in `test/Rings/AbelianClosure.jl:7`

**Comment by thofma** [comment]
Yes, the conformance tests are included also in another file. Otherwise that call in `test/Rings/AbelianClosure.jl:7` would just fail.

**Comment by thofma** [comment]
I found the problem. Currently discussing with @fieker the course of action.
