### ISSUE TITLE
Test failure on julia master (in GAP.jl)

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1395]
Oscar is not working with the nightly version of julia (master branch). The error starts with
```
signal (11): Segmentation fault
in expression starting at /home/runner/.julia/packages/GAP/v5lt8/src/GAP.jl:30
TryMarkRange at /workspace/srcdir/gap/src/julia_gc.c:598
GapRootScanner at /workspace/srcdir/gap/src/julia_gc.c:660
_jl_gc_collect at /cache/build/default-amdci5-3/julialang/julia-master/src/gc.c:3092
ijl_gc_collect at /cache/build/default-amdci5-3/julialang/julia-master/src/gc.c:3358
[...]
```
We have it on the radar and someone is working on it.

**Comment by fingolfin** [comment]
Should be fixed by https://github.com/JuliaLang/julia/pull/45678

**Comment by fingolfin** [comment]
Hehe, just at the moment I submitted my fix, they reverted the whole PR adding the issue in the first place.

So, this should be good, at least next time they regenerate the nightly binaries

**Comment by vchuravy** [comment]
I am glad you found this issue :)
