### ISSUE TITLE
Comparison of `MPolyQuoIdeal`'s not correct

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1408]
**Describe the bug**
The comparison of ideals in quotients of multivariate polynomial rings appears not to be implemented correctly.

**To Reproduce**
```
using Oscar
R, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"]);

Q, RtoQ = quo(R, ideal(R, [ x^2 - y*z ])); # btw, why does this not return a morphism but a julia map?

ideal(Q, [ Q(x) ]) == ideal(Q, [ Q(x), Q(y*z) ])
false
```
In `Q`, the ideal generated by `x` contains `x^2 == y*z`.

**Expected behavior**
`true` in the above example. I have the impression that the implementation only compares the "underlying" ideals in the polynomial ring but does not add the modulus.

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.9.0 - #master, 5c0b3600c3 -- 2022-06-17 14:55:41 +0200
  combining:
    AbstractAlgebra.jl   v0.26.0
    GAP.jl               v0.8.1
    Hecke.jl             v0.14.4
    Nemo.jl              v0.31.1
    Polymake.jl          v0.8.0
    Singular.jl          v0.10.2
  building on:
    Antic_jll               v0.200.501+0
    Arb_jll                 v200.2200.0+0
    Calcium_jll             v0.400.102+0
    FLINT_jll               v200.800.500+0
    GAP_jll                 v400.1192.2+1
    Singular_jll            v403.1.300+0
    libpolymake_julia_jll   v0.8.0+2
    libsingular_julia_jll   v0.23.1+0
    msolve_jll              v0.2.3+1
    polymake_jll            v400.600.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vim
Official https://julialang.org/ release
```

**Comment by tthsqe12** [comment]
will have a look

**Comment by tthsqe12** [comment]
Of course it is not doing the naive direct compairison on generators. The bug is in
`function simplify(a::MPolyQuoIdeal)`
I currently do not understand what this code is doing, but it is dodgy in at least one place.

**Comment by joschmitt** [comment]
> Of course it is not doing the naive direct compairison on generators.

Not what I meant, but I misread the code anyway. Thank you!

**Comment by wdecker** [comment]
We will change the code for simplify in this context as soon as the new Gröbner basis concept is implemented. Please be patient …

Von meinem iPhone gesendet
