### ISSUE TITLE
Support `Singular.ordering_a` in Oscar

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#1412]
Oscar used to be able to work with Singular orderings:

    R, (t, x1, x2, x3, x4) = PolynomialRing(QQ, ["t", "x1", "x2", "x3", "x4"], ordering = Singular.ordering_a([-1, 2, 0, 2, 0])*Singular.ordering_dp());

But the system was overhauled and now `ordering_a` is no longer supported. Would it be possible to add support for it? In particular, I need to be able to prepend several `ordering_a` to something like `ordering_lex`. It is essential for many polynomial computations in tropical geometry.

**Comment by tthsqe12** [comment]
It is in fact documented, but the Oscar.Orderings.singular is not exported. Something we need to do in oscar is stop deferring so easily to the matrix orderings, but this should get you the correct ordering.
```
julia> R, (t, x1, x2, x3, x4) = PolynomialRing(QQ, ["t", "x1", "x2", "x3", "x4"])
(Multivariate Polynomial Ring in t, x1, x2, x3, x4 over Rational Field, fmpq_mpoly[t, x1, x2, x3, x4])

julia> ord = Oscar.Orderings.singular(:a, gens(R), [-1,2,0,2,0])*degrevlex(gens(R))
Product ordering: Singular(a)(fmpq_mpoly[t, x1, x2, x3, x4]) * degrevlex(fmpq_mpoly[t, x1, x2, x3, x4])

julia> singular_poly_ring(R, ord.o)
Singular Polynomial Ring (QQ),(t,x1,x2,x3,x4),(M(-1,2,0,2,0,0,3,1,3,1,0,0,0,0,-1,0,0,0,-1,0,0,0,-1,0,0),C)
```

**Comment by tthsqe12** [comment]
@YueRen I am in the process of cleaning up the oscar orderings. If you have any comments on the interface below, please let me know soon.

```
julia> R, (x, y, s, t, u) = PolynomialRing(QQ, ["x", "y", "s", "t", "u"])
(Multivariate Polynomial Ring in x, y, s, t, u over Rational Field, fmpq_mpoly[x, y, s, t, u])

julia> O = weighted_ordering(gens(R),[-1,2,0,2,0])*degrevlex(gens(R))
weighted_ordering([x, y, s, t, u], [-1 2 0 2 0])*degrevlex([x, y, s, t, u])

julia> weight_matrix(O)
[-1    2    0    2    0]
[ 1    1    1    1    1]
[ 0    0    0    0   -1]
[ 0    0    0   -1    0]
[ 0    0   -1    0    0]
[ 0   -1    0    0    0]
[-1    0    0    0    0]

julia> canonical_weight_matrix(O)
[-1   2    0    2    0]
[ 0   3    1    3    1]
[ 0   0    0    0   -1]
[ 0   0    0   -1    0]
[ 0   0   -1    0    0]

julia> singular_poly_ring(R, O)
Singular Polynomial Ring (QQ),(x,y,s,t,u),(a(-1,2,0,2,0),dp(5),C)
```

**Comment by YueRen** [comment]
Really sorry for the late reply, the interface looks nice and many thanks for it!  

I would change the name from `weighted_ordering` to `weighted_preordering` just to emphasize that this ordering on the monomial is not a total ordering (it is a [preorder](https://en.wikipedia.org/wiki/Preorder#Formal_definition)).

**Comment by tthsqe12** [comment]
This leads to the next can of worms. Currently the methods with "ordering" in the name are
```
monomial_ordering(v::AbstractVector{<:MPolyElem}, s::Symbol)
monomial_ordering(v::AbstractVector{<:MPolyElem}, s::Symbol, w::Vector{Int})
matrix_ordering(::AbstractVector{<:MPolyElem}, ::fmpz_mat)
weighted_ordering(::AbstractVector{<:MPolyElem}, ::Vector{Int})
```
All of the oscar orderings are preorders until proven to be orders, we had a small debate on the meaning of these tests
https://github.com/oscar-system/Oscar.jl/blob/08988e0e5d8da3f45c6af62876b1d4d1d133c9b6/test/Rings/orderings-test.jl#L53-L55

**Comment by YueRen** [comment]
Ah, I see. I forgot that you can define an total ordering on a subset of the monomials, because I don't really use that feature. In that case I don't mind keeping the name for the sake of consistency.

**Comment by tthsqe12** [comment]
Do you have anything to say on the meaning of the predicates in the tests?

**Comment by YueRen** [comment]
I am closing the issue, since we now have `weight_ordering`.  Thanks a lot!
