### ISSUE TITLE
Don't export `SymmetricGroup` resp. replace it with an alias for `symmetric_group`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1418]
It is from AbstractAlgebra and not something we want to support at this point within OSCAR

**Comment by fingolfin** [comment]
@CameronBraunstein maybe you could look into this?

**Comment by CameronBraunstein** [comment]
Yes, I will look into it

**Comment by CameronBraunstein** [comment]
Should I also replace all AbstractAlgebra.SymmetricGroup objects with the corresponding symmetric_group (For example, in  ./test/StraightLinePrograms/straightline.jl and ./src/TropicalGeometry/semiring.jl), or leave them alone?

**Comment by fingolfin** [comment]
I believe this is fully resolved
