### ISSUE TITLE
latest version of msolve (msolve_jll v0.2.5+0) seems to be buggy

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Oscar.jl#1431]
@ederc 
the tests are all failing now c.f. 
https://github.com/oscar-system/Oscar.jl/pull/1429
https://github.com/oscar-system/Oscar.jl/pull/1427

If not buggy, then at least the tests are invalid. However, it is also easy to crash it
```
julia> using Oscar
julia> R, (x1,x2,x3) = PolynomialRing(QQ, ["x1", "x2", "x3"])

julia> I = ideal(R, [x1+2*x2+2*x3-1, x1^2+2*x2^2+2*x3^2-x1, 2*x1*x2+2*x2*x3-x2]); msolve(I);
Fixes info level to no output.

signal (11): Segmentation fault
in expression starting at REPL[3]:1
cfree at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
msolve_julia at /workspace/srcdir/msolve/src/msolve/msolve.c:5648
#msolve#739 at ~/.julia/dev/Oscar/src/Rings/msolve/msolve.jl:114
msolve at ~/.julia/dev/Oscar/src/Rings/msolve/msolve.jl:80
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]

```

**Comment by tthsqe12** [comment]
msolve_jll v0.2.3+1 seems to be fine c.f.
https://github.com/oscar-system/Oscar.jl/pull/1428

**Comment by ederc** [comment]
I need to update many things in Oscar for the new version of msolve to work. Please do not update msolve_jll on your own. 

-- 
gpg: http://hkps.pool.sks-keyservers.net/pks/lookup?search=0x6e0d034b959fde6a&fingerprint=on&op=index

**Comment by thofma** [comment]
Note that this also broke the released version of Oscar aka 0.10.0.

**Comment by thofma** [comment]
There was no update done by anyone by hand. This happened automatically by releasing a 0.2.5 version of msolve. Version 0.2.5 is per definition compatible with 0.2.* for the julia package manager, so the newest version is automatically used in any Oscar version.

**Comment by tthsqe12** [comment]
Yes, binary changes should go under v0.3.x now.

**Comment by ederc** [comment]
Sorry, I thought if we have `0.2.3` hardcoded in Project.toml it stays at this specific version. I am working on the problem.

**Comment by thofma** [comment]
We can pin the specific version in the meantime.

**Comment by ederc** [comment]
I should (hopefully) provide a fix tomorrow.
