### ISSUE TITLE
Behaviour of div/divrem in Oscar

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Oscar.jl#146]
As a consequence of https://github.com/Nemocas/Nemo.jl/pull/868 I offered to make the changes that would be necessary to support necessary changes to div/divrem that were made in Nemo in all our packages (except Hecke, which Tommy will deal with).

Unfortunately, as Oscar imports the Nemo behaviour, the current Oscar tests will break. Therefore a decision must be made as to what behaviour Oscar wants for div/divrem.

There are a number of options here:

* Just fix the tests that will break and make a decision later
* Remove the tests that will break and defer all decisions until later
* Make a decision now. There are three possibilities:
   - Make Oscar behave internally and externally the same way as Nemo/AbstractAlgebra behave internally/externally respectively
   - Make Oscar behave internally and externally as Nemo/AbstractAlgebra do internally
   - Make Oscar behave internally and externally as Nemo/AbstractAlgebra/Julia do externally. Here there are two options:
      + Do postprocessing on HNF and other functions which reduce their output so that it agrees with div/divrem and lose uniqueness of HNF over Z
      + Leave functions as they are and fix bugs as they pop up over time

I don't at all care what decision is made, just let me know and I'll make a PR with the changes to be applied when the next version of Nemo is made a dependency.

Note that the external behaviour of Nemo is currently under review. It may be changed at a later date to agree with the internal behaviour, which differs from the behaviour of Julia at the REPL. The internal behaviour of Nemo is considered stable and it is considered impractical to change it (again).

**Comment by micjoswig** [comment]
@thofma This seems outdated to me.  If you agree, can you please close this ticket?
