### ISSUE TITLE
Bug in crt(r1,m1,r2,m2) when m1 and m2 are not relatively prime

### ISSUE THREAD

**Issue by AndrewVSutherland** [oscar-system/Oscar.jl#1479]
**Describe the bug**
The function crt(r1,m1,r2,m2) may give the wrong answer when m1 and m2 are not relatively prime

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
crt(ZZ(11),ZZ(30),ZZ(41),ZZ(85))
```
outputs 1511, which is not congruent to 41 mod 85

**Expected behavior**
the output for this input should be 41.  I would also expect the output to be in the range [0,lcm(m1,m2)), and I think the function should raise an error if the modular constraints are incompatible, which it currently does not, e.g.
```
using Oscar
crt(ZZ(11),ZZ(30),ZZ(40),ZZ(85))
```
returns 611, which is not congruent to 40 mod 85 (in fact no integer congruent to 11 mod 30 is congruent to 40 mod 85)

I also think this function should accept types other than fmpz's (in particular it should accept any integer type).  In fact it is not hard to write a generic version of this function using +,*,÷,%,gcd,invmod that works in any Euclidean domain that supports these operations, e.g.
```
function CRT(r1,r2,m1,m2)
    d = gcd(m1,m2)
    if d != 1
        @assert r1 % d == r2 % d
        e = gcd(d, m1 ÷ d);
        d ÷= e;
        while gcd(d,e) != 1 f = gcd(d,e); d ÷= f; e *= f; end
        m1 ÷= d; m2 ÷= e
        r1 %= m1; r2 %= m2
    end
    return r1 + ((r2 + m2 - (r1 % m2)) * invmod(m1,m2) % m2) * m1;
end
```
Of course if you took this approach you would want the optional `signed` argument to apply only for a specialized version of the function that expects integers.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.10.0
  combining:
    AbstractAlgebra.jl   v0.26.0
    GAP.jl               v0.8.1
    Hecke.jl             v0.14.4
    Nemo.jl              v0.31.1
    Polymake.jl          v0.8.0
    Singular.jl          v0.10.2
  building on:
    Antic_jll               v0.200.501+0
    Arb_jll                 v200.2200.0+0
    Calcium_jll             v0.400.102+0
    FLINT_jll               v200.800.500+0
    GAP_jll                 v400.1192.2+1
    Singular_jll            v403.1.300+0
    libpolymake_julia_jll   v0.8.0+2
    libsingular_julia_jll   v0.23.1+0
    msolve_jll              v0.2.3+1
    polymake_jll            v400.600.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.6.6
Commit b8708f954a (2022-03-28 07:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Official https://julialang.org/ release
...
```

**Additional context**

**Comment by tthsqe12** [comment]
This is more a bug in the documentation of crt, which doesn't mention the assumption gcd(m1,m2)=1. 99.99% of uses of this function include this assumption. So much so that the one documenting crt didn't even consider the case of non-coprime moduli.

**Comment by thofma** [comment]
Is there a way of adding the check without making everything slow?

P.S.: A method that works for arbitrary euclidean domains is available via `crt(r::Vector, m::Vector)`

**Comment by tthsqe12** [comment]
There is nothing special about the c implementation in flint besides the assumtion gcd(m1,m2)=1, so I can move to julia and add the possibility of throwing.
P.S: why is `crt(r::Vector, m::Vector)` in hecke/src/misc? And it assumes coprime moduli as well?

**Comment by tthsqe12** [comment]
I have started https://github.com/Nemocas/AbstractAlgebra.jl/pull/1202
But it will take some time for this to filter through the packages before we can get it working for Oscar.ZZ

**Comment by thofma** [comment]
Everything is fixed except for the method for arbitrary Euclidean domains.

**Comment by AndrewVSutherland** [comment]
Thanks for the quick fix!  I can confirm that this fixes the problem I reported, and it is a relief to have crt support both fmpz's and integer types.

**Comment by tthsqe12** [comment]
Hmm, I wouldn't get your hopes up too high for zz (Int) as all of the arithmetic there is unchecked for overflow.

**Comment by AndrewVSutherland** [comment]
@tthsqe12 I'm not sure I understand your comment.  My understanding is that ZZ/fmpz and BigInt both handle arbitrary precision integers so overflow should not be a problem, is that not the case?

**Comment by tthsqe12** [comment]
Ah, ok. I thought by "integer types" you meant at least BigInt and Int. Of course BigInt is fine. Int is only fine in some ranges.

**Comment by AndrewVSutherland** [comment]
For fixed precision types, ideally one would want the result to be correct whenever the LCM of the moduli is small enough to be represented in that type -- this would require working at higher intermediate precision in some cases but using 128-bit arithmetic to handle Int64's would still be pretty fast.  In any case, it would be good to know (and document) what behavior to expect when fixed precision integer inputs are used.

**Comment by thofma** [comment]
When a fixed precision type is used and the result cannot be represented using the input type, the usual disclaimer of julia applies: https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior. I don't think adding warnings to every docstring is feasible.

**Comment by AndrewVSutherland** [comment]
@thofma I think that's totally fine, and is what I would expect, my question was whether the result will be correct when it can be represented in the input type -- if you are not careful in the implementation, you could produce the wrong result due to intermediate overflow even when the output will fit.  If the answer is that the result will be correct when it fits, maybe it does not need to be documented, since I think this would be the default expectation, but if the result may be incorrect even when it does fit, then I think that should be documented (otherwise there is really no point in supporting fixed precision types, since you would never know when you can rely on the result).

**Comment by thofma** [comment]
I guess the main application is entering `crt(1, 2, 2, 7)` quickly at the REPL without wrapping everything inside `ZZ()` or `BigInt()`. It seems people expect that to work. 

We have a fix lined up at https://github.com/Nemocas/AbstractAlgebra.jl/pull/1204/, which will add some explanation on the restriction for fixed precision types to the docstring of `crt`. I will close this issue here once it is available.

**Comment by thofma** [comment]
Should be fixed by doing `]up`.
