### ISSUE TITLE
F4 segfaults when exporting results back to Julia

### ISSUE THREAD

**Issue by RafaelDavidMohr** [oscar-system/Oscar.jl#1484]
# Bug Description

The `f4` function segfaults when called on a specific example. This seems to be caused by a function which exports data to julia in the C kernel. I would be happy to move this to the msolve repository if this does not fit here.

# To reproduce

Unfortunately I could not find a smaller example where the bug happens.

    using Oscar
    R, (t, x1, x2, x3, x4, x5, x6) = PolynomialRing(GF(5), ["t", "x1", "x2", "x3", "x4", "x5", "x6"])
    I = ideal(R, [x1 + x2 + x3 + x4 + x5 + x6, x1*x2 + x1*x6 + x2*x3 + x3*x4 + x4*x5 + x5*x6, x1*x2*x3 + x1*x2*x6 + x1*x5*x6 + x2*x3*x4 + x3*x4*x5 + x4*x5*x6, x1*x2*x3*x4 + x1*x2*x3*x6 + x1*x2*x5*x6 + x1*x4*x5*x6 + x2*x3*x4*x5 + x3*x4*x5*x6, x1*x2*x3*x4*x5 + x1*x2*x3*x4*x6 + x1*x2*x3*x5*x6 + x1*x2*x4*x5*x6 + x1*x3*x4*x5*x6 + x2*x3*x4*x5*x6, t*x1*x2*x3*x4*x5*x6 + 4*t + 4])
    f4(I, eliminate = 1)

    signal (11): Speicherzugriffsfehler
    in expression starting at REPL[4]:1
    export_julia_data_ff_8 at /workspace/srcdir/msolve/src/neogb/io.c:633
    export_results_from_f4 at /workspace/srcdir/msolve/src/neogb/f4.c:492
    f4_julia at /workspace/srcdir/msolve/src/neogb/f4.c:570
    #f4#708 at /home/mohr/.julia/dev/Oscar/src/Rings/msolve/f4.jl:74
    f4##kw at /home/mohr/.julia/dev/Oscar/src/Rings/msolve/f4.jl:53
    unknown function (ip: 0x7ff2bd856a21)
    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
    do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:126
    eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:215
    eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:166 [inlined]
    eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:587
    jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:731
    jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:885
    jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:830
    jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:944
    eval at ./boot.jl:373 [inlined]
    eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
    repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:246
    start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:231
    #run_repl#47 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:364
    run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:351
    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
    #930 at ./client.jl:394
    jfptr_YY.930_45169.clone_1 at /opt/julia-1.7.2/lib/julia/sys.so (unknown line)
    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
    jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:757
    #invokelatest#2 at ./essentials.jl:716 [inlined]
    invokelatest at ./essentials.jl:714 [inlined]
    run_main_repl at ./client.jl:379
    exec_options at ./client.jl:309
    _start at ./client.jl:495
    jfptr__start_38732.clone_1 at /opt/julia-1.7.2/lib/julia/sys.so (unknown line)
    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
    true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:559
    jl_repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:701
    main at julia (unknown line)
    __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    unknown function (ip: 0x400808)
    Allocations: 29167848 (Pool: 29131773; Big: 36075); GC: 24
    Speicherzugriffsfehler (Speicherabzug geschrieben)

# Expected behavior

No memory issues should happen on an example this small.

# System information

    OSCAR version 0.10.0 - #master, 1c8ef8b71 -- 2022-07-27 12:39:14 +0000
      combining:
        AbstractAlgebra.jl   v0.27.0
        GAP.jl               v0.8.1
        Hecke.jl             v0.14.11
        Nemo.jl              v0.32.0
        Polymake.jl          v0.8.0
        Singular.jl          v0.12.0
      building on:
        Antic_jll               v0.201.500+0
        Arb_jll                 v200.2300.0+0
        Calcium_jll             v0.401.100+0
        FLINT_jll               v200.900.1+0
        GAP_jll                 v400.1192.2+1
        Singular_jll            v403.100.100+0
        libpolymake_julia_jll   v0.8.1+0
        libsingular_julia_jll   v0.25.0+0
        msolve_jll              v0.4.3+0
        polymake_jll            v400.700.1+1
    See `]st -m` for a full list of dependencies.

    Julia Version 1.7.2
    Commit bf53498635 (2022-02-06 15:21 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
    Official https://julialang.org/ release

**Comment by ederc** [comment]
That's an msolve internal bug. Will fix it.

**Comment by ederc** [comment]
The bug is fixed with `msolve` resp. `msolve_jll` v0.4.4 which is available in the official registry as of now. So an `update` fixes this issue for `Oscar` users.
