### ISSUE TITLE
Preferred ordering for ideal computations

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1487]
We have an example from @AlheydisGeiger where computing a saturation with Singular(.jl) ideals is much faster than with Oscar ideals, because the provided ordering made everything faster. At the moment we have no way to have this as fast in Oscar, which is a shame. I think it would make sense to have a way to specify a possible ordering when doing ideal computations. This is for experienced users, who needs more control over these things.

So more concretely, I would propose to have a method
```julia
saturation(I::MPolyIdeal, J::MPolyIdeal; ordering = nothing)
```
and the docstring explains that by default the system will choose a default ordering and otherwise use the ordering provided.

Any other ideas or suggestions on how to tackle this problem?

CC: @tthsqe12 @wdecker @ederc

**Comment by wdecker** [comment]
Can I see the example in all details?

**Comment by thofma** [comment]
Here is the Singular.jl/singular code:
```julia
using Singular
r,(c1,c2,c3,c4,c5,c6,x,y,z,u,v,w,t) =
    PolynomialRing(QQ,["c1","c2","c3","c4","c5","c6","x","y","z","u","v","w","t"],
                   ordering=ordering_dp(6)*ordering_dp(7))
p = c1+c2*y+c3*y*z+c4*y^2+c5*x+c6*x*y^4*z;
q = c1+c2*v+c3*v*w+c4*v^2+c5*u+c6*u*v^4*w;
i = Ideal(r, [p,q,derivative(p,x),derivative(p,y),derivative(p,z),derivative(q,u),derivative(q,v),derivative(q,w),1-t*x*y*z*u*v*w])
j = Ideal(r, [x-u,y-v,z-w])
@time saturation(i,j)
```
Here the same in Oscar:
```julia
n = 6
R, c =  PolynomialRing(QQ,vcat(["c$i" for i in 1:n+7]))
x = c[n+1]
y = c[n+2]
z = c[n+3]
u = c[n+4]
v = c[n+5]
w = c[n+6]
t = c[n+7]
p= c[1] + c[2]*y + c[3]*y*z + c[4]*y^2 + c[5]*x + c[6]*x*y^4*z
q = evaluate(p,[x,y,z],[u,v,w])
I = ideal(R,[p,q,derivative(p,x),derivative(p,y),derivative(p,z),derivative(q,u),derivative(q,v),derivative(q,w),1-t*x*y*z*u*v*w])
Sat = saturation(I, ideal(R,[x-u,y-v,z-w]))
```

**Comment by ederc** [comment]
To have some interface as @thofma suggested is something we are working on. Problem is (as I already commented on issue #1481) that we are still waiting for a rework of the structure of GBs for ideals which coincides to `ModuleGens`.

On the other hand your statement that the above fast computation from Singular.jl is not possible in Oscar.jl is not completely correct: Saturation is nothing but GB computation, and for all the underlying GB stuff we have already an interface working with orderings. One can tweak your above example a little bit. It's not nice and of course not the way to go, but the best you can do until we have the user-friendly ordering interface for all these kinds of computations ready:

```julia
using Oscar
n = 6
R, c =  PolynomialRing(QQ,vcat(["c$i" for i in 1:n+7]))
x = c[n+1]
y = c[n+2]
z = c[n+3]
u = c[n+4]
v = c[n+5]
w = c[n+6]
t = c[n+7]
p= c[1] + c[2]*y + c[3]*y*z + c[4]*y^2 + c[5]*x + c[6]*x*y^4*z
q = evaluate(p,[x,y,z],[u,v,w])
I = ideal(R,[p,q,derivative(p,x),derivative(p,y),derivative(p,z),derivative(q,u),derivative(q,v),derivative(q,w),1-t*x*y*z*u*v*w])
J = ideal(R,[x-u,y-v,z-w])
ord = degrevlex(gens(R)[1:6])*degrevlex(gens(R)[7:13])
singular_assure(I, ord)
singular_assure(J, ord)
@time saturation(I,J)
```

The important calls are the two `singular_assure` ones in which we are telling the Singular side of the ideals to use the product ordering `ord` on their corresponding Singular ring. Then the call to `saturation` in Oscar is exactly the same as the one in Singular.jl above.

**Comment by ederc** [comment]
@thofma In #1489 I have tried to implement an interface for `saturation` also taking care of monomial orderings as you suggested. As already mentioned, this needs to be generalized at some point, but, in the meantime, it should provide a user-friendly way of dealing with examples like the above one.

**Comment by thofma** [comment]
As far as I know, the GB computations are hidden from the user for all ideal operations and `singular_assure` is an implementation detail that might vanish any time. It is also not clear what happens if one does `singular_assure(I, ord)` and `singular_assure(I, ord2)` before (which GB will be used)?

Anyway, thanks for the PR!

**Comment by tthsqe12** [comment]
Some possibilities, some serious, some not so serious.
1. Have a preferred ordering attached to the polynomial ring. Probably a non-starter because of == issues for polynomial rings.
2. Attach a preferred ordering to ideals. In the case of a clash, choose one deterministically.
3. Have a keyword ordering argument to each function that deals with a GB. This seems like it will become cumbersome for all parties involved.
4. Have the system scan the input and automatically choose The Best(TM) ordering.

**Comment by ederc** [comment]
@tthsqe12 

I think 1) is what we wanted to get rid of moving from Singular to Oscar, I don't see this a to be possible solution.
For 2) I think the ideal does not care about the monomial ordering, only the GBs and corresponding computed data do. For example , at the moment, we one ideal caches a dictionary of GBs where each GB is computed w.r.t. a given monomial ordering. I don't see the point why we should have different ideals for each chosen monomial ordering.

All in all, I think a combination of 3) and 4) is what we have to do: We should allow an optional keyword parameter `ordering` which defaults to what we know in general to be the best. Either by a default ordering for the given ring or by some heuristics we feed with meta data from the ring, ideal, computation, etc., which decides what should be the best. Still I think an expert user should be able use a specific user-defined monomial ordering via the keyword.

**Comment by YueRen** [comment]
I second @ederc 's suggestion. Regarding attaching a preferred ordering to ideals: realizing this will be incredibly messy since you will have to deal with inheritance. In @AlheydisGeiger example, the quotients would need the same preferred ordering, which then leads to the question what to do in more complicated examples (e.g. summation of two ideals).

**Comment by fieker** [comment]
On Fri, Jul 29, 2022 at 06:30:06AM -0700, dan wrote:
> Some possibilities, some serious, some not so serious.
> 1. Have a preferred ordering attached to the polynomial ring. Probably a non-starter because of == issues for polynomial rings.
> 2. Attach a preferred ordering to ideals. In the case of a clash, choose one deterministically.
> 3. Have a keyword ordering argument to each function that deals with a GB. This seems like it will become cumbersome for all parties involved.
> 4. Have the system scan the input and automatically choose The Best(TM) ordering.
> 
Option 4 is never going to be perfect, however it is the long term only
possibility. The further a user is away from a GB calculation, the less
likely it becomes that any of the other choices work.

1-3 only work if one directly calls GB - or is at most 1 call away.

How should one know if integral_basis calls GB and on what ring? Same
for basically any ideal operation....
