### ISSUE TITLE
`divrem` goes into overflow for quotient rings

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1534]
Try running this code:
```@julia
julia> R, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"])
julia> Q, _ = quo(R, ideal(R, x))
julia> divrem(Q(y^2), Q(y))
```
For me, it produces the following error:
```
ERROR: StackOverflowError:
Stacktrace:
     [1] divrem(a::MPolyQuoElem{fmpq_mpoly}, b::MPolyQuoElem{fmpq_mpoly}, r::RoundingMode{:ToZero})
       @ Base ./div.jl:124
     [2] divrem(x::MPolyQuoElem{fmpq_mpoly}, y::MPolyQuoElem{fmpq_mpoly})
       @ Base ./div.jl:120
     [3] divrem(a::MPolyQuoElem{fmpq_mpoly}, b::MPolyQuoElem{fmpq_mpoly})
       @ AbstractAlgebra ~/Kaiserslautern/AbstractAlgebra.jl/src/AbstractAlgebra.jl:82
     [4] div(a::MPolyQuoElem{fmpq_mpoly}, b::MPolyQuoElem{fmpq_mpoly})
       @ AbstractAlgebra ~/Kaiserslautern/AbstractAlgebra.jl/src/algorithms/GenericFunctions.jl:76
--- the last 4 lines are repeated 19994 more times ---
 [79981] divrem(a::MPolyQuoElem{fmpq_mpoly}, b::MPolyQuoElem{fmpq_mpoly}, r::RoundingMode{:ToZero})
       @ Base ./div.jl:124
 [79982] divrem(x::MPolyQuoElem{fmpq_mpoly}, y::MPolyQuoElem{fmpq_mpoly})
       @ Base ./div.jl:120
 [79983] divrem(a::MPolyQuoElem{fmpq_mpoly}, b::MPolyQuoElem{fmpq_mpoly})
       @ AbstractAlgebra ~/Kaiserslautern/AbstractAlgebra.jl/src/AbstractAlgebra.jl:82

```
What's going on? I'm almost sure, this used to work once. Or am I missing something?

**Comment by tthsqe12** [comment]
We decided in AA that divrem is the most primitive operation for euclidean rings. In Julia base, they took the opposite view and divrem is implemented in terms of div and rem. Since, in AA, div and rem are both implemented in terms of divrem, we get the overflow, which is basically saying the function is not implemented. @thofma what about a generic divrem(a,b) = NotImplementedError in AA?

**Comment by thofma** [comment]
@HechtiDerLachs: Do you remember when that worked? As @tthsqe12 said, in the Oscar bubble `divrem(x::RingElement, y::RingElement)` is usually legal only for Euclidean domains.

@tthsqe12 Yes, I think this is a good idea.

**Comment by HechtiDerLachs** [comment]
> @HechtiDerLachs: Do you remember when that worked?

No, not really, sorry. But we should make that work, right? I think it's part of the requirements of Oscar's ring interface to have either one of the division methods implemented. Even though there are no precise requirements on the remainder, etc.

**Comment by thofma** [comment]
No, it is not part of the ring interface. The functions `div, rem, divrem` (with ring elements as input) refer to the Euclidean structure and are optional.

**Comment by HechtiDerLachs** [comment]
> No, it is not part of the ring interface. The functions `div, rem, divrem` (with ring elements as input) refer to the Euclidean structure and are optional.

Ok, that is good to know; thanks for clarifying. I just had a look at the documentation of the ring interface and it seems that some things have slightly changed since last time I saw it. I thought that you were asked to implement `div` or `divrem` if your `is_exact_type` was returning `true` or something.

**Comment by thofma** [comment]
Maybe you mean `divexact/divides`? Can you clarify what you mean by "things have changed"? I don't recall that `divrem` was ever mandatory for exact rings.

**Comment by HechtiDerLachs** [comment]
> Maybe you mean `divexact/divides`? Can you clarify what you mean by "things have changed"? I don't recall that `divrem` was ever mandatory for exact rings.

Maybe it was that, yes! Sorry, but all I said was based on vague memory from oral discussions with @tthsqe12 once upon a time. By 'things have changed', I also mean the general documentation: The text has changed and improved. For instance, we can now use Latex-like indices in expressions, etc. I do not recall whether the requirements of the interface have changed mathematically or algorithmically; sorry!

**Comment by tthsqe12** [comment]
with https://github.com/Nemocas/AbstractAlgebra.jl/pull/1222
```
julia> divrem(Q(y^2), Q(y))
ERROR: function divrem is not implemented for arguments
MPolyQuoElem{fmpq_mpoly}: y^2
MPolyQuoElem{fmpq_mpoly}: y
```
