### ISSUE TITLE
Intersection of submodules makes trouble

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1546]
Try to run this code:
```@julia
R, (x,y,z) = QQ["x", "y", "z"]

F = FreeMod(R, 1)
I, _ = sub(F, [F[1]])
K, _ = sub(F, [zero(R)*F[1]])
I, _ = intersect(I, K)
I, _ = intersect(I, K)
``` 
I am getting the following error:
```
ERROR: LoadError: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T at missing.jl:105
  zero(::Union{Type{P}, P}) where P<:Dates.Period at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Dates/src/periods.jl:53
  zero(::Union{AbstractAlgebra.Generic.LaurentSeriesFieldElem{T}, AbstractAlgebra.Generic.LaurentSeriesRingElem{T}} where T<:RingElement) at /home/matthias/Kaiserslautern/AbstractAlgebra.jl/src/generic/LaurentSeries.jl:466
  ...
Stacktrace:
  [1] zero(#unused#::Type{Any})
    @ Base ./missing.jl:106
  [2] reduce_empty(#unused#::typeof(+), #unused#::Type{Any})
    @ Base ./reduce.jl:311
  [3] reduce_empty(#unused#::typeof(Base.add_sum), #unused#::Type{Any})
    @ Base ./reduce.jl:320
  [4] mapreduce_empty(#unused#::typeof(identity), op::Function, T::Type)
    @ Base ./reduce.jl:343
  [5] reduce_empty(op::Base.MappingRF{typeof(identity), typeof(Base.add_sum)}, #unused#::Type{Any})
    @ Base ./reduce.jl:329
  [6] reduce_empty_iter
    @ ./reduce.jl:355 [inlined]
  [7] mapreduce_empty_iter(f::Function, op::Function, itr::Vector{Any}, ItrEltype::Base.HasEltype)
    @ Base ./reduce.jl:351
  [8] _mapreduce(f::typeof(identity), op::typeof(Base.add_sum), #unused#::IndexLinear, A::Vector{Any})
    @ Base ./reduce.jl:400
  [9] _mapreduce_dim
    @ ./reducedim.jl:318 [inlined]
 [10] #mapreduce#672
    @ ./reducedim.jl:310 [inlined]
 [11] mapreduce
    @ ./reducedim.jl:310 [inlined]
 [12] #_sum#682
    @ ./reducedim.jl:878 [inlined]
 [13] _sum
    @ ./reducedim.jl:878 [inlined]
 [14] #_sum#681
    @ ./reducedim.jl:877 [inlined]
 [15] _sum
    @ ./reducedim.jl:877 [inlined]
 [16] #sum#679
    @ ./reducedim.jl:873 [inlined]
 [17] sum(a::Vector{Any})
    @ Base ./reducedim.jl:873
 [18] (::Oscar.var"#1290#1296"{SubQuo{fmpq_mpoly}})(k::SubQuoElem{fmpq_mpoly})
    @ Oscar ./none:0
 [19] iterate
    @ ./generator.jl:47 [inlined]
 [20] collect(itr::Base.Generator{Vector{SubQuoElem{fmpq_mpoly}}, Oscar.var"#1290#1296"{SubQuo{fmpq_mpoly}}})
    @ Base ./array.jl:681
 [21] intersect(M::SubQuo{fmpq_mpoly}, N::SubQuo{fmpq_mpoly})
    @ Oscar ~/Kaiserslautern/neuer_Oscar_Klon/Oscar.jl/src/Modules/UngradedModules.jl:2261
 [22] top-level scope
    @ /tmp/bug.jl:7
 [23] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [24] top-level scope
    @ REPL[25]:1
 [25] top-level scope
    @ ~/.julia/packages/Infiltrator/qHXTS/src/Infiltrator.jl:680
in expression starting at /tmp/bug.jl:7
```
However, I am expecting to be able to intersect (honest) submodules at will.

**Comment by tthsqe12** [comment]
some more missing inits.

**Comment by thofma** [comment]
(And some array for which the element type is not inferred.)

**Comment by tthsqe12** [comment]
@AlexD97 These are yours. Please check if the following sums can be empty, and provide the init argument if so:

https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L2269

https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L2276-L2277

https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L3456

https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L3586

https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L5133

**Comment by AlexD97** [comment]
> @AlexD97 These are yours. Please check if the following sums can be empty, and provide the init argument if so:
> 
> https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L2269
> 
> https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L2276-L2277
> 
> https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L3456
> 
> https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L3586
> 
> https://github.com/oscar-system/Oscar.jl/blob/6fa696ddb00ac758ae70c45e69419580f23f8396/src/Modules/UngradedModules.jl#L5133

Thanks, I made a PR.
