### ISSUE TITLE
Something goes wrong in the submodule constructor

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1547]
I have this code:
```julia
R, (x,y,z) = QQ["x", "y", "z"]

A = R[x-1 y z; y z x+1]
I = ideal(R, minors(A, 2))
Q, _ = quo(R, I)
L, _ = Localization(Q, units_of(R))

Ares = change_base_ring(L, A)
F = FreeMod(L, 3)
v = [sum([A[i,j]*F[j] for j in 1:ngens(F)]) for i in 1:nrows(A)]
M, _ = quo(F, v)

F = FreeMod(L, 1)
I = ideal(L, [one(L)])
v = gens(M)[1]
h = hom(F, M, [v])
K, _ = kernel(h)
@show iszero(K)
@show iszero(ambient_free_module(K))
w = gens(K)[1]
@show iszero(w)
@show w[1]
```
The problem is: The first coordinate of `w` is `1`, even though `w` is the zero element. This could be happening if the ambient module was already trivial, but it isn't. 

I thought that this bug might be due to my code in the localizations, but I'm afraid it isn't. As far as I could trace it, the problem seems to occur in 
```
sub(F::FreeMod{T}, A::MatElem{T}) where T in Oscar at src/Modules/UngradedModules.jl:2655
```
The input to this function is still clean and sound, but the output is bad.

**Comment by fingolfin** [comment]
Maybe @AlexD97 has an idea?

**Comment by AlexD97** [comment]
I can't reproduce this. I get `ERROR: Incompatible matrix dimensions` when executing kernel(h).

**Comment by tthsqe12** [comment]
> I can't reproduce this. I get ERROR: Incompatible matrix dimensions when executing kernel(h).

Can confirm. @HechtiDerLachs are you on master @ 6fa696d ?

**Comment by HechtiDerLachs** [comment]
Ah! No, I forgot that I had made a fix for that before. I will try to provide a PR with that fix and then you should be able to run the above code on that branch. Sorry for the inconvenience.

**Comment by AlexD97** [comment]
I'm not quite sure if there is an error. `w[1]` should be 1 since it is (by definition) 1 times the first generator (which is zero).

**Comment by HechtiDerLachs** [comment]
> I'm not quite sure if there is an error. `w[1]` should be 1 since it is (by definition) 1 times the first generator (which is zero).

Alright, now I understand. I guess the nonzero entry is due to the coefficients being a sparse vector? Either way, thanks for the clarification.
