### ISSUE TITLE
Comparison of submodules is not generic

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1562]
The code for the ungraded modules is supposed to be generic. But still, a lot of methods are implemented referring to the singular side. This is another instance of that problem: 
```julia
R, (x,y,z) = QQ["x", "y", "z"]
M = R[x-1 y; z x]
I = ideal(R, det(M))
Q = MPolyQuoLocalizedRing(R, I, units_of(R))
A = map_entries(Q, M)
F2 = FreeMod(Q, 2)
B0 = sub(F2, A)[1]
B1 = sub(F2, 2*A)[1]
B0 == B1 # This will error 
```
Comparison of submodules can be implemented on the generic level using submodule membership of generators. But the current implementation tries to fill in the singular side of `ModuleGens` which is impossible in this case. 

It might well be the case that this comparison is faster for modules over rings that can be understood by singular. But I suggest to then write this as a specialized method for the case where the base ring is a multivariate polynomial ring over a field and provide a truly generic method for the generic case. 

@AlexD97 : Have such issues already been addressed in the module code with the different new interfaces that you are currently working on?

**Comment by joschmitt** [comment]
The given example works now, so I close this.
