### ISSUE TITLE
Bug in affine_cone

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1580]
**Describe the bug**
Some dispatch ambiguity. Needs #1579 to run the following example. @HechtiDerLachs 
**To Reproduce**
**Describe the bug**
Some dispatch ambiguity. Needs #1579 to run the following example. @HechtiDerLachs 
**To Reproduce**
```   
   R,(x,) = PolynomialRing(GF(3),["x"])
   Rx,i = localization(R, x)
   x = Rx(x)
   P2 = projective_space(Rx, 2)
   affine_cone(P2) # boom
   S = ambient_ring(P2)  
   (s0, s1, s2) = homogeneous_coordinates(P2)
   A = subscheme(P2, [s0+1//x*s1])
   B = subscheme(P2, [x*s0+s1])
   Acone = affine_cone(A)
   Bcone = affine_cone(B)
```

**Comment by thofma** [comment]
I think some names changed
