### ISSUE TITLE
Warnings about `Hecke.solve_ineq` etc. conflicting with methods in Oscar

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1597]
I am currently seeing these warnings when precompiling (?) Oscar:

```
WARNING: import of Hecke.solve_ineq into Oscar conflicts with an existing identifier; ignored.
WARNING: import of Hecke.solve_mixed into Oscar conflicts with an existing identifier; ignored.
WARNING: import of Hecke.solve_non_negative into Oscar conflicts with an existing identifier; ignored.
```

Indeed we define functions with the same name in `src/PolyhedralGeometry/solving_integrally.jl` (and have done since at least 2021). Not sure what changed (perhaps on the Hecke side?). So perhaps we ought to add suitable `import` statements in the Oscar code, or rename the functions in one place?

Ping @thofma @lkastner

**Comment by thofma** [comment]
Will fix it in Hecke.

**Comment by lgoettgens** [comment]
Fixed by thofma/Hecke.jl#833
