### ISSUE TITLE
inside Oscar, GAP's Browse package cannot be loaded

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#160]
Currently I have problems to get a running version of Oscar.
Earlier this week I had a similar problem when I tried to update my installation, but removing my `~/.julia` directory and then reinstalling everything from scratch worked.
Now even this brute force approach does not help.

This is what I tried, first for installing the released version.
Remove `~/.julia`, call Julia 1.4, enter `using Pkg; Pkg.add( "Oscar" )`.
This works without problem. But then entering `using Oscar` results in the following message.
```
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
ERROR: LoadError: LoadError: could not load library "/export/home/sam/.julia/packages/Singular/5YqNQ/deps/usr/lib/libsingularwrap.so"
/export/home/sam/julia/julia-1.4.0/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /export/home/sam/.julia/packages/Singular/5YqNQ/deps/usr/lib/libsingularwrap.so)
```
When I try the current master branch of Oscar instead of the released version, the error is different.
Again, I remove `~/.julia`, call Julia 1.4, but now enter `using Pkg; Pkg.develop( PackageSpec( path = ".../Oscar.jl" ) ); Pkg.build( "Oscar" )`.
Then `using Oscar` results in
```
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
[ Info: Generating module common
[ Info: Generating module ideal
[ Info: Generating module graph
[ Info: Generating module fulton
[ Info: Generating module fan
[ Info: Generating module group
[ Info: Generating module polytope
[ Info: Generating module topaz
[ Info: Generating module tropical
[ Info: Generating module matroid
Error opening terminal: xterm-256color.
ERROR: Failed to precompile Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13] to /home/sam/.julia/compiled/v1.4/Oscar/aJ3Pg_rIEfL.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
```
(When I set the value of the `TERM` variable to `xterm`, I run into the same error, except that Julia says `Error opening terminal: xterm`.)

**Comment by thofma** [comment]
The first error is the usual https://github.com/oscar-system/Singular.jl/issues/257, which is fixed in the latest version of Singular. But since then there has not been a new Oscar release.

**Comment by fieker** [comment]
On Fri, Sep 11, 2020 at 05:52:00AM -0700, thofma wrote:
> The first error is the usual https://github.com/oscar-system/Singular.jl/issues/257, which is fixed in the latest version of Singular. But since then there has not been a new Oscar release.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/oscar-system/Oscar.jl/issues/160#issuecomment-691076047

Classical solution: find the c++ library in the julia folder - and
remove it or mark it a-rx
This solved teh problem repeatedly....

**Comment by ThomasBreuer** [comment]
Update:
The mentioned error with Oscar-dev (`Error opening terminal: xterm-256color.`) happens in the call `initscr()` in the initialization of GAP's Browse package.
This package is by default not compiled, this explains why others did not observe the problem.

On the other hand, I did not run into this problem before last week.
Moreover, the problem does not occur when I load just GAP.jl, so what causes it in the Oscar.jl context?
(The values of the variables `TERM`, `TERMINFO`, `TERMINFO_DIRS` are the same with or without the error, at the point where `initscr` is called.)

Some experiments:
When the `import GAP` statement in `src/Oscar.jl` is moved above `import Singular` and `import Polymake` then `import GAP` gets processed, including the initialization of `Browse`, and also the rest of the statements in `src/Oscar.jl` get processed without error, but afterwards Browse is apparently initialized again, and the error strikes now, this time even with a Julia crash.

**Comment by mohamed-barakat** [comment]
I should have suspected a connection to `Browse` earlier. I ran into the same problem when I started compiling `Browse` for the `HomalgProject` and therefore discarded it. Sorry for missing it.

**Comment by benlorenz** [comment]
Please try switching GAP.jl to the Yggdrasil binaries for Ncurses, my rather dated `ncursesBuilder` used slightly different configuration options for the directory layout in the terminfo directory (ascii values instead of letters, I think because of `--disable-mixed-case`).

**Comment by fingolfin** [comment]
Yeah, things are close to being ready for me resuming work on https://github.com/oscar-system/GAP.jl/pull/421 which switches GAP.jl to using JLLs. There were various issues in the past couple months preventing this, but I think now I can take care of those (ideally by switching to a GAP_jll, but one relevant PR for that was only merged into Julia today, so I'll have to see what I can do).

Will make this a priority next week.

**Comment by ThomasBreuer** [comment]
Just for the record, in order not to forget it:
After `using Oscar` and calling `GAP.prompt()`, line editing in the GAP session does not work.
Probably this problem will disappear when GAP_jll is available.

**Comment by fingolfin** [comment]
I am closing this in favor of https://github.com/oscar-system/GAP.jl/issues/553 (even though this issue here is technically older)
