### ISSUE TITLE
GAP groups: bring GAP groups and Hecke.jl groups (`GrpAbFinGen`)  together (e.g. providing homomorphisms, aligning names)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#161]

**Comment by fingolfin** [comment]
@ThomasBreuer : so @fieker and me discussed this a bit tomorrow. Here's my current idea (which we can still revise): we add a new function `isomorphism(T, G)` (name could clearly be improved). It computes an isomorphism from the group `G` into an isomorphic group `H` of type `T`. So you might call it as `isomorphism(GrpAbFinGen, G)` where `G` is any abelian GAP group; or conversely e.g. `isomorphism(PermGroup, G)`.

So this also replaces `isomorphic_perm_group`, `isomorphic_fp_group`, `isomorphic_pc_group`. We would then `@deprecate` those.

The isomorphic group then can be obtained via `codomain(iso)`. But in addition, we should allow writing `T(G)` in accordance with the usual Julia conventions; so e.g. `GrpAbFinGen(someAbelianPermGroup)` as shorthand for `codomain(isomorphism(someAbelianPermGroup))` (though of course more efficient implementations may be supplied).

**Comment by fingolfin** [comment]
Some more thoughts on how things map:
- `Hecke.id(G)` is `Oscar.one(G)`
- `Hecke.conjugancy_classes` is a typo (PR submitted)
- `Hecke.psylow_subgroup` is `Oscar.sylow_subgroup`
  - and the one in Oscar should accept an `fmpz` (or ideally `Union{fmpz,Base.Integer}`) as the prime
- `Hecke.commutator_subgroup` is `Oscar.derived_subgroup` (we probably should accept both names?)
- `derived_series`
- ...

**Comment by ThomasBreuer** [comment]
Concerning `Union{fmpz,Base.Integer}`, this occurs already frequently; should we define a name for it? (`OscarInteger`?)

Concerning `commutator_subgroup`, I had added a comment to `src/Groups/GAPGroups.jl`:

    In the literature, the name commutator subgroup is often used as a synonym of derived subgroup.
    GAP defines `CommutatorSubgroup( G, H )` for arbitrary groups `G`, `H` (in the same family);
    thus the result is in general not contained in `G` or `H`,  and we do not know into which group the result should be embedded.
    Is this function useful at all? (The name `Commutator*Subgroup*` is irritating, isn't it?)

**Comment by fingolfin** [comment]
We can still have `commutator_subgroup(G)` be an alias for `derived_subgroup(G)` and still at the same time support `commutator_subgroup(G, H)`

**Comment by thofma** [comment]
I am currently changing it such that the only groups leaking from Hecke into Oscar are the abelian ones. I will adjust them so that the functions use the same names as in `Oscar/src/Groups/...`. I am not sure we will use `one(G)`. Isn't this something where we would use the groups interface package that we hooked up?

**Comment by thofma** [comment]
@fingolfin @ThomasBreuer: For a project we would like to create `h = hom(::AutomorphismGroup{Hecke.TorQuadMod}, ::GrpAbFinGen, L::Vector)`, where `L` is the list of images of the generators of the domain. For the actual computation, say of the `kernel`, this would of course turn the codomain into something GAPish (this is how it is done at the moment) and then translate back and forth (no problem with that). But it would be really nice to have a way to create `h`. Of course I don't want to do this for every domain type, so do you have any suggestions? I am happy to give it a shot but I would like to hear how you imagined this to work.

**Comment by ThomasBreuer** [comment]
Now #2123 is merged, which provides a lot of "group functionality" for `GrpAbFinGen` groups.
Some names such as `commutator_subgroup` have not yet been added or unified, but I think the other tasks from this issue have been implemented.
In particular @thofma's wish for a generic `hom(::GAPGroup, ::GrpAbFinGen, ::Vector{GrpAbFinGenElem})` has been addressed in pull request #1890.
Thus we could close this issue.
