### ISSUE TITLE
`visualize` leads to Polymake exiting ("crashing") the Julia session when used in WSL

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1615]
We get the following crash on a Windows machine running OSCAR under WSL (it also happens with the dev version, @fieker can reproduce it):
```
julia> using Oscar
 -----    -----    -----      -      -----
|     |  |     |  |     |    | |    |     |
|     |  |        |         |   |   |     |
|     |   -----   |        |     |  |-----
|     |        |  |        |-----|  |   |
|     |  |     |  |     |  |     |  |    |
 -----    -----    -----   -     -  -     -

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.10.2 ...
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2022 by The Oscar Development Team

julia> visualize(simplex(3))
PropertyValue wrapping Visual::Polytope
reference to an undeclared variable $Visual::webbrowser at /home/markus/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/apps/common/rules/threejs.rules line 83.
$
```

So there are two problems:
1. It can't determine a web browser. Annoying, would be nice to have this work on WSL, but in the end OK...
2. it then crashes; this is serious and should of course not happen.

**Comment by fingolfin** [comment]
As to problem 1, a bunch of suggestions as to what might work on WSL are listed here: < https://superuser.com/questions/1262977>. Of course to know what *actually* works... we can ask @fieker to test but reading the answers to that question suggestions that all methods may have issues on some user's system *sigh*.

**Comment by benlorenz** [comment]
We have a [special polymake script for WSL users](https://polymake.org/doku.php/download/start#windows_10_with_the_linux_subsystem) to open the proper browser, the tricky part ist getting the correct path to the files that we need to open. (I don't know if this still works, this was written quite a while ago)

Maybe we can find a way to integrate this here as well.

I will have a look at the "crash" (in fact this is just a `exit` call directly from perl), usually such an error should throw an exception instead.
