### ISSUE TITLE
Clarify naming policy further: "long_form_names" over "shrt_frm_nms"

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1623]
Some of us (including @fieker @ThomasBreuer @thofma) recently discussed the discoverability of Oscar function names, and in the end agreed that the only way to make this possible in general is to avoid arbitrary abbreviations and to spell out things.

We should make this explicit in the dev guide; and then start to adapt everything for the resulting changes. As with our decision to use underscores consistently as name separators, this creates some tension with Julia builtin functions and some packages. These can be partially addressed by using `@alias`.

Some changes implied by this:
- `gen` -> `generator` (but of course we can keep the old name as an `@alias` indefinitely)
- `gens` -> `generators`
- `ngens` -> `number_of_generators`
- 
- ... and many many more

**Comment by fingolfin** [comment]
More stuff from some notes I had sitting around locally (in some cases overlaps with the above):

- short names that need longer alias (or be renamed outright?)
  - gen
  - gens
  - minpoly
  - charpoly
  - n_connected_components  -> `number_of_connected_components` ?
  - n_maximal_cells
  - n_maximal_cones
  - n_maximal_polyhedra
  - n_nodes
  - haspreimage
      - urgh there is even a warning saying this:
        > Do not confuse haspreimage with the function has_preimage, which
        > works on variable of type GrpGenToGrpGenMor

- what about
  - nrays
  - nrels
  - ngens
  - ncols
  - nv
  - ne
  - Hecke.t2
  - Hecke.norm2
  - psylow_subgroup (conflict with `sylow_subgroup`)
  - quotient (exists!) vs. quo
  - intersection vs. intersect

**Comment by JohnAAbbott** [comment]
Should we copy the discussion from here into the issue #1826 ?  And then "close" this discussion?

**Comment by fingolfin** [comment]
Done
