### ISSUE TITLE
Implement weighted projective space as toric variety, scheme and possibly more

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1644]
Possibly also for schemes.

cc @Lkastner and @HechtiDerLachs

**Comment by HechtiDerLachs** [comment]
What is the message? That we would like to have it? Yes, we do! Also for the schemes. I would be happy to have assistance in this as I have personally never actually worked with weighted projective space. Also, @afkafkafk13 might have some things in mind to take into account as these spaces frequently appear in resolutions of singularities.

**Comment by fieker** [comment]
we have weighted projective spaces:
```julia> Oscar.proj_space(QQ, [1,2,3])
(Weighted projective space of dim 2 over Rational Field and weights [1, 2, 3]
, MPolyElem_dec{fmpq, fmpq_mpoly}[x[0], x[1], x[2]])
```
I don't recall how far they work over Z and Z/nZ

**Comment by HereAround** [comment]
The toric part is currently missing this (unless I am overlooking something obvious). So I intend to close this gap on the toric side (that is the message @HechtiDerLachs - sorry for the confusion).

**Comment by HechtiDerLachs** [comment]
> we have weighted projective spaces:

Where? I don't find them in the documentation. And tab-completion also does not lead me anywhere.

**Comment by HereAround** [comment]
> > we have weighted projective spaces:
> 
> Where? I don't find them in the documentation. And tab-completion also does not lead me anywhere.

That also caught me by surprise. So I started digging ("git grep "weighted") and I found... definitions on (weighted) projective spaces in `src/Geometry/basics.jl`. Sadly, none of these functions are documented.

**Comment by HereAround** [comment]
Let me draft a PR on this behalf.

**Comment by HechtiDerLachs** [comment]
Is the file `src/Geometry/basics.jl` due to Delfine Pol? Who was working on that and for which purpose?

**Comment by HereAround** [comment]
What is Pol? For the most part, @fieker worked on this file. `git blame` can tell you when and also who else modified the file if you are interested.

**Comment by HechtiDerLachs** [comment]
That was a former colleague of ours in KL. I'm not sure I spelled her name correctly, sorry. She had been working out some package on curves. Thanks for reminding me about `git blame`; I didn't know which command would do that job.

**Comment by HereAround** [comment]
Thanks for the heads up. I need to read more carefully (I noticed "define" rather than Delfine. Silly me...)

**Comment by fieker** [comment]
On Tue, Oct 25, 2022 at 01:46:55AM -0700, Matthias Zach wrote:
> That was a former colleague of ours in KL. I'm not sure I spelled her name correctly, sorry. She had been working out some package on curves. Thanks for reminding me about `git blame`; I didn't know which command would do that job. 
> 
Delphine Pol

**Comment by HereAround** [comment]
The following PR adds the weighted projective space as toric variety https://github.com/oscar-system/Oscar.jl/pull/1646. This is what I had in mind/what I need for now.

**Comment by HereAround** [comment]
I just merged https://github.com/oscar-system/Oscar.jl/pull/1646. So this issue is closed as long as toric varieties are concerned.

It might be good to leave this open, so we do remember to add the weighted projective space also for schemes?

**Comment by HechtiDerLachs** [comment]
It's all good. We'll remember this to be on our list.

**Comment by HereAround** [comment]
Ok. Then I close this issue now.
