### ISSUE TITLE
Should affine schemes have an ambient space.

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1664]
Since we seem to disagree on whether affine schemes in Oscar (should) have an ambient space or not, I would like to collect the pro's and cons. 
 @afkafkafk13  @jankoboehm  @HechtiDerLachs @thofma @HereAround @wdecker @thofma  

Surely, I have forgotten many pros and cons. Please write yours and I will add them. 
Note that, mostly, this is a question about the user interface and not so much of the implementation and underlying algorithms. 

Here is the **current situation** as I see it. 

Let `MPolyAnyRing:= Union{MPolyRing,MPolyQuo, MPolyLocalizedRing, MPolyQuoLocalizedRing}
- Most affine schemes are constructed as `X=Spec(R::MPolyAnyRing)`. 
- By construction `R` comes with a map  $P\to R$ where $P$ is a polynomial ring over some base ring $B$. 
This $P$ can be accessed by `P=ambient_ring(X)`. It is not part of the "mathematical interface" but part of the "algorithmic interface".
- Two affine schemes `X,Y` compare via `==` , `issubset`, `isopen_embedding`, `is_closed_embedding`  if `ambient_ring(X) === ambient_ring(Y)` . 
- `coordinates(X)` returns elements of `P`. 

_Remarks:_
- we do not seem to have an official concept/interface of an `S`-algebra `R` in Oscar. One could argue that this is what `base_ring` does. But for our purposes it is unexpected that `base_ring(R/I) = R` i.e. that the quotient`R/I` is seen as an `R`-algebra and not as an `S` algebra  (maybe for good reasons) ... so the `base_ring(Spec(SomeRing)` cannot be consistently derived from `SomeRing` alone.
- Maybe we should rather define a `base_scheme`? and a `structure_morphism`? (but this is kind of independend of the ambient yes/no question). 
- A more clean/explicit way would be to allow constructors which take a ring homomorphism (the structure morphism) as input. But that seems very clumsy.

**Abstract affine Schemes** 
- Affine Schemes do not have an ambient space

Pros:
- we are closer to the textbook definition 

Cons:
- the comparison methods, and coordinates, rely on the ambient_ring which is part of the "algorithmic interface".  Hence they are not part of our "mathematical interface" :-(. More mathematically speaking: Two abstract schemes $X$ and $Y$ do not compare. The common way to relate them is by a morphism $g: X -> Y$ which can be an (open/closed) embedding, an isomorphism or anything else. 
- the methods that derive from `ambient_ring` do not have a clear interpretation. Such as `saturated_ideal`, `strict_modulus`. I tend to  forget what they mean. This indicates that they are problematic and not very user friendly.  
- `defining_ideal` is also part of the "algorithmic interface"
- `ambient_ring` does not always seem to be defined (only for `MPolyAnyRing`)

Remarks:
- a solution for the coordinates is to return generators of the `coordinate_ring(X)= OO(X)` instead.
- I am not aware of anyone else who divides into a "mathematical interface" and an "algorithmic interface".
- I think that the "algorithmic interface" should not be part of the interface at all, but just internal methods, i.e. not exported. We want to stay as close to the mathematics as possible. 
- the "algorithmic interface" seems to me more like a "commutative algebra interface".  Mixing "geometric interface" and "commutative algebra interface" seems a bit problematic because the terminology does not generalize well to covered schemes which are our ultimate goal.

 **Embedded affine Schemes** 
- most affine schemes have an `ambient_affine_space` at least the ones that derive from `MPolyAnyRing` 
- for `R` a field, or `ZZ` or something which is not an `MPolyAnyRing`  and `X= Spec(R)` we could set `ambient_affine_space(X)= X` which is justified by `Spec(R) = AA^0_R`.  More precisely if `R` is an `S` algebra, then `Spec(R)` should live in $\mathbb{A}^n_S$  (hopefully for $n \in \mathbb{N}_0$ 
- what the ambient space is should be clearly documented
- `ambient_ring` is renamed to `ambient_coordinate_ring`
- `ambient_coordinates(X)` live in `ambient_coordinate_ring(X)`
- `coordinates(X)` are elements of `coordinate_ring(X)=OO(X)`
- two schemes `X` and `Y` compare if and only if `ambient_affine_space(X) == ambient_affine_space(Y)`
- `embedding` returns a morphism `f: X -> ambient_affine_space(X)`, its pullback is the map `P -> R=OO(X)`
- The "algorithmic interface" are shortcuts for internal use 
 
Pros:
- It is clear where the coordinates come from and when doing calculations coordinates are important
- To move things to the `ambient_coordinate_ring`: Use the homomorphism `pullback(embedding(X))`.
- The meaning of `defining_ideal(X)< O(ambient_affine_space(X))` seems clear.
- Comparison of affine schemes is mathematically well defined if they have an ambient space.
- I is clear what an `A = ambient_affine_scheme` should satisfy: There should be an embedding `X -> A` .. but this property does not uniquely define `A`... see cons. 

Cons:
- in textbooks the spectrum of a ring `Spec(R)` does not have an ambient space (neither does it have coordinates) 
- in some cases our choice for `ambient_affine_space` does not seem intuitive
- it is implicitly inferred from the ring `R` -- this does not seem to be globally consistent since we have 
- For `X = Spec(R)` and `Y=Spec(R/I)` We have `ambient_space(X)==ambient_space(Y)` but not `ambient_space(X)===ambient_space(Y)` (which does not bother any of our methods so far), so there will be many equal ambient spaces flying around. 

Remark:
- to have less ambient spaces flying around one could cache `Spec(R)` if and only if `R` is cached. Then there would be a unique `Spec(ZZ)` and a unique `Spec(QQ)` and a unique `Spec(K[x1,...,xn])` ... but I am not sure about the implications.
- A very consistent but somewhat extreme possibility is to not allow Spec(R) at all. But to only allow geometric constructors such as
`subscheme(X, I)` for $X = \mathbb{A}^n_S$ or some subscheme thereof. (This is how Magma does it - but magma does not consider covered schemes I think.)
This allows to set the base scheme once for the ambient. The ambient is always well defined and not implicitly inferred from the input.

**Comment by afkafkafk13** [comment]
Changed MPolyAnything to MPolyAnyRing to make it clearer.

**Comment by fieker** [comment]
Out of band comment: base_ring is fragile. It was introduced to return in a
complicated ring construction the previous step, never intended to be
linked to Nath. Thus in quotients it return the ring, in finite fields it
return nothing as in Nemo they are primitive objects ...

**Comment by afkafkafk13** [comment]
As so many methods currently rely on ambient_ring, it feels dishonest to me to hide the fact of computing in an embedded situation from the user. 
Clearly there are locally ringed spaces/ affine schemes which do not have an embedding, but for these a significant part of the functionality does not work. So there is already a clear distinction into two classes: MPolyAnyRing and other rings. Things like dimension make sense without embedding, codimension does not and depends on the embedding. I am in favor of disclosing the map P -> R as a mathematical object to the user and at least:
- give access to the data of the ambient affine scheme (allowing the user to also change the map P -> R to some P' -> R it needed -- I do not say mutation, but having control of the object to create a copy with suitable changes)
- clearly document for all methods whether they depend solely on R or on the entire map P->R.

**Comment by afkafkafk13** [comment]
> Out of band comment: base_ring is fragile. It was introduced to return in a complicated ring construction the previous step, never intended to be linked to Nath. Thus in quotients it return the ring, in finite fields it return nothing as in Nemo they are primitive objects ..

Yet another reason to now discuss properly, what we really want for our affine schemes!

**Comment by jankoboehm** [comment]
A clean way could be to allow Spec essentially only for MPolyRing, MPolyLocalizedRing, and a few more, and then have a subscheme constructor subscheme(X, I) where X is either such a Spec or a subscheme. The embedding is then returned. This allows one to construct subobjects of a well-defined, unique, specified embedding object so that further constructions can rely on === instead of == for the embedding object, moreover it limits and controls the amount of parents constructed. Furthermore it avoids having a unique Spec for an MPolyRing etc. For consistency, Spec can still work for quotient, then contructing an embedding object. For the subquotient modules the analogous question came up and there went quite a bit of thought into it, and this solution seems to work well.

**Comment by simonbrandhorst** [comment]
Resolved by #1683

**Comment by thofma** [comment]
So the answer is yes?

**Comment by HechtiDerLachs** [comment]
The answer is "yes" for instances of `AbsSpec{<:Ring, <:MPolyAnyRing}` with `MPolyAnyRing` as in our discussions. Otherwise: "No".
