### ISSUE TITLE
Crash in PolyhedralGeometry (caused by OpenMP code?)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1674]
On the M1 mac `munk` in Kaiserslautern, I just got this crash with the Julia 1.8.2 installed there, doing `test Oscar` against the current master branch:
```
Test Summary:       | Pass  Total  Time
SubdivisionOfPoints |   15     15  0.6s
Test Summary: | Pass  Total  Time
OscarPolytope |  105    105  2.9s
OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.

signal (6): Abort trap: 6
in expression starting at /Users/horn/Projekte/OSCAR/Oscar.jl/test/PolyhedralGeometry/timing.jl:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 137297125 (Pool: 137203552; Big: 93573); GC: 50
```

However, I've just installed updates on that machine, and I'll retry once it is back up running.

**Comment by thofma** [comment]
Here is the answer I got a few weeks ago from @benlorenz: Looks like a bug in openmp for apple m1: https://github.com/llvm/llvm-project/issues/54422 (OP and the last report look like our crash).

**Comment by benlorenz** [comment]
A workaround ist to set `OMP_NUM_THREADS=1`.

**Comment by fingolfin** [comment]
Perhaps then we should default to that on M1 or even just disable OpenMP there?

**Comment by benlorenz** [comment]
As posted in #1670 I have prepared a test-build of [LLVMOpenMP_jll](https://github.com/benlorenz/LLVMOpenMP_jll.jl) version 15 which for me fixes the crashes and the timings seem fine on munk. I will prepare a PR for Yggdrasil with this.

**Comment by benlorenz** [comment]
The crash should be fixed with the LLVMOpenMP update, I ran those tests on munk many times.
