### ISSUE TITLE
More efficient Serialization of Arrays

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1706]
It would be great to have more memory efficient serialization for 
`Vector{fmpz}` and `Vector{Vector{fmpz}}`
```
L = fmpz.(rand(-1000000:1000000,10000000))
save("test1",L)
```
creates a file of 763 MB
```
fi = open("test2","w")
print(fi,L) ; 
close(fi)
```
Creates a file of only 89 MB  which is about 8.5 times smaller . So there is room for improvement. 

I have some larger datasets consisting of `Vector{Vector{fmpz}}` 
Let's say an array of 6.5 Million entries consisting of Vector{fmpz} of length 26. 
Here size matters for me and loading the files lets my computer go out of memory.
(which it certainly shouldn't because the arrays fit into memory).

**Comment by fingolfin** [comment]
Agreed. The JSON could be more compact; and we could also offer alternative formats. 

A lot of this is used up by the UUID, which is completely useless here; see also issue #1340. Using a flat integer that just reference all objects in the order they get created would take up a lot less space (but also be less resilient against minor damage to the data file, and be less "composable"). 

Also #1507 is somewhat related.

**Comment by fingolfin** [comment]
Ping @antonydellavecchia @lkastner
