### ISSUE TITLE
Add resp. expose more combinatorics features

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1732]
We already have some things (e.g. `subsets` from Hecke) which shoud be listed in the relevant chapter of the OScar manual.

But we also wanted to import code by @ulthiel from https://github.com/ulthiel/JuLie.jl/tree/master/src/combinatorics and possibly other sources.

**Comment by fingolfin** [comment]
Regarding `subsets` is also noticed that `subsets(1:5, 2)` doesn't work -- probably just a matter of an overly restrictive function signature

**Comment by fieker** [comment]
1:5 is no set...
Can be added

**Comment by ulthiel** [comment]
@micjoswig (et. al., e.g., @ThomasBreuer) will make a start integrating some stuff from JuLie (specifically, Schur polynomials). Once there's a skeleton and I see how it works, I'll help integrating and contribute future stuff directly to OSCAR. JuLie will be archived.

**Comment by wdecker** [comment]
Sounds great!

**Comment by fingolfin** [comment]
Closing in favor of issue #3147
