### ISSUE TITLE
rational_solutions 

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1744]
@ederc Can one use msolve to compute all rational solutions? If not, how hard would it to quickly get something non-optimal into Oscar?

**Comment by ederc** [comment]
Without any extra assumptions on the input it is undecidable. We will try to provide through `AlgebraicSolving.jl` a solution for zero dimensional input (approx. 2-3 weeks).

**Comment by fieker** [comment]
I understood the question to be for dim==0, else you run into Hilbert's n-th problem

**Comment by fieker** [comment]
see also pr #1748

**Comment by ederc** [comment]
I'm just on the way bumping `AlgebraicSolving.jl` which does now provide a function `rational_solutions()`. As such a naive function was already added via #1748 to `mpoly.jl`, how shall we call our function?

**Comment by thofma** [comment]
Can you wrap it as `_rational_solution` in Oscar? I will then hook it up with the rest, so that `_rational_solution` is called when applicable.

**Comment by ederc** [comment]
I will go with `_rational_solutions` since there might be more than one solution. ;)

**Comment by thofma** [comment]
Hehe.

P.S.: Ping me in the Oscar PR.

**Comment by ederc** [comment]
Yup.
