### ISSUE TITLE
Support `poly in ring` test?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1747]
I was surprised by this:
```
julia> U,x = ZZ[:x] ; x in U
ERROR: MethodError: no method matching iterate(::FmpzPolyRing)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:872
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:872
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:712
  ...
```

I think it would be nice if this just returned `true`

**Comment by thofma** [comment]
Hm, I am not sure why we would want this. As shorthand for `parent(x) == U`?
- If `R = parent(x)`, should `x in R` always return `true`? And `false` for anything else?
- Is `1 in U == true/false/error`?

**Comment by afkafkafk13** [comment]
@thofma has a point here: Whatever we return for '2 in U' will leave some users puzzled. Some will expect that the natural inclusion is fully transparent and others will expect it to not be taken into account. 
Some will ask 'p in base_ring(U)' for the element p=2 of U and expect this to be true or false depending on their perspective....
 
To me it would make sense to give a more meaningful error message (e.g. pointing to a relevant spot in documentation), but not implement a method here.

**Comment by tthsqe12** [comment]
We already have started code like this
https://github.com/oscar-system/Oscar.jl/blob/e1f4a3e59d30b9a379e73767150cad13843cd920/src/Modules/UngradedModules.jl#L219-L221

**Comment by thofma** [comment]
We might need to remove it, depending on the decision we reach.

**Comment by fingolfin** [comment]
I think my motivation for the issue was uniformity for someone coming from GAP, where `elm in SomeAlgebraicStructure` pops up a lot. It also does for groups in Oscar (but obviously that's my fault to a large degree, so this is not an argument for anything).

In contrast, we don't really have subrings, do we? So I guess `in` would amount to a parent check in most cases and one may indeed question how useful it is (well, `x in R` still is quicker to type and read than `parent(x) == R` but that's a weak argument).

So perhaps we should just close this and perhaps excise some existing `in` methods of this kind?

**Comment by fingolfin** [comment]
Discussed this in triage and I think we are mostly fine these days and close this
