### ISSUE TITLE
Can we tell in OSCAR if two quotient rings are identical or isomorphic?

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1772]
This question was raised by @bschroter and is partially related to https://github.com/oscar-system/Oscar.jl/pull/1684, where we compute Chow rings of matroids and toric varieties. Both happen to be quotients of certain polynomial rings. The theory tells us, that those rings must be isomorphic. Indeed, we checked this  by hand for simple examples. Still, for more involved examples (and possibly many other tasks) one might wonder if OSCAR can test this.

My naive approach would be the following:
* Construct a map of the polynomial rings by sending generators to generators. (Call it `b`).
* Compute a ~~post_inverse~~ pre-inverse for the quotient map of the domain. Call it `a`.
* Compute/access the quotient map of the codomain. Call it `c`.
* Finally tell if the composition `f = c \circ b \circ a` is an isomorphism of rings.

I have not tried this in an explicit example yet. Also, I was under the impression that isomorphism tests are typically hard (hence, if this is implemented for rings yet).

Any thoughts and suggestions are welcome.

**Comment by thofma** [comment]
What is the "post_inverse" in the second step? Is this a ring homomorphism?

**Comment by HereAround** [comment]
I meant the "inverse" of the quotient map f: R -> R/I, i.e. the pre_inverse g: R/I -> R s.t. f \circ g = id_(R/I).

(I mistakenly referred to it as post-inverse above. Sorry for the confusion.)

**Comment by thofma** [comment]
But is `g` a morphism of rings? Otherwise I don't know why `f` should be a morphism at all.

**Comment by HereAround** [comment]
`f: R -> R/I` is by construction a surjective ring homomorphism, namely the natural quotient map or the canonical homomorphism. As for its pre_inverse `g`, I am not entirely sure right now.

**Comment by wdecker** [comment]
The suggested approach has several problems, for example the one already mentioned by @thofma , but also in the first step: what does this mean if the ideals are in polynomial rings with a different number of variables? I am afraid, we do not know how to check whether two quotient rings are isomorphic.

**Comment by HereAround** [comment]
Thank you @wdecker . Yes @thofma is right. This is too naive.

But still, maybe there is hope for more specialized settings? For what I have in mind, the number of variables would be identical.

Specifically, what @bschroter brought to my attention was that Chow rings for certain matroids and toric varieties are isomorphic. Each of which is a quotient ring in a polynomial ring. The number of variables of those polynomial rings are (by construction) identical. Here is an example:
```julia
julia> M = uniform_matroid(2,4);
julia> pm_fan = Polymake.tropical.matroid_fan{min}(M.pm_matroid);
julia> fan_rays = pm_fan.RAYS[1:length(flats(M))-2,3:length(M)+1];
julia> fan_cones = pm_fan.MAXIMAL_POLYTOPES[1:pm_fan.N_MAXIMAL_POLYTOPES,1:length(flats(M))-2];
julia> polyfan = PolyhedralFan(fan_rays,fan_cones);
julia> tv = NormalToricVariety(polyfan);
julia> tCH = chow_ring(tv)
Quotient of Multivariate Polynomial Ring in x1, x2, x3, x4 over Rational Field by ideal(x1 - x2, -x2 + x3, -x2 + x4, x1*x2, x1*x3, x1*x4, x2*x3, x2*x4, x3*x4)

julia> mCH = chow_ring(M)
Quotient of Multivariate Polynomial Ring in x_{1}, x_{2}, x_{3}, x_{4} over Rational Field by ideal(x_{1} - x_{2}, x_{1} - x_{3}, x_{1} - x_{4}, x_{1}*x_{2}, x_{1}*x_{3}, x_{2}*x_{3}, x_{1}*x_{4}, x_{2}*x_{4}, x_{3}*x_{4})
```
One would hope that one can tell - without staring at the quotients for an extended period - that `tCH` and `mCH` are isomorphic. Any hope for this, or is all lost?

**Comment by wdecker** [comment]
I get this error:

julia> tCH = chow_ring(tv)
ERROR: ArgumentError: The Chow ring is (currently) only supported for simplicial and complete toric varieties

However, by copy and paste, we can of course compare the moduli which are equal in this case:

julia> R = base_ring(mCH)
Multivariate Polynomial Ring in x_{1}, x_{2}, x_{3}, x_{4} over Rational Field

julia> x1 = R[1]
x_{1}

julia> x2 = R[2]
x_{2}

julia> x3 = R[3]
x_{3}

julia> x4 = R[4]
x_{4}

julia> I = ideal(R, [x1 - x2, -x2 + x3, -x2 + x4, x1*x2, x1*x3, x1*x4, x2*x3, x2*x4, x3*x4])
ideal(x_{1} - x_{2}, -x_{2} + x_{3}, -x_{2} + x_{4}, x_{1}*x_{2}, x_{1}*x_{3}, x_{1}*x_{4}, x_{2}*x_{3}, x_{2}*x_{4}, x_{3}*x_{4})

julia> I == modulus(mCH)
true

**Comment by HereAround** [comment]
The functionality was extended in https://github.com/oscar-system/Oscar.jl/pull/1684, which I merged this afternoon. Most likely you need to update to the latest master branch.

**Comment by HereAround** [comment]
Thank you all for the useful feedback. Let me summarize:

* The approach that I sketched was indeed very naive. In a general setting, I am now convinced that this problem is a rather though cookie to crack.
* For the case that one has the same number of variables however, there is hope. And that is exactly how @bschroter and I will proceed with this.
