### ISSUE TITLE
Integration of bibtool into the CI possible?

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1773]
"As described in the documentation (https://docs.oscar-system.org/stable/DeveloperDocumentation/documentation/), we use
`bibtool` to standardize the bibkeys and also the bib-entries. Inspired by a discussion with @simonbrandhorst (and also with @lkastner today), I was wondering if we could integrate `bibtool` into the CI.

I guess the dream would be a CI run, that performs as follows:
1. Execute `bibtool`.
2. Check if `docs/oscar_references.bib` changed. Otherwise pass.
3. Apply `bibtool` and check for changes. If application of `bibtool` did not lead to changes, pass.
4. Find out which `bibkeys` changed, replace them (e.g. via `sed`) and add a corresponding commit.

Is something of that sort possible? Maybe @fingolfin knows/has an opinion?

**Comment by fingolfin** [comment]
Checking if running `bibtool` results in a diff, and failing CI in that case? That's fairly easy.

Adding a commit "fixing" things? Very tricky, and possibly confusing, because it'll modify the branch and in the past doing that often resulted in much pain and suffering for non-git-experts. So I don't think it's worth the effort. But of course the generated error should be helpful and point out how to locally address the issue.

**Comment by HereAround** [comment]
My hope was to actually remove the step "apply bibtool" from our (=human) workflow. But yes, I suspected that the fixing part would be tricky, in particular in the CI. Thank you for confirming @fingolfin .

The next best thing that comes to my mind is a fixing script that executes the changes **locally**. This is probably less confusing but still tricky. But I am not sure if this is feasible/efficient. It merely replaces the task "apply bibtool" with "apply new shiny script". In addition, I like to think that we usually add only a few references per PR, so the necessary changes will not take too long by hand.

Maybe the only reasonable adjustment is a CI check to see if running `bibtool` results in a diff?

**Comment by thofma** [comment]
I agree that we should just check for a fixpoint, i.e., `bibtool(bla.bib) == bla.bib` and throw an instructive error in case it fails.

**Comment by thofma** [comment]
Fixed in #1807
