### ISSUE TITLE
Addition of empty ideals fails

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1778]
I had some code where I was adding two ideals `I` and `J` over a polynomial ring `R` which both had an empty set of generators. Then [this](https://github.com/oscar-system/Oscar.jl/blob/master/src/Rings/mpoly.jl#L220) line caused trouble, because there was no element set. 

I tried to produce a minimal example, but failed. The point is that I did not find the constructor which would have an ideal with an empty set of generators as an output. But since this occured in my code, I know that there is a hole somewhere where such things can sneak in.  Either way, I personally think it would make sense to allow ideal with an empty set of generators. 

If necessary, I can upload a branch with the failing example. However, that will then be of more complicated nature. 

Edit: I just saw that the constructor above was called from [this](https://github.com/oscar-system/Oscar.jl/blob/master/src/Rings/mpoly-ideals.jl#L146) line. Most probably you already have the reason for the problem there.

**Comment by thofma** [comment]
I guess trying to add two zero ideals should trigger it?

**Comment by HechtiDerLachs** [comment]
> I guess trying to add two zero ideals should trigger it?

I thought so, but didn't succeed. But I hoped that either way, the problem was already sufficiently visible.

**Comment by thofma** [comment]
I agree with you that we should allow empty generating sets.

On the other hand, the `remove_zeros!` function only removes things in case `!is_zero(I)`, so it is not clear what happened. Do you have an example to reproduce it? Can also be a call to some (unrelated) geometric code.

**Comment by wdecker** [comment]
It seems to me that this function

  function IdealGens(O::Vector{T}; keep_ordering::Bool = true) where {T <: NCRingElem}
    return IdealGens(parent(O[1]), O; keep_ordering = keep_ordering)
  end

and similar functions in this file and other files are buggy: If no ring or so is given as an argument, we need to assert that the length of the vector is at least 1. Correct?

**Comment by thofma** [comment]
Yes, they should assert that. But given that they are for internal use only (are they?), it is less critical I guess.

**Comment by wdecker** [comment]
@jankoboehm What do you think?

**Comment by HechtiDerLachs** [comment]
I could finally reproduce the bug. It is a bit complicated, though. 

Check out [this](https://github.com/HechtiDerLachs/Oscar.jl/tree/exposing_a_bug_in_IdealGens) branch and run 
```julia
include("test/Schemes/ToricSchemes.jl")
```
That should then fail at the point described above.

**Comment by HechtiDerLachs** [comment]
One more thought on this issue: In our implementation of `IdealSheaf` it is essential that the internals of the ideals do **not** mess with the generators. I.e. if I type `I = ideal(R, [f, g])`, then I have to be able to rely on the fact that `gens(I)` reproduces either the list `[f, g]` for me, or their images under some canonical/coercion map to `R`. In particular, I want to find a list of length `n` whenever my input is of length `n`. This is important when it comes to computing transition matrices which are expected to be of the corresponding sizes. 

Now the constructor `I = ideal(R, [])` seems to break this paradigm when `R` is a multivariate polynomial ring: It silently adds `[0]` as a list of generators rather than keeping it empty. In my code for transition matrices, I would add a `0 x n` matrix `A` for the transition to another ideal `J`. When populating this matrix, e.g. via calls to `coordinates(a, I)`,  I would now get an error, because the output vector has length 1 rather than 0. 

In my personal opinion, such a behavior should not be considered correct. Note that such degenerate cases will appear frequently in automated computations and it is not a neglectable boundary case.

**Comment by thofma** [comment]
At the moment for us the datum of an ideal comes always with a fixed generating set. So I fully agree with you on this.

P.S.: I did not have time to look at your example yet.

**Comment by HechtiDerLachs** [comment]
I can confirm that the issue was solved by #1787. Thanks!
