### ISSUE TITLE
Move OSCAR homepage from oscar.computeralgebra.de to www.oscar-system.org ?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1792]
Right now the official OSCAR homepage is https://oscar.computeralgebra.de 

Some time ago I already registered https://www.oscar-system.org and set it up to forward to https://oscar.computeralgebra.de; also https://oscar-system.org forwards to it.

Based on some informal polling on the Slack, it seems I am not alone in preferring https://www.oscar-system.org -- e.g. it seems "more international" (`.de` instead of `.org)`.

Actually I already changed our documentation to be served under https://docs.oscar-system.org/ (instead of https://oscar-system.github.io/Oscar.jl/) and so far at least nobody complained ;-).

I thus propose we make https://www.oscar-system.org the new canonical homepage URL, and let https://oscar-system.org and https://oscar.computeralgebra.de redirect to it. (That is, *all existing links* would keep working, it is just a matter what URL is shown in the end in the address bar, and of course we'd also change our links to the website in our READMEs, manuals etc.)

I'll wait and here if @fieker @micjoswig @wdecker have any objections, or if they are OK with it.

**Comment by thofma** [comment]
Just before it vanishes in the slack blackhole: In #general, 10 persons  in favour of www.oscar-system.org and 1 person in favour of `oscar.computeralgebra.de`.
