### ISSUE TITLE
One test is not running, see https://github.com/oscar-system/Oscar.jl/actions/runs/3647065768/jobs/6158842919

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#1802]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
# Julia code
```

**Expected behavior**
A clear and concise description of what you expected to happen. Especially if
the bug is of mathematical nature we will need the mathematical context. If
applicable please provide references to relevant papers.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.8.3-DEV
...
```

**Additional context**

**Comment by fingolfin** [comment]
This was the error:
```
ERROR: LoadError: InitError: Error thrown by GAP: Error, HTTP/1.1 503 Egress is over the account limit while requesting https://github.com/gap-packages/ferret/releases/download/v1.0.9/ferret-1.0.9.tar.gz in
```
This is a temporary failure due to GitHub rate throtteling certain downloads. I've restarted the job.

**Comment by fingolfin** [comment]
The new job replacing the "bad" one in the title of this issue now is past the problematic point, and hopefully will finish "green" soon. See https://github.com/oscar-system/Oscar.jl/actions/runs/3647065768/jobs/6161419545
