### ISSUE TITLE
Segmentation fault in _rational_solutions

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1812]
@ederc I wanted to hook up the things you added in #1810, but I ran quickly into problems when I tested other examples:
```julia
julia> R,(x1,x2,x3) = PolynomialRing(QQ, ["x1","x2","x3"])
(Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, fmpq_mpoly[x1, x2, x3])

julia> I = ideal(R, [x1+2*x2+2*x3-1, x1^2+2*x2^2+2*x3^2-x1, 2*x1*x2+2*x2*x3-x2])
ideal(x1 + 2*x2 + 2*x3 - 1, x1^2 - x1 + 2*x2^2 + 2*x3^2, 2*x1*x2 + 2*x2*x3 - x2)

julia> rat_sols = Oscar._rational_solutions(I)
2-element Vector{Vector{fmpq}}:
 [1, 0, 0]
 [1//3, 0, 1//3]

julia> I = ideal(R, [x1,x2,x3])
ideal(x1, x2, x3)

julia> rat_sols = Oscar._rational_solutions(I)

signal (11): Segmentation fault: 11
in expression starting at REPL[8]:1
__gmpn_copyi at /bla/julia-1.8.2+0.aarch64/lib/julia/libgmp.10.dylib (unknown line)
Allocations: 62220972 (Pool: 62159640; Big: 61332); GC: 20
```
Can you reproduce this?

**Comment by ederc** [comment]
For the segfault: That's a bug in this edge case reintroduced in msolve due to fixing other stuff. I will take care of this in the next weeks, a new minor `msolve_jll.jl` update will then hopefully fix this.

For the first example: What exactly is wrong with it?

**Comment by thofma** [comment]
Nothing. Just showing that the example from the docs works with my setup.

**Comment by ederc** [comment]
Should be fixed via `msolve_jll.jl (v0.4.7)`, so `]up` should be enough.

**Comment by thofma** [comment]
Thanks!
