### ISSUE TITLE
Mixed volume with Polymake

### ISSUE THREAD

**Issue by efeliu** [oscar-system/Oscar.jl#1832]
**Describe the bug**
Hi, 

I encountered a problem with the computation of the mixed volume of three polytopes in R^3, where the output was wrong. I spend time trying to find out what happened, and I think it is because a bug for this function was found in Polymake and fixed in some later version. It seems Oscar is using an older version of Polymake, still having the bug. (Maybe this is not the reason, but the output of the computation is for sure wrong).

I give the details of the computation performed, and the data of my system. 

Thanks!

Elisenda

Using julia 1.8.3, Oscar version 0.11.2

R, (x,y,z) = PolynomialRing(QQ,["x","y","z"])
f = z+y^2+x*z^2-x*y*z^2
g = x*z-y+1
h = x^2*z-y+2

NPf = convex_hull(collect(exponent_vectors(f)))
NPg = convex_hull(collect(exponent_vectors(g)))
NPh = convex_hull(collect(exponent_vectors(h)))

Polymake.polytope.mixed_volume(NPf.pm_polytope,NPg.pm_polytope,NPh.pm_polytope)
6

The correct answer is 4!
Reordering the polytopes gives the right answer, and the dependence on the order was the bug found in Polymake.

**Comment by lkastner** [comment]
@SylvainSpitz Would you mind having a look at this? I think this bug also exists in polymake.

**Comment by micjoswig** [comment]
The new OSCAR 0.11.3 is based on polymake 4.9, where that error should be fixed.  Please try again and report back.  Close this issue if problem is solved.

**Comment by efeliu** [comment]
Fantastic, after the update the example works fine. I close the issue.
