### ISSUE TITLE
Admit different types for a group and a subgroup of it.

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#1838]
Currently subgroups of a given group `G` are constructed via `_as_subgroup` -> `_as_subgroup_bare` -> `_oscar_group`.
This implies that the subgroup gets the same Julia type as `G`.
(See #1836 for an example where this rule causes difficulties.)

Eventually it may be useful to admit other types for subgroups. Since all subgroup constructions come together with an embedding homomorphism, there is no problem with such a more general setup.

**Comment by lgoettgens** [comment]
Is this resolved by the introduction of `SubPcGroup` and `SubFpGroup`?

**Comment by ThomasBreuer** [comment]
Yes, the issue is resolved.
The solution was to introduce `_sub_type` in order to define a map from the type of a group to the type of its subgroups.
