### ISSUE TITLE
`save` and `load` not backwards compatible.

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1839]
I just tried to `load` some file I saved a while ago using `save`  It did not work.  (luckily nothing important). `ERROR: KeyError: key :base_ring not found` I could recover by going back to Oscar 0.10. But if we are not backward compatible, at least the error message should state the Oscar version one has to use to recover.

**Comment by fingolfin** [comment]
Going beyond this, I believe we need an extensive test suite of serialized data (json files) in the repo which we test for (de)serialization as part of the test suite, so that we notice breakage

**Comment by fingolfin** [comment]
@antonydellavecchia can you look into this? We need to find out what changed, and then perhaps the mechanism in PR #1730 can be used to address it?

**Comment by antonydellavecchia** [comment]
@simonbrandhorst could you share the file?

**Comment by antonydellavecchia** [comment]
So it seems like this file was saved at the early stages of Matrix serialization, and didn't include the parent ring of the entries. And in terms of the error message returning the version number, the  version of OSCAR that serialized file can be found at the top of the file in namespace section. I've added a test for backward compatibility of container types in #1730 and I've made sure that the upgrade script can handle all container types, this example made me find an edge case

**Comment by antonydellavecchia** [comment]
> @simonbrandhorst could you share the file?
[base_ring_error.zip](https://github.com/oscar-system/Oscar.jl/files/10519162/base_ring_error.zip)
