### ISSUE TITLE
Wrap Gap.Globals.SmallGeneratingSet

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1847]
The gap method `SmallGeneratingSet` is rather useful.
Could we wrap it? 
There is already `small_generating_set` on the oscar side.

**Comment by fingolfin** [comment]
I was confused by this until I figured out that `small_generating_set` is provided by Hecke :-). So you are asking for a `small_generating_set` method for GAP groups then -- sure, no problem -- @ThomasBreuer can you please take care of that?

Looking at the Hecke code, I am not sure what `small_generating_set` returns / takes, so I can't comment about the "compatibility"? Perhaps @thofma has a comment on this.

**Comment by thofma** [comment]
There seem to be different versions. One takes an ideal and returns a generating set with "few" elements. But there are also versions of the form `small_generating_set(G::Vector, op)` where `G` is closed under a binary operation `op` and the method returns a generating set with "few" elements.

I guess `small_generating_set(G::Group)` would be appropriate.

**Comment by ThomasBreuer** [comment]
O.k., I will add such a method.
