### ISSUE TITLE
Overrides for `Nemo._hnf` and `Nemo._hnf_with_transform` are causing invalidations

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1863]
Specifically this code from `experimental/GModule/GModule.jl:1372`:
```julia
function Nemo._hnf(x::fmpz_mat)
  if nrows(x) * ncols(x) > 100
    s = sparse_matrix(x)
    if sparsity(s) > 0.7
      return matrix(Hecke.hnf(s))
    end
  end
  return Nemo.__hnf(x) # use original Nemo flint hnf
end

function Nemo._hnf_with_transform(x::fmpz_mat)
  if nrows(x) * ncols(x) > 100
    s = sparse_matrix(x)
    if sparsity(s) > 0.7
      s = hcat(s, identity_matrix(SMat, ZZ, nrows(x)))
      m = matrix(Hecke.hnf(s))
      return m[:, 1:ncols(x)], m[:, ncols(x)+1:end]
    end
  end
  return Nemo.__hnf_with_transform(x) # use original Nemo flint hnf
end
```
I guess the right fix is to move them Nemo, or at least to Hecke (which also overrides `Nemo._hnf`)

CC @fieker @thofma

**Comment by thofma** [comment]
Can be removed.

**Comment by fieker** [comment]
weel,... argueably, the "right" way would actually be to find s.o. able to fix the lin. alg module...
It can be removed I guess as the "same" is done in Hecke.
Can't be moved to Nemo (of now) as the sparse stuff is in Hecke....(and (c/sh)ould possibly migrate to AbstractAlgebra....

**Comment by fingolfin** [comment]
When you say "the same" is done in Hecke, I have to wonder: where? I couldn't find a corresponding override for `_hnf_with_transform` there?

**Comment by thofma** [comment]
Ah, right. I did not move the `_hnf_with_transform` thing. Will do this.
