### ISSUE TITLE
add dimension range checks to visualize

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#1870]
The `visualize` function for various polyhedral objects calls suitable polymake functions. Of course the visualization is limited to low dimensions.

Currently, e.g., trying to visualize a 5-polytope triggers the polymake error (which is fine), but then we also get an awful stack trace from julia since the error is not caught.  Please check the ambient dimension before calling polymake, and exit gracefully if the dimension is too high.

Please also check out the updated doc string for `visualize(P::Polyhedron)`.  Adjust the docstrings of the other visualization functions accordingly.

**Comment by benlorenz** [comment]
fixed in #1933
