### ISSUE TITLE
Kernel and rationality of characters

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1875]
Would be great if we had `kernel(x)` or `is_rational(x)`, where `x` is a character of a finite group.

Edit: `is_abelian(x)` would also be nice, but I am not sure if you would endorse it.

**Comment by thofma** [comment]
ping @ThomasBreuer

**Comment by joschmitt** [comment]
This was fixed by #1989 as it seems. Please reopen if there is something missing.

**Comment by ThomasBreuer** [comment]
@joschmitt Thanks for spotting this.
Yes, I think this issue can be closed.
(I do not remember what the intended meaning of `Is_abelian` for characters had been, but we had agreed on leaving this out.)
