### ISSUE TITLE
is_surjective sometimes broken for module homomorphisms

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#1883]
Just so that we do not forget about it:
See the tests in #1879 for the details & an example.

CC: @jankoboehm

**Comment by lgoettgens** [comment]
The broken tests in https://github.com/oscar-system/Oscar.jl/pull/1879 have been enabled in https://github.com/oscar-system/Oscar.jl/pull/3021, and they work. So I would say this is fixed then.
