### ISSUE TITLE
Morphisms between GAP groups and abelian groups

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1884]
Would be great if we could make the following work:
```julia
julia> G = SymmetricGroup(3)
Sym( [ 1 .. 3 ] )

julia> A = abelian_group([2]);

julia> h = hom(G, A, [sign(g) == 1 ? zero(A) : A[1] for g in gens(G)])
```
(My end goal is to compute `kernel(h)`.)

CC: @fingolfin @ThomasBreuer

**Comment by ThomasBreuer** [comment]
So the point is to get a homomorphism from a multiplicative group to an additive group.
Should not be a technical problem.
(I will propose a pull request.)

**Comment by thofma** [comment]
Thanks! I know how to do it (by doing the detour via `isomorphism(A, PermGroup)`), but maybe there is a better way.

**Comment by ThomasBreuer** [comment]
My idea is to create the natural epimorphism from G to G/G' (using a map in GAP), to create an isomorphism from G/G' to a `GrpAbFinGen` B (we have this already), and then the map from B to A that is defined by the prescribed images.
This should work also if A is infinite, and computing the kernel of the composition is straightforward.
