### ISSUE TITLE
Behavior of `//` for elements in localization is inconsistent with the system

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1885]
The general rule for ring elements and which makes it possible to write generic algorithms is that `//` behaves as follows:
- If `x, y` are `FieldElem`, then `x//y == divexact(x, y) == x * inv(y)`.
- If `x, y` are `RingElem`, then `x//y` constructs an element of the field of fractions. It should not be used for division.

Obviously we should not deviate from this. The various localization elements do not adhere to this rule:

```julia
julia> R, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Rational Field, fmpq_mpoly[x, y, z])

julia> P = ideal(R, [x])
ideal(x)

julia> U = complement_of_ideal(P)
complement of ideal(x)

julia> Rloc, iota = localization(U);

julia> f = iota(x)//iota(y)
x//y

julia> typeof(f)
MPolyLocalizedRingElem{FlintRationalField, fmpq, FmpqMPolyRing, fmpq_mpoly, MPolyComplementOfPrimeIdeal{FlintRationalField, fmpq, FmpqMPolyRing, fmpq_mpoly}}

julia> parent(iota(x)//iota(y)) == Rloc
true
```

Would be good if we could fix this.

CC: @wdecker @HechtiDerLachs 

Edit: Nowadays we have a total field of fractions, so we could make `x//y` construct an element in the total field of fractions in general, and in the fraction field if `is_domain_type()` is true.

**Comment by HechtiDerLachs** [comment]
I remember having this on my plate yesterday. 

The rationale was this: Localizations of polynomial rings use the fraction fields in the internals. Hence, I allowed the `//` in this case. For localizations of `MPolyQuo`s, this is different. Hence, I did not allow `//` and hence the inconsistency. 

Let me know, what exactly you want and I can fix it.

**Comment by HechtiDerLachs** [comment]
Please, have a look at the respective commits in the pr #1943 and let me know whether you approve.

**Comment by simonbrandhorst** [comment]
There is still the following inconsistency.

For RingElem `/` is the same as `divexact`. 
but for localisations `x/y` is `x*inv(y)`. 

```
julia> R, (x,y) = polynomial_ring(QQ, ["x","y"])
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> P = ideal(R,[x])
Ideal generated by
  x

julia> U = complement_of_prime_ideal(P)
Complement
  of prime ideal (x)
  in multivariate polynomial ring in 2 variables over QQ

julia> RU,iU = localization(R,U)
(Localization of multivariate polynomial ring in 2 variables over QQ at complement of prime ideal (x), Hom: R -> localized ring)

julia> divexact(iU(x),iU(x))
1
```
@HechtiDerLachs  any reasons?
