### ISSUE TITLE
StackOverflowError invoking `simplex` with bad arguments

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1889]
I accidentally invoked `simplex` incorrectly
```julia
julia> simplex(1,2,3)
ERROR: StackOverflowError:

```

The problem is in this code:
```julia
simplex(::Type{T}, d::Int64, n) where T<:scalar_types = ...
simplex(::Type{T}, d::Int64) where T<:scalar_types = ...
simplex(x...) = simplex(fmpq, x...)
```
The last method should probably have a check that verifies that first argument is not already `fmpq`. Something like this perhaps?
```julia
function simplex(x...)
  x[1] === fmpq && error("TODO")
  return simplex(fmpq, x...)
end
```
Or perhaps even better: just provide dedicated fallbacks:
```julia
simplex(d::Int64, n) = simplex(fmpq, d, n)
simplex(d::Int64) = simplex(fmpq, d)
```

The same issue affects `cross` and `cube`.

**Comment by lkastner** [comment]
Thanks, as I am already fixing this for `convex_hull`, I'll do these as well.
