### ISSUE TITLE
CI reproducibly runs into timeout at a precise point in tests

### ISSUE THREAD

**Issue by afkafkafk13** [oscar-system/Oscar.jl#1900]
Tests seem to be killed at 120 min (system time limit) due to an extremely long running test 
test/InvariantTheory/invariant_rings-test.jl: "Invariant rings (for matrix groups)"

The start of this test is reached e.g. at 50m 56s in 1.6, x64, ubuntu-latest (i.e. mpoly_affine_homological-algebra.depth  finished), on other CI-setups the times are similar. But the end is not reached before the Ci gets killed after 120 min.

Could someone knowledgable about the Invariant Theory functionality please investigate what gets out of hand here. 
Thank you.

**Comment by afkafkafk13** [comment]
Additional information: problem does not occur, when the sequence of commands form test-file is run manually in an Oscar.

**Comment by thofma** [comment]
Do you have a link to such a CI log?

**Comment by afkafkafk13** [comment]
https://github.com/oscar-system/Oscar.jl/actions/runs/4078952480/jobs/7036176520
(This is on a 1.7 -- the log of the 1.6 has been overwritten, when I was looking for the error)

**Comment by joschmitt** [comment]
The tests run fine on master on my local machine. I will try the branch from this PR then.

**Comment by thofma** [comment]
The log says "cancelled", probably because a new commit was pushed or the jobs were restarted? The timeout for CI is 6 hours.

**Comment by fingolfin** [comment]
We the a custom timeout of 2 hours.

**Comment by fingolfin** [comment]
Latest master CI tests passed fine, see https://github.com/oscar-system/Oscar.jl/actions/runs/4076981358 (except for Julia nightly on macOS, for which we already have a separate issue)

**Comment by afkafkafk13** [comment]
Look at the latest 1.6 CI run in this PR
https://github.com/oscar-system/Oscar.jl/actions/runs/4078952480/jobs/7036176410
which was cancelled after 1h 57m 20 s  -- without anyone touching the PR in the meantime.

**Comment by thofma** [comment]
Why is it a problem in the invariant rings? The tests for the new
```
include("Rings/ReesAlgebra.jl")
```
do not finish, which come before the invariant rings?

**Comment by afkafkafk13** [comment]
My fault. Sorry. I seem to have missed that line....
I will investigate there without further need of assistance.

**Comment by fingolfin** [comment]
In https://github.com/oscar-system/Oscar.jl/actions/runs/4076981358/jobs/7025425776 the "Invariant rings (for matrix groups)" test passes in 6 seconds.

Looking at the log provided by @afkafkafk13 I don't understand where the conclusion comes from that that invariant ring is the one which is timing out. Rather it looks to me as if one of the tests added by that PR is timing out?

**Comment by afkafkafk13** [comment]
I already said sorry. I seem to have missed that line in the test file when analyzing the problem.

**Comment by fingolfin** [comment]
No worries, I was writing my comment while your last one was submitted, i.e., we crossed in time :-).
