### ISSUE TITLE
Make `exponent_vectors` use the same ordering as `coefficients` etc.

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1903]
#1696 introduced new functions for `coefficients`, `terms`, etc. which now use the `default_ordering` of the ring. However, there is still `exponent_vectors` from AbstractAlgebra which keeps using "some" ordering.
In consequence the output of `coefficients` and `exponent_vectors` might not match up anymore:
```
julia> R, x = GradedPolynomialRing(QQ, ["x1", "x2"], [1, 2])
(Multivariate Polynomial Ring in x1, x2 over Rational Field graded by 
  x1 -> [1]
  x2 -> [2], MPolyElem_dec{fmpq, fmpq_mpoly}[x1, x2])

julia> f = x[1] + 2*x[2]
x1 + 2*x2

julia> collect(coefficients(f))
2-element Vector{fmpq}:
 2
 1

julia> collect(exponent_vectors(f))
2-element Vector{Vector{Int64}}:
 [1, 0]
 [0, 1]

```
Could we either make `exponent_vectors` an alias for the new function `exponents` or at least not export it anymore (it appears to be imported from Hecke)? Like this it is just an accident waiting to happen, especially because the relevant documentation was deleted in c3d516a5916bc4c6a2e5768eeb408c50344795b4; see the deletions in `orderings.md`.
(In fact, that accident already happened in code of mine which was running fine until I updated...)

**Comment by thofma** [comment]
Let's not import and/or export it to make it consistent with the rest.

**Comment by wdecker** [comment]
There are more functions to consider here. I will make a list. We should see the whole picture.

**Comment by fingolfin** [comment]
Was there any progress on this yet? It seems `exponent_vectors` is still exported.

Note that for functions that don't care about the ordering, they just want to visit all terms / exponent vectors / coefficients, it can be quite useful to have a way to get these "as fast as possible".  Indeed, `exponent_vectors` is quite a bit faster (I dunno if there is a yet faster way?). E.g.:
```julia
julia> R, (x,y,z) = QQ["x", "y","z"];

julia> f = (x+ y^2 + 2*z)^3;

julia> using BenchmarkTools

julia> @btime collect(exponents(f));
  5.917 μs (22 allocations: 1.67 KiB)

julia> @btime collect(exponent_vectors(f))
  642.170 ns (12 allocations: 944 bytes)
```

**Comment by YueRen** [comment]
How about we just not export `exponent_vectors` and add a little note to the documentation of `exponents` that users can use `Hecke.exponent_vectors` for faster but "unsorted" exponent vectors (as in: not sorted in the monomial ordering, but still consistent with `Hecke.coefficients`)? 

The same goes of `coefficients` vs `Hecke.coefficients`:

```
julia> @btime collect(Hecke.coefficients(f));
  320.503 ns (12 allocations: 464 bytes)

julia> @btime collect(coefficients(f));
  5.269 μs (22 allocations: 1.20 KiB)
```

**Comment by joschmitt** [comment]
I agree, we should not export `exponent_vectors` to the Oscar namespace. I would also be in favour of explaining the situation in the documentation, but such documentation did exist for some time and then it got deleted; see my first post in this issue.
For completeness, this is how I understand the situation: In the "old days", there were only the methods `coefficients`, `terms`, `exponent_vectors`, etc. in AbstractAlgebra. These iterate the terms of a polynomial in a (consistent) order that cannot be specified by the user, but is related to how these polynomials are actually stored and therefore these functions are fast. Roughly half a year ago, similar functions were introduced in Oscar which now take a monomial ordering as second argument and iterate the terms in that ordering; they are hence slower. At that point, the functions `coefficients`, `monomials`, `terms`, etc. were stopped to be imported from AbstractAlgebra because that would have conflicted with the Oscar functions. However, what is called `exponent_vectors` in AbstractAlgebra is called  `exponents` in Oscar, so this function did not create a conflict and was overlooked.
