### ISSUE TITLE
Updating FLINT_jll (and other JLLs) across all OSCAR packages

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#193]
Yesterday I updated FLINT_jll to a snapshot of the latest git version, calling it 2.6.999 (and also update Singular_jll to use that new FLINT_jll; the motiviation for all that is to get lots of fixes and improvements made to polynomial factorization). Unfortunately this broken Nemo. @thofma quickly resolved this by getting the two new JLLs yanked from the registry.
Anyway, I am sorry for the annoyance I caused -- I was so focused on testing Singular.jl with the changes that I completely forgot that I should be testing Nemo.jl and also coordinate with LoadFlint.jl.

Still, the underlying issue is that FLINT and Singular simply don't follow semver, and pressing them into JLL semver version doesn't work well. As a matter of fact, FLINT 2.6 and 2.7 are *not* ABI compatible (which is the ultimate cause for the crashes in Nemo). 

For FLINT_jll, I was asked why I didn't call the update 2.7.0 instead of 2.6.999 -- well the reason was that this *isn't* 2.7.0, and this would have been misleading. So why didn't I call it 2.7.0-dev or something? Because prerelease versions are not allowed for JLLs and more generally packages in the general registry! (Which I think is a pity, but those are the rules). That left me with the choice of using 2.6.999 or else something like 2.7.0; you already know the issues with the former; for the later, it would mean decoupling the JLL version from the upstream (Flint) version; the actual Flint 2.7.0 would then be put in a JLL with a version like 2.7.1; or in fact perhaps 2.8 because this snapshot may very well ABI (or even API) incompatible with the final 2.7.0. And if you take a step back, an ABI incompatibility in the semver model actually means that the *major* version should have incremented, so to follow that, I would need to call the JLL version 3.0 (and then the final 2.7.0 may end up either as 3.1 or as 4.0), etc.

In fact, this is an actual problem for many JLLs, and the BinaryBuilder team already recognized this, and formed the plan is to decouple JLL versions from upstream project versions, and keep some internal tables that tell how JLL versions map to upstream versions. (Besides not following semver rules, there are also projects which don't follow the `x.y.z` pattern for versions -- e.g. Singular...)

Anyway, for the time being, we need  a way to deal with this, and also a plan how to roll out the FLINT_jll update. I just discussed this @thofma and here is an initial proposal how to go about this; further input is welcome (I hope that in particular @benlorenz will take a look at this):

1. [x] Since FLINT and Singular don't follow semver, I recommend that we change our packages to <s>hardcode a *specific* FLINT_jll version via a `=` compat bound in `Project.toml`</s> decouple the JLL version from the actual version, to give us room to maneuver; the plan is to map e.g. FLINT_jll 2.6.3 to `200.600.300`, and 2.7.0 to `200.700.000`; and then the 2.7 prerelease snapshot(s) can be e.g. `200.690.000`, leaving enough wiggle room for future eventualities; this way a compat entry like `FLINT = ~200.600.300` won't pick up the pre-release snapshot. But if e.g.e.g. Nemo were (hypothetically speaking) compatible with both 2.6.3 and 2.7.0, we could still declare this with a suitable compat entry. Another advantage of this approach is that it plays well with the current LoadFlint.jl release, which says `FLINT_jll = "^2.6.0"` so the new JLL won't be picked up prematurely.
   - [x] FLINT_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2234
   - [x] Arb_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2287
   - [x] Antic_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2280
   - [x] Normaliz_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2294
   - [x] Singular_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2235 https://github.com/JuliaPackaging/Yggdrasil/pull/2295
   - [x] libsingular_julia_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2300 https://github.com/JuliaPackaging/Yggdrasil/pull/2263 https://github.com/JuliaPackaging/Yggdrasil/pull/2303
   - [x] Polymake_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2304
   - [x] libpolymake_julia_jll.jl -- https://github.com/JuliaPackaging/Yggdrasil/pull/2306
2. [ ] Ideally also change the JLLs to use say a VersionSpec to ensure useful compat bounds in those JLLs... so that a Singular_jll linked against FLINT_jll 200.600.300 won't load with FLINT_jll 200.690.000 and vice versa (yes this may mean we need to make a few more JLL updates than otherwise, e.g. even if FLINT_jll 200.690 and 200.700 end up 100% ABI compatible, we'll have to regenerate Singular_jll with a new compat bound -- but that's a tradeoff, some extra work gives us extra control and protection against certain problems
3. [x] Once the new JLL versions are out, update packages to be able to use them (instead or in addition to older versions)
   - [x] LoadFlint.jl
   - [x] Nemo.jl -- requires https://github.com/Nemocas/Nemo.jl/pull/919
   - [x] Singular.jl -- https://github.com/oscar-system/Singular.jl/pull/321
   - [x] Polymake.jl -- https://github.com/oscar-system/Polymake.jl/pull/335
4. [x] then make releases of these packages
   - [x] LoadFlint.jl
   - [x] Nemo.jl
   - [x] Singular.jl
   - [x] Polymake.jl
5. [x] Add a comment to the `build_tarballs.jl` for FLINT_jll along the lines of this:
     > WARNING: whenever you update this, please consider how this may affect LoadFlint, Nemo, Polymake, Singular, and coordinate with other OSCAR projects"

Again, this is an initial proposal; feel free to point out issues, recommend improvements, etc.

**Comment by thofma** [comment]
I am okay with this. Note that for the second step, the more important thing is that we need to hardcode the FLINT_jll versions also for all previously released versions of Nemo (and the other packages where this is relevant). Thus we have to do some shenanigans in the registry.

**Comment by fingolfin** [comment]
What if we call the next FLINT_jll 3.0.0 ? Then the old Nemo etc version won't pick them up, will they? Then we don't these shenanigans

**Comment by thofma** [comment]
I think everything >= 2.7.0 should be fine.

**Comment by fingolfin** [comment]
Perhaps, but the 2.7.x snapshot may not be ABI compatible with the final 2.7.0 release; then we'll have to call that at least 2.8.x etc. -- might be best to move to completely different versions. Perhaps 100.0.0 would be even better, as both 2.7 and 3.0 could be misunderstood as to actually referring to the FLINT version when they really do not.

**Comment by thofma** [comment]
Yes, I guess we don't anticipate a proper version 100.0.0 of flint.

**Comment by thofma** [comment]
Another option would be to release a FLINT_dev_jll or something like that, with whatever version number scheme we want. This is probably the option with the least amount of work.

**Comment by thofma** [comment]
@tthsqe12 said that he is not anticipating any binary breakages between now and 2.7. If we believe in this, we could do now a 2.7.0+0 and bump it to 2.7.0+1 as soon as there is an official release.

**Comment by benlorenz** [comment]
Testing Polymake.jl with FLINT 2.6.999 (dev'ing the jll repo) seems to work fine without any rebuild (at least on my machine), probably because we don't use that much internals from flint.
Polymake.jl has `~2.6.2` as compat bound for FLINT_jll (all releases since the switch to JLLs have this entry) so we can just update it to allow 2.7 as well.

I prefer to use `~` instead of `=` as it allows some minor updates that usually should not cause any issues (but that probably depends on how closely entangled the packages are).
And I don't really like the idea to go through some lookup table to find out the versions of the packages.

If we want to do large numbers we could also do stuff like `20.70.000` or even `200.700.000` which would both encode the flint version and allow still allow separate updates in all version parts. So for this update you could have used `200.601.000` and Nemo would have ignored the update as the `~2.6.3` would correspond to `~200.600.300`.

**Comment by fingolfin** [comment]
I like the 200.600.300 etc scheme proposed by @benlorenz

**Comment by thofma** [comment]
Fine with me. Do we stay on the *00 scheme if 2.7.0 is released? Will it be 2.7.0 or 200.700.000?

**Comment by tthsqe12** [comment]
A scan of the 2.7 issues
https://github.com/wbhart/flint2/issues?q=is%3Aopen+is%3Aissue+milestone%3Aflint-2.7
reveals the only issue necessitating binary incompatibilities:
https://github.com/wbhart/flint2/issues/777

However, no one is using nmod_mat_scalar_mul_add (soon to be  nmod_mat_scalar_addmul).

**Comment by fingolfin** [comment]
@thofma @tthsqe12 @benlorenz I've updated the "plan" in the issue description based on our discussion. Does it look OK?

Then we could immediately start implementing it.

**Comment by benlorenz** [comment]
`^200.600.300` would in fact allow `200.690.000` since it allows up to `201.0.0`. I think in most places we should stick to tilde instead of caret unless we know that minor version updates are binary-compatible.

I think we could create a new FLINT_jll `>=3.0` right away as all downstream packages do have some (indirect) restriction in place:
- Polymake.jl: `~2.6.2`
- Nemo.jl: `~2.6.3`
- LoadFlint.jl: `^2.6.0`
- Singular.jl: no compat entry but it restricts the Nemo.jl version so as long as Nemo is fine Singular should be as well.

So it should not affect any users directly.

We need to be careful when building new artifacts (i.e. Singular_jll or polymake_jll) on Yggdrasil to avoid building them with the new version without some other restriction in place for that new jll. So we should probably put FLINT_jll restrictions on all future jll builds.

**Comment by thofma** [comment]
Looks OK to me.

**Comment by fingolfin** [comment]
@benlorenz the plan indeed is to only use ~ and not ^

**Comment by benlorenz** [comment]
I was referring to this which is probably a typo:

> and then the 2.7 prerelease snapshot(s) can be e.g. `200.690.000`, leaving enough wiggle room for future eventualities; this way a compat entry like `FLINT = ^200.600.300` won't pick up the pre-release snapshot.

I am fine with the current plan.

**Comment by fingolfin** [comment]
Yes that's a stupid typo, fixed now, thanks for reading carefully!

**Comment by benlorenz** [comment]
So, we just need a new release for Singular.jl now and afterwards release Oscar.jl with the required compat updates?

**Comment by fingolfin** [comment]
All done now! And "just" 6 weeks after this issue was opened *sigh*.
