### ISSUE TITLE
Deprecation warnings during tests

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1947]
I am seeing a lot of deprecation warnings during the tests:
```
┌ Warning: `map_from_cartier_divisor_group_to_picard_group(v::AbstractNormalToricVariety)` is deprecated, use `map_from_torusinvariant_cartier_divisor_group_to_picard_group(v)` instead.
│   caller = macro expansion at hirzebruch.jl:53 [inlined]
└ @ Core ~/xyz/dev/Oscar/test/ToricVarieties/hirzebruch.jl:53
```
It appears that they are all coming from the toric area, so let me ping @HereAround (sorry if you are not the right person, but you might know the right person).

This is with 2180d4b98e0b929ea5a07dbf38961ff9b54cfaf0, so rather recent.

**Comment by HereAround** [comment]
Thanks for the pointer. Yes, this warning is on me. I will fix it.

**Comment by HereAround** [comment]
The warnings indeed originate from the tests of the toric varieties. In https://github.com/oscar-system/Oscar.jl/pull/1937/commits/744093af127ce665cbd68e2c5036111ada409eea, I provide a (massive) overhaul of those tests. For that reasons, I have added a commit to this PR (https://github.com/oscar-system/Oscar.jl/pull/1937/commits/744093af127ce665cbd68e2c5036111ada409eea), which will hopefully make all these warning disappear.

**Comment by thofma** [comment]
Thanks for taking care of this.

**Comment by HereAround** [comment]
Of course. Btw. this should be resolved since https://github.com/oscar-system/Oscar.jl/pull/1937 was merged. Please confirm.

**Comment by thofma** [comment]
I just ran tests on top of 4998adb29769e3e0b6202bec2fda63c44e07a75f and hit:
```
 Error During Test at /xyz/.julia/dev/Oscar/test/ToricVarieties/hirzebruch_surfaces.jl:54
  Test threw exception
  Expression: domain(map_from_torusinvariant_cartier_divisor_group_to_picard_group(F5)) == cartier_divisor_group(F5)
  `cartier_divisor_group(v::AbstractNormalToricVariety)` is deprecated, use `torusinvariant_cartier_divisor_group(v)` instead.
```
By the way, if you start julia with `--depwarn=error`, it will turn those deprecation warnings into proper errors.

**Comment by HereAround** [comment]
Thank you for the pointer. It indeed seems I missed a few old methods. Sorry about that.

https://github.com/oscar-system/Oscar.jl/pull/1956 should (hopefully) finally fix all of them.

**Comment by HereAround** [comment]
Should we run the CI with the `--depwarn = error` option?

**Comment by thofma** [comment]
It should be rather easy to try, since this is just an option in the corresponding github actions action: https://github.com/julia-actions/julia-runtest/blob/fa1e6fac940a2785c35dddb5fbb98ed945e3d2a2/action.yml#L16-L17.

**Comment by HereAround** [comment]
Yes, let us try this out: https://github.com/oscar-system/Oscar.jl/pull/1957

**Comment by HereAround** [comment]
https://github.com/oscar-system/Oscar.jl/pull/1956 and https://github.com/oscar-system/Oscar.jl/pull/1957 are merged. So this issue should be resolved.
