### ISSUE TITLE
SLPolyRing not a ring?

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#195]
julia> S = slpoly_ring(QQ, 2)
SLP Multivariate Polynomial Ring in x_1, x_2 over Rational Field

julia> St, t = PolynomialRing(S)
ERROR: MethodError: no method matching elem_type(::Type{Oscar.StraightLinePrograms.SLPolyRing{fmpq,FlintRationalField}})

actually it is a bit more complicated, but this is the summary. Key problem is that typeing of SLPoly(Ring) is different from all other rings.  Thus it is not just a question of adding this one function.

**Comment by rfourquet** [comment]
Yes, I didn't put much effort into making `SLPolyRing` a proper ring. I was planning to put this functionality out of `StraightLinePrograms` and into `Oscar/src/Rings/`, this issue is a good opportunity to do so.
