### ISSUE TITLE
Add CI tests to our projects looking for "bad" exports

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1964]
We sometimes accidentally export non-existing things. E.g. from current Oscar.jl:
```
julia> filter(n->!isdefined(Oscar, n), names(Oscar))
32-element Vector{Symbol}:
 :AbsPrePreSheaf
 :CoherentSheaf
 :DirectProductOfElem
 :LineBundle
 :_non_degeneration_cover
 :affine_patch_type
 :ambient
 :as_smooth_lci_of_cod
 :as_smooth_local_complete_intersection
 :base_scheme_type
 :controlled_transform
 :coset_decomposition
 :covered_patches
 :covering
 :dualsubdivision
 :generator
 :has_complement_class_reps
 :ideal_dict
 :ideal_sheaf_type
 :images_of_variables
 :intersect_stably
 :load_simplicialcomplex
 :normalize
 :p
 :prepare_smooth_center
 :save_simplicialcomplex
 :set_complement_class_reps
 :set_is_finite
 :subdivision_of_vertices
 :total_transform
 :weak_transform
 :weight
```

The `:p` one is due to a typo, @HereAround is already fixing it.

I suggest the following:
- [ ] resolve these (either by adding missing functions or removing the exports)
- [ ] add something like this to our tests:
  ```julia
  @test all(n->isdefined(Oscar, n), names(Oscar))
  ```
- add similar tests to our other packages (AA, Nemo, Hecke, GAP, Singular, Polymake, ...)

**Comment by HereAround** [comment]
For completeness, the fix for `export p` is included in the PR https://github.com/oscar-system/Oscar.jl/pull/1958.

**Comment by thofma** [comment]
We could just use https://github.com/JuliaTesting/Aqua.jl (I used it successfully locally in the past).

**Comment by afkafkafk13** [comment]
I am working on 
 :total_transform
 :weak_transform
 :controlled_transform
right now.

**Comment by lkastner** [comment]
I like @thofma s suggestion very much.

**Comment by lgoettgens** [comment]
> We could just use https://github.com/JuliaTesting/Aqua.jl (I used it successfully locally in the past).

I added a first try to use it in #2370 now that the wrong exports have been removed (thanks, @lkastner!).
