### ISSUE TITLE
New rule: `export` only one identifier at a time

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1971]
I propose the following new rule for our code (and the dev docs): "Every `export` statement must export exactly one identifier. If multiple export statements appear in sequence, they must be sorted alphabetically.".

So this:
```julia
export foo, bar,
    qux
```
would become
```julia
export bar
export foo
export qux
```

If this seems to harsh, then I propose this relaxation: "Every `export` statement must be on a single line." Then we'd have:
```julia
export foo, bar, qux
```
or
```julia
export foo, bar
export qux
```

Rationale: Earlier today I spent 10 minutes trying to track down the place where a function was exported. And that wasn't the first time I was in this situation. I could not just do something like `git grep export.*SYMBOL` to find it because `export` and `SYMBOL` did not appear on the same line. (Yes, one can use fancier search methods to still find it, and I eventually did, but I a tempted to believe that many people would have had an even harder time than me, as they are not as proficient with regex and grep and similar tools.)

So one of the rules above would make such searches much easier. I can't think of a major downside other than subjective ones... ("This wastes spaces/lines, my computer is almost out of spare newlines! All those extra bytes will flood my hard disk! What should we do with all those commas this frees up?"). Likely that just means my imagination is too limited as usual, so I'll wait to hear what objections / better alternatives people have.

(I'd suggest a similar rules for imports, but we already moved most imports into a single file, so it's not that bad.)

**Comment by thofma** [comment]
Pretty please, let us do this. (Maybe also exports only in one place, but I do not want to sidetrack this issue here.)

**Comment by ThomasBreuer** [comment]
As an experiment, I have changed the `export` statements in the `src/Groups` files (see pull request #2007).
I am in favour of the relaxed version which admits several exported names on one line;
this (together with the rule that the names should be ordered alphabetically) seems to be natural in the situation of properties together with tester and setter, as in `export isfinite, has_is_finite, set_is_finite`.

Another place where several names on one line make sense is in `export GL, GO, GU, SL, SO, Sp, SU`.
(I am not sure whether we want to keep these names at all.)

**Comment by HereAround** [comment]
I collected the exports for `AlgebraicGeometry` and `Combinatorics` in https://github.com/oscar-system/Oscar.jl/pull/2016.

**Comment by HereAround** [comment]
Once https://github.com/oscar-system/Oscar.jl/pull/2045 is merged, I would claim that all exports in ~~the src-folder~~ OSCAR have been modified to comply with this new rule.

(As I was working on this, I came to wonder if we really need all the (sub)modules that currently exist in OSCAR.)
