### ISSUE TITLE
Document what was renamed and to what

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1980]
But where? Perhaps this should be a news item on our website, which gives the renamings, provides a link to a script doing (some) of the renamings, and then we can put this link into various places (e.g. the GitHub release notes for AA, Nemo, etc.)

**Comment by afkafkafk13** [comment]
A CheatSheat of the renaming would be great. This is something we can give to our students who have already written fragments of code (for e.g. Master Theses) and need to rebase now. It would also be helpful for developers not directly involved in the renaming.

**Comment by fingolfin** [comment]
Sure, that's what I mean with "document what changed". But note that for now you students should not have to change anything, their code should work. And as I mention above, we have a script that can perform most of the necessary renaming (at least on a Unix machine)

**Comment by fingolfin** [comment]
I've put my notes [into our Wiki](https://github.com/oscar-system/Oscar.jl/wiki/The-Big-Renaming). When we release 0.12.0, we can link that in the news I guess.

Feel free to suggest or request improvements.

**Comment by thofma** [comment]
This issue is on the milestone, but to solve the issue, I need to add something for the 0.12.0 news, which requires a 0.12.0 release. I will close this for now, just to reduce the number of items on the milestone.
