### ISSUE TITLE
exterior_algebra function noisy

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1984]
```
julia> exterior_algebra(QQ, 1);
// ** commutative ring with 1 variable
```
@JohnAAbbott Not sure where it is coming from directly, but hopefully we can somehow suppress this output?

**Comment by fingolfin** [comment]
While at it, let me point out that there is no need for trailing semicolons in Julia, so most of them in experimental/ExteriorAlgebra/ExteriorAlgebra.jl could be removed.

**Comment by JohnAAbbott** [comment]
Trailing semicolons: I prefer to keep them, as I find that they are helpful visual cues (perhaps deriving from my C++ experience?)  If that is a problem for others I can remove them.

I'll look into the unexpected message about "commutative ring with 1 variable": it is not directly from my code.

**Comment by hannes14** [comment]
The message comes from Singular, see https://github.com/Singular/Singular/commit/506095068890755dcdc88aecfd9a55dd47bd3d02

**Comment by fingolfin** [comment]
I just tried this on `master` and the "noise" seems to be gone now.
