### ISSUE TITLE
noisy functions from geometry(?)

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1985]
The test output is full of
```
has_attribute(Y2, :simplified_covering) = true
has_attribute(Y3, :simplified_covering) = true
starting primary decomposition of singular locus
finished primary decomposition of singular locus
"blowing up first center" = "blowing up first center"
gens.((l[1]).(patches(oscar.simplified_covering(X3)))) = Vector{MPolyQuoLocRingElem{Nemo.fpField, fpFieldElem, fpMPolyRing, fpMPolyRingElem, MPolyPowersOfElement{Nemo.fpField, fpFieldElem, fpMPolyRing, fpMPolyRingElem}}}[[1], [1], [1], [1], [1], [1], [(t0//t1), (u1//u2), (u0//u2)], [1], [1], [1], [1], [1]]
"done blowing up" = "done blowing up"
scheme(l2) === X41 = true
"blowing up second center" = "blowing up second center"
gens.(l2.(patches(oscar.simplified_covering(X41)))) = Vector{MPolyQuoLocRingElem{Nemo.fpField, fpFieldElem, fpMPolyRing, fpMPolyRingElem, MPolyPowersOfElement{Nemo.fpField, fpFieldElem, fpMPolyRing, fpMPolyRingElem}}}[[1], [1], [1], [1], [(s2//s0), (u2//u0), (u1//u0)], [1], [1], [1], [1], [1], [1], [1], [1], [1]]
starting primary decomposition of singular locus
```
This looks like schemes, so according to the recently added docs I can ping @HechtiDerLachs, @afkafkafk13, @simonbrandhorst  :)

**Comment by afkafkafk13** [comment]
Yes, this is from the premature merge of PR #1887 to get the functionality (of a thread of 4 PR) into master before the big renaming. The noisy output merely consists of debugging output from tracking down the individual steps, which was not removed. We are aware of this by now, but it was too late, when we noticed. There will be a PR fixing this after the big renaming (some parts are not transversal to the renaming, so we wait)

**Comment by HechtiDerLachs** [comment]
Sorry about this. This must have been due to the merge of #1918 . That happened during the night while I was on an intercontinental flight with absolutely no internet connection. Please, anyone: Just remove the printing statements from the test file.

**Comment by HereAround** [comment]
I assume that this can be closed as https://github.com/oscar-system/Oscar.jl/pull/1991 was merged.
