### ISSUE TITLE
`characteristic_polynomial` vs `charpoly`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2026]
We have a function `charpoly` with many methods -- and then we have `characteristic_polynomial`, with one method, for matroids. This is confusing.

Some possible solutions:
1. rename `characteristic_polynomial` to `charpoly`
2. the same but also add `@alias characteristic_polynomial charpoly`
3. rename `charpoly` to `characteristic_polynomial` in AA and add `@alias charpoly characteristic_polynomial` there

See also issue #1826, which in fact mentions `charpoly`; however I decided to open a dedicated issue because because we already are using both names with separate methods, which is IMHO worse than just having a name that is not 100% perfect.

**Comment by thofma** [comment]
I vote for 3.

**Comment by fingolfin** [comment]
Same for `minpoly` I guess.
