### ISSUE TITLE
minimal generating sets of ideals

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#2044]
Another issue originating from slack: Implement a function which returns minimal sets of generators of ideals in cases where such sets exist. I will discuss this with @hannes14, @ederc  and we will provide this functionality.

**Comment by afkafkafk13** [comment]
In the same flavor the question of determining a "small" set of generators often arises independent of a requirement whether this needs to be minimal or not. 
I am thinking of 
- throw out zeros
- throw out duplicates and scalar multiples
- optionally throw out elements f for which a syzygy 1 \cdot f - \sum a_i \dot g_i  appears (g_i = the other generaorts)
(In Singular often combinations of simplify and mstd[2] have been used depending on the context)

I would suggest to introduce commands minimal_generating_set and small_generating_set for our context in accordance with the terminology used in the GAP part of OSCAR for similar cases of finding small or minimal sets of generators of other objects.

**Comment by fingolfin** [comment]
So, with PR #2545 merged, what is left to do here, if anything?
