### ISSUE TITLE
Release OSCAR 0.12.0

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2054]
Two question: When do we want to release 0.12.0? And what should/must be in it?

As to when:
- I was asked to write an article about OSCAR for the Computeralgebra Rundbrief, and have written it using the new names. Of course it'd be great if 0.12.0 was out by the time people get the printed version in a few weeks, but for now I'll just hedge my bets by explaining that the examples need >= 0.12.0 OR a DEV version
- if there are upcoming schools or conferences or other things that might give reasons for a fast (or slow!) release timing

As to what should go in it: I created a [milestone](https://github.com/oscar-system/Oscar.jl/milestone/1) for this release with the issues and PRs I'd like to ideally resolve for it. Feel free to suggest other things or propose that we drop things. I'd rather not have anything big, though.

**Comment by thofma** [comment]
Is someone working on those milestones? I would like to have a new release.

**Comment by fingolfin** [comment]
Not really :-(.

I'd just say: go ahead and make that release

**Comment by thofma** [comment]
I will remove https://github.com/oscar-system/Oscar.jl/issues/2064 from the milestone. I guess you wanted https://github.com/oscar-system/Oscar.jl/issues/2064 for the Rundbrief, but it has been delivered already and 0.12.0 is not out?

**Comment by lgoettgens** [comment]
This can be closed now since 0.12.0 has been released, right?
