### ISSUE TITLE
Add `diagonal_matrix` variant taking base ring as first argument

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2061]
I wanted to simplify the creation of a diagonal matrix in my code:
```julia
julia> a = matrix(QQ, [1  0  0
                       0 -1  0
                       0  0 -1])
[1    0    0]
[0   -1    0]
[0    0   -1]
```
I guessed that there should be a function `diagonal_matrix`, and there is! My first intuitive guess as to use it (of course I don't read manuals, nobody does) was this:
```julia
diagonal_matrix(QQ, [1, -1, -1])
```
but of course that fails. After consulting the manual, I determined that this works (an example in the relevant docstring would be nice for beginners, I guess):
```julia
julia> diagonal_matrix([QQ(1), QQ(-1), QQ(-1)])
[1    0    0]
[0   -1    0]
[0    0   -1]
```
Of course if one knows Julia, one can simplify this via broadcast
```julia
diagonal_matrix(QQ.([1, -1, -1]))
```
but I am pretty sure beginners won't know that.

So: how about we add
```julia
diagonal_matrix(R::Ring, x::Vector) = diagonal_matrix(R.(x))
```
Is there anything inherently bad or problematic about this?

**Comment by thofma** [comment]
I also found myself wanring this in the past. I don't see any downside.
