### ISSUE TITLE
Visualization of polytope: vertex labels vs. automorphisms

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2068]
Consider the same example as in issue #2066:
```julia-repl
julia> F, t = quadratic_field(3)
(Real quadratic field defined by x^2 - 3, sqrt(3))

julia> a = diagonal_matrix(F.([1, -1, -1]));
julia> b = matrix(F, [1//2 -t//2 0
                      t//2  1//2 0
                         0     0 1]);

julia> G = matrix_group(a, b);

julia> o = orbit(G, *, F.([1,1,1]));

julia> vert = matrix(F, collect(o));

julia> ph = convex_hull(nf_elem, vert);

julia> visualize(ph)
```
One can visualize this, which is great! It also shows vertex indices, like this screenshot:
<img width="683" alt="visualization" src="https://user-images.githubusercontent.com/241512/225557411-02e3e805-a5db-499e-a3db-71caae565775.png">

Two issues:
1. using the "download screenshot" feature in the browser applet unfortunately does not export the vertex labels, so I had to take a regular (pixel) screenshot
2. the vertices are numbered starting from 0, which makes sense in a 0-based environment. But we are 1-based, and now this does not fit with the vertex automorphisms:
```julia-repl
julia> aut = automorphism_group(ph; action=:on_vertices)
Group([ (2,12)(3,7)(4,8)(5,9)(6,11),
        (1,2)(3,5)(4,7)(6,9)(8,11)(10,12),
        (1,3,6,10,11,7)(2,4,8,12,9,5) ])
```
Any chance this could be changed to show labels starting at 1?

**Comment by benlorenz** [comment]
Regarding the missing labels in the SVG: This is not something we can easily change, we just render the same image using the SVGRenderer from threejs but this doesn't seem to support the labels.
