### ISSUE TITLE
CI test failure: no method matching (::FlintRationalField)(::Singular.n_Q)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#208]
As is visible on https://github.com/oscar-system/Oscar.jl/actions?query=workflow%3A%22Run+tests%22+branch%3Amaster the  tests started failing between commits c46b63ee59bf4d2a61e9a80cd4f384c296fb480b and 27a505a67047814d098b2fc8d3f1a518c93f959d with this error:
```
Polynomial homs: Error During Test at /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-test.jl:43
  Test threw exception
  Expression: h(gen(S, 1)) == I1
  MethodError: no method matching (::FlintRationalField)(::Singular.n_Q)
  Closest candidates are:
    Any(!Matched::nf_elem) at /home/runner/.julia/packages/Hecke/SROq0/src/NumField/NfAbs/NfAbs.jl:1243
    Any() at /home/runner/.julia/packages/Nemo/oOtel/src/flint/fmpq.jl:819
    Any(!Matched::Int64, !Matched::Int64) at /home/runner/.julia/packages/Nemo/oOtel/src/flint/fmpq.jl:832
    ...
```

@fieker you pushed that code, I hope you have a fix.

May I suggest this is another example why it might be helpful to do these things via a PR, so that we detect mistakes earlier, instead of breaking the test suite for all?  It just cost me half an hour because I thought my PR #207 was the cause, since the message involves `gen` ... :-(

**Comment by fieker** [comment]
On Thu, Dec 17, 2020 at 02:01:09AM -0800, Max Horn wrote:
> As is visible on https://github.com/oscar-system/Oscar.jl/actions?query=workflow%3A%22Run+tests%22+branch%3Amaster the  tests started failing between commits c46b63ee59bf4d2a61e9a80cd4f384c296fb480b and 27a505a67047814d098b2fc8d3f1a518c93f959d with this error:
> ```
> Polynomial homs: Error During Test at /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/mpoly-test.jl:43
>   Test threw exception
>   Expression: h(gen(S, 1)) == I1
>   MethodError: no method matching (::FlintRationalField)(::Singular.n_Q)
>   Closest candidates are:
>     Any(!Matched::nf_elem) at /home/runner/.julia/packages/Hecke/SROq0/src/NumField/NfAbs/NfAbs.jl:1243
>     Any() at /home/runner/.julia/packages/Nemo/oOtel/src/flint/fmpq.jl:819
>     Any(!Matched::Int64, !Matched::Int64) at /home/runner/.julia/packages/Nemo/oOtel/src/flint/fmpq.jl:832
>     ...
> ```
> 
> @fieker you pushed that code, I hope you have a fix.
> 
> May I suggest this is another example why it might be helpful to do these things via a PR, so that we detect mistakes earlier, instead of breaking the test suite for all?  It just cost me half an hour because I thought my PR #207 was the cause, since the message involves `gen` ... :-(
> 
While I am sorry - this is actually even worse: the function was added
("moved") into Singular.jl, hence removed from Oscar.
as part of
403d4c6c70a065516eff082d10bc14b51de65135
I can add it back into Oscar, but then we're having duplicate symbols.
This is part of the upwards testing problem and the release cycle

**Comment by fingolfin** [comment]
https://github.com/oscar-system/Singular.jl/commit/403d4c6c70a065516eff082d10bc14b51de65135 ? OK, I don't see the relation, but it doesn't matter, really, as long as the core issue is: this needs a new Singular.jl.

Well, then we should just release a new Singular.jl today? While it won't have the new FLINT and Singular yet, I think there is no blocker for doing so? 

And it would be a good thing anyway, because the current Singular.jl release0 0.4.1 is "ancient" by out standards ;-), i.e. it is from September. More importantly, the old version has a Project.toml which blocks AbstractAlgebra 0.11, so it also causes us to use outdated versions of Nemo (and perhaps Hecke?).

**Comment by fieker** [comment]
On Thu, Dec 17, 2020 at 02:18:24AM -0800, Max Horn wrote:
> https://github.com/oscar-system/Singular.jl/commit/403d4c6c70a065516eff082d10bc14b51de65135 ? OK, I don't see the relation, but it doesn't matter, really, as long as the core issue is: this needs a new Singular.jl.
> 
> Well, then we should just release a new Singular.jl today? While it won't have the new FLINT and Singular yet, I think there is no blocker for doing so? 
> 
> And it would be a good thing anyway, because the current Singular.jl release0 0.4.1 is "ancient" by out standards ;-), i.e. it is from September. More importantly, the old version has a Project.toml which blocks AbstractAlgebra 0.11, so it also causes us to use outdated versions of Nemo (and perhaps Hecke?).
> 

I send the wrong sha, 
 3d29c3a1bbe116864941067bd7382dfbaf158847
introduced this
  commit 3d29c3a1bbe116864941067bd7382dfbaf158847
  Author: ....
  Date:   Thu Oct 22 12:26:56 2020 +0200

      fix #86, more conversions from/to n_Q

**Comment by wbhart** [comment]
In case it is relevant, I intend to make the current rc final for the Flint release tomorrow morning. I realise this is tight timing, for which I apologise, but the unexpected CMake issue took us nearly a week to sort out.

**Comment by fingolfin** [comment]
This has been resolved by the release of Singular.jl 0.4.2
