### ISSUE TITLE
Toric Varieties: ZZRingElem vs. IntegerUnion

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#2086]
Check if, and at what places, we want to replace `IntegerUnion` by `ZZRingElem`. (cf. https://github.com/oscar-system/Oscar.jl/pull/2080)

cc @thofma

**Comment by fingolfin** [comment]
Functions which take arguments ideally accept `IntegerUnion` not just `ZZRingElem`, to be more convenient to use. For internal storage, picking a concrete type is usually preferable, to allow the compiler to optimize the code better.

**Comment by HereAround** [comment]
This was - at the time - meant for optimization purposes. Still, it would seem that - at least as of now - no such optimization is needed. (At least, I have not received any complaints/uncovered undesired effects that trace back to the point in question). So I will close this issue.
