### ISSUE TITLE
Error when running `using Oscar` in a jupyter notebook for the first time

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#2090]
**Describe the bug**
In jupyter notebooks, I have to run `using Oscar` twice because I get the following error after running it for the first time:

(red box)
```
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: bundlerextension execute migrate nbextension notebook
serverextension troubleshoot

Jupyter command `jupyter-kernelspec` not found.
```

(output cell)
```
InitError: failed process: Process(`jupyter kernelspec list --json`, ProcessExited(1)) [1]

during initialization of module Polymake

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:565 [inlined]
  [2] read(cmd::Cmd)
    @ Base ./process.jl:449
  [3] read(cmd::Cmd, #unused#::Type{String})
    @ Base ./process.jl:458
  [4] prepare_jupyter_kernel_for_visualization()
    @ Polymake ~/.julia/packages/Polymake/A0Z5B/src/ijulia.jl:26
  [5] __init__()
    @ Polymake ~/.julia/packages/Polymake/A0Z5B/src/Polymake.jl:161
  [6] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, path::String, sourcepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:938
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loading.jl:1028
  [9] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1315
 [10] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
 [11] macro expansion
    @ ./loading.jl:1180 [inlined]
 [12] macro expansion
    @ ./lock.jl:223 [inlined]
 [13] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
```

**To Reproduce**
1. Start `jupyter notebook`
2. Open an Oscar jupyter notebook, e.g., [Martin's excellent tutorial on toric geometry](https://www.oscar-system.org/tutorials/) (I do this by running `using IJulia` + `notebook()` in Julia or by typing `jupyter notebook` in the terminal)
3. Run the cell with `using Oscar`

**Expected behavior**
Oscar should be loaded after the first execution of `using Oscar`.

**System:**
(executed in the jupyter notebook)
```
OSCAR version 0.11.3
  combining:
    AbstractAlgebra.jl   v0.27.10
    GAP.jl               v0.9.4
    Hecke.jl             v0.17.5
    Nemo.jl              v0.32.7
    Polymake.jl          v0.9.0
    Singular.jl          v0.16.1
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.4+0
    GAP_jll                 v400.1200.200+0
    Singular_jll            v403.101.500+0
    libpolymake_julia_jll   v0.9.0+0
    libsingular_julia_jll   v0.29.0+0
    polymake_jll            v400.900.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Official https://julialang.org/ release
...
```

**Comment by thofma** [comment]
@benlorenz any clue?

**Comment by benlorenz** [comment]
Maybe some weird interaction between different python / jupyter installations? How did you install python and jupyter?

Can you run this outside of julia just like you would start `jupyter notebook`?
```sh
which jupyter
which jupyter-kernelspec
```

And then run this within a jupyter session:
```julia
run(`which jupyter`)
run(`which jupyter-kernelspec`)
```

And maybe this as well:
```julia
using IJulia
IJulia.find_jupyter_subcommand("kernelspec")
```

But we can probably make that kernel stuff non-fatal to avoid this blocking Oscar from loading.
The reason for this call is that we need to add something to the julia-jupyter-kernel to make the threejs visualization work.

**Comment by YueRen** [comment]
So it seems to be something on my system, that's good to know!

When I run the commands in the terminal I get:
```
ren@thinkpad:~$ which jupyter
/usr/bin/jupyter
ren@thinkpad:~$ which jupyter-kernelspec
[nothing]
```

The commands in my jupyter notebook gives me:
![Screenshot from 2023-03-20 19-01-56](https://user-images.githubusercontent.com/1073963/226440251-0ae357d8-aeeb-4856-b0b7-ddbd5dfa34d1.png)

The command in julia gives me:
```
julia> using IJulia

julia> IJulia.find_jupyter_subcommand("kernelspec")
`/usr/bin/jupyter kernelspec`
```

Also, I can confirm that in-notebook visualisation does not work for me. When I ask for a visualisation, my browsers opens a new tab with it. My jupyter-notebook is up to date (v6.5.3).

**Comment by benlorenz** [comment]
I don't get such errors when loading Oscar in jupyter, and I do have this jupyter-kernelspec command.
Can you check if you can install something like `jupyter_client` or `python-jupyter-client`? This should bring the kernelspec subcommand (and I would have expected this to come with a default jupyter installation).

**Comment by thofma** [comment]
Is it normal that the systems `jupyter` is picked up?

**Comment by YueRen** [comment]
I just reinstalled jupyter with `pip install --upgrade --force-reinstall jupyter_client` and I have a `jupyter-kernelspec` now (the `--force-reinstall` was necessary because otherwise pip would do nothing).  I believe that I got an incomplete `jupyter` by only installing `jupyter-notebook` via `apt`, but not `jupyter-client`:
```
ren@thinkpad:~/oscar/master$ jupyter-kernelspec
Command 'jupyter-kernelspec' not found, but can be installed with:
sudo apt install jupyter-client

ren@thinkpad:~/oscar/master$ apt list --installed | grep jupyter

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

jupyter-core/jammy,jammy,now 4.9.1-1 all [installed,automatic]
jupyter-nbextension-jupyter-js-widgets/jammy,jammy,now 6.0.0-9 all [installed,automatic]
jupyter-notebook/jammy-updates,jammy-updates,jammy-security,jammy-security,now 6.4.8-1ubuntu0.1 all [installed]
python3-jupyter-client/jammy,jammy,now 7.1.2-1 all [installed,automatic]
python3-jupyter-core/jammy,jammy,now 4.9.1-1 all [installed,automatic]
python3-jupyterlab-pygments/jammy,jammy,now 0.1.2-8 all [installed,automatic]
```

**Comment by benlorenz** [comment]
> Is it normal that the systems `jupyter` is picked up?

Yes, that is fine, IJulia tries to use whatever jupyter it can find. And if none is found it might offer to install it via conda.

A long time ago IJulia did use the `jupyter kernelspec` as well to install the kernel, but the code now guesses the path via some environment variables / default paths and thus avoids such problems.
We can probably try to run that kernelspec command and if it fails try to use determine the paths from IJulia, there seems to be an internal function to get the kernel directory. (Unfortunately there does not seem to be a command to get the name of the currently active kernel.)
I opened https://github.com/oscar-system/Polymake.jl/issues/427 to make sure we don't forget this.

PS: https://xkcd.com/1987/
