### ISSUE TITLE
serialization versus the Big Renaming

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2143]
During the big renaming we renamed lots of types.

These type names are also used by the serialization, and are written in JSON files and read back from there to steer the deserialization.

I suspect that the Big Renaming thus broke importing of any old files using the old names... We can say that's OK, or we can say we need to do something. I am fine with either, as long as it is a deliberate choice.

**Comment by antonydellavecchia** [comment]
it shouldn't be too much to include an upgrade from old files, do we have a renaming map somewhere?

**Comment by lgoettgens** [comment]
Afaik https://github.com/oscar-system/Oscar.jl/wiki/The-Big-Renaming is the best resource for this.

**Comment by antonydellavecchia** [comment]
I will close since I haven't found time for this and doesn't seem to be setting anyone back
