### ISSUE TITLE
`deepcopy` for module elems

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2152]
`deepcopy` behaves differently for different OSCAR types. For polynomial rings, it creates an identical polynomial in the same parent. For `FreeMod` (and I think other module types, but I am not sure about that), it copies the parent as well, resulting in a mathematically identical element in a mathematically identical parent.

```julia
julia> R, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Rational Field, QQMPolyRingElem[x, y, z])

julia> x == deepcopy(x)
true

julia> F = free_module(R, 2)
Free module of rank 2 over Multivariate Polynomial Ring in x, y, z over Rational Field

julia> t = gen(F, 1)
e[1]

julia> t == deepcopy(t)
false
```

I would love to have consistent behavior on this for most/all of our types.

**Comment by fieker** [comment]
On Mon, Mar 27, 2023 at 04:20:49PM -0700, Lars Göttgens wrote:
> `deepcopy` behaves differently for different OSCAR types. For polynomial rings, it creates an identical polynomial in the same parent. For `FreeMod` (and I think other module types, but I am not sure about that), it copies the parent as well, resulting in a mathematically identical element in a mathematically identical parent.
> 
The module behaviour is wrong, the parent must not be dublicated.

**Comment by joschmitt** [comment]
I guess the "problem" is simply that nobody bothered to write a proper `deepcopy_internal` for the module elements so far. In your example:
```
julia> @which Base.deepcopy_internal(x, IdDict())
deepcopy_internal(a::QQMPolyRingElem, dict::IdDict) in Nemo at /home/schmitt/.julia/packages/Nemo/SV6sR/src/flint/fmpq_mpoly.jl:84

julia> @which Base.deepcopy_internal(t, IdDict())
deepcopy_internal(x, stackdict::IdDict) in Base at deepcopy.jl:53

```
