### ISSUE TITLE
CI failure due to serialization of universal polynomials

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2158]
Since the merge of #2113, there are CI failures on master, e.g. [https://github.com/oscar-system/Oscar.jl/actions/runs/4547519262/jobs/8017499717](https://github.com/oscar-system/Oscar.jl/actions/runs/4547519262/jobs/8017499717).

As far as I can tell, the test sets for serialization of universal polynomials over {Rationals, Integers modulo 6,Finite Field} error, the other cases pass.

**Comment by thofma** [comment]
@SoongNoonien any idea what could be wrong?

**Comment by SoongNoonien** [comment]
As the tests worked with all base rings as I implemented the serialization this may be a new issue with the universal polynomials in general similar to https://github.com/oscar-system/Oscar.jl/issues/2076. So me guess is that the error occurs while creating the universal polynomial ring. I'll try to reproduce it here to make some further tests.

**Comment by fingolfin** [comment]
I've reverted PR #2113 for now to make the tests pass again. This looks like one of those unfortunate cases were changes "cross", i.e., the CI tests passed separately, but not in combination. Perhaps we should try the beta "merge queue" feature which is meant to prevent exactly this kind of problem (well, up to a degree -- if one part of the changes is that a different package made a new release, then we can't fully avoid this)

**Comment by fingolfin** [comment]
@SoongNoonien can you resubmit your changes in a new PR? (Basically you can use `git revert` my revert commit; just edit the commit message to match what you had before). Alternatively I can do that for you.

**Comment by lkastner** [comment]
cc @antonydellavecchia

**Comment by benlorenz** [comment]
Apart from the serialization commit which just seems to be the only code in Oscar that uses this feature, the failure seems to be caused by this AbstractAlgebra change (https://github.com/Nemocas/AbstractAlgebra.jl/pull/1282, @mgkurtz) which was included starting in version 0.28.4:
```
8d769fa9d3fe0477b8cd3f5629302a7cb9d9aeec is the first bad commit
commit 8d769fa9d3fe0477b8cd3f5629302a7cb9d9aeec
Author: Markus Kurtz <kurtz@mathematik.uni-kl.de>
Date:   Mon Mar 20 20:43:46 2023 +0100

    Move `polynomial_ring` code to abstract level (#1282)
```

Starting from that commit we get this failure in Oscar:
```julia
julia> using Oscar
 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.12.0-DEV ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2023 by The OSCAR Development Team

julia> R = UniversalPolynomialRing(QQ)
ERROR: need at least one indeterminate
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] (::Nemo.var"#31#32"{Vector{Symbol}, Symbol})()
    @ Nemo ~/.julia/packages/Nemo/jFzAs/src/flint/FlintTypes.jl:1459
  [3] (::AbstractAlgebra.var"#16#17"{Nemo.var"#31#32"{Vector{Symbol}, Symbol}, AbstractAlgebra.WeakValueDict{Tuple{Vector{Symbol}, Symbol}, QQMPolyRing}, Tuple{Vector{Symbol}, Symbol}})()
    @ AbstractAlgebra ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:558
  [4] lock(f::AbstractAlgebra.var"#16#17"{Nemo.var"#31#32"{Vector{Symbol}, Symbol}, AbstractAlgebra.WeakValueDict{Tuple{Vector{Symbol}, Symbol}, QQMPolyRing}, Tuple{Vector{Symbol}, Symbol}}, l::ReentrantLock)
    @ Base ./lock.jl:185
  [5] lock
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:514 [inlined]
  [6] get!
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:548 [inlined]
  [7] get_cached!
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/AbstractAlgebra.jl:480 [inlined]
  [8] QQMPolyRing
    @ ~/.julia/packages/Nemo/jFzAs/src/flint/FlintTypes.jl:1448 [inlined]
  [9] QQMPolyRing
    @ ~/.julia/packages/Nemo/jFzAs/src/flint/FlintTypes.jl:1471 [inlined]
 [10] #polynomial_ring_only#363
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/MPoly.jl:1330 [inlined]
 [11] #polynomial_ring#362
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/MPoly.jl:1320 [inlined]
 [12] (::AbstractAlgebra.Generic.var"#9#10"{QQFieldElem, AbstractAlgebra.Generic.MPoly{QQFieldElem}, QQField, Symbol, Bool})()
    @ AbstractAlgebra.Generic ~/software/polymake/julia/AbstractAlgebra.jl/src/generic/GenericTypes.jl:424
 [13] (::AbstractAlgebra.var"#16#17"{AbstractAlgebra.Generic.var"#9#10"{QQFieldElem, AbstractAlgebra.Generic.MPoly{QQFieldElem}, QQField, Symbol, Bool}, AbstractAlgebra.WeakValueDict{Tuple{AbstractAlgebra.Ring, Symbol, DataType}, AbstractAlgebra.Ring}, Tuple{QQField, Symbol, DataType}})()
    @ AbstractAlgebra ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:558
 [14] lock(f::AbstractAlgebra.var"#16#17"{AbstractAlgebra.Generic.var"#9#10"{QQFieldElem, AbstractAlgebra.Generic.MPoly{QQFieldElem}, QQField, Symbol, Bool}, AbstractAlgebra.WeakValueDict{Tuple{AbstractAlgebra.Ring, Symbol, DataType}, AbstractAlgebra.Ring}, Tuple{QQField, Symbol, DataType}}, l::ReentrantLock)
    @ Base ./lock.jl:185
 [15] lock
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:514 [inlined]
 [16] get!
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/WeakValueDict.jl:548 [inlined]
 [17] get_cached!
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/AbstractAlgebra.jl:480 [inlined]
 [18] UniversalPolyRing
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/generic/GenericTypes.jl:423 [inlined]
 [19] #UniversalPolynomialRing#222
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/generic/UnivPoly.jl:1131 [inlined]
 [20] #UniversalPolynomialRing#370
    @ ~/software/polymake/julia/AbstractAlgebra.jl/src/UnivPoly.jl:36 [inlined]
 [21] UniversalPolynomialRing(R::QQField)
    @ AbstractAlgebra ~/software/polymake/julia/AbstractAlgebra.jl/src/UnivPoly.jl:35
 [22] top-level scope
    @ REPL[1]:1
```
(I needed to adjust the Project.toml to test it.)

Note that using QQ from AbstractAlgebra works fine:
```
julia> R = UniversalPolynomialRing(AbstractAlgebra.QQ)
Universal Polynomial Ring over Rationals
```

**Comment by thofma** [comment]
Ah, makes sense that this (the recent change to the multivariate polynomial constructors) interferes with the universial polynomials. They need to construct generic multivariate polynomial rings. I can have a look later if no one beats me to it. One needs to make sure that https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/GenericTypes.jl#L425 calls the generic polynomial ring constructor and not `AbstractAlgebra.polynomial_ring`. @mgkurtz how would one do this with the new interface?

**Comment by mgkurtz** [comment]
Indeed, I broke `Generic.polynomial_ring`. The easiest thing seems to call `polynomial_ring` with a keyword `generic=true` and let `polynomial_ring_only` use this keyword. I can provide this as a PR later today.

**Comment by thofma** [comment]
Nah, I don't like adding keyword arguments which change the type. Will also make everything unstable. Can we just call `Generic.MPolyRing{}(...)` instead?

**Comment by fingolfin** [comment]
Indeed, it seems the natural thing to do if one wants to construct a *specific* type of polynomials is to use the type constructor

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1311

**Comment by fingolfin** [comment]
Is this resolved now?

**Comment by benlorenz** [comment]
This was resolved: reverted, issue fixed in AbstractAlgebra, released and the original code re-added.
