### ISSUE TITLE
Enable codecov report comments

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2165]
At the beginning, I was not too excited about the automatic codecov reports posted as a comment on the pull request. But it has been super useful in the upstream projects and I have come to miss it in OSCAR. I would like to enable it also for OSCAR. Are there any reasons not to enable it? @fingolfin @fieker @benlorenz 

Edit: It was disabled in https://github.com/oscar-system/Oscar.jl/commit/a1074a2f780eec2cef28c0875c6f0de63170fb10 by @fingolfin, but I am not sure why? (Maybe I was complaining about it?)

**Comment by fingolfin** [comment]
I use Codecov comments everywhere (outside of Oscar, that is) and am pretty sure that if I disabled it here, then only because someone was complaining :-)

**Comment by benlorenz** [comment]
I remember that at some point (long ago) the coverage was very unreliable and would jump up and done a lot even without any relevant changes to the file. But I guess/hope this got better by now.

**Comment by thofma** [comment]
Codecov bot is being unhelpful again?

<img width="942" alt="Screenshot 2023-03-31 at 19 20 46" src="https://user-images.githubusercontent.com/11231648/229187807-ab04c69d-089f-4817-be24-90fa84959120.png">

This is from #2154

**Comment by benlorenz** [comment]
You have to wait until 1.6 is done, but we should probably skip the collection and upload steps for all runs where codecov is disabled anyway.
See the edits in this comment: https://github.com/oscar-system/Oscar.jl/pull/2157#issuecomment-1492247057

**Comment by thofma** [comment]
Hm yes, confusing. Why does it report 0.00% percent for the run of this one version?

**Comment by benlorenz** [comment]
Because the collect+upload steps are always running but we disabled the coverage generation for the tests for != 1.6 . Then it uploads everything as uncovered.
```
[ Info: CoverageTools.process_file: Detecting coverage for src/AlgebraicGeometry/Miscellaneous/basics.jl
┌ Info: CoverageTools.process_cov: Coverage file(s) for src/AlgebraicGeometry/Miscellaneous/basics.jl do not exist.
└ Assuming file has no coverage.
```

**Comment by thofma** [comment]
Thanks for the explanation. I only saw that collect + updated run, but missed that we disabled the generation.
