### ISSUE TITLE
A lot of infos during tests about "AUXILIARY ambient space"

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2180]
There are quite are lot of messages of the form 
```
[ Info: Base space was not fully specified. Returning AUXILIARY ambient space.
```
during the tests. Is there a way to disable this? See https://github.com/oscar-system/Oscar.jl/actions/runs/4577059265/jobs/8082008614#step:6:1194

Seem to be coming from the FTheoryTools. CC: @HereAround

**Comment by HereAround** [comment]
Thank you for pointing this out @thofma .

The origin is https://github.com/oscar-system/Oscar.jl/pull/2163. I replaced some slow `doctests` by faster `doctests`. This is at the expense of conducting computations, for which @apturner and I decided a while back that the user should be informed - hence the info that you mention.

Yes, the above info is printed quite a few times (~50 times). Still, the log seems still readable, not?

If you disagree, we can investigate if there is a way to disable this info while running the `doctests`. At the top of my head, I have no idea how this could be done.

Maybe @apturner has yet another idea?

**Comment by thofma** [comment]
Hm, so far the general consensus in OSCAR has been, that we do not print verbose output unless the user asked for it.

So not every groebner basis call leads to a
```
[ Info: Groebner basis is being computed. This might take very long]
```

**Comment by HereAround** [comment]
Alright, then we try to optimize along these lines. I will look into the groebner basis.

**Comment by fieker** [comment]
one should not use the julia info/warn/debug logging functions but the vprint ones. They provide finer granularity and the ability to switch globall on and off
