### ISSUE TITLE
Serialization: how to specify "parent" for serialized ideals?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2190]
Consider this:
```
julia> R, (x,y) = QQ[:x,:y];

julia> I = ideal([x^2, y^2]);

julia> save("ideal.json", I)
```

Now I would like to load the ideal again, with `R` as its "parent", except it's not the parent, but the base_ring. Anyway: load `I` as an ideal in that `R`, not an isomorphic copy. 
```julia
julia> J = load("ideal.json")
ideal(x^2, y^2)

julia> base_ring(I) == base_ring(J)
false
```

Is there a way? The "obvious" approach gives a (to me) surprising error:
```
julia> J = load("ideal.json", parent=base_ring(I))
ERROR: KeyError: key UUID("c39748ab-d150-4ff9-b834-9253f51991df") not found
```

**Comment by thofma** [comment]
(Hm, the parent of ideals should be the set of all ideals and not the base ring.)

**Comment by fingolfin** [comment]
OK, good point: one might say that the core of the problem is that `parent(I)` is not implemented. So I guess one way to address the issue would be to implement such an object.

**Comment by antonydellavecchia** [comment]
I have a fix that I am pushing to the file-formatting branch https://github.com/oscar-system/Oscar.jl/pull/2102 , some changes from this pull request were necessary to get things to work properly

**Comment by micjoswig** [comment]
> (Hm, the parent of ideals should be the set of all ideals and not the base ring.)

I disagree here.  The math needs to be separated from the syntax.  This is strictly necessary, e.g., in order to fulfill the request by @fingolfin and @fieker  to allow for serialization for interprocess communication.

Syntactically, in order to be able to properly decode a polynomial, I need to know the encoding of the base ring.

**Comment by lgoettgens** [comment]
Resolved by https://github.com/oscar-system/Oscar.jl/pull/2102
