### ISSUE TITLE
Adapt serialization to finite field changes

### ISSUE THREAD

**Issue by antonydellavecchia** [oscar-system/Oscar.jl#2192]
With the current changes to finite fields the serialization needs to be fixed

**Comment by micjoswig** [comment]
I just want to recheck.  The default finite field construction will be like `F, o = Hecke.Nemo._FiniteField(8)`, right? And `o` is a generator of the multiplicative group.  Then, for the serialization, it suffices to encode each element in that field by some integer between 0 and 7.  Probably, it makes sense to reserve 0 for the zero element, and we map k to o^k for the others.  Then o^7 would be the element 1 in the field.

And each copy of that field has its own generator (and thus interpretation of the serialization).  So they become parents, e.g., for a polynomial ring with those coefficients.

OK?

@thofma @antonydellavecchia

**Comment by thofma** [comment]
This is not quite right. It is not guaranteed that `o` is a multiplicative generator. It is a coincidence for small fields. The element `o` is (as it is now), a generator for the field over `F_2`.

**Comment by micjoswig** [comment]
So then each element in the field is a linear combination (with coefficients in `F_2`) of powers of `o`. 

The current serialization calls `defining_polynomial` and thus treats finite fields as special algebraic extensions.  This way you can explicitly work with towers of extensions.  That's what you need, right?

**Comment by thofma** [comment]
Yes and yes, treating this as an algebraic extension would make everything work.
