### ISSUE TITLE
OSCAR tests failing on 1.9 CI (precompilation failing)

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2199]
Failing during precompilation: https://github.com/oscar-system/Oscar.jl/actions/runs/4598065420/jobs/8121592229?pr=2198

This is julia 1.9-rc1. Anyone seen this before? @fingolfin @benlorenz?

**Comment by benlorenz** [comment]
That seems to be the same as https://github.com/JuliaLang/julia/issues/48150, the line has moved a bit but this still claims `unreachable`:
https://github.com/JuliaLang/julia/blob/v1.9.0-rc1/src/staticdata.c#LL3108

I haven't seen this so far for Oscar and I would guess this disappears with a re-run. Unless this happens more often I think we should ignore it.

**Comment by thofma** [comment]
Makes sense, thanks for checking.
