### ISSUE TITLE
Vector spaces complement.

### ISSUE THREAD

**Issue by GDeFranceschi** [oscar-system/Oscar.jl#221]
Can a `complement` function be added to Vector Space functionalities? It's a function that computes the complement vector subspace in `V` of a given subspace `W`. The following code is an example of how it could be: it computes `U` such that `U` and `W` are orthogonal with respect to the usual scalar product.

> function complement(V::AbstractAlgebra.Generic.FreeModule{T}, W::AbstractAlgebra.Generic.Submodule{T}) where T <: FieldElem
  > @assert issubmodule(V,W) "The second argument is not a subspace of the first one"

  > e = W.map
  > H = zero_matrix(base_ring(V), dim(W), dim(V))
  > for i in 1:dim(W)
   >   v = e(gen(W,i))
   >   for j in 1:dim(V)  H[i,j] = v[j]   end
  > end
  > d, K = kernel(H)
   > _gens = [ sum([K[j,i]*gen(V,j) for j in 1:dim(V)]) for i in 1:d ]
   > return sub(V,_gens)
> end

**Comment by fingolfin** [comment]
"The" complement does not exist / is not well-defined. And over finite fields or non-real fields, the standard scalar product in general is isotropic and so cannot be used to produce complements in general...

what do you really want to achieve ?

**Comment by thofma** [comment]
I think returning any complement would be already a useful function.

**Comment by GDeFranceschi** [comment]
> "The" complement does not exist / is not well-defined. And over finite fields or non-real fields, the standard scalar product in general is isotropic and so cannot be used to produce complements in general...
> 
> what do you really want to achieve ?

I need just "any" complement. On finite fields the condition of "orthogonality" is not required. If it creates confusion, it can be just deleted.

**Comment by fingolfin** [comment]
I agree any complement can be useful; it's easy to read one off from a rref basis, too; still would be useful to know what you need it for?

**Comment by GDeFranceschi** [comment]
> I agree any complement can be useful; it's easy to read one off from a rref basis, too; still would be useful to know what you need it for?

Yeah, I can delete the comment. I need it for the change of basis algorithm for bilinear forms. I have no problem in placing that function in the same file .jl with isometries stuff. I opened the issue just to ask if it would be better to put that function in the same file with other pre-existing vector space functionalities and avoid to have, in future, vector space functionalities scattered throughout Oscar in several files that have nothing to do with each other.

**Comment by thofma** [comment]
I would add your function as `_complement` in Oscar right now so that you can move on. Once we have it here we can just replace it.

**Comment by YueRen** [comment]
I'm closing the issue, as `complement` is now part of Oscar:

```
help?> complement
search: complement complement_ideal complement_system complement_scheme complement_of_ideal complement_equation complementary_divisor

  complement(V::AbstractAlgebra.Generic.FreeModule{T}, W::AbstractAlgebra.Generic.Submodule{T}) where T <: FieldElem

  Return a complement for W in V, i.e. a subspace U of V such that V is direct sum of U and W.
```
