### ISSUE TITLE
factor_absolute(f::QQMPolyRingElem) is unstable and does not match its documentation

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#2211]
```
julia> R,(x1,x2) = polynomial_ring(QQ,2);

julia> typeof(factor_absolute(x1))
Vector{Any} (alias for Array{Any, 1})

julia> factor_absolute((x1^2+1)*x2)
3-element Vector{Any}:
                                                           1
            AbstractAlgebra.Generic.MPoly{nf_elem}[x2, 1] => 1
 AbstractAlgebra.Generic.MPoly{nf_elem}[x1 - _a, x1 + _a] => 1

julia> factor_absolute((x1^2+1)*x1)
3-element Vector{Any}:
                                                           1
                                      QQMPolyRingElem[x1] => 1
 AbstractAlgebra.Generic.MPoly{nf_elem}[x1 - _a, x1 + _a] => 1

```
The expected output is probably
```
julia> factor_absolute((x1^2+1)*x1)
3-element Vector{Any}:
                                                           1
                                      QQMPolyRingElem[x1, 1] => 1
 AbstractAlgebra.Generic.MPoly{nf_elem}[x1 - _a, x1 + _a] => 1

```

**Comment by thofma** [comment]
@fieker

**Comment by fieker** [comment]
Is it wrong, unexpected or suboptimal? I'm happy to change the output, but this I though matched the conventions

**Comment by fieker** [comment]
I wrote it for fun, but have no use for it.... So tell me what you want

**Comment by simonbrandhorst** [comment]
The documentation states
```
  factor_absolute(f::QQMPolyRingElem)

  Compute the factorisation of f in Q[X] over C, returns an array with first component the leading coefficient, and then, for each irreducible factor over Q[X] a
  tuple, containing

    •  an irreducible factor over a number field

    •  the product of all the other conjugate factors over this field

    •  the multiplicity.

  Recall that for each irreducible over Q there is one (minimal) number field (possibly Q) where this factor splits further. In this case all the factor over this
  field are Galois-conjugate. In order to not create a huge splitting field, only one factor and the product of the conjugates is returned.

```
But "    •  the product of all the other conjugate factors over this field"  is missing for  the x1 factor

```
julia> factor_absolute((x1^2+1)*x1)
3-element Vector{Any}:
                                                           1
                                      QQMPolyRingElem[x1] => 1
 AbstractAlgebra.Generic.MPoly{nf_elem}[x1 - _a, x1 + _a] => 1
```
curiously it is there for
```
julia> factor_absolute((x1^2+1)*x2)
3-element Vector{Any}:
                                                           1
            AbstractAlgebra.Generic.MPoly{nf_elem}[x2, 1] => 1
 AbstractAlgebra.Generic.MPoly{nf_elem}[x1 - _a, x1 + _a] => 1
```
This does not match the documentation (if I understand it correctly) and seems inconsistent to me. 
If I have a wish, I would ask for `is_absolutely_irreducible` .
Note that the documentation of 
```
  factor_absolute(f::MPolyRingElem{Generic.Frac{QQMPolyRingElem}})
```
has different conventions on the return values. I find them hard to use and would recommend to follow the specification for `QQMPolyRingElem.`

**Comment by fieker** [comment]
I look into it. You want a Pure is_abs_irr just returning true/false?

**Comment by simonbrandhorst** [comment]
Yes, that would be convenient.

**Comment by simonbrandhorst** [comment]
Could you please also provide an 
`is_absolutely_irreducible(QQMPolyRingElem)`?
So far we have it only for `QQ(t)` .

**Comment by fieker** [comment]
On Tue, Apr 11, 2023 at 06:56:22AM -0700, simonbrandhorst wrote:
> Could you please also provide an 
> `is_absolutely_irreducible(QQMPolyRingElem)`?
> So far we have it only for `QQ(t)` .
the QQ case should be in Hecke - and available

**Comment by simonbrandhorst** [comment]
I can't find it. I just pulled the latest Hecke master.

```
julia> R,(x1,x2) = PolynomialRing(QQ,2)
(Multivariate Polynomial Ring in x1, x2 over Rational Field, QQMPolyRingElem[x1, x2])

julia> Hecke.is_absolutely_irreducible(x2)
ERROR: MethodError: no method matching is_absolutely_irreducible(::QQMPolyRingElem)
```

```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.2
  [3e1990a7] Hecke v0.18.8 `~/.julia/dev/Hecke`
  [7073ff75] IJulia v1.24.0
  [2edaba10] Nemo v0.33.7
  [f1435218] Oscar v0.12.0-DEV `~/.julia/dev/Oscar`
  [295af30f] Revise v3.5.2
```

**Comment by fieker** [comment]
On Tue, Apr 11, 2023 at 11:45:20PM -0700, simonbrandhorst wrote:
by the looks of it, it is there...and not:
Hecke/src/NumField/NfAbs/MPolyAbsFact.jl 
"""
    is_absolutely_irreducible(f::QQMPolyRingElem)

Tests if `f` is irreducible over `C`.
"""
function is_absolutely_irreducible(a::QQMPolyRingElem)
  @vprint :AbsFact 1 "testing  over QQ first...\n"
  is_irreducible(a) || return false
  unit, fp = absolute_multivariate_factorisation(a)
  return isone(fp[2])
end


but the export is missing on top of the file.
You can do (hopefully)
Hecke.MPolyFact.is_absolutely_irreducible
for now...

sorry

**Comment by simonbrandhorst** [comment]
Thanks! Do we want to make it part of the api, i.e. export it?

**Comment by fieker** [comment]
On Wed, Apr 12, 2023 at 12:23:09AM -0700, simonbrandhorst wrote:
> Thanks! Do we want to make it part of the api, i.e. export it?
Your call - that was my intend, but I never used this function (nor
factor_absolute)

**Comment by simonbrandhorst** [comment]
Let's export it. It seems useful to me - personally I use it in one place to check if a hypersurface is an integral scheme.

**Comment by fieker** [comment]
On Wed, Apr 12, 2023 at 12:51:34AM -0700, simonbrandhorst wrote:
> Let's export it. It seems useful to me - personally I use it in one place to check if a hypersurface is an integral scheme. 
> 
I'm glad i's useful. The Hecke PR is on its way
