### ISSUE TITLE
groebner_basis(...,algorithm=:f4) does not work over FiniteField()

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#2221]
**Describe the bug**
`groebner_basis([...],algorithm=:f4)` only works over `GF()` but not `FiniteField()`:

**To Reproduce**
```
F2,_ = FiniteField(2,1,"")
R,(x1,x2) = PolynomialRing(F2,2)
groebner_basis(ideal([x1]),algorithm=:f4) 
```

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.11.3-DEV
  combining:
    AbstractAlgebra.jl   v0.27.8
    GAP.jl               v0.9.2
    Hecke.jl             v0.17.2
    Nemo.jl              v0.32.7
    Polymake.jl          v0.8.3
    Singular.jl          v0.16.1
```

**Additional context**
This bug was found by @kemalrose

**Comment by thofma** [comment]
@ederc Can you give me the summary of the finite fields that `msolve` can handle? Prime/non-prime? Small/big characteristic?

**Comment by ederc** [comment]
As written in the documentation:

```
!!! note
    At current state only prime fields of characteristic `0 < p < 2^{31}` are supported.
```

**Comment by ederc** [comment]
Fixed via `AlgebraicSolving.jl v0.3.4`.
