### ISSUE TITLE
`complete_reduction` option for `reduce`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#2233]
`groebner_basis` has an option `complete_reduction`, which if set to `true` ensures that the returned Groebner basis is reduced.  

Can we equip `reduce` with the same option?  The default would be `false`, but if set to `true` then `reduce` would also perform tail reductions.  I would need it to read off the inequalities and equations of the Groebner cone.

**Comment by ederc** [comment]
There are already plans to do this, @hannes14 is preparing to provide the corresponding functionality via `Singular.jl` which can then be used in `Oscar`.

**Comment by wdecker** [comment]
At current state, in the case of a global ordering, all returned remainders are fully reduced.

**Comment by YueRen** [comment]
@wdecker Thanks for the tip!  That is more than enough for me for now (and what I thought was a non-tailreduced polynomial turned out to me a mistake on my end).

**Comment by joschmitt** [comment]
Appears to be resolved. An example from the documentation:
```
julia> R, (x, y, z) = polynomial_ring(QQ, ["x", "y", "z"]);

julia> f1 = x^2+x^2*y; f2 = y^3+x*y*z; f3 = x^3*y^2+z^4;

julia> g = x^3*y+x^5+x^2*y^2*z^2+z^6;

julia> reduce(g, [f1, f2, f3], ordering = lex(R))
x^5 + x^3*y + x^2*y^2*z^2 + z^6

julia> reduce(g, [f1,f2, f3], ordering = lex(R), complete_reduction = true)
x^5 - x^3 + y^6 + z^6
```
