### ISSUE TITLE
Research on multivariate polynomial ring constructors

### ISSUE THREAD

**Issue by mgkurtz** [oscar-system/Oscar.jl#2251]
We still have various implementations for the creation of polynomial rings:

<details><summary>Ordinary</summary>

* `R, x = polynomial_ring(QQ, :x)`
* `R, (x,y,z) = polynomial_ring(QQ, [:x, :y, :z])`
* `R, (x,y,z) = polynomial_ring(QQ, (:x, :y, :z))`

Caveat: If I write `R, (x,y,z,w) = polynomial_ring(QQ, [:w, :x, :y, :z])`, `x` prints `w` instead.
</details>

For rings like $\mathbb Q[x_1, x_2, x_3, x_4]$ and more complex layouts, there are various shortcuts. Also see the lower part of [this comment](https://github.com/Nemocas/AbstractAlgebra.jl/pull/1282#discussion_r1140602283) by @fingolfin.

<details><summary>Indexed variables</summary>

* `R, x = polynomial_ring(QQ, 4, :x)` yielding $\mathbb Q[x1, x2, x3, x4]$ -- Caveat: `x[1]` prints as `x1`. The argument order may be chosen to allow the variable name to be optional? Anyway, the ordering is inconsistent with my intuition and the variants below.
* `R, x, y, z = polynomial_ring(QQ, :x => (1:2, 1:2), :y => 0:2:4, :z => 1)` yielding $\mathbb Q[x_{1,1}, x_{1,2}, x_{2,1}, x_{2,2}, y_0, y_2, y_4, z_1]$. -- Caveat: `y[1]` prints as `y[0]`.

https://github.com/oscar-system/Oscar.jl/blob/6abf75f599c1f81abb17a2325e569cb6fcadee25/src/Rings/mpoly.jl#L17

* `R, x, y, z = AbstractAlgebra.@polynomial_ring QQ x[1:2, 1:2] y[0:2:4] z` for $\mathbb Q[x_{1,1}, x_{1,2}, x_{2,1}, x_{2,2}, y_0, y_2, y_4, z]$. See Nemocas/AbstractAlgebra.jl#140 and Nemocas/AbstractAlgebra.jl#1283. -- Caveat: `y[1]` prints as `y[0]`.
</details>

For internal code, which does not need the variable names, or lazy people there are variants with an implicit `:x`.

<details><summary>Implicit variables</summary>

* `R, x = polynomial_ring(QQ, 4)` identical to `polynomial_ring(QQ, 4, :x)`
* `R = PolyRing(QQ)` yielding $\mathbb Q[x]$ without caching. Implemented in AbstractAlgebra.
* `R, x = polynomial_ring(QQ)` yielding $\mathbb Q[x]$ without caching. Implemented in Hecke/src/Misc/Poly.jl

</details>

As of `methods(polynomial_ring)` there are a few more methods:

<details><summary>More `polynomial_ring` methods</summary>

* There is a specific method for `TropicalSemirings`. This probably exists only to circumvent, what I fixed in Nemocas/AbstractAlgebra.jl#1333:

https://github.com/oscar-system/Oscar.jl/blob/6abf75f599c1f81abb17a2325e569cb6fcadee25/src/AlgebraicGeometry/TropicalGeometry/semiring.jl#L465-L475

* There is a hack which seems like we should set `dense_poly_type` instead:

https://github.com/thofma/Hecke.jl/blob/46b30aaae5ae96a43196f8de45e01f8cc4edacbe/src/AlgAss/Types.jl#L350-L358

* The methods `polynomial_ring(::InvRing)` and `polynomial_ring(::NfNSGen{T, S})` simply accesses some fields. Seems strange to me and likely inconsistent to the one argument method from Hecke.

https://github.com/oscar-system/Oscar.jl/blob/6abf75f599c1f81abb17a2325e569cb6fcadee25/src/InvariantTheory/invariant_rings.jl#L10

https://github.com/oscar-system/Oscar.jl/blob/6abf75f599c1f81abb17a2325e569cb6fcadee25/src/Rings/NumberField.jl#L129
</details>

As @wdecker pointed out to me, `graded_polynomial_ring` only supports the most basic variant of indexed variables.
Notably, every design choice has to deal with providing the weights in addition to the variable names.

<details><summary>Graded polynomial rings</summary>

* `R, (x,y,z) = graded_polynomial_ring(QQ, [:x, :y, :z], W)`
* `R, x = graded_polynomial_ring(QQ, 4, :x, W)`
</details>

For `LaurentPolynomialRing`, `free_associative_algebra` and `free_group` the current situation is similar or worse to the `graded_polynomial_ring` case.

**Comment by mgkurtz** [comment]
<details><summary>First draft of a concept for constructors with indexed variable names</summary>

For the indexed variables, I could imagine various ways to use them:

```julia
R, x, y, z = polynomial_ring(QQ, :x => 1:3, :y => (1:2, 1:2), :z)  # No more arguments may follow. Bad for graded_polynomial_ring etc.
R, x = polynomial_ring(QQ, :x => 1:3)
R, (x, y, z) = polynomial_ring(QQ, (:x => 1:3, :y => (1:2, 1:2), :z))
R, (x, y, z) = polynomial_ring(QQ, (; x=1:3, y=(1:2, 1:2), z))
R, (; x, y, z) = polynomial_ring(QQ, (; x=1:3, y=(1:2, 1:2), z))
R, (; x, y, z) = polynomial_ring(QQ, Dict(:x => 1:3, :y => (1:2, 1:2), :z))
R, (x, y, z) = polynomial_ring(QQ, (:x => 1:3, :y => Iterators.product(1:2, 1:2), :z)) # probably to complicated
```

We could provide support for the non-commented variants like

```julia
const VarNameIndices = Union{AbstractUnitRange{<:Integer}, Tuple{Vararg{AbstractUnitRange{<:Integer}}}}
const VarNamePair = Pair{VarName, VarNameIndices}
const VarNames = Union{VarNamePair, Tuple{Vararg{VarNamePair}}, Vector{VarNamePair}, NamedTuple{<:Any, Tuple{Vararg{VarNameIndices}}}, Dict{VarName, VarNameIndices}}
function polynomial_ring(R::NCRing, v::VarNames)
    Rx, x_vector = polynomial_ring(R, variable_names(v))
    x = reshape_variables(v, x_vector)
    return Rx, x
end
```

and implementations for

```julia
variable_names(v::T) :: Vector{Symbol}
```

for each `T` in the `VarNames` type union. Plus methods

```julia
reshape_variables(v::VarNamePair, x_vector::Vector{S}) :: Array{S} where S<:PolyRingElem
reshape_variables(v::Tuple{Vararg{VarNamePair}}, x_vector::Vector{S}) :: Vector{<:Array{S}} where S<:PolyRingElem
reshape_variables(v::Vector{<:VarNamePair}, x_vector::Vector{S}) :: Vector{<:Array{S}} where S<:PolyRingElem
reshape_variables(v::NamedTuple{T, Tuple{Vararg{VarNameIndices}}}, x_vector::Vector{S}) :: NamedTuple{T, Tuple{Vararg{S}}} where S<:PolyRingElem
reshape_variables(v::Dict{VarName, <:VarNameIndices}, x_vector::Vector{S}) :: Dict{Symbol, <:Array{S}} where S<:PolyRingElem where S<:PolyRingElem
```

</details>
Updated concept following in a post below.

**Comment by mgkurtz** [comment]
Another thing we could do, would be, to have `R = @polynomial_ring QQ x` create the variable `x`, and matching adaptions for the multivariate case. This should be relatively easy to add, if we want it.

**Comment by thofma** [comment]
Is it correct to say that the inconsistencies are due to missing methods?

**Comment by wdecker** [comment]
It also means, that we have a unfied approach to creating polynomial rings and graded polynomial rings when it comes to allowing ways of introducing variable names.

**Comment by mgkurtz** [comment]
> Is it correct to say that the inconsistencies are due to missing methods?

Yes, to some extent. If I can give variable names like `x => 1:3, y => 1:4` for `polynomial_ring` but not for `graded_polynomial_ring`, this is a matter of a method which is not only missing, but (due to the `W` argument) also impossible to give a proper signature for.

**Comment by mgkurtz** [comment]
On the other hand, the constructors are also inconsistent in the sense, that I can hardly find a unifying idea, which would allow to document and explain those constructors cleanly.

To be honest, after sleeping over my sketch above, this also seems overly complicated. So, I will streamline and update it.

**Comment by mgkurtz** [comment]
I would like pretty method signatures

```julia
polynomial_ring(::Ring, ::VarNames)
free_associative_algebra(::Ring, ::VarNames)
LaurentPolynomialRing(::Ring, ::VarNames)
graded_polynomial_ring(::Ring, ::VarNames, W)
affine_space(::Ring, ::VarNames)
projective_space(::Ring, ::VarNames)
free_group(::VarNames)
```

with use cases

```julia
R, (x,y,z) = polynomial_ring(QQ, [:x, :y, :z])
R, x = polynomial_ring(QQ, :x => 3)
R, y = polynomial_ring(QQ, :y => (2,2))
R, (x, y, z) = polynomial_ring(QQ, (x=3, y=(2, 2), z=nothing))
R, (; x, y, z) = polynomial_ring(QQ, Dict(:x => 3, :y => (2, 2), :z => nothing))
```

for creating

$$
\begin{align}
&\mathbb Q[x, y, z] \\
&\mathbb Q[x_1, x_2, x_3] \\
&\mathbb Q[y_{1,1}, y_{1,2}, y_{2,1}, y_{2,2}] \\
&\mathbb Q[x_1,x_2,x_3, y_{1,1}, y_{1,2}, y_{2,1}, y_{2,2}, z] \\
&\mathbb Q[x_1,x_2,x_3, y_{1,1}, y_{1,2}, y_{2,1}, y_{2,2}, z]
\end{align}
$$

<details><summary>`VarNames` type union</summary>

```julia
const Dims = Union{Int, Tuple{Vararg{Int}}}
const VarNames = Union{
    Vector{<:VarName},
    Pair{<:VarName, <:Dims},
    Dict{<:VarName, <:Dims},
    NamedTuple{<:Any, <:Tuple{Vararg{Dims}}},
}
```

</details>

<details><summary>Implementation for `polynomial_ring`</summary>

```julia
function polynomial_ring(R::NCRing, v::VarNames)
    Rx, x_vector = polynomial_ring(R, variable_names(v))
    x = reshape_variables(v, x_vector)
    return Rx, x
end
```

</details>

<details><summary>Functions used in implementation</summary>

```julia
variable_names(v::T) :: Vector{Symbol}
reshape_variables(v::T, x_vector::Vector{S}) :: shape_type(T, S)
shape_type(::T, ::S)
```

for each `T` in the `VarNames` type union. Simple examples of `shape_type`:

```julia
shape_type(::Vector{<:VarName}, S) = Vector{S}
shape_type(::Pair{<:VarName, Int}, S) = Vector{S}
shape_type(::Pair{<:VarName, NTuple{N, Int}}, S) where N = Array{S, N}
```

</details>

<details><summary>Deprecations</summary>

```julia
R, x = polynomial_ring(R, 3, :x)  # Use `:x => 3` instead.
R, (x,y,z) = polynomial_ring(R, (:x, :y, :z))  # I introduced support for `Tuple` lately. Unnecessary, use `Vector` instead.
R, x = polynomial_ring(QQ, :x => -3:3)  # Then we also should return something, which we can index with -3:3. Would result in more complication than I think it worth. Use `:x => 7` instead.
R, x, y, z = polynomial_ring(QQ, :x => 1:3, :y => (1:2, 1:2), :z)  # No more arguments may follow. Bad for graded_polynomial_ring etc. Use a `NamedTuple` instead.
R, (x, y, z) = polynomial_ring(QQ, (:x => 1:3, :y => (1:2, 1:2), :z)) # Okayish, but unnecessary. Use a `NamedTuple` instead.
```

</details>

<details><summary>Aliases</summary>

```julia
polynomial_ring(QQ, 3) == polynomial_ring(QQ, :x => 3)
polynomial_ring(QQ) # Do we want to keep/rename that?
PolyRing(QQ) # Do we want to keep/rename that?
```

</details>

**Comment by fieker** [comment]
On Fri, Apr 14, 2023 at 03:27:52AM -0700, Markus Kurtz wrote:
> I would like pretty method signatures
> 
> ```julia
> polynomial_ring(::Ring, ::VarNames)
> free_associative_algebra(::Ring, ::VarNames)
> LaurentPolynomialRing(::Ring, ::VarNames)
> graded_polynomial_ring(::Ring, ::VarNames, W)
> free_group(::VarNames)
> ```
> 
> with use cases
> 
> ```julia
> R, (x,y,z) = polynomial_ring(R, [:x, :y, :z])
> R, x = polynomial_ring(QQ, :x => 3)
this should give only x[3]
:x => 1:3 will give x[1], x[2], x[3]

or is it part of the suggestion to not specify ranges?
> R, x = polynomial_ring(QQ, :y => (2,2))
> R, (x, y, z) = polynomial_ring(QQ, (x=3, y=(2, 2), z=nothing))
> R, (; x, y, z) = polynomial_ring(QQ, Dict(:x => 3, :y => (2, 2), :z => nothing))
:z => nothing I find particular bad, why not just :z?

**Comment by mgkurtz** [comment]
> this should give only x[3]
> :x => 1:3 will give x[1], x[2], x[3]
> 
> or is it part of the suggestion to not specify ranges?

Indeed, I would not specify ranges. As noted above, `:y => 0:2:4` means that `y[1]` prints as `y[0]`. Hence, I would only specify the size of the generator variable array. E. g. `:y => (2,2)` results in an array with `size(y) = (2,2)`.

> > ```julia
> > R, (x, y, z) = polynomial_ring(QQ, (x=3, y=(2, 2), z=nothing))
> > R, (; x, y, z) = polynomial_ring(QQ, Dict(:x => 3, :y => (2, 2), :z => nothing))
> > ```
> :z => nothing I find particular bad, why not just :z?

Yes, that is bad. My problem is, that if I want to use a `NamedTuple` or `Dict`, every key needs some value. Of course one may give `1` or `()` as a key for a variable named `z[1]` respectively `z[]`. But if the variable shall be named `z`, I need _something_ as a dummy key. I went with `nothing`.

An alternative would be to find some better dummy key or to specify a vector `[:x => 3, :y => (2,2), :z]`.

**Comment by JohnAAbbott** [comment]
Was a conclusion reached here?
It may be helpful to have distinct solutions for interactive use and for use inside programs.
Yesterday I wanted to create a `graded_polynomial_ring` (with standard grading) with variables `x[1,1]` to `x[5,5]` and `y[1,1]` to `y[5,5]`.  In CoCoA this was trivial; in Oscar I gave up, and renamed the variables to `x[1]` to `x[50]`, then had to do a lot of editing.  The CoCoA version of the polynomials was much easier to read & comprehend.

**Comment by thofma** [comment]
What you want is already doable:
```
julia> QQx, x = @polynomial_ring(QQ, x[1:5, 1:5]);

julia> x[1, 1]
x[1,1]

julia> x[3, 5]
x[3,5]
```

**Comment by JohnAAbbott** [comment]
Thanks, but not yet for `graded_polynomial_ring`  ... ah!  Maybe I should update to the latest GitHub code?
Still `@polynomial_ring(QQ, x[1:5, 1:5])` is easier to read than `polynomial_ring(QQ, :x => (1:5,1:5))`

I'm still hoping there will eventually be a macro **for interactive use**; perhaps something like
`@PolyRing  P  QQ  [x,y,z]`   or  `@PolyRing  P  QQ  [x[1:5,1:5]]`  so the user does not have to specify the names twice.

**Comment by fieker** [comment]
On Thu, May 04, 2023 at 05:44:48AM -0700, JohnAAbbott wrote:
> Was a conclusion reached here?
> It may be helpful to have distinct solutions for interactive use and for use inside programs.
> Yesterday I wanted to create a `graded_polynomial_ring` (with standard grading) with variables `x[1,1]` to `x[5,5]` and `y[1,1]` to `y[5,5]`.  In CoCoA this was trivial; in Oscar I gave up, and renamed the variables to `x[1]` to `x[50]`, then had to do a lot of editing.  The CoCoA version of the polynomials was much easier to read & comprehend.
> 

julia> R, g = grade(polynomial_ring(Oscar.QQ, :x => (1:5, 1:5), :y=>(1:5, 1:5))[1])
possibly followed by

x = reshape(g[1:25], 5, 5)
y = reshape(g[26:end], 5, 5)

there might be a transpose that would be handy...

**Comment by mgkurtz** [comment]
I have created a draft PR now. This includes a macro which introduces `x` into the scope, as @JohnAAbbott wished. As I created the PR in `AbstractAlgebra`, the `graded_polynomial_ring` is still not supported, and it is not entirely trivial, as I am unsure, how to provide the optional weights. Anyway, it is currently possible (with unit weights) as

```julia
R, g = grade(AbstractAlgebra.@polynomial_ring Oscar.QQ x[5, 5] y[5, 5])
x, y = AbstractAlgebra.reshape_to_varnames(g, (x = (5, 5), y = (5, 5)))
```

As remarked by @fieker `x = nothing` for an unindexed `x` is bad, so I replaced it by `missing` which is maybe a little bit less bad? I also added the `[:x => 3, :y => (2, 2), :z]` variant, which naturally extends `[:x, :y, :z]` and does not need a `missing` value for `z`.

**Comment by fingolfin** [comment]
We will meet this Friday 2pm (in room 436?) to make a decision on how to resolve this.

**Comment by fingolfin** [comment]
I'd like to move this forward. @mgkurtz perhaps we can meet next week to hash it out? Are you available on Thursday 10 or 11?

Here are my thoughts on this:
- I would *not* support `Dict` in any way, because the entries of `Dict` are not in a fixed order, and that can wreak havoc with what we have. Yes we can hack around it by letting the return value be a named tuple, but why bother?
- specifically I don't think *more* variants are a good thing; they just mean that people have to learn more ways, and also they will wonder *why* those exist... if the only reason is "we couldn't decide which to use, that's bad
- we should retain the variant `:x => 0:5` as people use and want it (I was asked about this during the meeting this week). And frankly I don't see wha we'd gain by dropping support for `:x => [0, -4, 2]` as well (I don't see myself using it, but it could be helpful for code)
- I don't mind having those named tuples also supported if that's possible but I'd put it on a backburner and focus on support for passing vectors of names and on `Pair`:

In that case I propose the following, which I think subsumes all existing cases in a logical manner and extends it in a flexible way: The core is to have
```
R, a1, ..., aN = polynomial_ring(QQ, desc1, ..., descN)
```
So we have N+1 arguments and N+1 return values. Each `desc` can be one of these:
- a `Vector{<:VarName}`: each such argument of length $m$ defines $m$ variables; these are returned together in one `Vector` of length $m$
- a `Matrix{<:VarName}`: almost the same but the return value of course now is a `Matrix` (this one is new!)
- `:SYM => VEC` is basically a shorthand for `["$SYM[$i]" for i in VEC]`
- `:SYM => (VEC1, VEC2)` is basically a shorthand for `["$SYM[$i,$j]" for i in VEC1, j in VEC2]`

This should support almost all existing cases and some more (`Matrix` support), yet is simple and regular enough to be explained in a reasonably compact fashion.

One thing that is missing is `:SYM => NUM` which currently is treated the same as `:SYM => [NUM]` resp. `["$SYM[$NUM]"]` which I find confusing... I would be tempted to say this should become an error. And then one day we can revisit the idea of treating it as a shorthand for `:SYM => 1:NUM` some time in the future.


The example
```julia
R, (; x, y, z) = polynomial_ring(QQ, Dict(:x => 3, :y => (2, 2), :z => nothing))
```
could be written as
```julia
R, x, y, z = polynomial_ring(QQ, :x => 1:3, y => (1:2, 1:2), [:z])
```


One of the motivations for the above is that I was asked during the meeting this week specifically how easy it is to have variables named `x1` instead of `x[1]`; or `y12` instead of `y[1,2]`; and it was stressed that some people really want to start numbering at 0. With the above approach they can easily achieve this via the following, thanks to the `Matrix{VarName}` support:

```julia
R, x, y = polynomial_ring(QQ, ["x$i" for i in 0:2], ["y$i$j" for i in 0:3, j in 0:3])
```

**Comment by wdecker** [comment]
Some remarks:

1) With respect to allowing  selected indices like in `:x => [0, -4, 2]`: Examples arise easily and regularly from applications like in statistics, physics, chemestry, ..., where real world problems are described.

2) We have already constructors for `x1` instead of `x[1]`. So what is better here?

3) With respect to "want to start numbering at 0:" I have asked for this for a long time. It is not just in the mind of some people, no serious projective algebraic geometer will work with OSCAR otherwise. However, the above solution still doesn't look nice. Ever

4) Everything we do must work identically for graded polynomial rings and should be compatible with our set-up for PBW algebras.

I would like to join the discussion but will not be available on Thursday.

**Comment by mgkurtz** [comment]
I appreciate going on here. Meeting on Thursday at 10 or 11 o’clock is fine for me. I will get around at 10.

Just providing one variant seems sane for me as well. (Seems like I have changed my mind there.) The vararg syntax also seems fine for me now.  With `Base.replace` there is also precedence for vararg `Pair` arguments. For me, the `desc` arguments could be

- `a::AbstractArray{<:VarName}`: This subsumes `Vector` and `Matrix`.
- `(:x => iter)::Pair{<:VarName}`: I prefer "$x$i" and "$x$i_$j" since it will not lie about "x[0]" being x[1].

A problem with the vararg approach is that the methods for `graded_polynomial_ring` with their trailing optional weights argument would have to change.
Perhaps use a keyword argument there?


Am Freitag, 29.09.2023 um 05:22 schrieb Max Horn ***@***.***>:

**Comment by fingolfin** [comment]
@wdecker wrote:

> Some remarks:
> 
> 1. With respect to allowing  selected indices like in `:x => [0, -4, 2]`: Examples arise easily and regularly from applications like in statistics, physics, chemestry, ..., where real world problems are described.

Excellent. So that validates my plan to keep the existing support for this around :-).

> 2. We have already constructors for `x1` instead of `x[1]`. So what is better here?

What are you referring to exactly? Could you clarify what you mean by providing a code snippet?

> 3. With respect to "want to start numbering at 0:" I have asked for this for a long time. It is not just in the mind of some people, no serious projective algebraic geometer will work with OSCAR otherwise. However, the above solution still doesn't look nice. Ever

It seems your sentence was cut off, so I am not sure what you wanted to convey here either.

Again, it might be best to talk about this in terms of "hypothetical" code snippets that show what you *wish* the system would do.

> 4. Everything we do must work identically for graded polynomial rings and should be compatible with our set-up for PBW algebras.

The plan is and always was to align all of these and many more places.

> 
> I would like to join the discussion but will not be available on Thursday.

From my POV Wednesday or Friday might also work, if any of those are better.

That said, I think it would really help us move along if we had *concrete* and *written* examples of things you'd like to do that you can't do or at least can't *easily* do right now, I think that will help us more than any more oral discussions...

**Comment by fingolfin** [comment]
@mgkurtz wrote:

> I appreciate going on here. Meeting on Thursday at 10 or 11 o’clock is fine for me. I will get around at 10.

Good.

> I prefer "$x$i" and "$x$i_$j" since it will not lie about "x[0]" being x[1].

I am completely neutral on this at this point, but I also think it is almost completely orthogonal to what we are talking about here -- changing this bit (how the variables are named in these cases) will be *trivial* compared to everything else.

> A problem with the vararg approach is that the methods for `graded_polynomial_ring` with their trailing optional weights argument would have to change. Perhaps use a keyword argument there?

I see multiple options, and it also depends a bit on how people will *really* use these rings. (To me, it still seems as if in many cases a better solution than manually creating a graded polynomial ring with many complicated weights will be to create multiple smaller coordinate rings (or rather: varieties, which take care of their coordinate rings) and then add functions that make it easy to form "products" of varieties and corresponding "products" of coordinate rings.)

Using a keyword argument would be one very natural way to go about this for sure. The weights can then be a single vector, if the varnames are in a single vector; or it could be a tuple of "weight descriptors", one for each "variable descriptor" as described above (i.e. `AbstractVector` or `Pair` instances). I guess if the var description is a vector or matrix, then the corresponding weight descriptor should be a vector or matrix of corresponding dimensions. But of course one could also allow shorthands. E.g. perhaps a single integer like `2` could mean "assign to all variables in this vector the weight "2"). Then one could write:

```
graded_polynomial_ring(QQ, [:x,:y], [:z => 0:4],
                weights = ([1,2], 3))
```
to get 7 variables, the first two with weights 1 and 2, the remaining 5 with weight 3.

**Comment by fingolfin** [comment]
@fieker just taught me about the use of `#` in variable names to control the names:
```
julia> polynomial_ring(QQ, "x#" => 1:10)
(Multivariate polynomial ring in 10 variables over QQ, QQMPolyRingElem[x1, x2, x3, x4, x5, x6, x7, x8, x9, x10])
```
versus
```
julia> polynomial_ring(QQ, "x" => 1:10)
(Multivariate polynomial ring in 10 variables over QQ, QQMPolyRingElem[x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10]])
```

**Comment by JohnAAbbott** [comment]
One awkward point remaining is the use of 0 as an index for inputs (_e.g._ in interactive use).  It would be handy to be able to write something like `x[1]*x[2]+x[0]^2`  or maybe  `x1*x2+x0^2` when doing computations in projective geometry.  I suspect that the proposals above would require adding 1 to all indexes (or else using `x[n+1]` in place of `x[0]`, which would be awkward/unnatural).  I think this is what @wdecker was referring to.
Do we have a reasonable proposal for permitting the user to do this when typing inputs?

**Comment by fingolfin** [comment]
A possible way to get that would be via the macros we also plan to have, i.e.:
```
julia> R = @polynomial_ring(QQ, "x#" => 0:10);

julia> x0
x0

julia> x10
x10
```
Of course that does not allow for a vector `x` with `x[0]`. But for interactive usage, `x0` is more convenient anyway. And for serious code, I've yet to see a convincing argument that the numbering (or even names) of the variables matter (I am happy to be shown one, but ideally in writing)

**Comment by mgkurtz** [comment]
> A possible way to get that would be via the macros we also plan to have, i.e.:
> 
> ```
> julia> R = @polynomial_ring(QQ, "x#" => 0:10);
> 
> julia> x0
> x0
> 
> julia> x10
> x10
> ```

Sadly not with macros.

<details><summary>Here is why</summary>
<p>
As long as the `0:10` above consists of literals this can be made to work, but I cannot generate code introducing `n` variables with `n` possibly changing. As an example think of a function

```julia
function f(n::Int)
    R = @polynomial_ring(QQ,` "x#" => 0:n)
    return R, x0
end
```

To introduce the variables `x0` to `xn` the macro would need to generate code writing down all the to be introduced variables explicitly as part of the code like
```julia
x0 = gen(R, 1)
x1 = gen(R, 2)
...
x10 = gen(R, 9)
```
but as the macro is expanded only once but used with different values of `n` this hardly works. (It kind of works if we give an upper bound for `n` like `n≤99` and add a bunch of preliminary `return`s.)

Even in interactive use, I guess people will often enough use variables `x[0:n]` with some variable `n`. So our macros should support that and can thus not support introducing all the variables in the current scope.
</p>
</details>

Still, as long as we are interested in interactive usage only, we can use `eval` to introduce the variable names in the `Main` module. Imagining some `introduce_variables` function this even works after the fact with the constructors we already have:

```julia
julia> R, = polynomial_ring(QQ, [:x, :y, :z]);

julia> introduce_variables(R)

julia> x
x
```

Using a macro `@introduce_variables` we could introduce the variables in the current module instead of guessing it to be `Main`. We could also allow writing it as
```julia
@introduce_variables R, = polynomial_ring(QQ, [:x, :y, :z])
@introduce_variables polynomial_ring(QQ, [:x, :y, :z])
```

An alternative would be any of the following syntactic sugars:
```julia
R(:x) + R(:y)
R(:(x + y))
@R x + y
@interpret R x + y
```

**Comment by fingolfin** [comment]
We just had a meeting about this (with @mgkurtz, @HechtiDerLachs, @wdecker, @jankoboehm and myself) and agreed on the above with a few tweaks and extensions. I'll not write the details down now as I hope @mgkurtz will soon be able to update his PR and we can then discuss fine points there if necessary (but I actually think we are mostly good on this front...)
