### ISSUE TITLE
Documentation updates are not deployed anymore

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2274]
It seems the "pages build and deployment" GH Action stopped working ~2 weeks ago, (see https://github.com/oscar-system/Oscar.jl/actions/workflows/pages/pages-build-deployment?page=4).

Consequently https://docs.oscar-system.org/dev/ is outdated.

The error message looks like this:

> github-pages 228 | Error:  No such file or directory @ rb_check_realpath_internal - /github/workspace/dev/Experimental/LieAlgebras

So it doesn't like something about the LieAlgebras stuff (CC @lgoettgens) -- perhaps that it doesn't contain any docs?

**Comment by fingolfin** [comment]
Seems @benlorenz found and fixed the problem, great :-)

**Comment by fingolfin** [comment]
Another problem is that the `gh-pages` branch is missing the 0.12.0 docs :-(

**Comment by benlorenz** [comment]
Projective Schemes docs are now successfully deployed: https://docs.oscar-system.org/dev/AlgebraicGeometry/Schemes/ProjectiveSchemes/

I don't think this will reappear as future runs on any PRs should run with on a fresh merge commit which already contains https://github.com/oscar-system/Oscar.jl/pull/2215.

**Comment by benlorenz** [comment]
> Another problem is that the `gh-pages` branch is missing the 0.12.0 docs :-(

Are you sure that this is correct:
https://github.com/oscar-system/Oscar.jl/commit/73bfbd84771e8a32677c40cf5ea45d185ff31acc

The [Documenter.jl docs](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions) (a little bit further down than my link, `TagBot & tagged versions`) state that the SSH key is needed to get docs for versions tagged by TagBot.

**Comment by lgoettgens** [comment]
> Another problem is that the `gh-pages` branch is missing the 0.12.0 docs :-(

I think they can be created once deployment works again by re-running https://github.com/oscar-system/Oscar.jl/actions/runs/4697421601/jobs/8328474631
Since the corresponding commit has been tagged in the meantime, Documenter should pick that up as well.

**Comment by lgoettgens** [comment]
> > Another problem is that the `gh-pages` branch is missing the 0.12.0 docs :-(
> 
> Are you sure that this is correct: [73bfbd8](https://github.com/oscar-system/Oscar.jl/commit/73bfbd84771e8a32677c40cf5ea45d185ff31acc)
> 
> The [Documenter.jl docs](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions) (a little bit further down than my link, `TagBot & tagged versions`) state that the SSH key is needed to get docs for versions tagged by TagBot.

This might indeed be the problem, why there was no documentation run on the v0.12.0 tag.

**Comment by lgoettgens** [comment]
> Another problem is that the `gh-pages` branch is missing the 0.12.0 docs :-(

I think the following workaround could fix this:
1. Make the documentation action run on `workflow_dispatch` (and merge into master).
2. Run the action by hand on the v0.12.0 tag.
3. If so wished, revert 1.

For a long-term solution, I think reverting 73bfbd8 is the way to go. 

Edit: Another, possibly easier way is copying the `dev` folder of https://github.com/oscar-system/Oscar.jl/tree/5e8352c8d2f13a7827302e53a2e4eda16bcb6671 into a new folder `v0.12.0`, adding a `v0.12` symlink onto it, and updating `versions.js` and the `stable` symlink accordingly.

**Comment by lgoettgens** [comment]
I think this is fixed by #2277 and #2278.

**Comment by benlorenz** [comment]
I think this can be closed now, we do have docs for 0.12 and the deploy job is running successfully.

Just one minor remark: We cannot run the docs build manually for 0.12.0 (via the newly added `workflow_dispatch`) as it needs to be there on that branch for this to work. But the manual approach seems to be fine for now: https://docs.oscar-system.org/stable/
And in the future we should be able to trigger the docs manually.

Thanks @lgoettgens !
