### ISSUE TITLE
ExteriorAlgebra failing on nightly

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2283]
It seems there is a new test failure on Julia nightly, in the ExteriorAlgebra tests, looking like this; I have not yet checked what's going there. 

Note that there was a Singular.jl updated today which also updated Singular itself, perhaps that is related?

CC @JohnAAbbott @hannes14 

```
ExteriorAlgebra: Error During Test at /Users/runner/work/Oscar.jl/Oscar.jl/test/Experimental/ExteriorAlgebra-test.jl:7
  Expression evaluated to non-Boolean
  Expression: exterior_algebra(QQ, 1)
       Value: ((PBW-algebra over Rational Field in e1 with relations )/two_sided_ideal(e1^2), PBWAlgQuoElem{QQFieldElem, Singular.n_Q}[e1])
Test Summary:   | Pass  Error  Broken  Total  Time
ExteriorAlgebra |   14      1       3     18  5.2s
ERROR: LoadError: Some tests did not pass: 14 passed, 0 failed, 1 errored, 3 broken.
in expression starting at /Users/runner/work/Oscar.jl/Oscar.jl/test/Experimental/ExteriorAlgebra-test.jl:1
in expression starting at /Users/runner/work/Oscar.jl/Oscar.jl/test/runtests.jl:113
ERROR: LoadError: Package Oscar errored during testing
```

**Comment by hannes14** [comment]
Singular recognised exterior_algebra(QQ, 1) as commutaive before, now reports "exterior_algebra".
See https://github.com/Singular/Singular/commit/f8b04d16808098323914dd4522d4be681409c179

**Comment by JohnAAbbott** [comment]
OK.  I think I have fixed everything now.  Just pushed.
Thanks to @hannes14 for updating Singular!

**Comment by fingolfin** [comment]
This is now resolved
