### ISSUE TITLE
Maintain order of rays/variables after toric blow_up

### ISSUE THREAD

**Issue by apturner** [oscar-system/Oscar.jl#2286]
Currently, the toric `blow_up` function sometimes changes the order of the rays/variables in the output relative to the input toric variety. This may result in user error when performing a sequence of blowups. It would be good to maintain the order of the original variables and then append the blowup variable to the end of the list.

@HereAround

**Comment by lkastner** [comment]
Probably it is ok to use `non_redundant` here, i.e. in `star_subdivision`?
```
PolyhedralFan(x...; non_redundant::Bool = false)
```
For this we just need to be sure that the cones computed are actually maximal. I had a look at the code and it seems fine, but maybe I am overlooking something @HereAround ?

**Comment by HereAround** [comment]
Yes, that sounds good.
