### ISSUE TITLE
Change order of inclusion of experimental code

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2300]
<s>Since the recent changes to the experimental directory, experimental code cannot call other experimental code anymore. An example is here: #2299.

Since the documentation explicitly mentions this (in a warning), I guess this should still work? @lkastner Any idea 
how can one do this now?
</s>

Is it possible to change the order of inclusion of the experimental code? I have to use functionality from JuLie, but J comes too late in the alphabet. @lkastner

**Comment by lkastner** [comment]
It works for the old stuff, I guess for the new stuff the issue stems from the loops we use to load these things. They are probably loaded in the wrong order if something fails. There are ways to solve this, but do we want to?

**Comment by lgoettgens** [comment]
I think this is (and has always been) dependent on the order of inclusion. For your example, `GModule.jl` comes in https://github.com/oscar-system/Oscar.jl/blob/3afd78da98555415a9bbd20ee4835ee2059621de/experimental/Experimental.jl before `JuLie.jl`.

**Comment by thofma** [comment]
Ah right. I guess I cannot change the order of inclusion anymore?

**Comment by thofma** [comment]
I updated the title and the question.

**Comment by lgoettgens** [comment]
> Ah right. I guess I cannot change the order of inclusion anymore?

As long as your both are included individually (i.e. follow the old structure), you can still do that. For new ones, they are included in alphabetical order. So renaming your subfolder in `experimental` would be a workaround.

**Comment by lkastner** [comment]
Try the following small change in `src/Oscar.jl`
```diff --git a/src/Oscar.jl b/src/Oscar.jl
index 4f1b78da44..7d7777c551 100644
--- a/src/Oscar.jl
+++ b/src/Oscar.jl
@@ -46,7 +46,12 @@ const oldexppkgs = [
   "Schemes",
   "SymmetricIntersections",
 ]
-const exppkgs = filter(x->isdir(joinpath(expdir, x)) && !(x in oldexppkgs), readdir(expdir))
+const orderedpkgs = [
+  "JuLie",
+  "TommysPkg",
+                ]
+exppkgs = filter(x->isdir(joinpath(expdir, x)) && !(x in oldexppkgs) && !(x in orderedpkgs), readdir(expdir))
+append!(exppkgs, orderedpkgs)

```
For copy-paste:
```
const orderedpkgs = [                                       
  "JuLie",                                                  
  "TommysPkg",                                              
                ]                                           
exppkgs = filter(x->isdir(joinpath(expdir, x)) && !(x in oldexppkgs) && !(x in orderedpkgs), readdir(expdir))       
append!(exppkgs, orderedpkgs) 
```
I don't think we should add this to the developer docs, but we could add a comment in the Oscar.jl that this is the way to go in those situations. What do you think?

**Comment by lkastner** [comment]
Sorry, I forgot to adjust the filter in the first version, I edited it to reflect that.

**Comment by fingolfin** [comment]
Since JuLie still uses the "old style" an even simpler workaround is this:
```patch
diff --git a/experimental/Experimental.jl b/experimental/Experimental.jl
index 1eb22ef61..75e96442a 100644
--- a/experimental/Experimental.jl
+++ b/experimental/Experimental.jl
@@ -1,3 +1,5 @@
+include("JuLie.jl")
+
 for pkg in Oscar.exppkgs
   include("$pkg/src/$pkg.jl")
 end
@@ -10,8 +12,6 @@ include("GModule.jl")
 include("MPolyRingSparse.jl")
 include("SymmetricIntersections.jl")
 
-include("JuLie.jl")
-
 include("Schemes/Types.jl")
 include("Schemes/SpecialTypes.jl")
 include("Schemes/CoveredScheme.jl")
```

**Comment by lgoettgens** [comment]
This has been resolved by https://github.com/oscar-system/Oscar.jl/pull/2363.
