### ISSUE TITLE
Converting `Int64` to `MPolyRingElem`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#2331]
**Is your feature request related to a problem? Please describe.**
I think there are missing conversions from `Int64` to element types of multivariate polynomial rings, which causes for example:
```
R,(x,y) = PolynomialRing(QQ,["x","y"])
evaluate(x+y,[x,R(0)]) # does work
evaluate(x+y,elem_type(R)[x,0]) # does not work
evaluate(x+y,[x,0]) # does not work
```

**Describe the solution you'd like**
It would be nice if the user could simply write the following without the need to manually cast `0` into the polynomial ring:
```
evaluate(x+y,[x,0])
```

I believe this is not only restricted to `evaluate` but any function that expects a vector of multivariate polynomials as part of its input but is then served the following type:
```
julia> [x,0]
2-element Vector{Any}:
  x
 0
```

**Comment by thofma** [comment]
It is technically not possible to implement this conversion (conversions are between different types, but to convert to `MPolyRingElem`, one needs an instance).

It has to be done for each method individually. But I would argue that we need it only for the functions where there is a chance a user might call them directly with input constructed themselves.

**Comment by YueRen** [comment]
I see, that's unfortunate.  With "has to be done for each method specifically", do you mean changing `evaluate`? Like:
```
import Oscar.evaluate
function evaluate(a::MPolyElem, A::Vector)
    return evaluate(a,parent(a).(A))
end

R,(x,y) = PolynomialRing(QQ,["x","y"])
evaluate(x+y,[x,0]) # does work
```

**Comment by thofma** [comment]
Yep, this is what I had in mind.
