### ISSUE TITLE
Make a new release, soon

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#234]
As @thofma suggested, we should have a new Oscar.jl release soon. Perhaps let's go over PRs and issues one more time? Also perhaps we first want/need a newer Singular.jl? (or perhaps that's independent from each other?)

**Comment by thofma** [comment]
We have a new Singular. Can we make a new release? Or should we sort out #262 first?

**Comment by thofma** [comment]
Would be good if we could get this done for the meeting next week.
