### ISSUE TITLE
Better feedback when users try to use our packages under Windows

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#235]
Several of course packages do not work under Windows (resp. only when run in WSL). We should detect when a user attempts to load it under Windows anyway, and print an error in a suitable place (during precompilation and/or in `__init__`). Something like this:
> This package unfortunately does not run natively under Windows. Please install Julia using Windows subsystem for Linux and try again.

This should be done for the following packages (ideally using more or less the same code):
- [x] Oscar.jl
- [x] GAP.jl
- [x] Singular.jl
- [ ] Polymake.jl

**Comment by thofma** [comment]
What about duing it during `]add ..` by customizing `build.jl`?

**Comment by fingolfin** [comment]
I am somewhat worried that build is only executed once and then not again, even if it failed; so users can quite easily miss it. Hence I would suggest to also print such a message during loading
