### ISSUE TITLE
Excessive memory consumption in euler_phi_inv

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#2367]
**Describe the bug**
`euler_phi_inv` sometimes requires a surprisingly large amount of memory.  And repeating a call can cause memory exhaustion (why?)

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
n = 958003200;
@time L = euler_phi_inv(n);  # about 37s
length(L)                    # 79971  Vector{ZZRingElem}  but all entries are small
@time L = euler_phi_inv(n);  # Killed ?!?
```

**Expected behavior**
Use less memory, and not cause exhaustion the second time around.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.12.1-DEV - #master, c10725df -- 2023-05-09 11:48:14 +0200
  combining:
    AbstractAlgebra.jl   v0.29.4
    GAP.jl               v0.9.4
    Hecke.jl             v0.18.9
    Nemo.jl              v0.33.7
    Polymake.jl          v0.9.0
    Singular.jl          v0.18.2
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.5+0
    GAP_jll                 v400.1200.200+1
    Singular_jll            v403.201.1+0
    libpolymake_julia_jll   v0.9.0+1
    libsingular_julia_jll   v0.30.0+1
    polymake_jll            v400.900.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 20 virtual cores
Environment:
  JULIA_LOAD_PATH = @:@v#.#:@stdlib:/environments/globalenv
  JULIA_DEPOT_PATH = /home/zez25zuh/.julia:
Official https://julialang.org/ release

```

**Additional context**
Hans tried it on a "big" machine, and julia used up to 70Gbytes RAM during the 2nd call; first call required much less (according to `top`)
This is neither important nor urgent for me.  Not even sure why I tried computing `euler_phi_inv` in the first place.

**Comment by fieker** [comment]
I can offer

julia> @time n = euler_phi_inv(958003200);
  1.046849 seconds (11.44 k allocations: 40.440 MiB)

julia> length(n)
  79971

**Comment by JohnAAbbott** [comment]
That's definitely better!  What did you do?

**Comment by fieker** [comment]
On Thu, May 11, 2023 at 02:39:27AM -0700, JohnAAbbott wrote:
> That's definitely better!  What did you do?
Less intelligent tools...(directly working with Int)

**Comment by JohnAAbbott** [comment]
Satisfactorily resolved.
