### ISSUE TITLE
OscarCI-doctest failures in upstream projects

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2413]
The `matching: [Oscar#master]` CI job fails on some doctests, e.g. https://github.com/oscar-system/Singular.jl/actions/runs/5078789737/jobs/9123769090?pr=652.

The failure seems to be due to some changes in https://github.com/oscar-system/Oscar.jl/pull/2345, in particular `set_current_module(@__MODULE__)` not being available in `OscarCI`.

After a Oscar release, this could probably be fixed by adding the above to https://github.com/oscar-system/OscarDevTools.jl/blob/master/src/OscarCI.jl#L340

@benlorenz proposed on slack:
> maybe it would make sense to add a `Oscar.doctestsetup()`  function which returns that expression? And in the oscar ci we try to use that or fall back to `using Module`, that way also other modules could add code to the `doctestsetup`

cc @benlorenz @thofma @fingolfin

**Comment by benlorenz** [comment]
fixed with #2423 and the [latest OscarDevTools.jl](https://github.com/oscar-system/OscarDevTools.jl/releases/tag/v0.2.12)
