### ISSUE TITLE
Implement `splitting_field` for finite fields

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2418]
For teaching it would be nice to have `splitting_field` support finite fields. Right now it seem it is only implemented for number fields (in Hecke)?

**Comment by fieker** [comment]
On Fri, May 26, 2023 at 01:27:43AM -0700, Max Horn wrote:
> For teaching it would be nice to have `splitting_field` support finite fields. Right now it seem it is only implemented for number fields (in Hecke)?
> 
Yep - but should be trivial to add...

**Comment by fieker** [comment]
Fixed in Hecke#1096
