### ISSUE TITLE
Do not run all the doctests in `build_doc`

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2422]
At the moment , `Oscar.build_doc` calls `makedocs(...)` with all our upstream packages. I think this is necessary, so that all docstrings are picked up properly. But this has the big disadvantage, that doctests for all upstream packages are run. This is quite a waste of time and also leads to errors, if run with `:fix` and something unrelated is broken in a dependency. And it is also not what we do test with CI. I propose to replace 
https://github.com/oscar-system/Oscar.jl/blob/b350dd12616a6771fd2d6c9ef089065d7c5c93f2/docs/make_work.jl#L184
by a separate manual `Documenter.doctest(Oscar; doctest = doctest)` call.

Any objections @fingolfin @benlorenz? Or something that I am missing?

**Comment by fingolfin** [comment]
Makes sense to me

**Comment by lgoettgens** [comment]
This has been fixed by https://github.com/oscar-system/Oscar.jl/pull/2423.

**Comment by fingolfin** [comment]
We now have `doctest_fix`. I am not sure if there is anything left to be done, @thofma ?

**Comment by thofma** [comment]
It was already fixed in #2423.
