### ISSUE TITLE
is_prime buggy for multivariate polynomial rings

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#2427]
By definition the (1) ideal is never prime. 
Yet:
```
julia> R,x = polynomial_ring(QQ,2);

julia> I = ideal(R,[1])
ideal(1)

julia> is_prime(I)
true
```
The reason is that 
```
julia> minimal_primes(I)
1-element Vector{MPolyIdeal{QQMPolyRingElem}}:
 ideal(1)
```
Refuses to return an empty list but instead returns a non-prime ideal. 
(Matching its documentation, so it is not a bug.)
In any case I would suggest to rather return only prime ideals,
even if it means that you cannot do 
`intersect(minimal_primes(I))`  (if the return value is the empty array). One can still do something like
`intersect(minimal_primes(I), init=R)` instead. 
We have the same situation when we sum the elements of an array.
@wdecker

**Comment by fingolfin** [comment]
We discussed this today and agreed that `minimal_primes` should return an empty vector in this case. Moreover, there are other functions that may suffer from similar problems, so we should check those as well. E.g. this is also questionable:
```julia-repl
julia> primary_decomposition(I)
1-element Vector{Tuple{MPolyIdeal{QQMPolyRingElem}, MPolyIdeal{QQMPolyRingElem}}}:
 (ideal(1), ideal(1))
```

There are further considerations (e.g. maybe `primary_decomposition` should return a special type; or should always include a "unit factor" etc.) but that goes beyond the point here.

**Comment by fingolfin** [comment]
@wdecker agreed to work on this. Meaning: just changing `minimal_primes` as discussed, verifying `is_prime` now works, perhaps adding a test. And depending on his time also look for other problematic commands that need similar fixes.

**Comment by wdecker** [comment]
Solved with PR https://github.com/oscar-system/Oscar.jl/pull/2473

**Comment by simonbrandhorst** [comment]
Thank you!
