### ISSUE TITLE
Oscar error after Singular_jll update?

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2438]
I get
```
Test Summary:                    | Pass  Total  Time
ProjCurveDivisor basic functions |    8      8  1.0s
/opt/hostedtoolcache/julia/1.8.5/x64/bin/julia: symbol lookup error: /home/runner/.julia/artifacts/029796c265bc6c7af5c20e51886bb69f7056f6a8/lib/libsingular_julia.so: undefined symbol: _Z9idMinBaseP10sip_sideal
ERROR: Package Oscar errored during testing (exit code: 127)
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /opt/hostedtoolcache/julia/1.8.5/x64/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
```
Since I did not see this yesterday but only today a few minutes ago, I suspect 
https://github.com/JuliaPackaging/Yggdrasil/pull/6830
CC: @hannes14 @fingolfin any idea?

**Comment by thofma** [comment]
OK, @fingolfin is aware and we are working on a fix.

**Comment by benlorenz** [comment]
I think this change
https://github.com/Singular/Singular/commit/c5f2e8eb06dd7f1cd9127b8a29888ef758601235#diff-2746d0607f8e1e10b950b66a643cf823d0ee10f6c03c72d23f914e9a82105eac
did not change the API, but it did change the ABI as the single argument call
```
idMinBase(sip_sideal*)
```
does not exist as a separate symbol now (the compiler will fill in the default NULL argument during compilation).

- So either we need to rebuild the old `libsingular_julia` 0.30 series with the new Singular_jll.
- Or we need to rebuild `libsingular_julia` 0.32, and then push through https://github.com/oscar-system/Singular.jl/pull/654 and make a new Singular.jl release to unbreak Oscar.
- Or build a new Singular_jll which contains both variants of that function, where the one-argument version may call the other one (with NULL as second argument) but inside the cc file.

**Comment by fingolfin** [comment]
see https://github.com/JuliaRegistries/General/pull/84667

**Comment by fingolfin** [comment]
This should be resolved now
