### ISSUE TITLE
Allow `AbstractUnitRange` where ever we allow `UnitRange`

### ISSUE THREAD

**Issue by mgkurtz** [oscar-system/Oscar.jl#2447]
In Nemocas/AbstractAlgebra.jl#1377 we replaced some `UnitRange`s in signatures by `AbstractUnitRange`. We could do this almost everywhere. Thus allowing e.g. `view(a, axes(b)...)` (which currently creates a stackoverflow).

As far, as I see, we would need to replace `UnitRange` in AbstractAlgebra, Nemo, Hecke, Oscar where ever it appears after `<:` or `::` and in some other places. Additionally, we would need to replace `\<([a-z]|do_it)\.(start|stop|step)` by the appropriate calls to `first`, `last`, and `step` everywhere, but in Hecke/src/Misc/Integer.jl.

**Comment by fieker** [comment]
On Fri, Jun 02, 2023 at 12:11:47PM -0700, Markus Kurtz wrote:
> In Nemocas/AbstractAlgebra.jl#1377 we replaced some `UnitRange`s in signatures by `AbstractUnitRange`. We could do this almost everywhere. Thus allowing e.g. `view(a, axes(b)...)` (which currently creates a stackoverflow).
> 
> As far, as I see, we would need to replace `UnitRange` in AbstractAlgebra, Nemo, Hecke, Oscar where ever it appears after `<:` or `::` and in some other places. Additionally, we would need to replace `\<([a-z]|do_it)\.(start|stop|step)` by the appropriate calls to `first`, `last`, and `step` everywhere, but in Hecke/src/Misc/Integer.jl.
> 
Bearing also in mind that the col-range for flint matrices needs to be
complete, no holes, so 
  axes might work
  1:2:5 cannot
for rows this is possible, but not for cols, so be careful..

**Comment by fingolfin** [comment]
PR welcome :-)

**Comment by mgkurtz** [comment]
Created PRs for AbstractAlgebra, Nemo, Hecke, and Oscar. As the PRs only allow more things without needing them, they should be mergable independently of each other. With those PRs applied, the word `UnitRange` appears in the code only, where we explicitly construct `UnitRange`s, as part of struct definitions, and in some explanations. All accesses to the `start` and `stop` fields of `UnitRange`s now use the functions `first` and `last`, thus working for `AbstractUnitRange`s as well.
