### ISSUE TITLE
`stabilizer` does not do what it says

### ISSUE THREAD

**Issue by StevellM** [oscar-system/Oscar.jl#2457]
**Describe the bug**
```
julia> fSB in OSB
true

julia> Oscar._on_modular_matrix_quad(M, fSB) == M
true

julia> stabilizer(OSB, M, Oscar._on_modular_matrix_quad)[1]
Group of isometries of Finite quadratic module: (Z/2)^4 -> Q/2Z generated by 3 elements

julia> fSB in ans
false
```
Even though `fSB` fixes `M` for my costum action `_on_modular_matrix_quad`, when computing the stabilizer of `M` under this action, `fSB` does not lie in the stabilizer. 

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
Bcov = matrix(FlintQQ, 4, 4 ,[1//2, 0, 0, 1//2, 0, 1//2, 1//2, 0, 0, 0, 1, 0, 0, 0, 0, 1]);
G = matrix(FlintQQ, 4, 4 ,[-2, 0, 0, 0, 0, -2, 0, 0, 0, 0, -2, 0, 0, 0, 0, -2]);
cov = integer_lattice(Bcov, gram = G);
Brels = matrix(FlintQQ, 4, 4 ,[2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, -1, 0, 0, 1]);
rel = lattice_in_same_ambient_space(cov, Brels);
SB = torsion_quadratic_module(cov, rel, modulus = QQ(1), modulus_qf = QQ(2));
OSB = orthogonal_group(SB);
fSB = OSB(matrix(ZZ,4,4,[0 1 0 0; 1 0 0 0; 0 0 0 1; 0 0 1 0]));
M = matrix(QQ, 4, 4, [3//2 0 0 1//2; 0 3//2 1//2 0; 0 1//2 1 0; 1//2 0 0 1])

function _on_modular_matrix_quad(M::QQMatrix, g::AutomorphismGroupElem)
  q = domain(parent(g))
  R1 = Hecke.QmodnZ(QQ(1))
  R2 = Hecke.QmodnZ(QQ(2))
  m = matrix(g)
  m1 = m*M*transpose(m)
  for i in 1:nrows(m1)
    for j in 1:ncols(m1)
      if i == j 
        m1[i,j] = lift(R2(m1[i,j]))
      else 
        m1[i,j] = lift(R1(m1[i,j]))
      end  
    end  
  end  
  return m1
end

_on_modular_matrix_quad(M, fSB) == M
fSB in stabilizer(OSB, M, _on_modular_matrix_quad)[1]
```

**Expected behavior**
As mentioned in the docstring of `stabilizer`, I would expect `fSB` to lie in the stabilizer.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.12.2-DEV
  combining:
    AbstractAlgebra.jl   v0.30.7
    GAP.jl               v0.9.6
    Hecke.jl             v0.18.14
    Nemo.jl              v0.34.4
    Polymake.jl          v0.9.2
    Singular.jl          v0.18.3
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.6+0
    GAP_jll                 v400.1200.200+1
    Singular_jll            v403.201.1+0
    libpolymake_julia_jll   v0.9.2+0
    libsingular_julia_jll   v0.30.0+1
    polymake_jll            v400.900.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Official https://julialang.org/ release
...
```

**Additional context**

**Comment by fingolfin** [comment]
The function `_on_modular_matrix_quad` must a right action. That is, `_on_modular_matrix_quad(X, a*b) == _on_modular_matrix_quad(_on_modular_matrix_quad(X, a), b)` must hold.

But I find this:
```
julia> a = rand(OSB); b = rand(OSB); _on_modular_matrix_quad(M, a*b) ==  _on_modular_matrix_quad(_on_modular_matrix_quad(M,a),b)
false
```
Indeed, the core of your action is `f(M,g) = g*M*transpose(g)` and therefore  `f(M,a*b) == a*b*M*transpose(a*b)`, but `f(f(M,a),b) == b*a*M*transpose(a)*transpose(b) == b*a*M*transpose(b*a)`

Move the transpose to the other side and it might work?

**Comment by StevellM** [comment]
Ah I see now what you meant for the right action stuff. Unfortunately I cannot move the transpose, but if I invert `g`, would that work maybe ? Looks like I have to work my group action courses again...

Now I am wondering: is it too much (i.e. too expensive), or even doable, to ask that the function checks whether the action is well-defined ?

**Comment by StevellM** [comment]
Ok yes that definitely works! I will write down somewhere to always check that my actions are always well-defined right actions whenever I need to use `stabilizer`. Sorry for the "fake issue". Everything's good on my part, issue can be closed.
