### ISSUE TITLE
Add display options from `AbstractAlgebra.YoungTableau` to `Tableau`

### ISSUE THREAD

**Issue by lvaness** [oscar-system/Oscar.jl#2462]
**Is your feature request related to a problem? Please describe.**
When displaying a `Tableau`, it gets printed as an array of vectors. Especially for classroom notebooks, it would be nice to have an option to have the proper filled young diagram drawn.

**Describe the solution you'd like**
`AbstractAlgebra.YoungTableau` already prints tableaux like such:
```
┌───┬───┬───┐
│ 1 │ 2 │ 3 │
├───┼───┼───┘
│ 4 │ 5 │
├───┼───┘
│ 6 │
└───┘
```
which would be ideal.

**Describe alternatives you've considered**
`Tableau.t` returns the tableau as vector of vectors, which is pretty close but doesn't align properly with large enough numbers.
Using `AbstractAlgebra.YoungTableau` directly would also be an option but both types have different constructors and you can't easily use `standard_tableaux()` etc.

**Additional context**
--

**Comment by micjoswig** [comment]
The decision in favor of the JuLie tableaux ober those from AbstractAlgebra was a conscious one.  While that pretty print function is nice, it should be easy to implement by someone who actually needs it.

**Comment by fingolfin** [comment]
Maybe @ulthiel is interested in adding a nicer printing method?
