### ISSUE TITLE
Zero rows in free resolutions

### ISSUE THREAD

**Issue by jankoboehm** [oscar-system/Oscar.jl#2471]
There seem to be zero rows in the matrices of free resolutions, that is, unit vectors are mapped to zero. Independent of whether we compute a minimal resolution or not, zero rows could be removed.

This only happens if we give to the Schreyer algorithm as required a Groebner basis. The current Oscar does not do this and only hands over a generating system (which is a bug). Then the zero rows do not appear. If we fix this bug the zero rows appear. So this issue is meant as a note to the ones currently fixing this bug.

I will try to generate an example which shows this with the current Oscar.

Note, the zero rows also a the root of a bug under discussion on graded resolutions, since they do not allow for determining the degree of the source unit vector.

**Comment by jankoboehm** [comment]
Should be resolved by PR #2634.

**Comment by fieker** [comment]
resolved @jankoboehm
