### ISSUE TITLE
Document `doctest_fix` in the dev manual and advertise it, possibly improve it

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2485]
Some time ago @fieker added a new helper `doctest_fix` which can be used to fix docstrings. It has two main variants:
1. `doctest_fix(FUNCTION)` to fix all docstrings of the given function -- e.g. `doctest_fix(symmetric_group)`
2. `doctest_fix(NAME::String)` to fix all docstrings for all files whose full path contains `NAME` -- e.g. `doctest_fix("src/Rings/")` to fix all files `src/Rings/` 

Also, this function uses some internals of Documenter.jl and as such it currently only works with the current Documenter master branch; but not with the latest release of Documenter
So we should...
- [ ] add invocation examples to their docstrings
- [ ] link them in the dev docs
- [ ] if possible make it work with latest Documenter.jl release, too
- [ ] possibly submit it back as a patch to Documenter.jl ?
- [ ] advertise it on Slack (??)

**Comment by lgoettgens** [comment]
The current version works with the latest Documenter release.
Documentation improvements are in https://github.com/oscar-system/Oscar.jl/pull/3155.
