### ISSUE TITLE
Duplicate `radical(I::MPolyQuoIdeal)`

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2518]
On the current master branch (`54ca9cb7dd42cbba6a451f77d86025fcaf6feeae`), there are two competing implementations for `radical(I::MPolyQuoIdeal)`, namely
https://github.com/oscar-system/Oscar.jl/blob/54ca9cb7dd42cbba6a451f77d86025fcaf6feeae/src/Rings/MPolyQuo.jl#L426-L430
 from #2468 by @afkafkafk13 and https://github.com/oscar-system/Oscar.jl/blob/54ca9cb7dd42cbba6a451f77d86025fcaf6feeae/src/Rings/MPolyQuo.jl#L450-L453 from #2460 by @HechtiDerLachs.

I think it is best if @afkafkafk13 and @HechtiDerLachs decide which of them can be removed.

**Comment by afkafkafk13** [comment]
The only difference between the two is that I take out zeros in the set of generators. But in principal any of the two is fine.
@HechtiDerLachs : which one should we keep?

**Comment by wdecker** [comment]
1) Why should there be zeros?
2) Did you perform a test series in comparing the effectivity of this approach with directly calling the Singular function for the quotient ring?

**Comment by afkafkafk13** [comment]
ad 1) saturated_ideal only takes the preimage_ideal under the canonical projection in this case (without any computation, just moving the generators  to the MPolyring and adding the generators of the modulus of the original ring to the list). Then our function (any of the two variants) calls the 'radical' function for the MPolyRing, which in turn uses the Singular function. Hence we get back an ideal in the MPolyRing, which is then moved to the quotient ring through canonical projection. In this process, zeros may be introduced. 
But as I said before, I do not insist on my version, which might indeed be slower than the one not checking for zeros; I simply needed the functionality in a PR and the PR of Matthias had been merged in the meantime, who also needed the functionality....

ad 2) As far as I saw in the proc radical in the library primdec.lib in Singular (on GitHub), there is a check that radical has not been called in a quotient ring setting at the beginning. Seeing this, I decided to do the preimage under the canonical projection on the Oscar side and use the existing radical function (knowing that it uses the Singular radical).

**Comment by HechtiDerLachs** [comment]
I think removing the zeroes is the cleaner way to do this for the time being. Either way: Both versions are just hacks to make the functionality available quickly. Nothing has ever been tested in speed against potentially more specialized routines. 

If it's possible to call the singular procedure on the quotient ring directly, we should probably do that. But then someone has to teach me how to achieve this with all the new versions of `BiPolyArray` and/or their replacements.

**Comment by afkafkafk13** [comment]
After discussion in the geometry group: 
Both competing original solutions are valid, Wolfram's does not comply with the current implementation in Singular and is hence not valid. Precedence should be given to the valid solution which agrees best with the current implementation of the quotient ring: @afkafkafk13 's solution, if a groebner basis is available (or available with very high probability), @HechtiDerLachs 's solution otherwise.

**Comment by afkafkafk13** [comment]
repaired by PR #2518,
