### ISSUE TITLE
Two different skew-symmetry checks

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2555]
**Describe the bug**
We have two different implementations for skew symmetry checks of a `MatElem`: 
```julia
julia> methods(is_skew_symmetric)
# 1 method for generic function "is_skew_symmetric" from AbstractAlgebra:
 [1] is_skew_symmetric(M::MatElem)
     @ ~/path/AbstractAlgebra.jl/src/Matrix.jl:2403

julia> methods(is_skewsymmetric_matrix)
# 1 method for generic function "is_skewsymmetric_matrix" from Oscar:
 [1] is_skewsymmetric_matrix(B::MatElem{T}) where T<:RingElem
     @ ~/path/Oscar.jl/src/Groups/matrices/matrix_manipulation.jl:171
```

As far as I can tell, the implementations differ in the behavior in characteristic 2, and the latter imposes a restriction on the element type of the matrices.

It would be great to have only one function doing that and not two. Similar functions would be named `is_skew_symmetric` (without `matrix`), so I would like that name here.

Can somebody with knowledge about the use-cases say a few words about the characteristic 2 stuff, so that we can decide, which version to keep? In all cases, this should probably go into AbstractAlgebra.

**Comment by fingolfin** [comment]
We are comparing 

https://github.com/oscar-system/Oscar.jl/blob/3b64d46d9ab90b1cd6e9b503fa1b7adf6667dbfa/src/Groups/matrices/matrix_manipulation.jl#L171-L183
 https://github.com/Nemocas/AbstractAlgebra.jl/blob/bfa185a7c074b20527009e039ad45be8ab1bdd7a/src/Matrix.jl#L2403-L2410

I would say the latter (in AbstractAlgebra) is what we want. The former (in Oscar) actually tests for an *alternating* form (resp. a representation matrix for such a form) -- we may also want such a test, but it should be under its own name. And indeed the restriction on the typ seems unnecessary.
