### ISSUE TITLE
CI: `signal (15): Terminated` while testing line_bundle_cohomologies.jl

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#2570]
This seems to happen on different julia version, latest occurrence with julia 1.6 today:
https://github.com/oscar-system/Oscar.jl/actions/runs/5596287816/jobs/10233127160#step:6:1709
Previously with 1.10:
https://github.com/oscar-system/Oscar.jl/actions/runs/5542800957/jobs/10117956123#step:6:1769
Or 1.8:
https://github.com/oscar-system/Oscar.jl/actions/runs/5538993303/jobs/10109491192#step:6:1787
https://github.com/oscar-system/Oscar.jl/actions/runs/5529093333/jobs/10086687187#step:6:1719
https://github.com/oscar-system/Oscar.jl/actions/runs/5522538540/jobs/10072274228#step:6:1719
https://github.com/oscar-system/Oscar.jl/actions/runs/5517015410/jobs/10059075149#step:6:1721
https://github.com/oscar-system/Oscar.jl/actions/runs/5514895096/jobs/10054660090#step:6:1721
(These are from the two pages of most recent commits on master)

The terminated probably means that the process ran out of memory and was killed by the operating system, this might explain why it does not seem to happen on the macos runners (which have more RAM).
On a successful run one can see that this test does quite a lot of allocations:
```
-> Testing AlgebraicGeometry/ToricVarieties/line_bundle_cohomologies.jl took: runtime 50.507 seconds + compilation 8.342 seconds + recompilation 0.000 seconds, 12781.50 MB
```
12 GB is one of our larger test-files, which can be seen in the table here: https://github.com/oscar-system/Oscar.jl/actions/runs/5592243123#summary-15147145693
Whether this leads to such a crash also depends how much of this memory is needed at the same time, but bringing this down might help avoiding these failures.

cc: @HereAround who created this test file.

PS: I have seen these `Terminated` prints also during other tests but most of the time this happens in the `line_bundle_cohomologies.
Other cases:
- `AlgebraicGeometry/Schemes/Glueing.jl`: https://github.com/oscar-system/Oscar.jl/actions/runs/5592619727/jobs/10225306056#step:6:3051

**Comment by lgoettgens** [comment]
This is a duplicate of https://github.com/oscar-system/Oscar.jl/issues/2441.

**Comment by benlorenz** [comment]
> This is a duplicate of #2441.

Indeed, I added more details there, adjusted the title a bit and a added link to this ticket.
