### ISSUE TITLE
Doctest failing on 1.10 and nightly

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2596]
**Describe the bug**
See https://github.com/oscar-system/Oscar.jl/actions/runs/5680901276/job/15395925254?pr=2595#step:8:11
I think I have seen it today on 1.10 as well, but I could not find it to link here.
Unfortunately, the bug occurs only sometimes. I could not get it reproduced locally.

It seems to be due to some docstring of `abstract_flag_variety` in `experimental/IntersectionTheory/src/Main.jl`.

**Comment by fingolfin** [comment]
Thank you!

Hmm, what makes you think that it is related to the docstring of `abstract_flag_variety` in `experimental/IntersectionTheory/src/Main.jl`? I saw no reference to either in the logs (not saying you are wrong, just wondering how you deduced this, might be something useful to learn for me :-) ). Anyway, I'll have a look...

One minor quibble: the CI logs are removed after some time, so it's usually a good idea to at least copy the relevant error message into the issue (it also makes it easier for everyone to know what the problem is... "wait, did I look at this issue before [skims CI logs for a few minutes] ah right, that's *this* issue").

So, in this vein, here is the error in the log you linked.
```
[ Info: Doctest: running doctests.
┌ Error: JuliaSyntax parser failed — falling back to flisp!
│   exception =
│    BoundsError: attempt to access empty SubString{String} at index [0]
│    Stacktrace:
│      [1] checkbounds
│        @ Base ./strings/basic.jl:214 [inlined]
│      [2] getindex(s::SubString{String}, i::Int64)
│        @ Base ./strings/substring.jl:91
│      [3] getindex(source::Base.JuliaSyntax.SourceFile, i::Int64)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/source_files.jl:120
│      [4] highlight(io::IOBuffer, source::Base.JuliaSyntax.SourceFile, range::UnitRange{…}; color::Tuple{…}, context_lines_before::Int64, context_lines_inner::Int64, context_lines_after::Int64, note::String, notecolor::Symbol)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/source_files.jl:222
│      [5] highlight
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/source_files.jl:190 [inlined]
│      [6] show_diagnostic(io::IOBuffer, diagnostic::Base.JuliaSyntax.Diagnostic, source::Base.JuliaSyntax.SourceFile)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/diagnostics.jl:76
│      [7] show_diagnostics(io::IOBuffer, diagnostics::Vector{Base.JuliaSyntax.Diagnostic}, source::Base.JuliaSyntax.SourceFile)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/diagnostics.jl:86
│      [8] showerror(io::IOBuffer, err::Base.JuliaSyntax.ParseError)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/parser_api.jl:20
│      [9] sprint(f::Function, args::Base.JuliaSyntax.ParseError; context::Nothing, sizehint::Int64)
│        @ Base ./strings/io.jl:114
│     [10] sprint
│        @ Base ./strings/io.jl:107 [inlined]
│     [11] core_parser_hook(code::String, filename::String, lineno::Int64, offset::Int64, options::Symbol)
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/hooks.jl:184
│     [12] invoke_in_world(::UInt64, ::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│        @ Base ./essentials.jl:921
│     [13] invoke_in_world(::UInt64, ::Any, ::Any, ::Vararg{Any})
│        @ Base ./essentials.jl:918
│     [14] (::Base.JuliaSyntax.var"#invoke_fixedworld#120"{…})(::String, ::Vararg{…}; kws::@Kwargs{})
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/hooks.jl:118
│     [15] (::Base.JuliaSyntax.var"#invoke_fixedworld#120"{…})(::String, ::Vararg{…})
│        @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/hooks.jl:117
│     [16] _parse_string(text::String, filename::String, lineno::Int64, index::Int64, options::Symbol)
│        @ Base.Meta ./meta.jl:200
│     [17] #parse#3
│        @ Base.Meta ./meta.jl:238 [inlined]
│     [18] parse
│        @ Base.Meta ./meta.jl:236 [inlined]
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:963 [inlined]
│     [56] macro expansion
│        @ Documenter /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.11/Test/src/Test.jl:669 [inlined]
│     [57] macro expansion
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:963 [inlined]
│     [58] macro expansion
│        @ Documenter /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.11/Test/src/Test.jl:1577 [inlined]
│     [59] doctest(source::String, modules::Vector{Module}; fix::Bool, testset::String, doctestfilters::Vector{Regex})
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:963
│     [60] doctest
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:927 [inlined]
│     [61] doctest(package::Module; manual::Bool, testset::Nothing, kwargs::@Kwargs{})
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:898
│     [62] doctest(package::Module)
│        @ Documenter ~/.julia/packages/Documenter/bYYzK/src/Documenter.jl:884
│     [63] top-level scope
│        @ none:5
│     [64] eval
│        @ Core ./boot.jl:383 [inlined]
│     [65] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:291
│   offset = 0
│   code = ","
└ @ Base.JuliaSyntax /cache/build/default-amdci5-2/julialang/julia-master/base/JuliaSyntax/src/hooks.jl:258
```

It seems something flummoxed the new JuliaSyntax parser (written in pure Julia) so that it feel back to the original parser. That suggest we have some subtle syntax error somewhere that is "harmless"... the docstring you point out as a suspect is a *raw* string, though, hence I am confused as to how it could cause this? Though it seems it might be while trying to parse it for Markdown? Annoyingly the error is inside `show_diagnostics` which is probably trying to tell us more about the actual error... the `code = ","` bit is not very helpful here :joy: 

At least I can reproduce it locally via `using Oscar ; Oscar.build_doc(;doctest=true)` ...

Perhaps this is of interest to @c42f who wrote the new JuliaSyntax code?

**Comment by fingolfin** [comment]
OK in local tests, I've now seen 
- `code = ","`
- ``code = ", one should call `direct"``
- `code = ", parametrizing flags of subspaces \$V"`

While the first one is useless, the others indeed point to a handful of docstrings, the latter one to the two docstrings for different `abstract_flag_variety` methods.

Still don't see anything unusual about that docstring, though :-(

**Comment by benlorenz** [comment]
The third seems to be this:
```
julia> md"""Construct an abstract flag abstract_variety $\mathrm{Fl}(d_1,\dots,d_k)$, parametrizing
       flags of subspaces $V_{d_1}\subset V_{d_2}\subset\cdots\subset V_{d_k}=V$.
       """
┌ Error: JuliaSyntax parser failed — falling back to flisp!
```

I got it reduced a little bit further, the underscore seems to be important for this error to trigger and the `$,` but I not completely sure with the interaction:
```
julia> md"""Test abstract_variety $x_1$, parametrizing"""
┌ Error: JuliaSyntax parser failed — falling back to flisp!
```

In this case changing it to a literal 
```
`abstract_variety`
```
seems to help.

**Comment by lgoettgens** [comment]
This could be another variant of https://github.com/JuliaLang/JuliaSyntax.jl/issues/332.

**Comment by fingolfin** [comment]
Haha I just also discovered that issue but @lgoettgens beat me by 20 minutes ;-). I discovered it while browsing the Julia slack, were people are discussing this on the #release channel. See also https://github.com/JuliaLang/julia/issues/50703

**Comment by benlorenz** [comment]
This is [fixed on nightly now](https://github.com/oscar-system/Oscar.jl/actions/runs/5903303359/job/16012950771#step:8:18) and cherry-picked to the next backports-1.10 branch. (Also this was not really a failure)
