### ISSUE TITLE
wrong type?

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#260]
Have starting group with id 59
ERROR: InexactError: Int64(1124000727777607680000)
Stacktrace:
 [1] Type at ./gmp.jl:360 [inlined]
 [2] convert(::Type{Int64}, ::BigInt) at ./number.jl:7
 [3] length(::PermGroup) at /home/fieker/.julia/dev/Oscar/src/Groups/GAPGroups.jl:254
 [4] galois_group(::AnticNumberField, ::Int64) at /home/fieker/.julia/dev/Oscar/experimental/GaloisGrp/GaloisGrp.jl:856
 [5] galois_group(::AnticNumberField) at /home/fieker/.julia/dev/Oscar/experimental/GaloisGrp/GaloisGrp.jl:684
 [6] top-level scope at REPL[13]:1

The group is most likely 59 T 22 - or a maximal subgroup hereof

**Comment by fieker** [comment]
slight update: we have length(G) -> Int and order(G) -> fmpz
length is intended(?) for iterators

that is unfortunate, but what is the plan here?

**Comment by thofma** [comment]
I guess you can use `order` in GaloisGrp.jl for the moment.

We could change `length` to return a `BigInt`. Would make looping over `1:length(G)` quite a bit slower, but I am not sure this pattern is actually used in practice.

**Comment by fieker** [comment]
On Wed, Feb 03, 2021 at 03:21:10AM -0800, thofma wrote:
> I guess you can use `order` in GaloisGrp.jl for the moment.
> 
> We could change `length` to return a `BigInt`. Would make looping over `1:length(G)` quite a bit slower, but I am not sure this pattern is actually used in practice.

The problem is that we're going to hit this over and over again: people
wil be using length as it gived the correct size.
I don't know if this is fixable while wanting to iterate directly over a
group...

**Comment by thofma** [comment]
I think `length` is not involved when calling `iterate`. If you call `collect`, it will call `length`, but julia does not care if it is a `BigInt`. It will try to cast to `Int` anyway.

Here is an example where `length` returns a `BigInt` by default:
```julia
julia> collect(Hecke.SymmetricGroup(3))
6-element Array{Perm{Int64},1}:
 ()
 (1,2)
 (1,3,2)
 (2,3)
 (1,2,3)
 (1,3)

julia> collect(Hecke.SymmetricGroup(100))
ERROR: InexactError: Int64(93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000)
Stacktrace:
 [1] Type at ./gmp.jl:360 [inlined]
 [2] _similar_for(::UnitRange{Int64}, ::Type{Perm{Int64}}, ::AbstractAlgebra.Generic.SymmetricGroup{Int64}, ::Base.HasLength) at ./array.jl:597
 [3] _collect at ./array.jl:630 [inlined]
 [4] collect(::AbstractAlgebra.Generic.SymmetricGroup{Int64}) at ./array.jl:624
 [5] top-level scope at REPL[85]:1
```

The only problem could arise if we allow linear indexing into groups (which we don't at the moment). I doubt we will allow this in the future.

**Comment by fieker** [comment]
On Wed, Feb 03, 2021 at 03:27:49AM -0800, thofma wrote:
> I think `length` is not involved when calling iterate. If you call `collect`, it will call `length`, but julia does not care if it is a `BigInt`. It will try to cast to `Int` anyway.
> 
> ```julia
> julia> collect(Hecke.SymmetricGroup(3))
> 6-element Array{Perm{Int64},1}:
>  ()
>  (1,2)
>  (1,3,2)
>  (2,3)
>  (1,2,3)
>  (1,3)
> 
> julia> collect(Hecke.SymmetricGroup(100))
> ERROR: InexactError: Int64(93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000)
> Stacktrace:
>  [1] Type at ./gmp.jl:360 [inlined]
>  [2] _similar_for(::UnitRange{Int64}, ::Type{Perm{Int64}}, ::AbstractAlgebra.Generic.SymmetricGroup{Int64}, ::Base.HasLength) at ./array.jl:597
>  [3] _collect at ./array.jl:630 [inlined]
>  [4] collect(::AbstractAlgebra.Generic.SymmetricGroup{Int64}) at ./array.jl:624
>  [5] top-level scope at REPL[85]:1
> ```
> 
> The only problem could arise if we allow linear indexing into groups (which we don't at the moment). I doubt we will allow this in the future.
> 
Great, then we should change it to fmpz.
If we ever allow linear indexing, then we will write a getindex with
fmpz...

**Comment by fingolfin** [comment]
Several remarks:
- order is supposed to return an fmpz by default; this still needs to be corrected in the code, though
- Also order is supposed to let you specify alternate return types via the optional return type
- I'd prefer if there was no length method for groups at all, by defining IteratorSize suitably
- Indexed access ("enumeration") to groups makes no sense in general

**Comment by fieker** [comment]
On Wed, Feb 03, 2021 at 03:39:06AM -0800, Max Horn wrote:
> Several remarks:
> - order is supposed to return an fmpz by default; this still needs to be corrected in the code, though
fine
> - Also order is supposed to let you specify alternate return types via the optional return type
fine
> - I'd prefer if there was no length method for groups at all, by defining IteratorSize suitably
don't think is possible...
> - Indexed access ("enumeration") to groups makes no sense in general
but for certain groups it is ... (abelian groups)

**Comment by fingolfin** [comment]
> - I'd prefer if there was no length method for groups at all, by defining IteratorSize suitably
> don't think is possible...

According to the documentation, it should be. I'll see what happens.

> - Indexed access ("enumeration") to groups makes no sense in general
> but for certain groups it is ... (abelian groups)

It is *possible*, sure, even for arbitrary groups (as long as you have an iterator, you can of course turn that into a very inefficient enumerator). 

But is it *sensible*? What definition would you use for abelian groups? And, most importantly, what is the application?

**Comment by fieker** [comment]
OK, you can tell julia that this iterator is length free. At this point I am not argueing for or against, as I don't have any application. However, if we ever have one, we can go back and allow it... in This case...

**Comment by thofma** [comment]
> * I'd prefer if there was no length method for groups at all, by defining IteratorSize suitably

What is the advantage of not defining length? Those who want to use it will be annoyed and those who don't want to use don't care anyway.

**Comment by fingolfin** [comment]
I believe the error reported here has been resolved, by using `order` instead of `length`.
