### ISSUE TITLE
ideal in quotient ring

### ISSUE THREAD

**Issue by delphinepol** [oscar-system/Oscar.jl#263]
I can't define an ideal in a quotient ring, and I guess that the basic ideal operations are missing, like ":"
```
julia> R, (x,y) = PolynomialRing(QQ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Rational Field, fmpq_mpoly[x, y])

julia> I = ideal(R, [x^2+y+y^2])
ideal generated by: x^2 + y^2 + y

julia> Q = quo(R, I)
(Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^2 + y^2 + y, Map from
Multivariate Polynomial Ring in x, y over Rational Field to Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^2 + y^2 + y defined by a julia-function with inverse
)

julia> ideal(Q[1], [Q[1](x)])
ERROR: MethodError: no method matching ideal(::Oscar.MPolyQuo{fmpq_mpoly}, ::Array{Oscar.MPolyQuoElem{fmpq_mpoly},1})
Closest candidates are:
  ideal(::Hecke.NfRelOrd{T,S,U}, ::S) where {T, S, U} at /home/pol/.julia/packages/Hecke/xnDZl/src/NumField/NfRel/Ideal.jl:300
  ideal(::Hecke.NfRelOrd{T,S,U}, ::S, ::Bool) where {T, S, U} at /home/pol/.julia/packages/Hecke/xnDZl/src/NumField/NfRel/Ideal.jl:300
  ideal(::Hecke.NfRelOrd{T,S,U}, ::U, ::U, ::S, ::S) where {T, S, U} at /home/pol/.julia/packages/Hecke/xnDZl/src/NumField/NfRel/Ideal.jl:228
  ...
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

**Comment by fieker** [comment]
On Thu, Feb 04, 2021 at 06:31:43AM -0800, delphinepol wrote:
> I can't define an ideal in a quotient ring, and I guess that the basic ideal operations are missing, like ":"
Yep, Ideals there are not present at all... its clear what needs to be
done, but....
foer ideals in R itself, "most" of the "normal" operations are there...

**Comment by delphinepol** [comment]
For the normal ideals I saw the operations, but I would need them in the quotient ring to be able to continue with my divisors...

**Comment by thofma** [comment]
What is your definition of `:`?

**Comment by delphinepol** [comment]
It's the colon ideal.

**Comment by tthsqe12** [comment]
> On Thu, Feb 04, 2021 at 06:31:43AM -0800, delphinepol wrote: I can't define an ideal in a quotient ring, and I guess that the basic ideal operations are missing, like ":"
> Yep, Ideals there are not present at all... its clear what needs to be done, but.... foer ideals in R itself, "most" of the "normal" operations are there...

For the normalization I have to create maps between quotient rings and return fractional ideals in quotient rings. So, I guess you could say that I am working on this.

**Comment by tthsqe12** [comment]
@delphinepol  How are the current ideals in oscar working out for you here?

**Comment by delphinepol** [comment]
Yes, it is working now.
