### ISSUE TITLE
`Oscar.build()` is broken

### ISSUE THREAD

**Issue by aaruni96** [oscar-system/Oscar.jl#2631]
**Describe the bug**

Currently, `Oscar.build()` is broken, as it runs tests by simply including the `runtests.jl` file. This currently poses multiple problems : 

 - The path to tests is wrong. As the `runtests.jl` file assumes the current working directory is `Oscar/test`, we get a `No such file or directory` error if one runs `Oscar.build()` from any other working directory.
 - We have a different `Project.toml` for the tests and main Oscar. So, we get a `LoadError` when trying to run the Aqua tests, as that is a dependency only for the Oscar tests, not for Oscar itself. Thus, one needs to manually add Aqua to the current Project before `Oscar.build()` can be used.
 - We can't just include Aqua in the Oscar `Project.toml`, as that causes the Aqua test to fail.

The current workarounds to build a system image is to either activate an environment which already includes Aqua (but not as a direct dependency of Oscar), or comment out the Aqua test.

**To Reproduce**

In a clean environment (such that `Aqua.jl` is not already in the `Project.toml` file)

```
julia> using Oscar
julia> Oscar.build()
```

**Expected behavior**
All the tests should run successfully, and then a system image should be generated which includes Oscar.

**Comment by lgoettgens** [comment]
I think we do not want to include test-only dependencies (like Aqua) in a sysimage, as they have nothing to do with running Oscar. Unfortunately, the only solution I can think of right now right now is to split `testlist` in `runtests.jl` into two lists, one that works just with the Oscar dependencies and one that needs test-only dependencies.

Another way would be to have a separate list of statements for precompilation and tests. But that seems to be a lot more work for now and to maintain.
