### ISSUE TITLE
Reenable duvalsing tests

### ISSUE THREAD

**Issue by ederc** [oscar-system/Oscar.jl#2638]
We removed duvalsing tests in https://github.com/oscar-system/Oscar.jl/pull/2637 due to problems with absolute factorization. These tests need to be reenabled at some point.

**Comment by ederc** [comment]
We also had to disable FTheory tests, thus the same holds for them.
@HereAround

**Comment by lgoettgens** [comment]
> We also had to disable FTheory tests, thus the same holds for them. @HereAround

The FTheory tests have already been enabled again in https://github.com/oscar-system/Oscar.jl/pull/2640.

**Comment by HereAround** [comment]
> > We also had to disable FTheory tests, thus the same holds for them. @HereAround
> 
> The FTheory tests have already been enabled again in https://github.com/oscar-system/Oscar.jl/pull/2640.

This is on purpose as @lkastner fixed the problem.

**Comment by fingolfin** [comment]
@ederc this might be resolved now, can you try re-enabling it (via a PR)?
