### ISSUE TITLE
Doctest regression in `hilbert_series` tests

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2678]
There is a genuine failure in the doctests now, see [this log](https://github.com/oscar-system/Oscar.jl/actions/runs/5862154400/job/15893510384?pr=2578). Here is one of the failures; it looks as if either the return value of `hilbert_series` changed, or the printing of that return value.
```
┌ Error: doctest failure in ~/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-affine-algebras.jl:205-221
│ 
│ ```jldoctest
│ julia> R, (w, x, y, z) = graded_polynomial_ring(QQ, ["w", "x", "y", "z"]);
│ 
│ julia> A, _ = quo(R, ideal(R, [w*y-x^2, w*z-x*y, x*z-y^2]));
│ 
│ julia> hilbert_series(A)
│ (2*t^3 - 3*t^2 + 1, Factored element with data
│ Dict{ZZPolyRingElem, ZZRingElem}(-t + 1 => 4))
│ 
│ julia> R, (x, y, z) = graded_polynomial_ring(QQ, ["x", "y", "z"], [1, 2, 3]);
│ 
│ julia> A, _ = quo(R, ideal(R, [x*y*z]));
│ 
│ julia> hilbert_series(A)
│ (-t^6 + 1, Factored element with data
│ Dict{ZZPolyRingElem, ZZRingElem}(-t^2 + 1 => 1, -t + 1 => 1, -t^3 + 1 => 1))
│ ```
│ 
│ Subexpression:
│ 
│ hilbert_series(A)
│ 
│ Evaluated output:
│ 
│ (2*t^3 - 3*t^2 + 1, (-t + 1)^4)
│ 
│ Expected output:
│ 
│ (2*t^3 - 3*t^2 + 1, Factored element with data
│ Dict{ZZPolyRingElem, ZZRingElem}(-t + 1 => 4))
│ 
│   diff =
│    (2*t^3 - 3*t^2 + 1, Factored element with data
│    Dict{ZZPolyRingElem, ZZRingElem}(-t (-t + 1 => 4))1)^4)
└ @ Documenter.DocTests ~/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-affine-algebras.jl:205
```
and then some more

**Comment by fingolfin** [comment]
The first such failure I see on the master branch is [here](https://github.com/oscar-system/Oscar.jl/actions/runs/5857762672/job/15880328786) when PR #2661 was merged. But of course it is also possible that its not a change we made in Oscar.jl, but rather on in Hecke or Nemo or AbstractAlgebra that is causing this? Aha: indeed, on https://github.com/oscar-system/Oscar.jl/pull/2661/checks the tests were passing, and I notice that between the last working build and the first failing, we went from Hecke 0.20.0 to 0.20.1.

Ping @thofma

**Comment by fieker** [comment]
On Tue, Aug 15, 2023 at 03:16:00AM -0700, Max Horn wrote:
> The first such failure I see on the master branch is [here](https://github.com/oscar-system/Oscar.jl/actions/runs/5857762672/job/15880328786) when PR #2661 was merged. But of course it is also possible that its not a change we made in Oscar.jl, but rather on in Hecke or Nemo or AbstractAlgebra that is causing this? Aha: indeed, on https://github.com/oscar-system/Oscar.jl/pull/2661/checks the tests were passing, and I notice that between the last working build and the first failing, we went from Hecke 0.20.0 to 0.20.1.
> 
> Ping @thofma
> 
Doctests are outdated. One of the merge variants missed the doctest fix
- a change that needed coordiation between Oscar and Hecke

**Comment by thofma** [comment]
I will fix it
