### ISSUE TITLE
Master CI failing since JLLWrappers.jl v1.4.2

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2693]
Starting at https://github.com/oscar-system/Oscar.jl/actions/runs/5882459447, the OSCAR CI fails on all julia versions, while on the previous master commit it was mostly fine (or better to say "usual"; see https://github.com/oscar-system/Oscar.jl/actions/runs/5875640056).
The changes #2682 do not seem to be the root of the failure, but an update of Singular (see the error log below).
The relevant version changes:
```
Singular.jl               v0.18.9 -> v0.18.10
libsingular_julia_jll     v0.36.0+0 -> v0.39.0+0
Singular_jll              v403.203.202+0 -> v403.206.600+0
```

From https://github.com/oscar-system/Oscar.jl/actions/runs/5882459447/job/15953026725
```julia
ERROR: LoadError: libparse() is deprecated, use the non-do-block form
Stacktrace:
  [1] depwarn(msg::String, funcsym::String; force::Bool)
    @ Base ./deprecated.jl:124
  [2] depwarn(msg::String, funcsym::String)
    @ Base ./deprecated.jl:121
  [3] libparse(f::Function; adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ Singular_jll ~/.julia/packages/JLLWrappers/nEaFF/src/products/executable_generators.jl:20
  [4] libparse(f::Function)
    @ Singular_jll ~/.julia/packages/JLLWrappers/nEaFF/src/products/executable_generators.jl:19
  [5] (::Singular.Setup.var"#2#7"{Dict{Symbol, Vector{Tuple{String, String}}}, Vector{String}, String})()
    @ Singular.Setup ~/.julia/packages/Singular/NnGm6/src/setup.jl:43
  [6] cd(f::Singular.Setup.var"#2#7"{Dict{Symbol, Vector{Tuple{String, String}}}, Vector{String}, String}, dir::String)
    @ Base.Filesystem ./file.jl:112
  [7] regenerate_libraryfuncdictionary(prefixpath::String)
    @ Singular.Setup ~/.julia/packages/Singular/NnGm6/src/setup.jl:39
  [8] top-level scope
    @ ~/.julia/packages/Singular/NnGm6/src/setup.jl:54
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [10] include(x::String)
    @ Singular ~/.julia/packages/Singular/NnGm6/src/Singular.jl:8
 [11] top-level scope
    @ ~/.julia/packages/Singular/NnGm6/src/Singular.jl:79
 [12] include
    @ ./Base.jl:457 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2049
 [14] top-level scope
    @ stdin:3
in expression starting at /home/runner/.julia/packages/Singular/NnGm6/src/setup.jl:1
in expression starting at /home/runner/.julia/packages/Singular/NnGm6/src/Singular.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile Singular [bcd08a7b-43d2-5ff7-b6d4-c458787f915c] to "/home/runner/.julia/compiled/v1.9/Singular/jl_zn2pgV".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2300
  [3] compilecache
    @ ./loading.jl:2167 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1805
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1660
  [6] macro expansion
    @ ./loading.jl:1648 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1611
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [10] include(x::String)
    @ Oscar ~/work/Oscar.jl/Oscar.jl/src/Oscar.jl:20
 [11] top-level scope
    @ ~/work/Oscar.jl/Oscar.jl/src/Oscar.jl:25
 [12] include
    @ ./Base.jl:457 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2049
 [14] top-level scope
    @ stdin:3
```

cc @fingolfin @hannes14

**Comment by lgoettgens** [comment]
There is already a fix in work by @benlorenz in https://github.com/oscar-system/Singular.jl/pull/700.

**Comment by fingolfin** [comment]
The cause of this is actually an update to https://github.com/JuliaPackaging/JLLWrappers.jl and so it also affects older Singular.jl versions.

I've merged @benlorenz's fix and will  make a new Singular.jl release shortly.

We also should make sure to use `depwarn=error` in the CI of all our "satellite packages", not just Oscar.jl, to potentially catch such issues earlier (I am not sure it would have helped in this case, but it might in others)

**Comment by lgoettgens** [comment]
Thanks for working on this that fast!

> The cause of this is actually an update to https://github.com/JuliaPackaging/JLLWrappers.jl and so it also affects older Singular.jl versions.

I am really not a fan of adding something like this in a patch version.

> We also should make sure to use depwarn=error in the CI of all our "satellite packages", not just Oscar.jl, to potentially catch such issues earlier (I am not sure it would have helped in this case, but it might in others)

I will have a look at that. Should we do the same for OscarCI/OscarDevTools and doctests as well?

**Comment by fingolfin** [comment]
This should now be resolved.

**Comment by benlorenz** [comment]
> We also should make sure to use `depwarn=error` in the CI of all our "satellite packages", not just Oscar.jl, to potentially catch such issues earlier (I am not sure it would have helped in this case, but it might in others)

I don't think it would have helped in this case.

To reduce the impact of such issues we could also remove the `depwarn=error` from all current test jobs and add one (or two) separate jobs which uses this flag? Then we would still have test runs for PRs and have a separate `deprecations` check entry.

**Comment by lgoettgens** [comment]
There are more deprecation errors, e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/5882459447/job/15973528619#step:6:1082 for `lib4ti2_jll.exe4ti2gmp`.
I am working on it.
