### ISSUE TITLE
`doctest_fix` broken for submodules

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2714]
**Describe the bug**
`doctest_fix` does not try to fix any doctests, if the file containing the doctest is loaded into a submodule.

**To Reproduce**
Change any doctest output in `experimental/LieAlgebras/src/LinearLieAlgebra.jl`.
```
using Oscar
Oscar.doctest_fix("LieAlgebras")
```
The above call should have reverted the before change, but it doesn't.

**Expected behavior**
`doctest_fix` working independently of submodules.

**System**
current master (ae19865edbb00b2554bdf2e1ed00c3b4c6a2321e)

**Comment by fingolfin** [comment]
Are you sure the problem is caused by this being in a submodule (how so), and not e.g. because it is in experimental?

**Comment by lgoettgens** [comment]
> Are you sure the problem is caused by this being in a submodule (how so), and not e.g. because it is in experimental?

Yes, for other experimental projects without a submodule, it does work as expected. E.g. for `FTheoryTools` and `QuadFormAndIso`.

**Comment by fingolfin** [comment]
This seems to be caused by the fact that `Base.Docs.meta` does not list `general_linear_lie_algebra`, i.e.: 
```
julia> bm = Base.Docs.meta(Oscar);

julia> filter(contains("general_linear_lie_algebra"), [string(x[1]) for x in bm])
String[]
```
In contrast (and just to verify my code snippet above is not fundamentally broken):
```
julia> filter(contains("factor"), [string(x[1]) for x in bm])
9-element Vector{String}:
 "Oscar.factorisations"
 "Oscar.hastorusfactor"
 "Oscar.dim_of_torusfactor"
 "Oscar.factor_of_direct_product"
 "Oscar.isotypical_factors"
 "Oscar.isotypical_factor"
 "Oscar.has_torusfactor"
 "Oscar.cox_ring_of_qq_factorial_terminalization"
 "Oscar.number_of_factors"

```

So maybe we need to recurse over submodules manually, or find some other undocumented helpers, or ...

CC @fieker
