### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#2746]
Can we please have a new release?

cc @mgemath @fingolfin

**Comment by fingolfin** [comment]
Fine by me. @thofma @benlorenz @fieker any objections?

**Comment by thofma** [comment]
no objection

**Comment by benlorenz** [comment]
~~We would like to have #2750 and #2754 in there, both will be merged shortly.~~ _(done)_ Other than that no objections from me.

**Comment by HereAround** [comment]
So I suppose a new release can be created?
