### ISSUE TITLE
Adjust printing of `MPolyAnyMap` to follow OSCAR printing guidelines

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2773]
... as described in https://docs.oscar-system.org/dev/DeveloperDocumentation/printing_details/ (with fixes in PR #2769).

Right now I see this:
```
julia> psi = hom(R, R, [x^2, y^3])
Map with following data
Domain:
=======
Multivariate polynomial ring in 2 variables over QQ
Codomain:
=========
Multivariate polynomial ring in 2 variables over QQ

julia> print(psi)
Map with following data
Domain:
=======
Multivariate polynomial ring in 2 variables over QQ
Codomain:
=========
Multivariate polynomial ring in 2 variables over QQ
julia> print(IOContext(stdout, :supercompact => true), psi)
Map with following data
Domain:
=======
Multivariate polynomial ring
Codomain:
=========
Multivariate polynomial ring
```

Based on [this discussion](https://hackmd.io/cwOoBrTaReihNtmFjSdtTg) I think it rather should look something like this (up to details, of course, feel free to modify):
```
julia> psi  # detailed
Ring homomorphism 
  from Multivariate polynomial ring in 2 variables over QQ
  to Multivariate polynomial ring in 2 variables over QQ
defined by 
 x -> x^2
 y -> y^3

julia> print(psi)  # oneline
Hom: Multivariate polynomial ring -> Multivariate polynomial ring

julia> print(IOContext(stdout, :supercompact => true), psi)
Ring homomorphism
```

**Comment by fingolfin** [comment]
@simonbrandhorst @afkafkafk13 @wdecker @HechtiDerLachs @HereAround and others: maybe think about how should work on this? (It shouldn't be *that* much work, I'd hope...?)

Of course there might be other map types (or other types, period) where work should be applied, but this one figures quite high in my personal wish list for printing improvements :-)

**Comment by lgoettgens** [comment]
```julia
julia> print(psi)  # oneline
Hom: Multivariate polynomial ring -> Multivariate polynomial ring

julia> print(IOContext(stdout, :supercompact => true), psi)
Ring homomorphism
```

the supercompact printing conveys more easily seeable information than the online. I would prefer that one to look more like:
```
julia> print(psi)  # oneline
Ring homomorphism: Multivariate polynomial ring -> Multivariate polynomial ring
```
In particular, in which category this is a hom. I don't care if it says `Ring hom: ...` or `Ring homomorphism: ...`.
