### ISSUE TITLE
Deprecate `listperm`, instead add constructors

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#282]
Consider this:
```julia
julia> G = symmetric_group(4)
Sym( [ 1 .. 4 ] )

julia> pi = G([4,3,2,1])
(1,4)(2,3)
```

To turn this back into a vector, right now you need to write this:
```julia
julia> listperm(pi)
4-element Vector{Int64}:
 4
 3
 2
 1

```

But the more Julia-like approach would be to provide constructors. Like this (pseudo code):
```julia
julia> Vector(pi) # default is Vector{Int}
4-element Vector{Int64}:
 4
 3
 2
 1

julia> Vector{fmpz}(pi)
4-element Vector{fmpz}:
 4
 3
 2
 1

```

**Comment by GDeFranceschi** [comment]
Do we want to allow the use of `fmpz` also for the inverse construction, that is `S([1,2,3,4,5])` for `S` symmetric group and `[1,2,3,4,5]` of type `Array{fmpz,1}`?

**Comment by fingolfin** [comment]
@GDeFranceschi that would be a nice bonus, but also should be fairly trivial to add once we have the rest proposed in here.

**Comment by GDeFranceschi** [comment]
Why does this happen?
> julia> Li = [2,3,4,1]
> julia> Lf = fmpz.([2,3,4,1])
> julia> GAP.julia_to_gap(Li)==GAP.julia_to_gap(Lf)
> true
> julia> GAP.Globals.PermList(GAP.julia_to_gap(Li))
> GAP: (1,2,3,4,5)
> julia> GAP.Globals.PermList(GAP.julia_to_gap(Lf))
> GAP: fail

**Comment by ThomasBreuer** [comment]
Concerning the question about the `fail` result:
```
julia> GAP.julia_to_gap(Li)
GAP: [ 2, 3, 4, 1 ]

julia> GAP.julia_to_gap(Lf)
GAP: [ <Julia: 2>, <Julia: 3>, <Julia: 4>, <Julia: 1> ]

```
The function `GAP.Globals.PermList` does not accept a GAP list of fmpz as input.

(The reason why the two objects are regarded as equal by Julia is as follows:
Julia asks GAP to decide the question.
GAP sees two lists, and compares their entries.
And the question for the equality of `2` and `fmpz(2)` is delegated back to Julia; there is a method that says they are equal.)
