### ISSUE TITLE
Scary but harmless error about ferret binary missing

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#283]
There is a scary but harmless error about the ferret.so binary missing when running Oscar the first time. It happens because we try tomload the GAP package ferret; this detects that ferret was not compiled (resulting in the error), but then we just install and compile it.

we should not show this message in this form

**Comment by ulthiel** [comment]
There's also more: "wget not found" (on macOS).

```
WARNING: could not import Hecke.valence into Oscar
Error: Cannot load 'Ferret' due to missing binary library
Please run './configure; make' in the 'pkg/ferret' directory
#I  Getting PackageInfo URLs...
#I  Command wget not found
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/ferret/PackageInfo.g ...
#I  Command wget not found
#I  Downloading archive from URL https://github.com/gap-packages/ferret/releases/download/v1.0.5/ferret-1.0.5.tar.gz ...
#I  Command wget not found
#I  Saved archive to /var/folders/yc/96qfykgx19b7b9y5nh_g5hmr0000gn/T//tmcsnWuM/ferret-1.0.5.tar.gz
#I  Extracting to /Users/thiel/.julia/gaproot/v4.11/pkg/ferret-1.0.5 ...
#I  Checking dependencies for ferret...
#I    GAPDoc >= 1.5: true
#I  Command wget not found
```

**Comment by thofma** [comment]
Does it succeed in the end?

**Comment by ulthiel** [comment]
It seems so, as far as I can tell. There's no wget on macOS, I guess this is the problem.

**Comment by fingolfin** [comment]
It tries to use wget, then falls back to curl. I am not sure why it displays this though (because I can't look at the code right now)

**Comment by fingolfin** [comment]
It = the GAP package "PackageManager" we use to install ferret here

**Comment by edubya** [comment]
I see this error but in a slightly different manifestation on WSL Ubuntu. I am unsure if it succeeded with installing Ferret in the end because of an additional error:
```
~/.julia/gaproot/v4.11/pkg$ cat log/ferret-1.0.5.err
In file included from gap_cpp_headers/gap_cpp_mapping.hpp:13,
from src/cppmapper.cc:3:
gap_cpp_headers/include_gap_headers.hpp:6:10: fatal error: gmp.h: No such file or directory
6 | #include "gmp.h"
|          ^~~~~~~
compilation terminated.
make: *** [Makefile.gappkg:121: gen/src/cppmapper.lo] Error 1
```
Any advice on how to proceed?

**Comment by fingolfin** [comment]
That's completely different, it looks like there was an actual error.  I'll open a separate issue.
