### ISSUE TITLE
How does `:compact` printing mode fit into our printing model

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2861]
We defined three levels of printing (detailed, oneline, supercompact). But Julia has an existing notion of `compact` printing, and e.g `macro show_name` from AA uses that to drive decisions whether to print the "name" of an object or not.

But how does `compact` mode fit with our three printing modes? I noticed this in `@show_name` where I had some trouble triggering it until I realized that it checks for `:compact`...

**Comment by thofma** [comment]
Here are some examples from Base types.

```
julia> struct A end

julia> Base.show(io::IO, ::A) = print(io, get(io, :compact, false))

julia> [A(); A()]
2-element Vector{A}:
 false
 false

julia> [A() A(); A() A()]
2×2 Matrix{A}:
 true  true
 true  true

julia> (A(),)
(false,)

julia> [A() A();;; A() A()]
1×2×2 Array{A, 3}:
[:, :, 1] =
 true  true

[:, :, 2] =
 true  true

julia> Dict(1 => A())
Dict{Int64, A} with 1 entry:
  1 => true
```

As with many other things in the julia printing system, it is not clear what it is used for. I don't see how this could be useful to us.

**Comment by fingolfin** [comment]
OK, but I still think it would be good if the printing chapter in our dev docs at least mentioned this.

Also, it seems Hecke is still checking for `:compact` in a bunch of places where perhaps now it should be checking for supercompact?

**Comment by thofma** [comment]
Sure. Not all things have been adjusted to the new printing yet.

**Comment by fingolfin** [comment]
The only thing in the Julia documentation dealing with `:compact` I could find is here: https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext-Tuple{IO,%20Pair}

**Comment by fingolfin** [comment]
We ended up deciding that compact is simply completely orthogonal to our printing modes. We renamed `supercompact` to `terse` to make this clearer (previously one might have mistakenly assumed that supercompact implied compact, based on their names)
