### ISSUE TITLE
Improve metadata for serialization and Oscar master

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2873]
Someone send me an "mrdi" file, but I could not read it because things changed and our versions of Oscar were incompatible. While the serialization is still a moving target, maybe we could do the following. Make the metadata more useful by not only recording `{"Oscar":["https://github.com/oscar-system/Oscar.jl","0.13.1-DEV"]}`, but the actual commit (say `"0.13.1-DEV-f9fb3b54ad976b2a1ca65de54d6c5c39c177c34d"`). This should be done 
of course only in case it is not a proper version.

I guess a proper warning would have been nice ("version mismatch for the serialization format") instead of some obscure error, but I think this will be obsolete once things settle and we have possibility to "update".

What do you think @antonydellavecchia?

**Comment by antonydellavecchia** [comment]
It shouldn't be a problem to add this. I will also add better error handling
