### ISSUE TITLE
Rename `mat` to `matrix` ?

### ISSUE THREAD

**Issue by felix-roehrich** [oscar-system/Oscar.jl#2885]
I believe the following two functions should be renamed to `matrix`. Is there any reason why they were named `mat` ?
`git blame` shows @fieker and @wbhart, respectively.
If there are no protests, I can refactor this.

https://github.com/oscar-system/Oscar.jl/blob/0c82301ca340ad6998a6700488f2b80a04fdbd3e/experimental/GModule/Cohomology.jl#L1617-L1619

https://github.com/Nemocas/AbstractAlgebra.jl/blob/e1c902fc1d45281d65a7cb7b4dda4bb55a3f77d4/src/ModuleHomomorphism.jl#L13

**Comment by fieker** [comment]
On Thu, Oct 05, 2023 at 04:55:30AM -0700, Felix Röhrich wrote:
> I believe the following two functions should be renamed to `matrix`. Is there any reason why they were named `mat` ?
> `git blame` shows @fieker and @wbhart, respectively.
> If there are no protests, I can refactor this.
It was less typing....

But please, try to avoid merge conflicts in CF-WorkInProgress, pr 2870

**Comment by felix-roehrich** [comment]
> It was less typing....

Understandable, but since these functions are exported, I think it is better to be careful with such abbreviations, as we don't want to pollute the global namespace. I found this because I wanted to name a variable `mat` in the CLI.

I will rename the occurrences and see if a rebase is possible without conflicts. If not, this can be done after #2870 is merged.

**Comment by felix-roehrich** [comment]
Closed with #2903
