### ISSUE TITLE
Parallel testing broken

### ISSUE THREAD

**Issue by aaruni96** [oscar-system/Oscar.jl#2939]
**Describe the bug**
Currently, the parallel testing is broken, due to something in the Serialization tests.

**To Reproduce**
As of commit 65c9c93c , 
```
using Pkg
Pkg.test("Oscar", ["-j4"])
```

**Expected behavior**
Oscar finishes testing successfully using 4 processors.

**Actual Behaviour**
```
LoadError: Only process 1 can add and remove workers
in expression starting at /home/runtime/Oscar.jl/test/Serialization/IPC.jl:3
ERROR: Package Oscar errored during testing
```

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.14.0-DEV - #master, 65c9c93cf -- 2023-10-18 12:31:54 +0200
  combining:
    AbstractAlgebra.jl   v0.33.0
    GAP.jl               v0.10.0
    Hecke.jl             v0.22.3
    Nemo.jl              v0.37.1
    Polymake.jl          v0.11.6
    Singular.jl          v0.18.17
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+7
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.10.6+0
    libsingular_julia_jll   v0.40.3+0
    polymake_jll            v400.1000.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 1 on 20 virtual cores
Environment:
  JULIA_DEBUG = loading
Official https://julialang.org/ release
```

**Comment by benlorenz** [comment]
This will be fixed / worked around with #2810 where it is only run when `numprocs == 1` (and `testset != short` as it takes quite a bit of time): https://github.com/oscar-system/Oscar.jl/pull/2810/files#diff-3b9314a6f9f2d7eec1d0ef69fa76cfabafdbe6d0df923768f9ec32f27a249c63R136-R138

We might refactor the test to work better with parallelization once Antony is back from vacation.

**Comment by fingolfin** [comment]
So #2810 was merged, is this better now, @aaruni96 ?

Also I think @antonydellavecchia is back now?

**Comment by lkastner** [comment]
> Also I think @antonydellavecchia is back now?

October 31st

**Comment by aaruni96** [comment]
Yes, this is fixed.
