### ISSUE TITLE
Missing fn to reduce ZZMatrix to ZZModMatrix

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#2947]
**Describe the bug**
I can reduce a `ZZMatrix` to a `zzModMatrix` using `matrix_space`; this does not work for conversion to `ZZModMatrix`

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
ZZmod9 = residue_ring(ZZ,9)
ZZmod9big = residue_ring(ZZ,ZZ(9))
S = matrix_space(ZZmod9,3,3)
Sbig = matrix_space(ZZmod9big,3,3)
M = identity_matrix(ZZ,3)
S(M);    # --> works :-)
Sbig(M)  # --> error :-(
```

**Expected behavior**
The analogous syntax should work also for "large" moduli: _i.e._ the last line in the example above should return a `ZZModMatrix` rather than an error.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.13.1-DEV - #Hilbert_series_integration, 0a286f97 -- 2023-10-12 11:53:59 +0200
  combining:
    AbstractAlgebra.jl   v0.33.0
    GAP.jl               v0.9.8
    Hecke.jl             v0.22.3
    Nemo.jl              v0.37.1
    Polymake.jl          v0.11.6
    Singular.jl          v0.18.17
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+7
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.10.5+0
    libsingular_julia_jll   v0.40.3+0
    polymake_jll            v400.1000.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 20 virtual cores
Environment:
  JULIA_LOAD_PATH = @:@v#.#:@stdlib:/environments/globalenv
  JULIA_DEPOT_PATH = /home/zez25zuh/.julia:
Official https://julialang.org/ release
```

**Additional context**
The relevant source code appears to be in `Nemo/src/flint/nmod_mat.jl` and in `Nemo/src/flint/fmpz_mod_mat.jl`
The conversion functions in `nmod_mat.jl` around lines 750-810 are mirrored in `fmpz_mod_mat.jl` (lines 780-840) **except** for the last fn in `nmod_mat.jl` which is absent from `fmpz_mod_mat.jl`.  I suppose that copy-pasting with very minor editing should suffice:
```
function (a::zzModMatrixSpace)(b::ZZMatrix)
  (ncols(a) != b.c || nrows(a) != b.r) && error("Dimensions do not fit")
  z = zzModMatrix(modulus(base_ring(a)), b)
  z.base_ring = a.base_ring
  return z
end
```
No idea why `AbstractMatrix{ZZRingElem}` fails to match `ZZMatrix`... one feels that it ought to match.

**Comment by fingolfin** [comment]
> No idea why `AbstractMatrix{ZZRingElem}` fails to match `ZZMatrix`... one feels that it ought to match.

Our matrix types are *not* subtypes of Julia's `AbstractMatrix` type, so no, this won't match.

It seems you already analyzed the root cause of the issue and have a fix, so perhaps you could just submit a PR with the missing function added and perhaps a test case added to verify it works as intended?

**Comment by thofma** [comment]
Fixed by @JohnAAbbott himself in https://github.com/Nemocas/Nemo.jl/pull/1564.

**Comment by JohnAAbbott** [comment]
OK.  I'll close this issue.
