### ISSUE TITLE
Website manual search window sometimes unresponsive

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#2970]
**Describe the bug**
I wish to report an **intermittent bug**
On the website `https://docs.oscar-system.org/dev/` there is a search window near top left.
If I click in it, sometimes a pop-up window appears into which I can type the string I want to search for, but other times clicking in the small search window produces no apparent effect (in particular, it is not possible to type the search string into it).

**To Reproduce**
Go to the website `https://docs.oscar-system.org/dev/` then try clicking on the small search window near top left.
I am using Firefox 119.0 on Ubuntu 23.04.

**Expected behavior**
A way to type in the search string should be become obviously available.  Previously no pop-up would appear, but starting maybe about 2 weeks ago the pop-up would be the way to enter the search string.  Unrelated: I'm not really a fan of the pop-up.

**System (please complete the following information):**
Today's date is 2023-10-31.  But the problem has arisen intermittently for a week or more.
I am using Firefox 119.0 on Ubuntu 23.04.

**Additional context**
I do not believe that I have any special blockers, etc. in Firefox.

**Comment by joschmitt** [comment]
This also happens erratically for me. I could just produce it by chance in locally build docs and found this error message in the "developer tools" of firefox:
```
Uncaught TypeError: document.querySelector(...) is null
    <anonymous> http://localhost:8000/assets/documenter.js:683
    execCb https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    bind https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    emit https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    each https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    emit https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    init https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    a https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    completeLoad https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    onScriptLoad https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
```
Unfortunately, I am not a web developer.

**Comment by fingolfin** [comment]
Just to say: none of this functionality is implemented by us, it all comes from Documenter. It probably would be best if you open an issue on the Documenter.jl repository instead (assuming you can reproduce the issue also on, say, https://documenter.juliadocs.org/stable/

**Comment by thofma** [comment]
I would guess this is https://github.com/JuliaDocs/Documenter.jl/issues/2430
