### ISSUE TITLE
problem with `save_typed_object` for empty objects

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#2984]
The following works in the master branch.
```
julia> using Oscar
[...]
julia> file = open( "resultfile", "w" );

julia> s = Oscar.state(Oscar.serializer_open(file, Oscar.JSONSerializer));

julia> x = Tuple{Int, Int, Vector{Int64}}[(1, 1, [1,2])];

julia> Oscar.save_typed_object(s, x, :entries)
1
```

The following does not work.
```
julia> y = Tuple{Int, Int, Vector{Int64}}[];  # empty vector

julia> Oscar.save_typed_object(s, y, :entries)
ERROR: BoundsError: attempt to access 0-element Vector{Tuple{Int64, Int64, Vector{Int64}}} at index [1]
[...]
```
Apparently the `save_type_params(s::SerializerState, obj::S) where {T, S <:MatVecType{T}}` method assumes that `obj` is not empty.

Perhaps it is a bad idea to serialize vectors whose entries are of type `Tuple{Int, Int, T}`, but I thought that such objects would be a natural description of (for example) sparse matrices with entries of type `T`. I would be happy about suggestions for a simpler way to serialize such objects.

**Comment by antonydellavecchia** [comment]
The issue is for any vector type whose entry types are also parametrized, for instance tuples. The current serialization code does expect there to be a least one element in the vector,  since getting the params in general uses an entry. The issue is more delicate then it appears. Might take some time for a solution, but ideal the serialization should be able to handle such cases.

**Comment by ThomasBreuer** [comment]
O.k., in the applications I have in mind, I can catch the case of empty vectors in both save and load. So maybe we should just document this behaviour, and remove the "bug" label.

**Comment by fingolfin** [comment]
What's the status here?

**Comment by ThomasBreuer** [comment]
I think @antonydellavecchia should decide whether this issue should be closed.
As I wrote, I have a workaround for my use cases.

**Comment by antonydellavecchia** [comment]
A quick fix solves this issue. There might be some examples where this actually becomes a problem. I would then need to do some refactoring on container loading. I'll close till issue pops up again, it's possible I have a way to clean this up during the current refactor of load https://github.com/oscar-system/Oscar.jl/pull/3032
