### ISSUE TITLE
`isdefined` checks on primitive struct members

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#3000]
As this just came up with weird effects in #2998, while julia does have `isdefined` checks to test whether struct fields have been assigned, this does not work for `primitive` or `bitstype` fields (i.e. they are always defined but have undefined values):
```
julia> mutable struct Dummy2
       a::Bool
       b::Int
       function Dummy2()
       return new()
       end
       end

julia> for i in 1:1000
       x = Dummy2();
       println(isdefined(x, :a), " - ", x.a)
       println(isdefined(x, :b), " - ", x.b)
       end
true - false
true - 139972274657792
true - false
true - 32
true - false
true - 0
true - false
true - 0
true - false
true - 0
true - true
true - 139972163252336
true - false
...
```

This is in my opinion not really well documented. It is not mentioned for [`isdefined`](https://docs.julialang.org/en/v1/base/base/#Core.isdefined). It is mentioned at [`isbitstype`](https://docs.julialang.org/en/v1/base/base/#Base.isbitstype) with "may not track isdefined...". Some references to this fact are also in the [Incomplete-Initialization](https://docs.julialang.org/en/v1/manual/constructors/#Incomplete-Initialization) docs.

While trying to search for such usages I found for example:
```julia
    if isdefined(r, :isGB) # why can this even happen?
      r.isGB = false
    end
```
(`src/Rings/mpoly.jl:236`)

There are a bunch of such calls in the DoubleComplexes:
```julia
### Boundedness
has_right_bound(D::DoubleComplexOfMorphisms) = isdefined(D, :right_bound)
has_left_bound(D::DoubleComplexOfMorphisms) = isdefined(D, :left_bound)
has_upper_bound(D::DoubleComplexOfMorphisms)   = isdefined(D, :upper_bound)
has_lower_bound(D::DoubleComplexOfMorphisms)   = isdefined(D, :lower_bound)

function is_complete(D::DoubleComplexOfMorphisms)
  if isdefined(D, :is_complete) && D.is_complete
    return true
  end
```
(`is_complete` is `Bool` and the `*_bound` are `Int64`)

But I fear there may be more... (currently trying to run the testsuite and collect such calls).

cc: @HechtiDerLachs @thofma

**Comment by lkastner** [comment]
I want to add that I consider relying on members of structs being undefined bad style. Either actively set them to `nothing` and change the type accordingly to `Union{Nothing,...}` or use the attributes functionality.

**Comment by thofma** [comment]
I like using `::Int` and setting it to `-1`, `0` and `1` for "not set", `false` and `true`. Personally I am in favour of purging `Nothing`.

**Comment by HechtiDerLachs** [comment]
I didn't know that using `isdefined` is considered bad style. Good to know, then.

**Comment by thofma** [comment]
It is not (in all cases).

**Comment by fieker** [comment]
On Wed, Nov 08, 2023 at 01:57:00AM -0800, Lars Kastner wrote:
> I want to add that I consider relying on members of structs being undefined bad style. Either actively set them to `nothing` and change the type accordingly to `Union{Nothing,...}` or use the attributes functionality.
> 
I disagree, e.g. attributes are non-discoverable.
Bittypes can (and possibly should) be initialised, but non-bit-types can
be left undefined.
We also had this discussion today...

**Comment by benlorenz** [comment]
I haven't found any further occurrences, closing this now as both reported cases have been resolved.
