### ISSUE TITLE
About the `as = :blub` keyword argument

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#301]
I noticed that we started using lots of `as = :blub` keyword arguments, for example, https://github.com/oscar-system/Oscar.jl/blob/master/src/Polytopes/Polyhedron.jl#L187. Similar for the recent draft of Lars. Here is one example:
```julia
function facets(P::Polyhedron; as::Symbol = :halfspaces)
    if as == :halfspaces
        PolyhedronFacetHalfspaceIterator(P)
    elseif as == :polyhedra
        PolyhedronFacetPolyhedronIterator(P)
    elseif as == :halfspace_matrix_pair
        return decompose_hdata(pm_polytope(P).FACETS)
    else
        throw(ArgumentError("Unsupported `as` argument :" * string(as)))
    end
end
```
The problem is that this makes the function type unstable (because depending on the value of the symbol `as`, the return type changes). Although the syntax is rather clean, this will lead to decreased performance down the road, both for runtime and compile time.
Here are two ways to work around this:
1. Introduce some types for the parameters (or reuse them if they are already there):
    ```julia
    struct Halfspaces end
    struct Polyhedra end # maybe this exists already
    struct HalfspaceMatrixPair end
    ```
    and then do
    ```julia
    function facets(P::Polyhedron, as::Type{T} = Halfspaces) where {T} # need the T to force specialization
        if as === Halfspaces
            PolyhedronFacetHalfspaceIterator(P)
        elseif as === Polyhedra
            PolyhedronFacetPolyhedronIterator(P)
        elseif as === HalfspaceMatrixPair
            return decompose_hdata(pm_polytope(P).FACETS)
        else
            throw(ArgumentError("Unsupported `as` argument :" * string(as)))
        end
    end
    ```
    Then the invocation looks like `facets(P, HalfspaceMatrixPair)`. At the moment `as` cannot be a keyword argument, since julia seems to not specialize (check with `@code_warntype`) in this case. (I am currently trying to find out if we can have it as a keyword argument somehow.)

2. Another option would be to use `Val`, so that it would look like
    ```julia
    function facets(P::Polyhedron, as::Type{Val{T}} = Val{:halfspaces}) where {T}
        if as === Val{:halfspaces}
            PolyhedronFacetHalfspaceIterator(P)
        elseif as === Val{:polyhedra}
            PolyhedronFacetPolyhedronIterator(P)
        elseif as === Val{:halfspace_matrix_pair}
            return decompose_hdata(pm_polytope(P).FACETS)
        else
            throw(ArgumentError("Unsupported `as` argument :" * string(as)))
        end
    end
    ```
    This would have to be invoked as `factes(P, Val{:halfspace_matrix_pair})`. Regarding keyword argument or not, this has the same limitation.

There is no real difference, but I would prefer option 1) for aesthetic reasons. Note that for the user it does not matter, because he has to look at the docstring anyway to figure out the options.

What y'all think? Also pinging @tbrysiewicz.

**Comment by tbrysiewicz** [comment]
We discussed this today briefly and agreed that the current status is not the way to go. 
We chose to have vertices always output an iterator, and then include a separate function called vertices_as_matrix. 
But in the case of facets, the iterator may iterate over Polyhedra, or over matrix pairs; so I guess our change doesn't solve the issue.
I'm happy to update things based on whatever you all decide.

**Comment by thofma** [comment]
OK, sounds good.

P.S.: It should probably be `Matrix(::NameOfTheIterator)`.

**Comment by fingolfin** [comment]
So, who is "you all" who are going to decide this? Are people discussing this, e.g. in gather.town?

**Comment by thofma** [comment]
I don't think anyone is discussion this right now and I don't know who is making final decisions.

**Comment by fingolfin** [comment]
I guess I am confused then who is waiting for what: @tbrysiewicz wrote "I'm happy to update things based on whatever you all decide" and I am not sure what that means... IMHO the Polytope people should pick one of @thofma suggestions (and if unsure, pick his preference, 1); and if there are concerns or questions how to deal with certain aspects of that, ask concretely/ Right now, it seems to me as if @tbrysiewicz is waiting for something, but I am not sure what is... :-)

**Comment by tthsqe12** [comment]
@thoma could you provide your proposed syntax for algorithm selection to
https://github.com/delphinepol/Oscar.jl/blob/polyringops/src/Rings/mpoly.jl#L1142
We need this for https://github.com/oscar-system/Oscar.jl/pull/292
, and once I see this in action, I can reproduce it elsewhere.

**Comment by thofma** [comment]
It does not matter for algorithm selection if it does not effect the return type. I think @tbrysiewicz & co are going with `; algorithm = :bla` in the signature. I would do the same.

**Comment by tthsqe12** [comment]
`algorithm` or `algo`, or `alg`? Note the wonderful consistency here:
```
sort!(stuff, by = fxn, alg=InsertionSort)
```

**Comment by thofma** [comment]
Should be a different issue. For now you can follow your heart.

**Comment by saschatimme** [comment]
I just want to note that you could also define methods this way
```julia
facets(polyhedron; as = :halfspaces) = facets(polyhedron, Val(as))
facets(polyhedron, ::Val{:halfspaces}) = PolyhedronFacetHalfspaceIterator(polyhedron)
facets(polyhedron, ::Val{:polyhedra}) = PolyhedronFacetPolyhedronIterator(polyhedron)
....
```

So that if performance matters you can use the `facets(polyhedron, Val(:polyhedra))` syntax and otherwise `facets(polyhedron; as = :polyhedra)`.

**Comment by lkastner** [comment]
Another suggestion was to move the 'as' keyword into the function name. I.e.
```
vertices  # whatever the default is
vertices_as_point_matrix  # returns a matrix
```
Would this be acceptable?

**Comment by thofma** [comment]
Yes, no objection from my part.
