### ISSUE TITLE
leading_term() ignores ordering and assumes degrevlex

### ISSUE THREAD

**Issue by m-kaltoft** [oscar-system/Oscar.jl#3039]
**Describe the bug**
`leading_term()` ignores ordering and assumes `degrevlex`

Same issue happens with `leading_monomial()` and `leading_coefficient()`, The issue doesn't affect the `divrem()` command.

**To Reproduce**
Run the following:
```
using Oscar
R, (x,y,z) = polynomial_ring(QQ, ["x","y","z"]; ordering = :lex)
f=x*z+y^2
println(leading_term(f))
R, (x,y,z) = polynomial_ring(QQ, ["x","y","z"]; ordering = :deglex)
f =x*z+y^2
println(leading_term(f))
R, (x,y,z) = polynomial_ring(QQ, ["x","y","z"]; ordering = :degrevlex)
f = x*z+y^2
println(leading_term(f))
```

Output:

```
y^2
y^2
y^2
```

**Expected behavior**
It should have printed:

```
xz
xz
y^2
```
**System (please complete the following information):**

```
OSCAR version 0.13.0
  combining:
    AbstractAlgebra.jl   v0.31.1

    GAP.jl               v0.9.8
    Hecke.jl             v0.20.3
    Nemo.jl              v0.35.3
    Polymake.jl          v0.11.8
    Singular.jl          v0.18.16
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+7
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.11.0+0
    libsingular_julia_jll   v0.40.3+0
    polymake_jll            v400.1100.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1260P
...
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_NUM_THREADS = 
Official https://julialang.org/ release
...
```

**Additional context**

This error occurred while working in a Jupyter notebook. 

The same error happens on both MacOS and Windows 10 as well (tested on other computers in class).

**Comment by joschmitt** [comment]
Unfortunately, there are two ways to choose a monomial ordering in OSCAR (and you are not the first person who stumbles over this, so we should do something to clarify the situation!).
In OSCAR, the ordering that is used for `leading_term` (and also for `groebner_basis`, `normal_form` etc.) does not need to be specified when creating the ring. By default, `degrevlex` is used, but any ordering from https://docs.oscar-system.org/stable/CommutativeAlgebra/GroebnerBases/orderings/ can be selected:
```
julia> R, (x, y, z) = QQ["x", "y", "z"];

julia> f = x*z + y^2;

julia> leading_term(f, ordering = lex(R))
x*z

julia> leading_term(f, ordering = degrevlex(R))
y^2

julia> leading_term(f, ordering = deglex(R))
x*z

julia> leading_term(f, ordering = wdegrevlex(R, [ 3, 1, 3 ]))
x*z
```
The ordering one can specify when creating the ring is mostly used internally and to my knowledge only controls how the polynomial is printed as far as the user is concerned.

**Comment by m-kaltoft** [comment]
@joschmitt 
Thank you! This makes sense. The defined order is also used in `divrem` among others. I appreciate the clarification. But yes, it is definitely not clear that the user defined order is not the one used in the commands.

**Comment by thofma** [comment]
Maybe we should just forbid supplying an ordering in the constructor.

**Comment by joschmitt** [comment]
> Maybe we should just forbid supplying an ordering in the constructor.

I agree. I opened #3040 and would close this issue here if nobody objects.
