### ISSUE TITLE
Remainders in reduce and reduce_with_quotients

### ISSUE THREAD

**Issue by efeliu** [oscar-system/Oscar.jl#3043]
**Describe the bug**
Hi, I'm not sure is a bug or me not understanding the command properly. Shouldn't reduce and reduce_with_quotients build on the same division algorithm and return the same remainder?

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug. 

For the following code:
```
using Oscar
# Julia code
R, (x,y) = PolynomialRing(QQ,["x","y"])
f = x^2+x*y^2+y
g1 = x + x*y
g2 = x + y
println(reduce(f, [g1,g2], ordering = lex(R)))
println(reduce_with_quotients(f, [g1,g2], ordering = lex(R)))
```
The output is
-y^3 + y^2 + y
([y-2 x+2], -y)

So, remainders are not the same. 

**Expected behavior**
I expect the remainders to be the same. 

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
...
OSCAR version 0.13.0
  combining:
    AbstractAlgebra.jl   v0.31.1
    GAP.jl               v0.9.8
    Hecke.jl             v0.20.3
    Nemo.jl              v0.35.3
    Polymake.jl          v0.11.8
    Singular.jl          v0.18.16
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+7
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.11.0+0
    libsingular_julia_jll   v0.40.3+0
    polymake_jll            v400.1100.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 2 on 8 virtual cores
Official https://julialang.org/ release
```

**Additional context**

**Comment by joschmitt** [comment]
In the current documentation it says:
> The reduction strategy behind the `reduce` function and the reduction strategy behind the functions `reduce_with_quotients` and `reduce_with_quotients_and_unit` differ. As a consequence, the computed remainders may differ.

Unfortunately, this text is not yet in the documentation of the released version of OSCAR you probably have.

**Comment by efeliu** [comment]
Ah ok thanks! Yes, this text is not the documentation for the latest released version. It would be nice if the documentation explained what algorithm is behind the reduction in each case. It seems to me that reduce_with_quotients performs standard euclidean division (like with the divrem command).
