### ISSUE TITLE
`primary_decomposition` won't finish on very simple input

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#3083]
I have a principal ideal for which the generator can easily be decomposed with `factor`. If I run `primary_decomposition`, however, the computation simply won't finish. 

I wrote out the ideal using the serialization, the file should be here:
[difficult_ideal.txt](https://github.com/oscar-system/Oscar.jl/files/13613084/difficult_ideal.txt)

Download the file, start Oscar and type `I = load("difficult_ideal.txt")`. 
Now try `primary_decomposition(I)` and in contrast `factor` for the one non-zero generator. 

Any ideas what might be going on here?

**Comment by HechtiDerLachs** [comment]
CC: @hannes14, @afkafkafk13, @wdecker .

**Comment by HechtiDerLachs** [comment]
Here's another case with a simple algebraic extension of QQ as coefficient ring: 
[another_difficult_ideal.json](https://github.com/oscar-system/Oscar.jl/files/13613865/another_difficult_ideal.json)
`minimal_primes` takes ages to finish while `factor` on the one generator returns instantly.

**Comment by hannes14** [comment]
Singular should report an error here: it does not anything about the coefficient ring (beside basic arithmetic),
so for example Groebner base computation will work, but for example factorization not.

**Comment by afkafkafk13** [comment]
For me this gives the impression that Singular is being called with insufficiently prepared input. 

We know very well about the limitations of Singular, when working over algebraic field extensions and in particular of the primary decomposition functionality. This could be taken into account in the respective Oscar method.

A quick and dirty (i.e. rather suboptimal) solution could be to disallow the call to  Singular's primary decomposition in those cases which cannot be handled by Singular directly. A more elaborate and more satisfactory solution would be to rewrite the polynomial ideal over the (possibly repeated) algebraic extension of QQ into a polynomial ideal in a larger polynomial ring over QQ taking the minimal polynomials of the (tower of) extensions as additional generators of the ideal -- like the Singular user currently does, when such a situation arises.

**Comment by HechtiDerLachs** [comment]
> Singular should report an error here: it does not anything about the coefficient ring (beside basic arithmetic),
> so for example Groebner base computation will work, but for example factorization not.

Makes sense. But the CPU is running on 100% either way. 

Is there any way I would get a primary decomposition to work in my cases?

**Comment by HechtiDerLachs** [comment]
> A more elaborate and more satisfactory solution would be to rewrite the polynomial ideal over the (possibly repeated) algebraic extension of QQ into a polynomial ideal in a larger polynomial ring over QQ taking the minimal polynomials of the (tower of) extensions as additional generators of the ideal -- like the Singular user currently does, when such a situation arises.

But Singular can also model simple algebraic extensions for their coefficient rings. Can't we just make sure that a Hecke field is translated accordingly?

**Comment by thofma** [comment]
The coefficient field is
```
Relative number field with defining polynomial T^2 - z_16^6 + z_16^4 - z_16^2
  over number field with defining polynomial _$^8 + 1
    over rational field
```
which is not a simple algebraic extension that can be handled by Singular, if I understand correctly. Not sure how to do proceed best. I guess one way would be to turn it into some simple algebraic extension of the rationals and then do the translation. The translation has to be overhauled anyway.

**Comment by afkafkafk13** [comment]
We could indeed pass to a simple extension by using the theorem of the primitive element. In my practical experience this has often led to harder problems for this particular part of the functionality of Singular than adjoining several variables -- certainly if the tower is higher than just 2. (This, of course, is just my personal user experience.) 

If I were to decide this question, I would go for a adjoining one variable for each symbol of the tower of extensions and adding the minimal polynomials to the generators of the ideal. In this way, the primary decomposition of Singular plays on its home grounds. (This only refers to primary decomposition; if we were considering other tasks, my choice might differ!)

**Comment by thofma** [comment]
The Oscar <-> Singular translation works by translating the coefficient field/ring. Translating a single ideal in an ad hoc fashion does not really fit into this setup.

**Comment by afkafkafk13** [comment]
I was talking about the primary decomposition method in Oscar creating a new ring and a new ideal in this ring and then calling the translation to Singular -- of course translating back the result afterwards.

I did not mean this as a general method, but as a tailormade solution for the primary decomposition part, which relies on functionality in Singular which has never been designed for algebraic extensions in the first place.

**Comment by HechtiDerLachs** [comment]
The second example I posted has a simple algebraic extension of `QQ` as a coefficient ring (of type `AnticNumberField`) which does have a translation via `singular_coeff_ring`. But the primary decomposition does not run nevertheless. @hannes14 said, he wanted to look into this, too.

**Comment by wdecker** [comment]
What is reported here concerns more than one functionsand should be resolved as suggested by @afkafkafk13. @HechtiDerLachs, @hannes14: Let us sit together next week and do just that.

**Comment by HechtiDerLachs** [comment]
> The Oscar <-> Singular translation works by translating the coefficient field/ring. Translating a single ideal in an ad hoc fashion does not really fit into this setup.

Unfortunately, I can confirm @afkafkafk13 's experience. Here's the ideal I try to decompose: 
[decomposition_ideal.json](https://github.com/oscar-system/Oscar.jl/files/13650210/decomposition_ideal.json)
If I first translate it to an ideal over the `absolute_simple_field` of the `coefficient_ring` of its `base_ring`, then the computation does not even finish. With the material from this PR I get `3.542763 seconds (8.74 M allocations: 144.843 MiB)` instead. So a taylor-made rerouting for primary decomposition seems to be apt here. 

Edit: I am wondering whether it would make sense to provide a special ordering to be used in the decomposition. So that the added variables take some precedence over the others? As the system of equations added is "triangular" that might make a difference.

**Comment by HechtiDerLachs** [comment]
It seems to be similar with `minimal_primes` (rerouting not yet included in this PR). Interestingly, `minimal_primes` takes about 18 seconds while `primary_decomposition` takes ~3.5s. @afkafkafk13 : Shouldn't `minimal_primes` be significantly faster than `primary_decomposition`?

**Comment by afkafkafk13** [comment]
Are these timings stable over 10 runs (with empty cache each time)? 

Both algorithms use 'sufficiently random' coordinate changes internally at some point. This may affect the presentation of the output (order of components in the list), but also the computing time. Here it is useful to not only look at one run, but at a bunch of runs and take the average.

Concerning the idea with the special ordering: New rings are created in the Singular internals of primary decompostion quite early anyway, so these changes might quickly vanish without any effect.  

For any intimate knowledge of the inner workings of primdec.lib @wdecker is the person to ask.

**Comment by wdecker** [comment]
@HechtiDerLachs, @hannes14 and @wdecker  will meet tomorrow to clearify this.

**Comment by fieker** [comment]
This should, currently, given an error, so after verfication -> close

**Comment by lgoettgens** [comment]
I re-tested the initial input with the following result:
```julia
julia> I = load("/home/lgoe/Downloads/difficult_ideal.txt");

julia> @time primary_decomposition(I)
  7.573532 seconds (36.33 M allocations: 3.034 GiB, 1.36% gc time)
2-element Vector{Tuple{MPolyIdeal{AbstractAlgebra.Generic.MPoly{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}}}, MPolyIdeal{AbstractAlgebra.Generic.MPoly{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}}}}}:
 (Ideal with 5 generators, Ideal with 5 generators)
 (Ideal with 5 generators, Ideal with 5 generators)

julia> I = load("/home/lgoe/Downloads/difficult_ideal.txt");

julia> @time factor.(gens(I))
  0.072497 seconds (225.99 k allocations: 13.998 MiB)
4-element Vector{Fac{AbstractAlgebra.Generic.MPoly{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}}}}:
 0
 1 * ((s1//s0) + (-z_16^6 - z_16^4 - z_16^2)*(w//x)^4 - 1) * ((s1//s0) + (z_16^6 + z_16^4 + z_16^2)*(w//x)^4 + 1)
 0
 0
```

-> `primary_decomposition` finishes, but still needs 100x times compared to `factor`

**Comment by afkafkafk13** [comment]
@lgoettgens : The order of magnitude in the running time does not strike me as particularly odd or extremely worrying. Factoring generators appears as a subtask somewhere inside primary decomposition, but primary decomposition has a lot more tasks to accomplish in general. However, looking at the memory used by the computation, I still worry quite a bit -- somehow the fact that the ideal is principal is not recognized and the general methods are used (which include a sufficiently general change of coordinates quite early in the computation).

**Comment by lgoettgens** [comment]
@HechtiDerLachs told us to close this

**Comment by HechtiDerLachs** [comment]
@afkafkafk13 : Feel free to re-open this if you have time to look into this. @hannes14 told me via email that most probably we're just unlucky with the particular constellation of this ideal.

**Comment by afkafkafk13** [comment]
> @afkafkafk13 : Feel free to re-open this if you have time to look into this. @hannes14 told me via email that most probably we're just unlucky with the particular constellation of this ideal.

Closing is fine, I agree with @hannes14 that sometimes we simply get unlucky and this might well be one of the cases.

**Comment by HechtiDerLachs** [comment]
But let me just put another example here which has been sent to me by @simonbrandhorst : 
[primary.txt](https://github.com/oscar-system/Oscar.jl/files/15247399/primary.txt). Do `P = load("primary.txt")`. 

According to him Magma finishes instantly on this. So we should eventually find out why this takes ages for us.

**Comment by afkafkafk13** [comment]
> But let me just put another example here which has been sent to me by @simonbrandhorst : [primary.txt](https://github.com/oscar-system/Oscar.jl/files/15247399/primary.txt). Do `P = load("primary.txt")`.
> 
> According to him Magma finishes instantly on this. So we should eventually find out why this takes ages for us.

It is good to have the example in a file, but if it is short enough, please also add it explicitly -- we might want to cross-compare to other systems.

**Comment by HechtiDerLachs** [comment]
> if it is short enough

It is not.

**Comment by simonbrandhorst** [comment]
Magma will compute the following in milliseconds. Oscar does not terminate at all whatever algorithm I choose.
@wdecker 
```
> PolynomialRing(nf,3);            
Polynomial ring of rank 3 over nf
Order: Lexicographical
Variables: $.1, $.2, $.3
> P:=PolynomialRing(nf,3);
>                
> R<x,y,t> :=PolynomialRing(nf,3);
> x;
x
> z
> ;
nf.1
> z*x;
nf.1*x
> f:=-x^3 + ((486*z^11 - 1620*z^10 + 513*z^9 + 3888*z^8 - 4077*z^7 - 2565*z^6 + 5616*z^5 - 1269*z^4 - 3591*z^3 + 1620*z^2 + 675*z - 567)*t^8 + (6696*z^11 - \
17712*z^10 - 432*z^9 + 44712*z^8 - 30024*z^7 - 36720*z^6 + 53352*z^5 + 2808*z^4 - 39960*z^3 + 10800*z^2 + 10368*z - 7344)*t^7 + (2808*z^11 - 10044*z^10 + 17\
172*z^9 + 1080*z^8 - 52488*z^7 + 64044*z^6 + 29484*z^5 - 84024*z^4 + 35208*z^3 + 37044*z^2 - 32076*z - 5832)*t^6 + (11016*z^11 - 48384*z^10 + 63288*z^9 + 65\
664*z^8 - 222696*z^7 + 81648*z^6 + 238248*z^5 - 201960*z^4 - 56376*z^3 + 164592*z^2 - 7560*z - 45360)*t^5 + (12690*z^11 - 93150*z^10 + 118260*z^9 + 171990*z\
^8 - 411750*z^7 - 44280*z^6 + 487890*z^5 - 222750*z^4 - 287820*z^3 + 247590*z^2 + 90180*z - 76680)*t^4 + (1296*z^11 - 37800*z^10 + 41256*z^9 + 86832*z^8 - 1\
39320*z^7 - 98280*z^6 + 151200*z^5 - 20088*z^4 - 151632*z^3 + 23760*z^2 + 50112*z - 7776)*t^3 + (13284*z^11 - 39204*z^10 - 19224*z^9 + 132732*z^8 - 37260*z^\
7 - 183384*z^6 + 110052*z^5 + 78516*z^4 - 152928*z^3 - 25272*z^2 + 41796*z - 9180)*t^2 + (6048*z^11 - 2808*z^10 - 28944*z^9 + 30240*z^8 + 46656*z^7 - 59184*\
z^6 - 11664*z^5 + 63072*z^4 - 15336*z^3 - 28296*z^2 + 7776*z + 2592)*t - 297*z^11 + 1026*z^10 - 3456*z^8 + 2889*z^7 + 3699*z^6 - 5562*z^5 + 81*z^4 + 4590*z^\
3 - 1782*z^2 - 1242*z + 756)*x + y^2 + (7722*z^11 - 22086*z^10 + 3240*z^9 + 50652*z^8 - 38502*z^7 - 40500*z^6 + 59562*z^5 + 4482*z^4 - 45576*z^3 + 8856*z^2 \
+ 15012*z - 6804)*t^12 + (98496*z^11 - 212544*z^10 - 90072*z^9 + 555336*z^8 - 109512*z^7 - 583200*z^6 + 423144*z^5 + 344088*z^4 - 430272*z^3 - 70632*z^2 + 1\
74960*z - 44064)*t^11 + (-223560*z^11 + 733536*z^10 + 90072*z^9 - 2659716*z^8 + 2026620*z^7 + 3154464*z^6 - 4465044*z^5 - 323352*z^4 + 3957336*z^3 - 1499148\
*z^2 - 1261980*z + 763992)*t^10 + (-3447576*z^11 + 7511184*z^10 + 4469040*z^9 - 24927480*z^8 + 8393328*z^7 + 28239408*z^6 - 28654992*z^5 - 10934352*z^4 + 25\
684344*z^3 - 5006664*z^2 - 8851896*z + 3840912)*t^9 + (-3403296*z^11 + 3695868*z^10 + 11826648*z^9 - 21801312*z^8 - 9769248*z^7 + 33295536*z^6 - 15361812*z^\
5 - 25153416*z^4 + 19040832*z^3 + 2238678*z^2 - 8672670*z + 812592)*t^8 + (4041576*z^11 - 18718128*z^10 + 16985376*z^9 + 32168016*z^8 - 60015816*z^7 - 76632\
48*z^6 + 64441656*z^5 - 30965328*z^4 - 37784232*z^3 + 26276400*z^2 + 8659872*z - 11021184)*t^7 + (18053280*z^11 - 49242816*z^10 + 3374784*z^9 + 119968128*z^\
8 - 88202520*z^7 - 97750800*z^6 + 151035192*z^5 + 9475704*z^4 - 111685392*z^3 + 32377968*z^2 + 36442224*z - 19078416)*t^6 + (17546544*z^11 - 38331792*z^10 -\
 13155048*z^9 + 99952056*z^8 - 34218288*z^7 - 90345456*z^6 + 89199792*z^5 + 39875328*z^4 - 68240880*z^3 + 1063368*z^2 + 24871536*z - 5820336)*t^5 + (-181909\
8*z^11 + 11564532*z^10 - 6563106*z^9 - 34937082*z^8 + 42080796*z^7 + 40589748*z^6 - 69748452*z^5 + 4833270*z^4 + 64619694*z^3 - 25145964*z^2 - 20500938*z + \
14105664)*t^4 + (-8464824*z^11 + 19295928*z^10 + 8678016*z^9 - 58692600*z^8 + 20930616*z^7 + 64744704*z^6 - 63535752*z^5 - 26203392*z^4 + 58450032*z^3 - 767\
1024*z^2 - 20609856*z + 8338032)*t^3 + (-1602828*z^11 + 1830924*z^10 + 4247964*z^9 - 7142256*z^8 - 4926420*z^7 + 9102456*z^6 - 1647540*z^5 - 8908056*z^4 + 2\
494800*z^3 + 2839860*z^2 - 1512432*z - 366768)*t^2 + (200232*z^11 - 598752*z^10 + 12960*z^9 + 1662768*z^8 - 1236384*z^7 - 1578528*z^6 + 2214864*z^5 + 97848*\
z^4 - 1799496*z^3 + 498960*z^2 + 505440*z - 283824)*t + 6534*z^11 - 10422*z^10 - 17712*z^9 + 45144*z^8 + 9180*z^7 - 67824*z^6 + 36072*z^5 + 45360*z^4 - 4924\
8*z^3 - 3996*z^2 + 19440*z - 6480
> ;
> f;
-x^3 + (486*nf.1^11 - 1620*nf.1^10 + 513*nf.1^9 + 3888*nf.1^8 - 4077*nf.1^7 - 2565*nf.1^6 + 5616*nf.1^5 - 1269*nf.1^4 - 3591*nf.1^3 + 1620*nf.1^2 + 675*nf.1 -
    567)*x*t^8 + (6696*nf.1^11 - 17712*nf.1^10 - 432*nf.1^9 + 44712*nf.1^8 - 30024*nf.1^7 - 36720*nf.1^6 + 53352*nf.1^5 + 2808*nf.1^4 - 39960*nf.1^3 + 
    10800*nf.1^2 + 10368*nf.1 - 7344)*x*t^7 + (2808*nf.1^11 - 10044*nf.1^10 + 17172*nf.1^9 + 1080*nf.1^8 - 52488*nf.1^7 + 64044*nf.1^6 + 29484*nf.1^5 - 
    84024*nf.1^4 + 35208*nf.1^3 + 37044*nf.1^2 - 32076*nf.1 - 5832)*x*t^6 + (11016*nf.1^11 - 48384*nf.1^10 + 63288*nf.1^9 + 65664*nf.1^8 - 222696*nf.1^7 + 
    81648*nf.1^6 + 238248*nf.1^5 - 201960*nf.1^4 - 56376*nf.1^3 + 164592*nf.1^2 - 7560*nf.1 - 45360)*x*t^5 + (12690*nf.1^11 - 93150*nf.1^10 + 118260*nf.1^9 + 
    171990*nf.1^8 - 411750*nf.1^7 - 44280*nf.1^6 + 487890*nf.1^5 - 222750*nf.1^4 - 287820*nf.1^3 + 247590*nf.1^2 + 90180*nf.1 - 76680)*x*t^4 + (1296*nf.1^11 -
    37800*nf.1^10 + 41256*nf.1^9 + 86832*nf.1^8 - 139320*nf.1^7 - 98280*nf.1^6 + 151200*nf.1^5 - 20088*nf.1^4 - 151632*nf.1^3 + 23760*nf.1^2 + 50112*nf.1 - 
    7776)*x*t^3 + (13284*nf.1^11 - 39204*nf.1^10 - 19224*nf.1^9 + 132732*nf.1^8 - 37260*nf.1^7 - 183384*nf.1^6 + 110052*nf.1^5 + 78516*nf.1^4 - 152928*nf.1^3 
    - 25272*nf.1^2 + 41796*nf.1 - 9180)*x*t^2 + (6048*nf.1^11 - 2808*nf.1^10 - 28944*nf.1^9 + 30240*nf.1^8 + 46656*nf.1^7 - 59184*nf.1^6 - 11664*nf.1^5 + 
    63072*nf.1^4 - 15336*nf.1^3 - 28296*nf.1^2 + 7776*nf.1 + 2592)*x*t + (-297*nf.1^11 + 1026*nf.1^10 - 3456*nf.1^8 + 2889*nf.1^7 + 3699*nf.1^6 - 5562*nf.1^5 
    + 81*nf.1^4 + 4590*nf.1^3 - 1782*nf.1^2 - 1242*nf.1 + 756)*x + y^2 + (7722*nf.1^11 - 22086*nf.1^10 + 3240*nf.1^9 + 50652*nf.1^8 - 38502*nf.1^7 - 
    40500*nf.1^6 + 59562*nf.1^5 + 4482*nf.1^4 - 45576*nf.1^3 + 8856*nf.1^2 + 15012*nf.1 - 6804)*t^12 + (98496*nf.1^11 - 212544*nf.1^10 - 90072*nf.1^9 + 
    555336*nf.1^8 - 109512*nf.1^7 - 583200*nf.1^6 + 423144*nf.1^5 + 344088*nf.1^4 - 430272*nf.1^3 - 70632*nf.1^2 + 174960*nf.1 - 44064)*t^11 + 
    (-223560*nf.1^11 + 733536*nf.1^10 + 90072*nf.1^9 - 2659716*nf.1^8 + 2026620*nf.1^7 + 3154464*nf.1^6 - 4465044*nf.1^5 - 323352*nf.1^4 + 3957336*nf.1^3 - 
    1499148*nf.1^2 - 1261980*nf.1 + 763992)*t^10 + (-3447576*nf.1^11 + 7511184*nf.1^10 + 4469040*nf.1^9 - 24927480*nf.1^8 + 8393328*nf.1^7 + 28239408*nf.1^6 -
    28654992*nf.1^5 - 10934352*nf.1^4 + 25684344*nf.1^3 - 5006664*nf.1^2 - 8851896*nf.1 + 3840912)*t^9 + (-3403296*nf.1^11 + 3695868*nf.1^10 + 11826648*nf.1^9
    - 21801312*nf.1^8 - 9769248*nf.1^7 + 33295536*nf.1^6 - 15361812*nf.1^5 - 25153416*nf.1^4 + 19040832*nf.1^3 + 2238678*nf.1^2 - 8672670*nf.1 + 812592)*t^8 +
    (4041576*nf.1^11 - 18718128*nf.1^10 + 16985376*nf.1^9 + 32168016*nf.1^8 - 60015816*nf.1^7 - 7663248*nf.1^6 + 64441656*nf.1^5 - 30965328*nf.1^4 - 
    37784232*nf.1^3 + 26276400*nf.1^2 + 8659872*nf.1 - 11021184)*t^7 + (18053280*nf.1^11 - 49242816*nf.1^10 + 3374784*nf.1^9 + 119968128*nf.1^8 - 
    88202520*nf.1^7 - 97750800*nf.1^6 + 151035192*nf.1^5 + 9475704*nf.1^4 - 111685392*nf.1^3 + 32377968*nf.1^2 + 36442224*nf.1 - 19078416)*t^6 + 
    (17546544*nf.1^11 - 38331792*nf.1^10 - 13155048*nf.1^9 + 99952056*nf.1^8 - 34218288*nf.1^7 - 90345456*nf.1^6 + 89199792*nf.1^5 + 39875328*nf.1^4 - 
    68240880*nf.1^3 + 1063368*nf.1^2 + 24871536*nf.1 - 5820336)*t^5 + (-1819098*nf.1^11 + 11564532*nf.1^10 - 6563106*nf.1^9 - 34937082*nf.1^8 + 
    42080796*nf.1^7 + 40589748*nf.1^6 - 69748452*nf.1^5 + 4833270*nf.1^4 + 64619694*nf.1^3 - 25145964*nf.1^2 - 20500938*nf.1 + 14105664)*t^4 + 
    (-8464824*nf.1^11 + 19295928*nf.1^10 + 8678016*nf.1^9 - 58692600*nf.1^8 + 20930616*nf.1^7 + 64744704*nf.1^6 - 63535752*nf.1^5 - 26203392*nf.1^4 + 
    58450032*nf.1^3 - 7671024*nf.1^2 - 20609856*nf.1 + 8338032)*t^3 + (-1602828*nf.1^11 + 1830924*nf.1^10 + 4247964*nf.1^9 - 7142256*nf.1^8 - 4926420*nf.1^7 +
    9102456*nf.1^6 - 1647540*nf.1^5 - 8908056*nf.1^4 + 2494800*nf.1^3 + 2839860*nf.1^2 - 1512432*nf.1 - 366768)*t^2 + (200232*nf.1^11 - 598752*nf.1^10 + 
    12960*nf.1^9 + 1662768*nf.1^8 - 1236384*nf.1^7 - 1578528*nf.1^6 + 2214864*nf.1^5 + 97848*nf.1^4 - 1799496*nf.1^3 + 498960*nf.1^2 + 505440*nf.1 - 283824)*t
    + 6534*nf.1^11 - 10422*nf.1^10 - 17712*nf.1^9 + 45144*nf.1^8 + 9180*nf.1^7 - 67824*nf.1^6 + 36072*nf.1^5 + 45360*nf.1^4 - 49248*nf.1^3 - 3996*nf.1^2 + 
    19440*nf.1 - 6480
> J:=JacobianIdeal(f)+Ideal(f);
> PrimaryDecomposition(J);
[
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Non-radical, Primary, Non-prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x + (702*nf.1^11 - 2142*nf.1^10 + 450*nf.1^9 + 5562*nf.1^8 - 5220*nf.1^7 - 4788*nf.1^6 + 9180*nf.1^5 - 306*nf.1^4 - 7092*nf.1^3 + 3222*nf.1^2 + 
            2430*nf.1 - 1746)*t^2 + (-240*nf.1^11 + 672*nf.1^10 + 36*nf.1^9 - 1944*nf.1^8 + 1368*nf.1^7 + 1968*nf.1^6 - 2832*nf.1^5 - 264*nf.1^4 + 2376*nf.1^3
            - 804*nf.1^2 - 780*nf.1 + 504)*t - 21*nf.1^11 + 48*nf.1^10 + 18*nf.1^9 - 138*nf.1^8 + 48*nf.1^7 + 159*nf.1^6 - 159*nf.1^5 - 72*nf.1^4 + 156*nf.1^3
            - 24*nf.1^2 - 60*nf.1 + 30,
        y,
        t^3
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x + 237*nf.1^11 - 498*nf.1^10 - 273*nf.1^9 + 1446*nf.1^8 - 300*nf.1^7 - 1584*nf.1^6 + 1278*nf.1^5 + 816*nf.1^4 - 1161*nf.1^3 - 39*nf.1^2 + 444*nf.1 - 
            84,
        y,
        t + 2*nf.1^10 - 5*nf.1^9 + 11*nf.1^7 - 6*nf.1^6 - 9*nf.1^5 + 11*nf.1^4 + 2*nf.1^3 - 7*nf.1^2 + nf.1 + 2
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x - 60*nf.1^11 + 180*nf.1^10 + 18*nf.1^9 - 588*nf.1^8 + 414*nf.1^7 + 669*nf.1^6 - 891*nf.1^5 - 144*nf.1^4 + 789*nf.1^3 - 240*nf.1^2 - 303*nf.1 + 138,
        y,
        t + 1
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x - 120*nf.1^11 + 354*nf.1^10 - 36*nf.1^9 - 969*nf.1^8 + 843*nf.1^7 + 882*nf.1^6 - 1623*nf.1^5 + 99*nf.1^4 + 1302*nf.1^3 - 618*nf.1^2 - 345*nf.1 + 
            378,
        y,
        t + nf.1^11 - 2*nf.1^10 - 2*nf.1^9 + 8*nf.1^8 - 2*nf.1^7 - 10*nf.1^6 + 10*nf.1^5 + 4*nf.1^4 - 11*nf.1^3 + 3*nf.1^2 + 4*nf.1 - 3
    ]
]
[
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x - 21*nf.1^11 + 48*nf.1^10 + 18*nf.1^9 - 138*nf.1^8 + 48*nf.1^7 + 159*nf.1^6 - 159*nf.1^5 - 72*nf.1^4 + 156*nf.1^3 - 24*nf.1^2 - 60*nf.1 + 30,
        y,
        t
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x + 237*nf.1^11 - 498*nf.1^10 - 273*nf.1^9 + 1446*nf.1^8 - 300*nf.1^7 - 1584*nf.1^6 + 1278*nf.1^5 + 816*nf.1^4 - 1161*nf.1^3 - 39*nf.1^2 + 444*nf.1 - 
            84,
        y,
        t + 2*nf.1^10 - 5*nf.1^9 + 11*nf.1^7 - 6*nf.1^6 - 9*nf.1^5 + 11*nf.1^4 + 2*nf.1^3 - 7*nf.1^2 + nf.1 + 2
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x - 60*nf.1^11 + 180*nf.1^10 + 18*nf.1^9 - 588*nf.1^8 + 414*nf.1^7 + 669*nf.1^6 - 891*nf.1^5 - 144*nf.1^4 + 789*nf.1^3 - 240*nf.1^2 - 303*nf.1 + 138,
        y,
        t + 1
    ],
    Ideal of Polynomial ring of rank 3 over nf
    Order: Lexicographical
    Variables: x, y, t
    Inhomogeneous, Dimension 0, Radical, Prime
    Size of variety over algebraically closed field: 1
    Groebner basis:
    [
        x - 120*nf.1^11 + 354*nf.1^10 - 36*nf.1^9 - 969*nf.1^8 + 843*nf.1^7 + 882*nf.1^6 - 1623*nf.1^5 + 99*nf.1^4 + 1302*nf.1^3 - 618*nf.1^2 - 345*nf.1 + 
            378,
        y,
        t + nf.1^11 - 2*nf.1^10 - 2*nf.1^9 + 8*nf.1^8 - 2*nf.1^7 - 10*nf.1^6 + 10*nf.1^5 + 4*nf.1^4 - 11*nf.1^3 + 3*nf.1^2 + 4*nf.1 - 3
    ]
]

```

**Comment by wdecker** [comment]
Please send me your OSCAR code.

**Comment by HechtiDerLachs** [comment]
The Oscar code is above. You can download the file and load it with the given command.
