### ISSUE TITLE
`are_associated` for ring elements

### ISSUE THREAD

**Issue by flyingapfopenguin** [oscar-system/Oscar.jl#3093]
I wasn't able to find are function testing association of two ring elements.

As I needed this especially for integers and univariate polynomial rings over finite fields, I implemented the following:

```julia
are_associated(x::ZZRingElem, y::ZZRingElem) = (abs(x) == abs(y))

function are_associated(x::fpPolyRingElem, y::fpPolyRingElem)
    check_parent(x,y)
    is_zero_x = is_zero(x)
    is_zero_y = is_zero(y)
    if (is_zero_x && is_zero_y)
        return true
    end
    if (is_zero_x != is_zero_y)
        return false
    end
    return leading_coefficient(x)*y == leading_coefficient(y)*x
end
```

A generic implementation for (euclidean) rings might be:
```julia
unction are_associated(x::T, y::T) where T <: RingElem
    check_parent(x,y)
    is_zero_x = is_zero(x)
    is_zero_y = is_zero(y)
    if (is_zero_x && is_zero_y)
        return true
    end
    if (is_zero_x != is_zero_y)
        return false
    end
    return (is_zero(rem(x, y)) && is_zero(rem(y, x)))
end
```

Because I've no idea where this code would belong Nemo/Flint/AbstractAlgebra, I'm dumping it here. Feel free to modify, simply take or drop it.

**Comment by fieker** [comment]
On Sat, Dec 09, 2023 at 12:49:09PM -0800, Jens Brandt wrote:
> I wasn't able to find are function testing association of two ring elements.
> 
> As I needed this especially for integers and univariate polynomial rings over finite fields, I implemented the following:
> 
> ```julia
> are_associated(x::ZZRingElem, y::ZZRingElem) = (abs(x) == abs(y))
> 
> function are_associated(x::fpPolyRingElem, y::fpPolyRingElem)
>     check_parent(x,y)
>     is_zero_x = is_zero(x)
>     is_zero_y = is_zero(y)
>     if (is_zero_x && is_zero_y)
>         return true
>     end
>     if (is_zero_x != is_zero_y)
>         return false
>     end
>     return leading_coefficient(x)*y == leading_coefficient(y)*x
> end
> ```
> 
> A generic implementation for (euclidean) rings might be:
> ```julia
> unction are_associated(x::T, y::T) where T <: RingElem
>     check_parent(x,y)
>     is_zero_x = is_zero(x)
>     is_zero_y = is_zero(y)
>     if (is_zero_x && is_zero_y)
>         return true
>     end
>     if (is_zero_x != is_zero_y)
>         return false
>     end
>     return (is_zero(rem(x, y)) && is_zero(rem(y, x)))
This is a tricky one.... do we assume that if a division is exact we
have to return a rem of 0? This is not part of the usual euc definition
in text books...
I actually do not know if we assume that or not.

> end
> ```
> 
> Because I've no idea where this code would belong Nemo/Flint/AbstractAlgebra, I'm dumping it here. Feel free to modify, simply take or drop it.

Thanks

**Comment by thofma** [comment]
We could simplify it to `divides(x, y) && divides(y, x)`.

**Comment by flyingapfopenguin** [comment]
@fieker Yes, I was assuming that division is exact (and didn't know a `divides` function exists).

If anyone tells me where this snippet belongs, I can create a PR.

**Comment by lgoettgens** [comment]
I would see the generic implementation in AbstractAlgebra in `src/Rings.jl`. If the method for ZZRingElem is significantly faster, it should go to Nemo to `src/flint/fmpz.jl` (after the function in AA has been released).

**Comment by thofma** [comment]
We should first agree on a name. Maybe `is_associated` would fit better into the Oscar method name landscape?

**Comment by fieker** [comment]
the name will be is_... as there are no are_... functions so far.
