### ISSUE TITLE
macOS CI job times out regularly

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#3136]
For ubuntu, we now have three jobs (short, long, doctests).
On the other hand for macOS, all three of these are combined into one single job. This is unfortunately makes the job no longer succeed in 150 minutes (at least sometimes, re-running helps).
We could either split the job up or increase the allowed time.

**Comment by lgoettgens** [comment]
Any opinions @benlorenz @fingolfin?

**Comment by lgoettgens** [comment]
This is happening regularly now, and e.g. this test timing out blocks the automatic codecov comment as codecov waits for another coverage upload.

**Comment by benlorenz** [comment]
I think we could try splitting the job and see how the macos worker usage turns out. At least for ubuntu the sum of the three jobs usually seems to be a lot less than 150 minutes.

**Comment by lgoettgens** [comment]
I'll cook something up once https://github.com/oscar-system/Oscar.jl/pull/3144 is merged
