### ISSUE TITLE
Quotient of automorphism groups sometimes errors

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3145]
I am computing outer automorphism groups naively as quotient groups, but this sometimes errors:

```julia
julia> begin
         G = small_group(12, 5)
         A = automorphism_group(G)
         H, HtoA = Oscar.inner_automorphism_group(A)
         Q, AtoQ = quo(A, H)
       end
ERROR: Not a known type of group
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] _get_type(G::GAP.GapObj)
   @ Oscar ~/bla/dev/Oscar/src/Groups/types.jl:490
 [3] quo(G::Oscar.AutomorphismGroup{Oscar.PcGroup}, N::Oscar.AutomorphismGroup{Oscar.PcGroup})
   @ Oscar ~/bla/dev/Oscar/src/Groups/sub.jl:861
 [4] top-level scope
   @ REPL[87]:5
```
Works as expect for other groups though:
```julia
julia> begin
         G = small_group(12, 1)
         A = automorphism_group(G)
         H, HtoA = Oscar.inner_automorphism_group(A)
         Q, AtoQ = quo(A, H)
       end
(Pc group of order 2, Hom: aut( <pc group of size 12 with 3 generators> ) -> pc group)
```
CC: @fingolfin @ThomasBreuer

**Comment by ThomasBreuer** [comment]
Given two groups which store underlying GAP groups, `quo` leaves the creation of the quotient to GAP, and then constructs a corresponding Oscar group from it; the type of this Oscar group is determined via `Oscar._get_type`.
(Note that `quo` does not promise which type its result has. In the failing example, the normal subgroup that is factored out is trivial, and then GAP simply returns the given group.)

In the example that fails, the quotient in GAP is a group of automorphisms, which is currently not known to `Oscar._get_type`.

An easy workaround would be to catch the case of a quotient by a trivial group on the Oscar side,
but of course we should support groups of automorphisms in `Oscar._get_type`.

I will provide a pull request that solves the problem.

**Comment by thofma** [comment]
Thanks for looking into this Thomas.
