### ISSUE TITLE
Printing of finite fields

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#3165]
Since https://github.com/oscar-system/Oscar.jl/pull/3153, finite fields of positive characteristic print as
```julia
julia> GF(3)
Finite field of degree 1 over GF(3)

julia> GF(5, 2)
Finite field of degree 2 over GF(5)
```

I think that at least for prime fields we should omit the degree there as it is kind of contradicting in the current printing (`GF(p)` gives an extension over `GF(p)`).

**Comment by JohnAAbbott** [comment]
So how should the value of `GF(3)` be printed out?   Simply as `GF(3)`?  Or something more descriptive such as `Prime finite field of characteristic 3`?

**Comment by lgoettgens** [comment]
Both of these are valid options. I just opened this issue to keep track of the need to change the current state, but without a concrete solution.

Let me ping some more people that might have an opinion/ideas for this. @thofma @fingolfin @fieker

**Comment by mjrodgers** [comment]
I think something like `Finite field with prime order 3` would be good.

**Comment by fingolfin** [comment]
How about 
```
Finite field of order 3
Finite field of order 3^2
```

**Comment by fingolfin** [comment]
and for supercompact `GF(3)` resp. `GF(3,2)`  ? I also like `GF(3^2)` but then if this doesn't work as user input, it would be confusing, so

**Comment by fingolfin** [comment]
people in the meeting here right now at least don't loudly object to my suggestion.... some even seem to agree

**Comment by thofma** [comment]
`GF(3^2)` is working as user input.

But one can also construct an extension `F` of `GF(3^2)` of degree `5`. How should that be printed? I think it should be conveyed by the printing, that it has a different "base field".

**Comment by lgoettgens** [comment]
> But one can also construct an extension `F` of `GF(3^2)` of degree `5`. How should that be printed? I think it should be conveyed by the printing, that it has a different "base field".

That's true. Do you have a suggestion for this?

**Comment by thofma** [comment]
For extensions of $\mathbf{F}_p$ (which will be 99% of the uses):
```
Finite field of degree 2 over GF(3) 
Finite field of order 3^2 # alternative
Prime field of order 3 # in case it is a prime field
GF(3^2) # compact
```
For the other ones:
```
Finite field of degree 5 over GF(3^2)
GF((3^2)^5) # compact, but I don't like it
```
Just some suggestions.

**Comment by JohnAAbbott** [comment]
@thofma is right that `GF(3^10)` can be created in several different ways, but the resulting fields are all isomorphic.  I am not sure what purpose there is to indicating a "base field" when printing out; can anyone clarify?

I am a little more concerned about finite fields whose order/cardinality is greater than `2^63` because a printed form such as `GF(3^44)` **looks like** it should be valid input but would be interpreted unexpectedly by julia (and still give a valid argument to `GF`).  The problem would not arise if the printed form were `GF(ZZ(3)^44)`, but that does impinge upon human readability.  In general, OSCAR does not produce output which is valid as input (sometimes yes, but in general no).

What are the advantages of `GF(3^10)` over `GF(3,10)`?  Or _vice versa_?  I note that `GF(9^5)` works while `GF(9,5)` produces an error.

**Comment by thofma** [comment]
Because I personally think it is odd to have
```
julia> F
Finite field of order 3^10
```
but
```
julia> degree(F)
2
```

**Comment by lgoettgens** [comment]
compromise of the afternoon discussion with @fieker, @thofma, @ThomasBreuer, @JohnAAbbott:
- absolute: `Prime field of characteristic $p` or  `Finite field of characteristic $p$ of degree $k` (dependent on `k = 1` or `k > 1`)
- absolute supercompact: `GF($p)` or `GF($p, $k)` (dependent on `k = 1` or `k > 1`)
- relative: `Finite field of degree $d over $supercompact(basefield)`
- relative supercompact: `GF(2, 2*3)`  for `GF(2,2)[x]/(x^3+x+1)`

**Comment by thofma** [comment]
Oops, I actually missed that we have twice an "of":
```
Finite field of characteristic 3 of degree 2
```
Should the second "of" be an "and"?

**Comment by lgoettgens** [comment]
> Should the second "of" be an "and"?

I have no idea about the grammar here, maybe @JohnAAbbott can say something?

**Comment by JohnAAbbott** [comment]
Yes, "and" is better than  "of" appearing twice.

I notice that in the full printing the order of info in the absolute and relative cases is inverted:
```
Finite field of characteristic 3 and degree 6
Finite field of degree 6 over GF(3)
```
Is this desired/desirable?

**Comment by lgoettgens** [comment]
> Yes, "and" is better than "of" appearing twice.

Thanks

> Is this desired/desirable?

No, not intended.
My new suggestion based on the two things above:

- absolute: `Prime field of characteristic $p` or  `Finite field of degree $k and characteristic $p` (dependent on `k = 1` or `k > 1`)
- absolute supercompact: `GF($p)` or `GF($p, $k)` (dependent on `k = 1` or `k > 1`)
- relative: `Finite field of degree $d over $supercompact(basefield)`
- relative supercompact: `GF(2, 2*3)`  for `GF(2,2)[x]/(x^3+x+1)`

Can people leave a :+1: if they are fine with this?
