### ISSUE TITLE
Something with automorphism groups hanging

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3167]
The following hangs for me:
```julia
julia> F = free_group(["x", "y"])
Free group of rank 2

julia> (x, y) = gens(F);

julia> Q, = quo(F, [x^-3*y^-3*x^-1*y*x^-2,  x*y^-1*x^-1*y*x^-1*y^-1*x^3*y^-1, x*y^-1*x^-1*y^2*x^-2*y^-1*x^2]);

julia> A = automorphism_group(Q);

julia> H, HtoA = inner_automorphism_group(A);

julia> Q, AtoQ = quo(A, H);

julia> [preimage(AtoQ, q) for q in Q] #this will hang forver
```
Any idea @ThomasBreuer? I tried adding `check = false`, but it does not exist for the argument types.

**Comment by ThomasBreuer** [comment]
`Q` has order 16.
I can reproduce that the `primage` computation for some of the elements takes very long.
This happens inside the GAP function `PreImagesRepresentative`. I will try to find a fix for that.

**Comment by ThomasBreuer** [comment]
@thofma Concerning `check = false`, one can enter `[haspreimage(AtoQ, q, check = false) for q in Q]`.
Currently the documentation for `preimage` suggests this if one wants to omit the membership tests.
If you thinkk that it is better to support `check = false` also for `preimage` then we can easily change this.

#3190 yields already some improvement, but there is still the problem from gap-system/gap/issues/5590.

**Comment by thofma** [comment]
Thanks for the explanation. I don't mind too much about the `check = false`. I was just wondering about the inconsistency in the keyword arguments of `preimage/haspreimage`.

**Comment by thofma** [comment]
Should we close this and keep the discussion/progress at #3171?

**Comment by ThomasBreuer** [comment]
@thofma 
> Should we close this and keep the discussion/progress at #3171?

Yes, #3171 is more general.
