### ISSUE TITLE
Automorphisms of groups issue

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3171]
I have been using the automorphism groups of groups more extensively lately and noticed a few things. I will use the following as an example:
```julia
julia> F = free_group(["x", "y"]);

julia> x, y = gens(F);

julia> Q, = quo(F, [x^-3*y^-3*x^-1*y*x^-2,  x*y^-1*x^-1*y*x^-1*y^-1*x^3*y^-1, x*y^-1*x^-1*y^2*x^-2*y^-1*x^2]);

julia> A = automorphism_group(Q);

julia> auts = collect(A)
16-element Vector{AutomorphismGroupElem{FPGroup}}:
 IdentityMapping( <fp group of size 16 on the generators [ x, y ]> )
 [ x*y^-18, y^7 ] -> [ x, y ]
 [ x*y^-12, y^5 ] -> [ x, y ]
 [ x*y^-102, y^35 ] -> [ x, y ]
 [ (y^-4*x^-1)^2*y^-1, y*x*y^3 ] -> [ x, y ]
 [ (y^-10*x^-1)^2*y^-7, y^7*x*y^3 ] -> [ x, y ]
 [ (y^-8*x^-1)^2*y^-5, y^5*x*y^3 ] -> [ x, y ]
 [ (y^-38*x^-1)^2*y^-35, y^35*x*y^3 ] -> [ x, y ]
 [ x*y^8, y^5 ] -> [ x, y ]
 [ x*y^-82, y^35 ] -> [ x, y ]
 [ x*y^-52, y^25 ] -> [ x, y ]
 [ x*y^-502, y^175 ] -> [ x, y ]
 [ (y^-28*x^-1)^2*y^-5, y^5*x*y^23 ] -> [ x, y ]
 [ (y^-58*x^-1)^2*y^-35, y^35*x*y^23 ] -> [ x, y ]
 [ (y^-48*x^-1)^2*y^-25, y^25*x*y^23 ] -> [ x, y ]
 [ (y^-198*x^-1)^2*y^-175, y^175*x*y^23 ] -> [ x, y ]
```

1. Why are the automorphisms "the other way around" aka why are they not `[x, y] -> ...`? At the moment, I can't even evaluate those automorphisms. It will hang for some of them:
  ```julia
julia> for i in 1:length(auts)
         @info i, auts[i](gen(Q, 1))
       end
[ Info: (1, x)
[...]
[ Info: (13, x*y*(y^2*x)^3*y^2) # all fine so far, but it is hanging for i = 14
```

  If I instead use the inverses, everything works fine:

```julia
julia> for i in 1:length(auts)
         @info i, inv(auts[i])(gen(Q, 1))
       end
[ Info: (1, x)
[...]
[ Info: (16, (y^-198*x^-1)^2*y^-175) # all fine
```
2. Is there are a reason those words are so large? My group has order `16` and `[ (y^-198*x^-1)^2*y^-175, y^175*x*y^23 ] -> [ x, y ]` looks quite daunting!
3. <s>`preimage(auts[1], gen(Q, 1))` is missing.</s> (fixed by @ThomasBreuer in #3190)

CC: @ThomasBreuer 

P.S.: I am happy to hear that there is nothing to do about 1) and 2), since it might be just the way things are with these objects.

**Comment by ThomasBreuer** [comment]
@thofma 3. will be fixed by #3190.
Concerning 1. and 2., I have opened an issue for GAP, see gap-system/gap/issues/5590.

**Comment by thofma** [comment]
I guess f.p. groups are just hard, and what might look easy in my small example, usually does not scale to arbitrary f.p. groups. I think we can close this issue. I will try to change to a different representation of my group as early as possible in my code.

**Comment by ThomasBreuer** [comment]
My interpretation of Alexander's comment in the discussion of gap-system/gap/issues/5590 is that in general the user should switch from the given f.p. group to a nicer representation when (s)he knows that computations are needed that do not need the f.p. data. This would look as follows.
```
julia> F = free_group(["x", "y"]);

julia> x, y = gens(F);

julia> rels = [x^-3*y^-3*x^-1*y*x^-2,
               x*y^-1*x^-1*y*x^-1*y^-1*x^3*y^-1,
               x*y^-1*x^-1*y^2*x^-2*y^-1*x^2];

julia> Q, = quo(F, rels);

julia> iso = isomorphism(PermGroup, Q);

julia> PQ = codomain(iso);

julia> PA = automorphism_group(PQ);

julia> gen1 = iso(gen(Q, 1));

julia> Pauts = collect(PA);

julia> for i in 1:length(Pauts)
         @info i, preimage(iso, Pauts[i](gen1))
       end
[ Info: (1, x)
[ Info: (2, x^-1)
[ Info: (3, x^-3)
[ Info: (4, x^3)
[ Info: (5, y)
[ Info: (6, y^-1)
[ Info: (7, y*x^-4)
[ Info: (8, x^4*y^-1)
[ Info: (9, x)
[ Info: (10, x^-1)
[ Info: (11, x^-3)
[ Info: (12, x^3)
[ Info: (13, y)
[ Info: (14, y^-1)
[ Info: (15, y*x^-4)
[ Info: (16, x^4*y^-1)
```
Alternatively, if one knows that the f.p. group is small enough then one can use the hint to use `GAP.Globals.SetReducedMultiplication`.
```
julia> F = free_group(["x", "y"]);

julia> x, y = gens(F);

julia> rels = [x^-3*y^-3*x^-1*y*x^-2,
               x*y^-1*x^-1*y*x^-1*y^-1*x^3*y^-1,
               x*y^-1*x^-1*y^2*x^-2*y^-1*x^2];

julia> Q, = quo(F, rels);

julia> GAP.Globals.SetReducedMultiplication(Q.X)   #  "Yes, I really want to work with Q."

julia> A = automorphism_group(Q);

julia> auts = collect(A);

julia> for i in 1:length(auts)
         @info i, auts[i](gen(Q, 1))
       end
[ Info: (1, x)
[ Info: (2, x^-1)
[ Info: (3, x^-3)
[ Info: (4, x^3)
[ Info: (5, y^-1*x^-2)
[ Info: (6, y*x^2)
[ Info: (7, y)
[ Info: (8, y^-1)
[ Info: (9, x)
[ Info: (10, x^-1)
[ Info: (11, x^-3)
[ Info: (12, x^3)
[ Info: (13, y^-1*x^-2)
[ Info: (14, y*x^2)
[ Info: (15, y)
[ Info: (16, y^-1)
```

**Comment by thofma** [comment]
Yes, I will go via this route, thanks. Still strange, that everything is stored as `[.., ..] -> [x, y]` and not the other way around.
