### ISSUE TITLE
(minor) DOCUMENTATION  mistake for `divisible`

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#3178]
**Describe the bug**
Documentation for `divisible(x,y)` incorrectly says that `x \neq 0` is required; should be `y \neq 0` (but one could argue that `divisible(1,0)` should return `false`; personally, I prefer an error here)
I notice that there is also `is_divisible_by`; does this mean that `divisible` is obsolete?  I also note that `is_divisible_by` produces no error if the second argument is 0.

**To Reproduce**
Steps to reproduce the behaviour, please provide a code snippet that triggers
the bug.
```
using Oscar
?divisible
```

**Expected behaviour**
Correct description of `divisible`, and ideally a cross-ref to `is_divisible_by` (and maybe a cross-ref back from `is_divisible_by`?)

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.14.0 - #master, 999cc8e46f -- 2024-01-10 17:52:04 +0000
...
```

**Additional context**
No doubt there are many such minor mistakes in the manual.  It'll be no fun finding them (nor correcting them), but it is important that the release 1.0 have good, reliable documentation.  I actually found `divisible` using the documentation on the website (because I did not want to clutter up my julia window).

**Comment by fieker** [comment]
On Thu, Jan 11, 2024 at 06:06:46AM -0800, JohnAAbbott wrote:
> **Describe the bug**
> Documentation for `divisible(x,y)` incorrectly says that `x \neq 0` is required; should be `y \neq 0` (but one could argue that `divisible(1,0)` should return `false`; personally, I prefer an error here)
> I notice that there is also `is_divisible_by`; does this mean that `divisible` is obsolete?  I also note that `is_divisible_by` produces no error if the second argument is 0.
> 
> **To Reproduce**
> Steps to reproduce the behaviour, please provide a code snippet that triggers
> the bug.
> ```
> using Oscar
> ?divisible
> ```

This is AA I think. The point is that divisible(a,b) makes it hard to
guess/ see what is tested: a divdes b or the other way round.
is_dividible_by was added to clarify this.

I'd say divisible should/ could go
