### ISSUE TITLE
Unexpected behaviour in `(::MPolyRing)(::MPolyRingElem)`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#3193]
This was found while experimenting in OSCAR with @oskarhenriksson.  The following should either return `x+y` or raise an error:

```
julia> Qxy,(x,y) = QQ["x","y"]
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> f = x+y
x + y

julia> Qt,t = rational_function_field(QQ,"t")
(Rational function field over QQ, t)

julia> Qtxy,(x,y) =Qt["x","y"]
(Multivariate polynomial ring in 2 variables over rational function field, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}[x, y])

julia> Qtxy(f)
t

```

**Comment by thofma** [comment]
Looking into it

**Comment by thofma** [comment]
Fixed in https://github.com/Nemocas/Nemo.jl/pull/1620, but we first need to check if someone is using this. It will give an unhelpful error in the future.

**Comment by thofma** [comment]
And of course someone is using this, so it will take a bit to adjust this.

**Comment by lgoettgens** [comment]
the fix will propagate to Oscar in the next week or so
