### ISSUE TITLE
`right_transversal` should return a "smart" transversal object (wrapping the corresponding "smart" object produced by GAP) instead of coercing into a `Vector`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3197]

**Comment by ThomasBreuer** [comment]
So the idea is to create a new type for the right transversal objects, and to support element access, `findfirst`, and `length` for this type?
Also the underlying GAP objects do not have more functionality.

(Oscar has also `left_transversal`, this should be handled analogously.)
