### ISSUE TITLE
Add convenience method for producing free modules over rings?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3198]
We could add such a method to AA; should we?
```
julia> Base.:^(R::Ring, n::Int) = free_module(R, n)

julia> ZZ^2
Free module of rank 2 over integer ring
```

**Comment by fieker** [comment]
I'd argue against it as it is ambigous. Depending on context
  - O^2 -> direct_product (with our without maps?)
  - free_module
  - subset of squares
  - subsets of products of length 2
  - the square of the object
which is the reason it is not here - I already had it once
