### ISSUE TITLE
Restore printing of symmetric group as `Sym(n)` 

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3225]
It was requested that a group created by `symmetric_group(n)` is again printed as `Sym(n)` (or perhaps some variation of that); and similar for `alternating_group(n)` and perhaps some other "constructors".

This is only for groups created this way; if a group is e.g. an alternating group "by chance" then we don't check for that (well, if the GAP filter `HasIsNaturalSymmetricGroup` is set then we can of course use it, but we shouldn't trigger a computation).

This is consistent with how e.g. `GL(3,3)` is printed.

The idea is *not* to use GAP's `Name` attribute, which has its own issues.

**Comment by ThomasBreuer** [comment]
My idea would be that any permutation group with known property `IsNaturalSymmetricGroup` or `IsNaturalAlternatingGroup` is printed as `Sym(n)` or `Alt(n)`, respectively.
And this should hold for all three modes: detailed, one-line, supercompact.

Do we have a general solution for the problem that these names should *not* be put to lowercase when they are printed, in spite of a `Lowercase()` call, like for `GL(n, q)`?

**Comment by thofma** [comment]
Yes, you can print a `LowercaseOff()`, see https://github.com/oscar-system/Oscar.jl/pull/3226.

**Comment by ThomasBreuer** [comment]
Yes, I see. Thanks.
