### ISSUE TITLE
Implement `stabilizer` for (transitive?) G-sets

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3259]
I would expect `stabilizer(gset)` to return the stabilizer of `representative(gset)` with respect to the action.

Moreover, I would expect it to cache that stabilizer.

This way it would be a very natural fit for e.g. representing conjugacy classes, or the result of orbit-stabilizer computations

This mirrors the GAP function `StabilizerOfExternalSet` 

One might perhaps restrict this to transitive G-sets, though technically there is no reason as long as we are clear what it means.

See also issue #108

**Comment by fingolfin** [comment]
@ThomasBreuer @mjrodgers it would be great if you could resolve this feature request

**Comment by mjrodgers** [comment]
If the action is not transitive, then we could have different results depending on which representative is chosen. How should this be handled in this case?

**Comment by ThomasBreuer** [comment]
As Max wrote, `representative(gset)` is the reference point for `stabilizer(gset)`.
Besides that, I think `stabilizer(gset, pnt)` can be supported, without caching.

(Jens Brandt @flyingapfopenguin had talked to me about this feature just an hour ago. I will provide a pull request.)

**Comment by mjrodgers** [comment]
Yes, I guess I understand that `gset` will have some order put on it in the background and then this will return `stabilizer(gset, gset[1])` but I guess I am just uncomfortable that the representative could be different depending on various factors that could decide what the reference point is. But if this is consistent with GAP then I suppose there is no issue.

**Comment by lgoettgens** [comment]
I would already be happy with `stabilizer(gset)` only for transitive G-sets, and `stabilizer(gset, pnt)` for the general case.
