### ISSUE TITLE
Turn conjugacy classes of elements and subgroups into G-sets

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3261]
See also issue #108.

**Comment by fingolfin** [comment]
@ThomasBreuer we discussed this before....

@mjrodgers maybe once you are ready with the G-modules (I hope to see a first draft PR from you soonish?), you can coordinate with @ThomasBreuer to see whether and how you can work together on the G-sets stuff, too? We have a bunch of older issues on this but I've been opening smaller new issues in the hopes that this will make it easier to get started with at least some of them...

**Comment by ThomasBreuer** [comment]
Concerning the conjugacy classes (the title of the issue), I can change the implementation in the same spirit as the right cosets.

**Comment by fingolfin** [comment]
@ThomasBreuer is this resolved now? If so please close the issue, if not, please comment what you think is missing

**Comment by ThomasBreuer** [comment]
Yes, I think this is resolved now.
