### ISSUE TITLE
`Int.(RayVector{QQFieldElem})` and `ZZ.(RayVector{QQFieldElem})` return `RayVector{QQFieldElem}`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#3275]
Both `RayVector` and `PointVector` currently cannot be cast to an integer (this is for example relevant when trying to use the vertices of a Newton polytope as exponent vectors of a polynomial):

```
julia> r = first(rays(positive_hull([[1,2,3]])))
3-element RayVector{QQFieldElem}:
 1
 2
 3

julia> Int.(r)
3-element RayVector{QQFieldElem}:
 1
 2
 3

julia> ZZ.(r)
3-element RayVector{QQFieldElem}:
 1
 2
 3

julia> v = first(vertices(convex_hull([[1,1,1]])))
3-element PointVector{QQFieldElem}:
 1
 1
 1

julia> Int.(v)
3-element PointVector{QQFieldElem}:
 1
 1
 1

julia> ZZ.(v)
3-element PointVector{QQFieldElem}:
 1
 1
 1

```

**Comment by joschmitt** [comment]
For what it's worth, using `map` works:
```
julia> r = first(rays(positive_hull([[1,2,3]])))
3-element RayVector{QQFieldElem}:
 1
 2
 3

julia> map(Int, r)
3-element Vector{Int64}:
 1
 2
 3

julia> map(ZZ, r)
3-element Vector{RingElem}:
 1
 2
 3

julia> v = first(vertices(convex_hull([[1,1,1]])))
3-element PointVector{QQFieldElem}:
 1
 1
 1

julia> map(Int, v)
3-element Vector{Int64}:
 1
 1
 1

julia> map(ZZ, r)
3-element Vector{RingElem}:
 1
 2
 3
```
Although it seems like this could be improved as the return type for `ZZ` is not really precise.

**Comment by thofma** [comment]
I don't quite understand. Is the aim to turn it into a `Vector` or change it into some `RayVector` with different type?

**Comment by YueRen** [comment]
I'm not 100% sure myself, I just found it unintuitive that the type of the entries did not change.  Under the assumption that `PointVector` and `RayVector` should behave like `Vector`, I was expecting `RayVector{Int}`.

**Comment by benlorenz** [comment]
I think this should work and I think there is something slightly wrong in the broadcasted implementation for these vectors, maybe @alexej-jordan has an idea?

**Comment by alexej-jordan** [comment]
Broadcasting is indeed faulty for these types. Doing some checks I have also discovered another (semi-related) issue. I think I fixed both and will prepare a PR shortly.
