### ISSUE TITLE
(Regression) `dot(Vector{QQFieldElem},Vector{Int})` errors

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#3277]
(Please close if already fixed with https://github.com/oscar-system/Oscar.jl/issues/3204.)

Computing dot products of the form `dot(Vector{QQFieldElem},Vector{Int})` used to work (not sure how long ago), and is for example used [in the `initial` command](https://github.com/oscar-system/Oscar.jl/blob/e75fc82eb3a1fa19abe05134fbbf1e0b9e7e312b/src/TropicalGeometry/initial.jl#L57), but now gives an error. 

For comparison, `dot(Vector{QQFieldElem},Vector{ZZRingElem})` still works.

Discovered together with @YueRen. 

```
julia> dot(QQ.([1,2,3]),[1,2,3])

MethodError: no method matching iterate(::QQFieldElem)

Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen})
   @ Base range.jl:880
  iterate(::Union{LinRange, StepRangeLen}, ::Integer)
   @ Base range.jl:880
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}}
   @ Base dict.jl:698
  ...

Stacktrace:
 [1] dot(x::QQFieldElem, y::Int64)
   @ LinearAlgebra [~/.julia/juliaup/julia-1.9.4](https://file+.vscode-resource.vscode-cdn.net/Users/dhb306/Dropbox/Apps/ShareLaTeX/Tropical%20count%20--%20Report/code/~/.julia/juliaup/julia-1.9.4)+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:848
 [2] dot(x::Vector{QQFieldElem}, y::Vector{Int64})
   @ LinearAlgebra [~/.julia/juliaup/julia-1.9.4](https://file+.vscode-resource.vscode-cdn.net/Users/dhb306/Dropbox/Apps/ShareLaTeX/Tropical%20count%20--%20Report/code/~/.julia/juliaup/julia-1.9.4)+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:886
 [3] top-level scope
   @ In[314]:1

```

**Comment by thofma** [comment]
We should probably add some very generic `LinearAlgebra.dot(x::RingElem, y::RingElem) = x * y` method + some other signatures in AbstractAlgebra.

**Comment by YueRen** [comment]
As Oskar mentioned, this is breaking the `initial` function of OSCAR. The reason my tests did not catch it is because all weight vectors are integral.

**Comment by thofma** [comment]
I'll have a look later today.

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1593

**Comment by thofma** [comment]
If you `]up`, it should be working again.
