### ISSUE TITLE
Revised interface for homogenization

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#3307]
**Is your feature request related to a problem? Please describe.**
Currently homogenization may or may not specify the codomain.  If the codomain (parent) is not given then a new ring is created (and not cached) for each homogenization operation; so the resulting homogenized polynomials cannot be interoperated (similarly for ideals). 

Bad things happen if homogenization into the same codomain is performed but specifying different "position" for homogenizing variable: then the variables in the homogenized polynomial are "scrambled"

```
# Homogenization problem

# Default position for homogenizing variable is "after the last"
# All works well here:
P,(x,y,z) = polynomial_ring(QQ, ["x", "y", "z"]);
f = x - y^2;
fh = homogenization(f, "w")
Ph = parent(fh)    # variables are x, y, z, w
homogenization(f, Ph)
ans == fh  # --> true

# Problems arise if we use non-default position to create the
# extended polynomial ring, and then try to use default position
# when homogenizing into the extended ring
fh1 = homogenization(f, "w"; pos=1) # NON DEFAULT POSITION
Ph1 = parent(fh1)  # variables are w, x, y, z

homogenization(f, Ph1) # homogenize into Ph1 but with DEFAULT position
# Last result is weirdly wrong: all variables are "shifted by 1"
```

**Describe the solution you'd like**
A reasonable suggestion is for homogenization to be performed by
a ``homogenizer``, a map from one polynomial ring to another
(note that the map is not a ring homomorphism).

The above example might then be achieved using code similar to the
following:
```
P,(x,y,z) = polynomial_ring(QQ, ["x", "y", "z"]);
f = x - y^2;

H = homogenizer(P)   # by default the new variable is at the end
fh = H(f)
Ph = parent(fh)      # also codomain of map H
#NOT PERMITTED  homogenization(f, Ph)

H1 = homogenizer(P,1)  # new variable appears in position 1
fh1 = H1(f)
Ph1 = parent(fh1)   # also codomain of map H1
#NOT PERMITTED  homogenization(f, Ph1)
```

For ideals, it should be possible to have an interface similar to
```
I = ideal(f)
H(I)  # the homogenization of the ideal I; an ideal in Ph

H1(I) # another homogenization of the ideal I; an ideal in Ph1
```

**Describe alternatives you've considered**
There is a workaround where the caller must always specify the position when homogenizing; and specifying a wrong position will lead to a garbled result (but no error).

I do not currently have any other alternatives.

**Additional context**

No other context.

**Comment by jankoboehm** [comment]
We should keep in mind that at some point we might want to also specify a weight to the homogenization variable which not one. We would also want to specify a name in addition to the position. So perhaps we should use keyword arguments?

**Comment by JohnAAbbott** [comment]
We could indeed specify weights for the homogenizing variables.  I presume we would want that the determinant of the matrix of these weights is non-zero?  If the determinant is not invertible then there may be some polynomials which cannot be homogenized.  If the lattice generated by the degrees/weights of the non-homogenizing variables is a sublattice of that generated by the degrees/weights of the homogenizing variables then we can homogenize any polynomial (with some careful handling of "negative degrees").  I propose ignoring this generalization until after OSCAR 1.0.  Is there a genuine use-case?

**Comment by JohnAAbbott** [comment]
**Quick question:** do we want to be able to apply a homogenizer to a list, or it is sufficient just use Julia broadcasting?
```
L = [x^2+y, x+y^2];
Lh = H(L);     # Current prototype offers this
Lh2 = H.(L);  # using Julia broadcasting...
```

**Comment by JohnAAbbott** [comment]
This has been settled by PR #3344
