### ISSUE TITLE
MINOR/LOW-PRIORITY: unhelpful compact/supercompact printing of Groebner basis

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#3322]
**Describe the bug**
It is unhelpful to print ``with elements...``:  see the recorded output immediately below
```
Dict{MonomialOrdering, Oscar.IdealGens{QQMPolyRingElem}} with 1 entry:
  degrevlex([x, y]) => Gröbner basis with elements…
```
**To Reproduce**
Steps to reproduce the behaviour, please provide a code snippet that triggers
the bug.
```
using Oscar
P, (x,y) = polynomial_ring(QQ, ["x", "y"]);
I = ideal([x,y]);
groebner_basis(I)
I.gb
```

**Expected behavior**
I suggest either simply  ``Gröbner basis`` or maybe ``Gröbner basis with 2 elements``.
It would also be helpful to indicate a corresponding monomial ordering, but that might not be compact, so should probably only be given when printing out with maximum details (if at all).

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. 
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.15.0-DEV - #master, a91222cd18 -- 2024-02-05 21:24:09 +0000
...
```

**Additional context**
**LOW PRIORITY**
I wonder if similar behaviour occurs in other analogous contexts?

**Comment by joschmitt** [comment]
I guess this is (one of the many...) special cases of #2166. There is just one `show` function for `IdealGens` which basically does what is nowadays called "detailed mode".
