### ISSUE TITLE
Deprecation handling before the 1.0 release

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#3356]
How do we wanna handle the accumulated years of deprecations that accumulated here and in Hecke/Nemo/AA/...?

Before the 1.0 release would be a good point to remove most of them, as the next possibility would be the 2.0 release. I think that all deprecations that have been there at the last (0.14.0) release could and should be removed before 1.0.
They no longer represent the way we want people to interact with Oscar.

What do others think?

**Comment by benlorenz** [comment]
I also think we should remove most of the deprecations, at least everything that was marked as deprecated in latest release 0.14.0. But it would probably be ok to also remove some of the more recent deprecations.

**Comment by lgoettgens** [comment]
> I also think we should remove most of the deprecations, at least everything that was marked as deprecated in latest release 0.14.0. But it would probably be ok to also remove some of the more recent deprecations.

One common practice in the julia world would be to release an additional version 0.15.0 right before the 1.0 release, and to include all upcoming deprecations in 0.15.0 and then just remove all deprecations between 0.15.0 and 1.0. This way, users of Oscar can get a smooth process while upgrading.

**Comment by micjoswig** [comment]
> One common practice in the julia world would be to release an additional version 0.15.0 right before the 1.0 release, and to include all upcoming deprecations in 0.15.0 and then just remove all deprecations between 0.15.0 and 1.0. This way, users of Oscar can get a smooth process while upgrading.

I think another 0.15.0 release is not really necessary.  After all 0.14.0 is from January only.  Let's focus on v1.0.  After all, creating a release is not something which comes for free.

But, generally, the idea is not bad.  Maybe keep in mind for v2.0.

**Comment by lgoettgens** [comment]
obsolete
