### ISSUE TITLE
G-sets: define and document an interface for getting group,domain,action

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3370]
$G$-sets in OSCAR represent group actions. That is, given an action $f:\Omega\times G\to \Omega$, they capture the acting group $G$, the domain $\Omega$ and the action "function" $f$.

I think there should thus be a documented way to get to these components that works for all $G$-sets. It should be explained on <https://docs.oscar-system.org/dev/Groups/action/#G-Sets>.

Current status:

- `acting_group`
  - [x] exists
  - [x] exported
  - [ ] docstring
- `action_function`
  - [x] exists
  - [ ] exported   
  - [ ] docstring
- `domain` (or `action_domain` or ...?)
  - [ ] exists
  - [ ] exported
  - [ ] docstring

(We can of course also change some or all of these names).

BTW @ThomasBreuer recently added `action_range` on my suggestion (not exported) but that's something else (and perhaps should be renamed `_action_range` as it is somewhat special and internal?)

@ThomasBreuer @mjrodgers thoughts? can you please coordinate and look into it (it is of course also fine if one you handles it alone, just coordinate it)

**Comment by fingolfin** [comment]
Maybe `domain` is a bad idea because the $G$-set itself "is" the domain -- fine by me, then this should still be explained in the manual (and perhaps we can point out that one can call `collect` on a $G$-set to get its elements as a vector)

**Comment by mjrodgers** [comment]
I can make a quick pull request adding simple documentation for `acting_group` and `action_function`.

If I'm understanding correctly, the third method would just return the underlying set? I agree that I would not call this `domain`. Putting something in the manual about using `collect` is a good option, or making an `underlying_set` method?
