### ISSUE TITLE
Add `all_perfect_groups`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3376]
We have small groups, primitive groups, transitive groups, but somehow we forgot the perfect groups?

**Comment by lgoettgens** [comment]
There is https://github.com/oscar-system/Oscar.jl/blob/master/src/Groups/libraries/perfectgroups.jl which I think does exactly what you want, doesn't it?

**Comment by fingolfin** [comment]
Ah, I was only looking for `all_perfect_groups` which appears to be missing.

**Comment by lgoettgens** [comment]
It is unfortunately not as easy to add this, as there is no corresponding GAP function `AllPerfectGroups` (in contrast to e.g. `AllTransitiveGroups`) that can be used to bootstrap this.

**Comment by fingolfin** [comment]
Sure, but it's not that hard either :-). It's not urgent, we can take care of it later this year, after July perhaps
