### ISSUE TITLE
Support `character(group, values)`?

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#3390]
I would like to have an exported version of the function `Oscar.class_function(::Oscar.GAPGroup, ::Vector{<:QQAbElem})` without the need to work in the abelian closure on the user side. So something like `character(::GAPGroup, ::Vector{<:FieldElem})`. Is there any reason against this?

CC @ThomasBreuer

**Comment by ThomasBreuer** [comment]
Defining a class functions over a field F requires to define how F embeds into a suitable cyclotomic field.
Several such embeddings are possible, we have to make sure that the choices are compatible.

**Comment by fingolfin** [comment]
@joschmitt Would you expect this function to perform input validation? I.e. should it check that the given vector actually defines a character? This problem does not exist for `class_function`, of course.

**Comment by joschmitt** [comment]
I think it should check the input, yes. We can also call it `class_function`. I guess, I haven't really thought about this very well.

**Comment by thofma** [comment]
The interface will be awkward, since one has to construct the character table first to get the right order for the conjugacy classes. But then I could have called `class_funtion(::GAPGroupCharacterTable, values)` directly.

**Comment by joschmitt** [comment]
Yeah, so all of this answers my question why the function does not exist.
