### ISSUE TITLE
build_doc expects that Documenter, DocumenterCitations, DocumenterMarkdown are installed

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#340]
I just tried to run `Oscar.build_doc` and it failed because I did not have all of Documenter, DocumenterCitations, DocumenterMarkdown are installed installed in my environment.

So we can of course simply document this as a requirement. Or perhaps we could change the function to execute a subprocess julia  using the `docs/Project.toml` environment (plus a dev'ed copy of the current Oscar).

**Comment by thofma** [comment]
I don't think we want to execute a subprocess, since one of the advantages now is that the build is running in a "hot" session, with everything already compiled.

We could alternatively activate the environment in `docs/Project.toml` via `Pkg.activate`.

**Comment by fieker** [comment]
On Tue, Mar 16, 2021 at 02:30:58AM -0700, Max Horn wrote:
> I just tried to run `Oscar.build_doc` and it failed because I did not have all of Documenter, DocumenterCitations, DocumenterMarkdown are installed installed in my environment.
> 
> So we can of course simply document this as a requirement. Or perhaps we could change the function to execute a subprocess julia  using the `docs/Project.toml` environment (plus a dev'ed copy of the current Oscar). 
> 
Using a subprocess invalidates part of the point of build_docs - it
would jit everything again all the time...

**Comment by fingolfin** [comment]
@fieker makes sense. Well, this issue was partially motivated by *your* troubles yesterday with missing `DocumenterCitations`; when I tried to replicate, I got even worse issues, as described here. So, I am fine with just asking the user of build_doc to install those packages, but if even you, as the author of the code, are confused by it, perhaps we ought to document this requirement ;-).

(What I actually ended up doing is that I started Julia with `--project=docs` and then `]dev .` and now in that session I run `Oscar.build_doc()`)

**Comment by fieker** [comment]
On Tue, Mar 16, 2021 at 02:38:54AM -0700, Max Horn wrote:
> @fieker makes sense. Well, this issue was partially motivated by *your* troubles yesterday with missing `DocumenterCitations`; when I tried to replicate, I got even worse issues, as described here. So, I am fine with just asking the user of build_doc to install those packages, but if even you, as the author of the code, are confused by it, perhaps we ought to document this requirement ;-).
> 
> (What I actually ended up doing is that I started Julia with `--project=docs` and then `]dev .` and now in that session I run `Oscar.build_doc()`)
> 

Yep it is confusing... I guess the key problem is that there are
different requirements to be put in Project.toml
 - user: does not need all of the documenter tools I hope, so should not
   be a requirement
 - developer: needs them

But it needs docu...but where?
