### ISSUE TITLE
Complete documentation for Group Libraries

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3427]
There are TODO comments on https://docs.oscar-system.org/dev/Groups/grouplib -- clearly those most go in time for 1.0 resp. in time for the Begehung.

**Comment by fingolfin** [comment]
@ThomasBreuer if you have some spare cycles (dunno what you are working on right now, I do not mean to push something else you are busy with down), perhaps you could have a look at this?

**Comment by ThomasBreuer** [comment]
O.k., fits.
