### ISSUE TITLE
`is_conjugate_with_data(Omega::GSet, omega1, omega2)` missing from "Group Actions" section in the manual

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3454]
We already have a docstring for it, but there is no hint about this function on https://docs.oscar-system.org/dev/Groups/action

It should be added.

Going beyond this, we should look through src/Groups/gsets.jl to see if any other things in there are missing from that manual section and should be mentioned there one way or another.

**Comment by fingolfin** [comment]
@mjrodgers can you perhaps take care of at least the initial point?

**Comment by mjrodgers** [comment]
Sure no problem, I will take care of this this evening
