### ISSUE TITLE
Elements of `SubObjectIterator{Union{PointVector, RayVector}}` forget their type after broadcasting

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#3461]
This is just a very minor issue, since I don't think many people will encounter it and it can be worked around easily.  Elements of `SubObjectIterator{Union{PointVector, RayVector}}` forget their type if one scales or shifts them via broadcasting (forget meaning that both `PointVector` and `RayVector` become `AbstractVector`):

```
julia> VR = [0 0 0; 1 0 0; 0 1 0; -1 0 0];

julia> IM = IncidenceMatrix([[1,2,3],[1,3,4]]);

julia> far_vertices = [2,3,4];

julia> L = [0 0 1];

julia> PC = polyhedral_complex(IM, VR, far_vertices, L)
Polyhedral complex in ambient dimension 3

julia> vr = vertices_and_rays(PC)
4-element SubObjectIterator{Union{PointVector{QQFieldElem}, RayVector{QQFieldElem}}}:
 [0, 0, 0]
 [1, 0, 0]
 [0, 1, 0]
 [-1, 0, 0]

julia> first(vr) .* 2 # remembers it is a PointVector
3-element PointVector{QQFieldElem}:
 0
 0
 0

julia> Vector(vr) # elements remember their type
4-element Vector{Union{PointVector{QQFieldElem}, RayVector{QQFieldElem}}}:
 [0, 0, 0]
 [1, 0, 0]
 [0, 1, 0]
 [-1, 0, 0]

julia> vr .* 2 # elements forget their type
4-element Vector{AbstractVector{QQFieldElem}}:
 [0, 0, 0]
 [2, 0, 0]
 [0, 2, 0]
 [-2, 0, 0]

julia> vr .+ Ref([0,0,0]) # elements forget their type
4-element Vector{AbstractVector{QQFieldElem}}:
 [0, 0, 0]
 [1, 0, 0]
 [0, 1, 0]
 [-1, 0, 0]

```

**Comment by benlorenz** [comment]
It seems that this is an issue (feature?) of broadcasting in general, digging through a bit reveals this call:
```julia
julia> Base.promote_typejoin_union(Union{PointVector{QQFieldElem}, RayVector{QQFieldElem}})
AbstractVector{QQFieldElem} (alias for AbstractArray{QQFieldElem, 1})
```

The same happens for plain julia types:
```julia
julia> r = 1:3; v = [1,2,3]; vec = Union{typeof(r), typeof(v)}[r,v]
2-element Vector{Union{UnitRange{Int64}, Vector{Int64}}}:
 1:3
 [1, 2, 3]

julia> vec .* 2
2-element Vector{AbstractVector{Int64}}:
 2:2:6
 [2, 4, 6]
```

But note that the elements itself don't lose the type, only the type parameter of the outer container is different after broadcasting:
```julia
julia> vr2 = vr .* 2
4-element Vector{AbstractVector{QQFieldElem}}:
 [0, 0, 0]
 [2, 0, 0]
 [0, 2, 0]
 [-2, 0, 0]

julia> vr2[1]
3-element PointVector{QQFieldElem}:
 0
 0
 0

julia> vr2[2]
3-element RayVector{QQFieldElem}:
 2
 0
 0
```

**Comment by alexej-jordan** [comment]
`AbstractVector` is an abstract type. In julia that means there can be no instances of that type directly, only of concrete types (which descend from abstract type(s)). `PointVector{T}` and `RayVector{T}` both are derived from `AbstractVector{T}`, and during broadcasting the most precise abstract type, in our case `AbstractVector{QQFieldElem}` is chosen as template parameter of the result. This should not change anything about the data inside, as demonstrated by the previous comment of @benlorenz .
Also, type unions as an abstract type are a bit special. You should be fine with that `AbstractVector` template. But if you really need that specific template parameter for your result I would just suggest enforcing it with something like
```
julia> Vector{Union{PointVector{QQFieldElem}, RayVector{QQFieldElem}}}(vr .* 2)
4-element Vector{Union{PointVector{QQFieldElem}, RayVector{QQFieldElem}}}:
 [0, 0, 0]
 [2, 0, 0]
 [0, 2, 0]
 [-2, 0, 0]
```

**Comment by YueRen** [comment]
Ah, okay.  Thanks for the clarification!  As long as the individual entries
of the vector remember their type then no information is lost.
