### ISSUE TITLE
Add `map_word(g::PcGroupElem, genimgs::Vector)`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3468]
Similar to the method for `FPGroupElem`.

Of course the long-term plan is to have a common parent for PcGroupElem and FpGroupElem and that might also solve that, but since it's not clear to me when that will actually happen, let's do this one ASAP

CC @ThomasBreuer @mjrodgers

**Comment by ThomasBreuer** [comment]
O.k., I will create a pull request for that.

**Comment by lgoettgens** [comment]
Does https://github.com/oscar-system/Oscar.jl/pull/3472 resolve this or is there anything else left to do?

**Comment by ThomasBreuer** [comment]
@lgoettgens Yes, from my point of view, this issue can be closed. Thanks for taking care of this.
