### ISSUE TITLE
Add `regular_gmodule`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3475]
Could be implemented like this:
```julia
function regular_gmodule(F::Field, G::Oscar.GAPGroup)
    FM = free_module(F, order(Int, G))
    gs = gset(G, *, [one(G)])
    return gmodule(G, [hom(FM, FM, permutation_matrix(F, permutation(gs, g))) for g in gens(G)])
end
```
@mjrodgers could you add that in your upcoming 2nd G-modules PR?

**Comment by fieker** [comment]
help?> Oscar.GModuleFromGap.natural_gmodule
  Returns Z[G] and a function f that, when applied to a G-module M will return
  a map representing the action of Z[G] on M:

  f(C) yields the extension of g -> action(C, g)

  The third value returned is a Map between group elements and the index of
  the corresponding module generator.

So I think the functino is already there....
We can (and should) dicuss names and interfaces

**Comment by fingolfin** [comment]
We now have `regular_gmodule(G::Oscar.GAPGroup, R::Ring)` and also `regular_gmodule(::Type{FinGenAbGroup}, G::Oscar.GAPGroup, ::ZZRing)`
