### ISSUE TITLE
Large monomial exponents freezes Oscar

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#3484]
The following commands causes my Oscar (and @YueRen's entire system!) to freeze.

```
K, t = polynomial_ring(QQ,"t")
t^1000000
```

```
K, t = rational_function_field(QQ,"t")
t^(-400000)
```

We don't know why this is the case, because `t^700000` works, and only takes a few seconds.

**Comment by YueRen** [comment]
We encountered the bug when feeding the output of a function into the exponent caused OSCAR to freeze.  

The exact exponent isn't important, it's just weird to me that the timing of `t^N` rises so sharply from one value of `N` to another not-much-bugger value of `N`.

**Comment by fieker** [comment]
This univariate, hense dense. It will kill the memory

**Comment by YueRen** [comment]
Oh, I see.  Then the sudden spike means that the system ran out of memory.

**Comment by YueRen** [comment]
Closed it since we weren't supposed to use `rational_function_field` in the first place for our application.
