### ISSUE TITLE
vector_space_dimension throws error for a 0 dimensional vectorspace

### ISSUE THREAD

**Issue by Syz-MS** [oscar-system/Oscar.jl#3496]
**Describe the bug**
The function vector_space_dimension(A::MPolyQuoRing) throws  an error instead of returning 0 for a zero dimensional vectorspace. 

**To Reproduce**
Create a quotient of a MPolyRing which has vectorspace dimension 0 and compute its vector_space_dimension
```
using Oscar:

julia> R, (x,y) = QQ["x", "y"]
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> Q,_ = quo(R, ideal(R, [1]))
(Quotient of multivariate polynomial ring by ideal (1), Map: multivariate polynomial ring -> Q)

julia> vector_space_dimension(Q)
ERROR: ArgumentError: The ideal must be zero-dimensional
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Hecke/1fdag/src/Assertions.jl:561 [inlined]
 [2] vector_space_dimension(A::MPolyQuoRing{QQMPolyRingElem})
   @ Oscar ~/Oscar.jl/src/Rings/mpoly-affine-algebras.jl:65
 [3] top-level scope
   @ REPL[19]:1
```

**Expected behavior**
The funtion should return 0.

**System (please complete the following information):**
julia> Oscar.versioninfo(full=true)
OSCAR version 1.1.0-DEV - #ms/tjurina, 8aa91c1ea7 -- 2024-03-06 16:30:26 +0100
  combining:
    AbstractAlgebra.jl   v0.40.1
    GAP.jl               v0.10.3
    Hecke.jl             v0.30.2
    Nemo.jl              v0.43.1
    Polymake.jl          v0.11.14
    Singular.jl          v0.22.4
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.9+0
    GAP_jll                 v400.1200.200+9
    Singular_jll            v403.214.1400+0
    libpolymake_julia_jll   v0.11.4+0
    libsingular_julia_jll   v0.43.0+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Official https://julialang.org/ release

**Additional context**
For an  infinte dimensional vectorspace an output like -1 instead of an error would be nice like it was the case for vdim() before it was replaced.

**Comment by joschmitt** [comment]
In the example, `Q` is a polynomial ring over QQ. This is infinite dimensional as a vector space.
This is also what the error says: the modulus is not zero dimensional with respect to Krull dimension.

**Comment by wdecker** [comment]
No, the 1-ideal is divided out.

**Comment by joschmitt** [comment]
Yes, I'm sorry, I misread.

**Comment by joschmitt** [comment]
@Syz-MS Regarding this point:
> **Additional context** For an infinte dimensional vectorspace an output like -1 instead of an error would be nice like it was the case for vdim() before it was replaced.

I personally don't see the reason for this. Right now you can do:
```
if dim(Q) > 0
  # do plan A
else
  n = vector_space_dimension(Q)
  # do plan B
end
```
If `vector_space_dimension` would return `-1` for an infinite dimensional space, you would do (I assume):
```
n = vector_space_dimension(Q)
if n == -1
  # do plan A
else
  # do plan B
end
```
Since the dimension of the modulus of `Q` is cached on the ideal, there should not be much of a performance difference. I feel that the first version makes it clearer what is happening mathematically.
If you don't agree, please open a new issue about this, so that other people can voice their opinion.
