### ISSUE TITLE
Printing of `MonomialBasis` is broken

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#3515]
**Describe the bug**
Printing of `MonomialBasis` is broken. It will
- Break in the middle of words
- Not break consistently
- (Not respect the value of `ENV["COLUMNS"])

**To Reproduce**
This is what happens on my terminal filling half the screen.
```
julia> using Oscar

julia> basis_lie_highest_weight_nz(:C, 3, [1,1,1], [3,2,3,2,1,2,3,2,1])
Monomial basis of a highest weight module
  of highest weight [1, 1, 1]
  of dimension 512
  with monomial ordering degrevlex([x1, x2, x3, x4
  , x5, x6, x7, x8, x9])
over Lie algebra of type C3
  where the used birational sequence consists of the following roots (g
  iven as coefficients w.r.t. alpha_i):
    [0, 0, 1]
    [0, 1, 0]
    [0, 0, 1]
    [0, 1, 0]
    [1, 0, 0]
    [0, 1, 0]
    [0, 0, 1]
    [0, 1, 0]
    [1, 0, 0]
  and the basis was generated by Minkowski sums of the bases of the following highes
  t weight modules:
    [1, 0, 0]
    [0, 1, 0]
    [0, 0, 1]
```

One can also try something like
```
julia> withenv("LINES" => 40, "COLUMNS" => 80, "DISPLAY" => "") do
       basis_lie_highest_weight_nz(:C, 3, [1,1,1], [3,2,3,2,1,2,3,2,1])
       end
```
to see that the `ENV` is not respected.

**Expected behavior**
Lines should be broken consistently at the same length.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.1.0-DEV - #lk/booktests, 668021d9e0 -- 2024-03-14 10:17:22 +0100
  combining:
    AbstractAlgebra.jl   v0.40.1
    GAP.jl               v0.10.3
    Hecke.jl             v0.30.2
    Nemo.jl              v0.43.1
    Polymake.jl          v0.11.14
    Singular.jl          v0.22.4
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.9+0
    GAP_jll                 v400.1200.200+9
    Singular_jll            v403.214.1400+0
    libpolymake_julia_jll   v0.11.4+0
    libsingular_julia_jll   v0.43.0+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_LIBRARY_PATH = :/usr/local/lib:/usr/local/lib
Official https://julialang.org/ release
```

**Additional context**
The show method is in `experimental/BasisLieHighestWeight/src/MonomialBasis.jl`. Nevertheless I suspect that the issue could be in `AbstractAlgebra.jl/src/PrettyPrinting.jl` in the function `_write_line`.

**Comment by thofma** [comment]
Can you clarify if julia itself does something useful in this case? I tried
```
julia> withenv("LINES" => 40, "COLUMNS" => 80, "DISPLAY" => "") do
              "s"^200
       end
```
but I am not sure what the expected result is.

**Comment by lkastner** [comment]
We used this mechanism for testing the book. @benlorenz gave this snippet.
```
julia> withenv("LINES" => 40, "COLUMNS" => 30, "DISPLAY" => "") do
       display(displaysize())
       display(["s"^100])
       end
(40, 30)
1-element Vector{String}:
 "ssssss" ⋯ 88 bytes ⋯ "ssssss"

julia> withenv("LINES" => 40, "COLUMNS" => 60, "DISPLAY" => "") do
       display(displaysize())
       display(["s"^100])
       end
(40, 60)
1-element Vector{String}:
 "sssssssssssssssssssss" ⋯ 58 bytes ⋯ "sssssssssssssssssssss"
```
Probably that is not very relevant, the varying width is the real issue.

**Comment by fingolfin** [comment]
I don't think that Julia printing code honors LINES and COLUMNS in general. The only reference to them I see in Julia itself are in the `displaysize()` method (without arguments). But for `show` method, I think using `displaysize(io)` is the more appropriate solution (which falls back to the result of `displaysize()` in certain situations, but e.g. for `stdout` it will try to get the actual dimension of the terminal.

It may be different if stdout is redirect to a file, I guess then it'd use the fallback? But for interactive use I don't see why it would be used?

**Comment by benlorenz** [comment]
> I don't think that Julia printing code honors LINES and COLUMNS in general. The only reference to them I see in Julia itself are in the `displaysize()` method (without arguments). But for `show` method, I think using `displaysize(io)` is the more appropriate solution (which falls back to the result of `displaysize()` in certain situations, but e.g. for `stdout` it will try to get the actual dimension of the terminal.

This does work fine for overriding the width in the REPL:

```julia
julia> ["s"^200]
1-element Vector{String}:
 "sssssssssssssssssssssssssssssss" ⋯ 139 bytes ⋯ "ssssssssssssssssssssssssssssss"

julia> ENV["COLUMNS"] = 50
50

julia> ["s"^200]
1-element Vector{String}:
 "ssssssssssssssss" ⋯ 169 bytes ⋯ "sssssssssssssss"

julia> ENV["COLUMNS"] = 200
200

julia> ["s"^200]
1-element Vector{String}:
 "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss" ⋯ 18 bytes ⋯ "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
```

(using the `withenv` makes it a bit complicated in the REPL because it is non-obvious to figure out the correct call that replicates REPL-printing within that block)

**Comment by lkastner** [comment]
`displaysize` is already used in `_write_line` in `PrettyPrinting.jl`, so it seems that the intent was to adhere to this. Nevertheless the lines should have the same (maximal) length.

Also
```
julia> ENV["COLUMNS"] = 20
20

julia> ENV["COLUMNS"] 
"20"

julia> using Oscar
  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.0-DEV

julia> ENV["COLUMNS"]
"93"
```
So clearly Oscar also cares.

**Comment by lkastner** [comment]
Since @fingolfin and @lgoettgens are happy with the current behaviour, I want to illustrate, why I need a way to set the output width: We are working on testing that the book examples continue giving the same output. If we cannot control the width of the output, then the tests will fail for everyone using a "non-standard" width terminal. So how should I go about this problem if this approach is not supported? We want to be a bit more strict here than we were within the book testing, so just relaxing a bunch of newlines away is not a viable solution.

**Comment by lgoettgens** [comment]
You can override the displaysize using an `IOContext` around your IO object, see https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext-Tuple{IO,%20Pair}.
Alternatively, you can use something similar to the doctest workaround in `_write_line`, see
https://github.com/Nemocas/AbstractAlgebra.jl/blob/1fd3fe34512666be43cd267574017ebefc604d97/src/PrettyPrinting.jl#L1885-1890.
(Why not even use actual doctests like https://github.com/oscar-system/Oscar.jl/blob/556be5ae27a4fe3d45dfd26e536101e535085d0b/test/Groups/group_characters.jl#L755 for all of this? You may have reasons for this, but that would be the first thing I would have thought about.)

**Comment by lkastner** [comment]
> (Why not even use actual doctests like

Because Documenter is broken https://github.com/JuliaDocs/Documenter.jl/issues/2303 and they refuse to merge/adapt my proposed fix or to fix the issue on their own. The system that splits the jlcons inside of Documenter is different from Julias REPL, in particular, while you can paste the content of a jlcon into Julia and it will just work, this is not true for the same stuff in the jldoctest's. It is subtle, but the differences are there and before we try fixing more stuff there it is easier to use a FakeREPL as in the tests for Julia's own REPL.

**Comment by lgoettgens** [comment]
I think for your concrete use-case, it could work to replace
```julia
repl = REPL.LineEditREPL(FakeTerminals.FakeTerminal(input.out, output.in, err.in, options.hascolor), options.hascolor, false)
```
by
```julia
repl = REPL.LineEditREPL(FakeTerminals.FakeTerminal(input.out, IOContext(output.in, :displaysize => (foo, bar)), err.in, options.hascolor), options.hascolor, false)
```

**Comment by benlorenz** [comment]
> You can override the displaysize using an `IOContext` around your IO object, see [https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext-Tuple{IO,%20Pair}](https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext-Tuple%7BIO,%20Pair%7D). 

Yes, thanks, this seems to work.

Regarding the main issue here, setting the width to 40 gives:
```julia
Monomial basis of a highest weight module
  of highest weight [1, 1, 1]
  of dimensio
  n 512
  with monomial ordering degrevlex(
  [x1, x2, x3, x4, x5, x6, x7, x8, x9])
over Lie algebra of type C3
  w
  here the used birational sequence cons
  ists of the following roots (given as 
  coefficients w.r.t. alpha_i):
    [0, 0, 1]
    [0, 1, 0]
    [0, 0, 1]
    [0, 1, 0]
    [1, 0, 0]
    [0, 1, 0]
    [0, 0, 1]
    [0, 1, 0]
    [1, 0, 0]
  and the basis was generated b
  y Minkowski sums of the bases of the f
  ollowing highest weight modules:
    [1, 0, 0]
    [0, 1, 0]
    [0, 0, 1]
```

**Comment by lkastner** [comment]
Thank you @lgoettgens 

The other issue still remains though.

**Comment by lgoettgens** [comment]
Or, the in my opinion cleaner solution, would be to add `_isbuffer(::Pipe) = true` to AA, or for the time being `AbstractAlgebra.PrettyPrinting._isbuffer(::Pipe) = true` to your file.
`IOBuffers` get skipped in AA in `_write_line` when computing line breaks to not have these kinds of issues, and I see no reason why not to add `Pipe` to this.

**Comment by lkastner** [comment]
I don't see how that solves the issue of the weird line breaks in the terminal.

**Comment by lgoettgens** [comment]
> I don't see how that solves the issue of the weird line breaks in the terminal.

It doesn't. It just fixes it for all code that redirects stdout to a `Pipe`, like your script

**Comment by lkastner** [comment]
I agree that the main issue is not adherence to displaysize. I said this before. You solved that, thank you. However this is not the main point of this issue. I think when someone uses Oscar they should not get weird inconsistent line breaks.

**Comment by lgoettgens** [comment]
> I think when someone uses Oscar they should not get weird inconsistent line breaks.

I agree. I am currently looking into the last changes in the AbstractAlgebra pretty printing code if they changed this in any way, and otherwise trying to create a more minimal example to debug this with.

**Comment by lgoettgens** [comment]
smaller example:
```
julia> struct Foo end

julia> function Base.show(io::IO, ::MIME"text/plain", ::Foo)
         io = AbstractAlgebra.pretty(io)
         print(io, AbstractAlgebra.Indent(), "x"^175)
         print(
           io,
           "\nabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab",
           AbstractAlgebra.Dedent(),
         )
       end

julia> Foo()
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  a
  bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab

julia> displaysize(stdout)
(27, 178)
```
I think that it is no accident that 178 (displaysize) is 175 (number of `x`s) + 2 (indent size) + 1 (characters until weird linebreak). (similar results with resized terminal window)
I am switching over to AA with this to get faster precompilation.
