### ISSUE TITLE
CI, doctest:  occasional differences in output of cellular_primary_decomposition(I) cause error

### ISSUE THREAD

**Issue by afkafkafk13** [oscar-system/Oscar.jl#3529]
**Describe the bug**
doctest(1.9,ubuntu-latest) sometimes, but not always fails in the following test:
in `~/work/Oscar.jl/Oscar.jl/src/Rings/binomial_ideals.jl:845-864`

If the problem occurs, it is due to an extra line of output and  the offending line of output reads
`coeff 22 already initialized`

**To Reproduce**
Look at 
https://github.com/oscar-system/Oscar.jl/actions/runs/8348394603/job/22850192888

**Expected behavior**
CI shows deterministic behaviour.

**Comment by joschmitt** [comment]
This is a debug (?) print coming from Singular which has been removed about two months ago (https://github.com/Singular/Singular/commit/aabd0c258f09541f944044c02f87388aee115919). But this change still needs to trickle down to OSCAR. Usually restarting the CI job helps or you can add a filter for the time being as in https://github.com/oscar-system/Oscar.jl/pull/3479.

**Comment by fingolfin** [comment]
We'll make a new Singular.jl release later today.

**Comment by fingolfin** [comment]
Should be fixed in Singular 0.22.6, if not please reopen.
