### ISSUE TITLE
Do not export SymmetricGroup and some other stuff from AbstractAlgebra

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#353]
It seems Oscar currently exports `SymmetricGroup` from AbstractAlgebra, which leads to some confusion (see issue #345). We shouldn't do that. Not sure where this comes from, I didn't see an obvious "export" -- perhaps it is inherited from Hecke (we export almost all Hecke symbols, I think?)

**Comment by kalmarek** [comment]
In general I think it would be favourable to confine `AA.Perm`, `AA.perm`, `AA.SymmetricGroup` etc. either to `AA`, i.e. don't export it, or simply remove these completely; this would allow to get rid of `gap_perm` (i.e. rename it to `perm`) in Oscar.

grepping for `Perm` or `SymmetricGroup` in `AA` gives just a few results where the underlying array of a perm is used for calls in linear algebra. This could be easily patched using just `Vector{Int}` (and it won't work with Oscar GAP-based perms anyway).
I'm not sure how extensive are these used in Nemo/Hecke though?

@thofma @wbhart @fieker

**Comment by thofma** [comment]
They are used extensively.

**Comment by wbhart** [comment]
I'm not in favour of removing them. But I am perfectly happy for Oscar to not import and use them. There was never any expectation that these would be the permutation types for Oscar. We always made that clear.

The difficulty is going to come when applying permutations to matrices, e.g. row permutations, which both Flint and AA use extensively in LU and many other linear algebra functions. Either Oscar needs to use the AbstractAlgebra types for this, or convert to and from the AA types under the hood when doing permutations of rows, etc.

**Comment by kalmarek** [comment]
If you decide not to remove it, the issue rised by @fingolfin was that these should definitely be not exported. Which implies  the same for all methods requiring `Perm` or `SymmetricGroup`, I guess?

----

not sure about Hecke, but both AA and Nemo "extensive use of `Perm`" boils down to only a few calls (I counted 6 for `AA/src/generic/Matrix.jl` and ~9 in `Nemo`). All of these calls treat `Perm` as vector of integers exclusively. The uses I found could be fully covered by `Base.Vector` (by using the existing `invperm`, `permute!`, `invpermute!`).

@thofma Could you have a look how much of actual `Perm` functionality is used in Hecke? Of course we're interested here only where the actual storage (`p.d`) is used, all others could be easily (and should, on the Oscar level) be replaced by GAP permutations.

**Comment by thofma** [comment]
Hecke has no GAP dependency.

**Comment by fingolfin** [comment]
This was resolved some time ago (IIRC by a PR by @CameronBraunstein )
