### ISSUE TITLE
inconsistent directions of isomorphisms

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#3547]
(The following arose from a discussion with @fieker.)

There are quite a few Oscar functions that take a group and return an isomorphism from or to an isomorphic group, typically one of a prescribed different type.
The problem is whether "from" or "to" shall be used.

The `isomorphism(T, G)` methods for a type `T` and a group `G` return an isomorphism from the given `G` to a new group of type `T`, whereas `Oscar.fp_group_with_isomorphism` and `Oscar.pc_group_with_isomorphism` return an isomorphism from the newly created group to the given one.
(One argument for the latter choice could be that `isomorphism(H, G)`, for two groups, returns an isomorphism from `H` to `G`.)

Technically, the direction of the map does not really matter; one can ask for images or preimages, depending on which direction one gets. Thus there is no "natural" direction, contrary to the situation with embeddings (where the map naturally goes from the small to the large object) or quotients (from the large object to the factor) or maps describing actions (from the given group to something that contains the image, without the need to actually compute this image).

One non-breaking solution would be to keep and deprecate the current `Oscar.fp_group_with_isomorphism` (`Oscar.pc_group_with_isomorphism`), and to introduce recommended `isomorphism_from_fp_group` or `isomorphism_to_fp_group` (`isomorphism_from_pc_group` or `isomorphism_to_pc_group`), such that the function name explains what the result is. (Claus does not like this idea.)

Magma seems to live with the same inconsistencies: `PCGroup(G)` returns a map from `G` to a pc group, whereas `FpGroup(G)` returns a map from an fp group to `G`.

If we keep the current "mixed" situation then the documentation of each function that returns an isomorphism must state which direction the result has.

**Comment by fieker** [comment]
On Wed, Mar 27, 2024 at 07:51:01AM -0700, Thomas Breuer wrote:
> (The following arose from a discussion with @fieker.)
> 
> There are quite a few Oscar functions that take a group and return an isomorphism from or to an isomorphic group, typically one of a prescribed different type.
> The problem is whether "from" or "to" shall be used.
> 
> The `isomorphism(T, G)` methods for a type `T` and a group `G` return an isomorphism from the given `G` to a new group of type `T`, whereas `Oscar.fp_group_with_isomorphism` and `Oscar.pc_group_with_isomorphism` return an isomorphism from the newly created group to the given one.
> (One argument for the latter choice could be that `isomorphism(H, G)`, for two groups, returns an isomorphism from `H` to `G`.)
> 
> Technically, the direction of the map does not really matter; one can ask for images or preimages, depending on which direction one gets. Thus there is no "natural" direction, contrary to the situation with embeddings (where the map naturally goes from the small to the large object) or quotients (from the large object to the factor) or maps describing actions (from the given group to something that contains the image, without the need to actually compute this image).
> 
> One non-breaking solution would be to keep and deprecate the current `Oscar.fp_group_with_isomorphism` (`Oscar.pc_group_with_isomorphism`), and to introduce recommended `isomorphism_from_fp_group` or `isomorphism_to_fp_group` (`isomorphism_from_pc_group` or `isomorphism_to_pc_group`), such that the function name explains what the result is. (Claus does not like this idea.)
> 
> Magma seems to live with the same inconsistencies: `PCGroup(G)` returns a map from `G` to a pc group, whereas `FpGroup(G)` returns a map from an fp group to `G`.
> 
> If we keep the current "mixed" situation then the documentation of each function that returns an isomorphism must state which direction the result has.

And I cannot write any function that, given a group G, reliably get a
map from FP to G (or the other way round)...

I do not mind which direction, but it should be one...

**Comment by ThomasBreuer** [comment]
@fieker Sorry, I do not catch the point.

> And I cannot write any function that, given a group `G`, reliably get a map from FP to `G` (or the other way round)...

As far as I understand, the inconsistency happens w.r.t. different functions. If you use always the same function, for example `isomorphism(FPGroup, G)` then the direction is the same, as far as I see (currently from `G` to a f.p. group).

(I see 14 methods for `isomorphism`:
7 take a type and a group, 3 take two groups, and 4 take something non-groupy.
The 7 relevant `isomorphism(T, G)` methods return an isomorphism from the given group `G` to a group of the prescribed type `T`.)

**Comment by fieker** [comment]
I'd say pick on direction, possibly using a coin of your choice, and we'll
henceforth use this as THE standard

**Comment by joschmitt** [comment]
For context: I introduced the names `fp_group_with_isomorphism`  and `pc_group_with_isomorphism` in #2588 as a stopgap to avoid the names `fp_group` and `pc_group`. I think they can and should just be replaced by the corresponding `isomorphism(::T, ...)` functions. Since they only exist in one experimental directory and are not exported this should not break anything.

**Comment by ThomasBreuer** [comment]
Thanks @joschmitt for the clarification.
I am am already working on modifying `isomorphism` such that `fp_group_with_isomorphism` and `pc_group_with_isomorphism` can use it.

**Comment by fingolfin** [comment]
So with PR #3563 merged, what is left to be done for this issue?

**Comment by ThomasBreuer** [comment]
I think that the documentation should state (where?) that all functions returning isomorphisms should have a consistent direction:
If two groups are given as inputs then the domain is the first given group and the codomain is the second.
If one group is given then the domain is this group, and the codomain is some new group constructed by the function.

**Comment by fingolfin** [comment]
@ThomasBreuer OK so if "only" documentation needs to be added, can you maybe make a quick PR for that and then we close this?

**Comment by ThomasBreuer** [comment]
> if "only" documentation needs to be added, can you maybe make a quick PR for that and then we close this?

Yes.
