### ISSUE TITLE
efficiency problem with `show` methods

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#3593]
The recommended `show` methods for an Oscar object support detailed, one-line, and supercompact printing.
For objects with extremely involved detailed printing, also the one-line printing is very slow.
(Is this known, and thus a feature and not a bug? I am still surprised.)

Consider the following implementation, as recommended in the documentation.
```julia
struct SlowShow
end

# supercompact and one-line printing
function Base.show(io::IO, obj::SlowShow)
  if get(io, :supercompact, false)
    println("# call show (supercompact)")
    # no nested printing
    print(io, "supercompact, for an object with otherwise slow show method")
  else
    # nested printing allowed, preferably supercompact
    println("# call show (one-line)")
    print(io, "one-line, for an object with otherwise slow show method")
  end
end

function Base.show(io::IO, ::MIME"text/plain", obj::SlowShow)
  println("# call show (detailed)")
  sleep(5)  # make this method really slow
  println(io, "text/plain, for an object")  # at least one newline
  print(io, "with slow show method")        # last line without newline
end
```
Then I get the following.
```
julia> using Oscar
[...]

julia> x = Oscar.SlowShow();

julia> x   # this is slow, as expected
# call show (detailed)
text/plain, for an object
with slow show method

julia> [x, x]   # this is also slow
2-element Vector{Oscar.SlowShow}:
# call show (one-line)
# call show (one-line)
 # call show (one-line)
# call show (detailed)
# call show (one-line)
one-line, for an object with otherwise slow show method
 # call show (one-line)
# call show (detailed)
# call show (one-line)
one-line, for an object with otherwise slow show method
```
The output itself is correct.
However, since the method for detailed printing gets called for each `SlowShow` object even if only the one-line method is intended, producing this one-line output is very time consuming.

How can I avoid the expensive calls?

(Also funny: Entering `@time [x, x]` does apparently not count the time that is spent inside the `show` methods. A very short time is reported, and afterwards the `show` method with its `sleep` command gets executed.)

**Comment by thofma** [comment]
```
julia> Base.show(IOContext(stdout, :supercompact => true), SlowShow())
# call show (supercompact)
supercompact, for an object with otherwise slow show method
```

This is very fast for me, so I don't quite follow the statement

> For objects with extremely involved detailed printing, also the one-line printing is very slow.

Are you concerned about the slowness of the one-line printing or the slowness of the `Vector/Array` printing? The Array printing code will call the mime version and check whether it contains new lines. If so, it is just used. Otherwise, the non-mime version is called. For example, if you remove all `println` statements in the methods above, you get

```
julia> [SlowShow(), SlowShow()]
2-element Vector{SlowShow}:
 with slow show method
 with slow show method
```

This is something we cannot change.

**Comment by ThomasBreuer** [comment]
@thofma Thanks for the explanations.

Yes, the point is that printing the array calls, for each entry, the `show` method for the mime version (which may trigger expensive computations).

If this is intended then it is not a bug but a feature.

A workaround is to call `Base.show([x, x])` instead of `[x, x]`.

**Comment by thofma** [comment]
I don't know which objects we are talking about, but I would say that if printing takes too long, then then printing should be adjusted? I don't see how `Base.show([x, x])` fixes that problem, since

```julia
julia> x
[...]
```

still takes 5 seconds.

**Comment by fingolfin** [comment]
> (Also funny: Entering `@time [x, x]` does apparently not count the time that is spent inside the `show` methods. A very short time is reported, and afterwards the `show` method with its `sleep` command gets executed.)

The `@time expr` macro evaluates `expr` and measures the time take by it. It then prints the timing, and returns the evaluated object. Then this is printed by the REPL -- after the timing has completed. So I don't find this surprising at all.

If you want to measure the time for printing, try this:
```julia
@time show(stdout, [x,y])
```
or possibly
```julia
@time show(stdout, MIME("text/plain"), [x,x])
```

**Comment by ThomasBreuer** [comment]
@fingolfin Thanks.

The point is that `show(stdout, [x, x])` is *not* slow (apparently `show` for the mime version is *not* called in this case), whereas just entering `[x, x]` runs the expensive computations.

**Comment by thofma** [comment]
If printing an object a la 
```
julia> x
[...]
```
takes noticeable time and is not instantaneously, I would consider this a bug.

**Comment by ThomasBreuer** [comment]
Currently the "detailed" `show` method for character tables produces formatted output, which takes considerable time if the table is large.
I would be happy to change this, and to show just one or two lines in the "detailed" `show` case.
Which function should then be called in order to get formatted output?
(In GAP, there is `Display` for that purpose, but Julia's `display` has a different meaning.)

**Comment by thofma** [comment]
Can you share a concrete example? I am mainly curious and was wondering, for which OSCAR objects printing takes a noticeable time.

**Comment by ThomasBreuer** [comment]
```
julia> t = character_table("B");  # if you really want to see the formatted output then omit the semicolon

julia> [ t ]   # takes long because internally the detailed printing is called
1-element Vector{Oscar.GAPGroupCharacterTable}:
 character table of B
```

**Comment by thofma** [comment]
I am afraid that there is nothing we can do, sorry.
