### ISSUE TITLE
Add a "caching policy" section to OSCAR dev docs

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3616]
... based on what we just discussed... 

to be written this afternoon

**Comment by joschmitt** [comment]
I'm not sure you could hear me earlier (my microphone/zoom didn't seem to work): I started writing something on caching in #3599 which is possibly wrong or documents things we don't want to document. Maybe you can start from there or decide to throw it away :)

**Comment by fingolfin** [comment]
@joschmitt I've written something fresh for now, but I'd greatly appreciate your input on that PR
