### ISSUE TITLE
Short term TODOs for FTheoryTools

### ISSUE THREAD

**Issue by apturner** [oscar-system/Oscar.jl#3635]
- The parameters `D1` and `D2` parameters for hypersurface models need to be set properly in the literature model database
    - The current values of `D1` and `D2` are incorrect for the toric hypersurface models
    - The coordinates of the fiber ambient space need to be reordered so that `D1` and `D2` correspond to the first two given coordinates, OR we need a new piece of information that indicates how `D1` and `D2` correspond to the given coordinates and update the constructor appropriately
        - If the coordinates are reordered, the ambient space rays need to be correspondingly reordered, and the maximal cones need to be rewritten to match this ordering
- The model F4 cannot currently be handled, which requires updating the constructor
- The name `model_sections` should be updated to clarify that these are the parameters whose divisor *class* needs to be given by the user; the actual sections themself do not need to be specified a priori
- The constructor for literature hypersurface models should handle any grading, without assuming that the first two base coordinates are elements of the basis for the grading 
- Extend the index for the literature model database to allow for hypersurface model and Weierstrass model versions of the same model
- Add CI tests for Weierstrass model version of toric hypersurface models
- Add new field to literature models for torsion sections of Mordell–Weil group

@emikelsons

**Comment by HereAround** [comment]
Based on our discussion this afternoon @apturner and @emikelsons , I believe this issue can be closed.
