### ISSUE TITLE
Reducing a non-homogenous polynomial in a graded polynomial ring

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3658]
It seems I am not allowed to reduce an arbitrary (graded) polynomial by an ideal of a graded polynomial ring; it gives an error as in the example below:
```
julia> R,(a,b,c) = graded_polynomial_ring(QQ,["a","b","c"]);

julia> J = ideal(R,[a^2 + b^2, c^2]);

julia> normal_form(a^2 + c^2, J)   # works
-b^2

julia> normal_form(a^2 + c, J)     # doesn't work
ERROR: ArgumentError: The generators of the ideal must be homogeneous
Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/Hecke/jLTFH/src/Assertions.jl:561 [inlined]
  [2] MPolyIdeal(B::Oscar.IdealGens{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:629
  [3] MPolyIdeal
    @ ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:614 [inlined]
  [4] ideal(Rx::MPolyDecRing{QQFieldElem, QQMPolyRing}, s::Singular.sideal{Singular.spoly{Singular.n_Q}})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:648
  [5] _normal_form_singular(A::Vector{…}, J::MPolyIdeal{…}, ordering::MonomialOrdering{…})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/groebner.jl:1163
  [6] normal_form(A::Vector{…}, J::MPolyIdeal{…}; ordering::MonomialOrdering{…})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/groebner.jl:1066
  [7] normal_form
    @ ~/Projekte/OSCAR/Oscar.jl/src/Rings/groebner.jl:1061 [inlined]
  [8] normal_form(f::MPolyDecRingElem{…}, J::MPolyIdeal{…}; ordering::MonomialOrdering{…})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/groebner.jl:1056
  [9] normal_form(f::MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}, J::MPolyIdeal{MPolyDecRingElem{…}})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/groebner.jl:1055
 [10] top-level scope
    @ REPL[20]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

But why is that? Mathematically it seems absolutely fine to me?

**Comment by fingolfin** [comment]
But if there is a good reason: where can I find this in the documentation? I would expect this restriction to be mentioned in e.g. the [`normal_form` documentation](https://docs.oscar-system.org/stable/CommutativeAlgebra/GroebnerBases/groebner_bases/#normal_form-Union{Tuple{T},%20Tuple{T,%20MPolyIdeal}}%20where%20T%3C:MPolyRingElem) but as far as I can tell it isn't (or I haven't found it)

**Comment by joschmitt** [comment]
Somebody made the design decision that all ideals in a graded ring need to be generated by homogeneous elements. The only piece of documentation I could find for this is in the constructor for ideals https://docs.oscar-system.org/stable/CommutativeAlgebra/ideals/#Constructors .
I ran into this several times, but I never had a use case that I felt was convincing enough.
One reason for this I can think of is that a quotient of a graded ring will only be graded if the ideal was homogeneous. But I don't see why this restriction forbids us to use non-homogeneous ideals in general.

**Comment by thofma** [comment]
The "problem" is that the non-homogenous ideal pops up indirectly here (as `normal_form(f, I)` calls `normal_form(ideal(f), I)`, yielding a confusing error message. Even if `normal_form(f, I)` is deemed to be illegal with non-homogenous `f`, there is something to improve here.

**Comment by fieker** [comment]
On Mon, Apr 29, 2024 at 05:32:02AM -0700, Johannes Schmitt wrote:
> Somebody made the design decision that all ideals in a graded ring need to be generated by homogeneous elements. The only piece of documentation I could find for this is in the constructor for ideals https://docs.oscar-system.org/stable/CommutativeAlgebra/ideals/#Constructors .
> I ran into this several times, but I never had a use case that I felt was convincing enough.
> One reason for this I can think of is that a quotient of a graded ring will only be graded if the ideal was homogeneous. But I don't see why this restriction forbids us to use non-homogeneous ideals in general.
> 
> 
There are 2 different things involved
 - banning to have a homogeneous ideal with non. hom. gens
 - banning to have non hom ideals
The 2nd one was completely unanimous: in the graded case, all ideals are
homogeneous.
The 1st was controversal, but resolved like it is since Wolfram couldn't
think of any (reasonable) situation where he'd end up with an ideal
known to be hom, but with bad gens. Janko beleived he could deliver, but
somehow it was not convincing.

What is your use case?

**Comment by joschmitt** [comment]
The concrete problem with `normal_form` seems to be fixed if one removes the construction of an ideal in `_normal_form_singular` which seems unnecessary to me anyway. If we agree that the behaviour of `normal_form` is not desired as is, I can make a pull request.

For entertainment:
```
julia> R,(a,b,c) = graded_polynomial_ring(GF(3),["a","b","c"]);

julia> J = ideal(R,[a^2 + b^2, c^2]);

julia> normal_form(a^2 + c, J)
2*b^2 + c
```
This works because it calls another `_normal_form_...` routine which does not try to create an ideal.

**Comment by fingolfin** [comment]
I have a fix that also speeds up things but this code reveals some serious issues. I'll submit a PR and another issue or two

**Comment by fieker** [comment]
On Mon, Apr 29, 2024 at 05:39:03AM -0700, Tommy Hofmann wrote:
> The "problem" is that the non-homogenous ideal pops up indirectly here (as `normal_form(f, I)` calls `normal_form(ideal(f), I)`, yielding a confusing error message. Even if `normal_form(f, I)` is deemed to be illegal with non-homogenous `f`, there is something to improve here.
> 
I have no (strong) opinion here... the original discussion even included
not allowing non-hom polys to exist (Mohammed's idea), up to no
restricionts at all, may the user know what they are doing...
Maybe ask Wolfram?

**Comment by fingolfin** [comment]
My /our use case (this is for invariant theory code by @Lax202) is that we have a single non-homogeneous graded polynomial and we need to reduce it modulo a graded ideal. The polynomial is from a standard text book on invariant theory, so "pretty natural".

I guess we could define a custom grading to deal with it, but I don't see why being forced to jump through such an extra hoop would be helpful to anyone; or conversely, why reducing a non-homogeneous polynomial is controversial at all?

**Comment by simonbrandhorst** [comment]
Should be fine to reduce any polynomial by a homogeneous ideal.

**Comment by wdecker** [comment]
Of course, we should be able to reduce any polynomial by a homogeneous ideal. Removing the unneccessary construction of an ideal as suggested by @joschmitt  should do the job. @joschmitt, please go ahead.

**Comment by joschmitt** [comment]
> @joschmitt, please go ahead.

@fingolfin already opened #3659.
