### ISSUE TITLE
Oscar installation fails (because of Hecke)

### ISSUE THREAD

**Issue by fralembo** [oscar-system/Oscar.jl#3685]
Hello everybody, 

I tried to install Oscar yesterday (2nd May 2024), and I followed step by step the procedure on the Oscar website.
I have a Windows, so I used the WSL and followed the instructions for Ubuntu.
Everything is good with Julia, but when i write Pkg.add("Oscar") , at the moment "Precompiling project", it bugs when it's time precompile Hecke: it tries for some minutes, then fails. After that, also Hecke → PolymakeExt, Hecke → GAPExt, and Oscar fail.

I tried to uninstall everything, but it didn't work. 

I attach screenshot of the error.

Thank you very much for your help!

![Immagine 2024-05-03 173322](https://github.com/oscar-system/Oscar.jl/assets/168846953/6c99cb0d-5da5-4950-92c2-8d49577d8025)

![Immagine 2024-05-03 173412](https://github.com/oscar-system/Oscar.jl/assets/168846953/314871fe-5b57-4ce2-82c6-53d68150d705)

**Comment by thofma** [comment]
Can you try `]precompile Hecke` and post the error? Thanks

**Comment by benlorenz** [comment]
Maybe your computer ran out of memory? 2000 seconds is really long and might indicate swapping, on my old Windows desktop this took about 500 seconds (including Hecke and also Oscar). Precompiling Hecke is quite demanding and the peak usage I observed was about 3.5 GB for the corresponding julia process.

You can check how much memory is available to julia by running `versioninfo(verbose=true)` in the julia shell, maybe post the output here as well?

**Comment by fralembo** [comment]
I did both, and these are the outputs:

![Screenshot 2024-05-03 190414](https://github.com/oscar-system/Oscar.jl/assets/168846953/acd87c4e-36ea-4be6-9ce5-6b177296db97)
![Immagine 2024-05-03 190249](https://github.com/oscar-system/Oscar.jl/assets/168846953/9a1ef5c8-3df9-40e5-806e-bc047d42325c)

Thank you again

**Comment by thofma** [comment]
No clue if this is enough memory. Can you start julia as
```
julia --heap-size-hint=2GB
```
and try again `]precompile Hecke`? And please show what `err` shows if you encounter an error.

**Comment by fralembo** [comment]
I did it and nothing changed. I tried to write `err` but it shows nothing.

![Immagine 2024-05-06 172120](https://github.com/oscar-system/Oscar.jl/assets/168846953/6d736ff3-4231-4e3f-a2a6-197cc8b268f0)

**Comment by benlorenz** [comment]
You could try increasing the available memory for the WSL VM by creating a `.wslconfig` file in your windows profile folder, usually `C:\Users\<username>`. It should contain:
```
[wsl2]
memory=4GB
```
That limit should be less than your total memory, but your current limit of 3GB (should be 50% of your total by default) seems to be too low.

I could reproduce a similar error after setting this to `memory=3GB`, with `4GB` precompilation and `using Oscar` did work. Restart the VM after changing the file with `wsl --shutdown` in a windows command prompt.
See https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig for details.

But note that you might run out of memory during your Oscar computations as well.

**Comment by fingolfin** [comment]
Unfortunately it seems this is caused by limited memory during precompilation of Hecke by Julia, and we can't do anything about that.

So closing this. We'll think about adding a warning about this to the installation instructions ("system requirements").
