### ISSUE TITLE
Planning software demos for the Begehung

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3706]
For the SFB Begehung in July we need to prepare some Software demonstrations. We will have up to 4 computers with 55" screens. The big question is what we want to show. This issue is meant to gather ideas and coordinate planning. Of course it primarily is for the OSCAR PIs to decide what we do, but I am interested in ideas and suggestions from anyone!

One IMHO obvious place to start are our [tutorials](https://www.oscar-system.org/tutorials/) -- we could have them "run" on the machines (whatever that means; could be just a browser open with the tutorial loaded; could be a slide show of the various tutorials running as a screen saver, and then when you move the mouse you can select one of them to run it; could be something else, e.g. perhaps someone has some nice ideas for visual things... e.g. polyhedral geometry).

Of course we can also do multiple things (e.g. have two machines run tutorial and two visual demos, etc. etc.). And of course we will also be ready to open a fresh OSCAR session in a REPL or Jupyter notebook to run demos on requests...

If we agree that using some or all of the tutorials is a good idea, then all PIs should take some time to look at them, and make sure they are OK with those tutorials. If you think some need changes, or we are missing important things that should be covered in existing or new tutorials: speak up! We still have time to add content, but we need to know this sooner rather than later so we can prepare it well.

To add a tutorial, just create a nice Jupyter notebook, put it somewhere on GitHub, and send @HereAround the link, and we can take care of the rest.

(All Tutorials should run with the latest stable OSCAR release, so right now 1.0.x and perhaps soon 1.1. Once we have accepted a tutorial we keep an eye on that and notify authors if changes need to be made -- if just output changed we can usually also just take care of it ourselves).

Of course we also need to be prepared to run and explain the notebooks. So for every tutorial / notebook we select for the Begehung, we need to have people there who are familiar with it to show it. We should also practice this (e.g. during the trial run for the Begehung) and e.g. train what to do if a notebook hangs or runs into other issues.

**Comment by micjoswig** [comment]
Well, this is very different from a usual software demonstration.  Therefore the word "tutorial" is maybe a bit misleading.

It is necessary to show computations which demonstrate mathematical impact. A simple overview is not enough.

Of course, the challenge is to present relevant math concisely.

**Comment by fingolfin** [comment]
We are doing the planing elsewhere, so closing this
