### ISSUE TITLE
ambiguous printing of sub-pc groups

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/Oscar.jl#3732]
The `SubPcGroup`s introduced in pull request #3166 currently print themselves as follows.
```
julia> normal_subgroups(quaternion_group(8))
6-element Vector{SubPcGroup}:
 Subgroup of pc group of order 8
 Subgroup of pc group of order 4
 Subgroup of pc group of order 4
 Subgroup of pc group of order 4
 Subgroup of pc group of order 2
 Subgroup of pc group of order 1
```
What is meant is `(Subgroup of pc group) of order 4` not `Subgroup of (pc group of order 4)`.

In order to remove the ambiguity, @fingolfin proposes `Sub-pc group of order 4`.

The same question will arise when sub-f.p. groups will be introduced.

**Comment by fingolfin** [comment]
@fieker any comments?

**Comment by fieker** [comment]
`Sub-pc group of order 4.`

**Comment by ThomasBreuer** [comment]
O.k., I will make a pull request for that.
