### ISSUE TITLE
Casting `PolyhedralFan` to `PolyhedralComplex`

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#3748]
It happens now and then that I want to convert a polyhedral fan to a polyhedral complex in Oscar. There are already versions of `polyhedral_complex` that do this for polyhedra and tropical varieties, so perhaps it could make sense to have one also for fans? 

I'm currently using the following function locally (thanks for @lkastner for helping me with this over on Slack!). Perhaps something along these lines should be in Oscar? 

```
function polyhedral_complex_from_fan(F::PolyhedralFan)
    K = F.parent_field
    rml, L = rays_modulo_lineality(F)
    rays_and_vertex = vcat(matrix(K, rml), zero_matrix(ZZ, 1, ambient_dim(F)))
    cells = maximal_cones(IncidenceMatrix, F)
    new_cells = IncidenceMatrix(nrows(cells), ncols(cells)+1);
    new_cells[1:nrows(cells), 1:ncols(cells)] = cells;
    for i in 1:nrows(cells) 
        new_cells[i, ncols(cells)+1] = 1
    end
    return polyhedral_complex(new_cells, rays_and_vertex, collect(1:length(rml)))
end
```

**Comment by oskarhenriksson** [comment]
It sounded like @oliverdaisey also had needs along these lines, so maybe you have thoughts on how this potentially could be implemented in a good way?

**Comment by oliverdaisey** [comment]
I still think fans should be a concrete subtype. It seems complexes have an implementation as sliced fans, but this shouldn't be a user-level concern.

**Comment by lkastner** [comment]
@oliverdaisey What do you mean by "concrete subtype"?

**Comment by oliverdaisey** [comment]
> @oliverdaisey What do you mean by "concrete subtype"?

The type tree for `PolyhedralComplex` is
`PolyhedralComplex{T} <: Oscar.PolyhedralObject{T} <: Any`.

The type tree for `PolyhedralFan` is
`PolyhedralFan{T} <: Oscar.PolyhedralObject{T} <: Any`.

I think it is more natural (at least, I would expect) to have something like
`PolyhedralFan{T} <: PolyhedralComplex{T} <: Oscar.PolyhedralObject{T} <: Any`
which would guarantee that anything one can do with a complex, one can do with a fan.

**Comment by lkastner** [comment]
@oliverdaisey  You are aware of that one cannot inherit from concrete types in Julia?

**Comment by lkastner** [comment]
Of course we could introduce another abstract type and have something like
```
PolyhedralComplex{T} <: AbstractPolyhedralComplex{T} <: PolyhedralObject{T}
PolyhedralFan{T} <: AbstractPolyhedralComplex{T} <: PolyhedralObject{T}
```
But this still does not give us the guarantee you want.

Furthermore, also every `Polyhedron` and `Cone` are mathematically speaking just other variants of `PolyhedralComplex`. So that is why we introduced the abstract type `PolyhedralObject{T}`.

**Comment by lkastner** [comment]
@oskarhenriksson I'll try to make a PR next week.
