### ISSUE TITLE
`libgap` symbol lookup error on julia nightly

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#3769]
Oscar does not load on the current julia nightly (1.12.0-DEV.573, Commit 263928f9ad4), see e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/9187618666/job/25265680433?pr=3679#step:9:384

```
ERROR: LoadError: The following 1 direct dependency failed to precompile:

Oscar --code-coverage=none --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=yes --inline=yes --startup-file=no --track-allocation=none --check-bounds=yes 

Failed to precompile Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13] to "/home/runner/.julia/compiled/v1.12/Oscar/jl_tkfvhv".
/opt/hostedtoolcache/julia/nightly/x64/bin/julia: symbol lookup error: /home/runner/.julia/artifacts/25ba2c3f606ffb19948ac2cde2f774abe3b2d3b7/lib/libgap.so: undefined symbol: jl_task_stack_buffer, version JL_LIBJULIA_1.1
in expression starting at /home/runner/work/_actions/julia-actions/julia-runtest/latest/test_harness.jl:7
Error: Process completed with exit code 1.
```

**Comment by fingolfin** [comment]
Urgh, yeah, we removed `jl_task_stack_buffer` from Julia, because it was unusued -- or so I thought, but actually there is still a use of it even if it has been deprecated since 2020.

I'll get on it today, either by reverting the removal, or by updating the GAP_jll.

**Comment by fingolfin** [comment]
ping @ThomasBreuer just so you are aware -- don't worry, I am on it

**Comment by benlorenz** [comment]
This is resolved in the latest nightly build, thanks Max.
