### ISSUE TITLE
free_resolution using `mres` does not grade zero module at homological degree -2

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#3797]
@RafaelDavidMohr See below for an example

julia> R, (x,y) = graded_polynomial_ring(QQ, [:x, :y]);

julia> I = ideal(R, [x, y]);

julia> FIn = free_resolution(I, algorithm = :nres);

julia> FIn[-2]
Graded free module R^0 of rank 0 over R

julia> FIm = free_resolution(I, algorithm = :mres);

julia> FIm[-2]
Free module of rank 0 over R

**Comment by ederc** [comment]
Working on a fix.
