### ISSUE TITLE
Book test issues

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3809]
While trying to understand why the book tests failed on a PR of mine (I think it was a fluke in the end?), I had a look [at this log](https://github.com/oscar-system/Oscar.jl/actions/runs/9277391037/job/25526477175?pr=3808), and noticed some things I find concerning:

First off, this looks as if some files are included multiple times?
```
WARNING: Method definition base_coefficient_rings(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:4 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition collect_terms(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:10 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition factorise_terms(Base.Dict{K, V} where V where K) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:36 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition factorize_collected_terms(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:44 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition tropical_base(Array{var"#s631", 1} where var"#s631"<:(Base.Dict{K, V} where V where K)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:50 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition modified_support(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:63 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition nonlinear_resonator_system(Int64, Int64) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:101 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition kwcall(NamedTuple{names, T} where T<:Tuple where names, typeof(__228.nonlinear_resonator_system), Int64, Int64) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:101 overwritten on the same line (check for duplicate calls to `include`).
WARNING: Method definition generic_root_count(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:124 overwritten on the same line (check for duplicate calls to `include`).
  closing mockrepl: Main.__228
specialized/bies-turner-string-theory-applications
  created mockrepl: Main.__230
    SU5.jlcon

....
```

Then this one (this might be relevant for @thofma and @fieker as it seems to be in the number theory chapter?). Notice the "core dumped" in the middle

```
┌ Warning: possibly wrong file type: cornerstones/number-theory/intro_plot_lattice.jlcon
└ @ Main ~/work/Oscar.jl/Oscar.jl/test/book/test.jl:241
WARNING: using deprecated binding Colors.RGB1 in PlotUtils.
, use XRGB instead.
WARNING: using deprecated binding PlotUtils.RGB1 in Plots.
, use ColorTypes.XRGB{T} where T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint{T, f} where f where T<:Integer} instead.
WARNING: using deprecated binding Colors.RGB4 in PlotUtils.
, use RGBX instead.
WARNING: using deprecated binding PlotUtils.RGB4 in Plots.
, use ColorTypes.RGBX{T} where T<:Union{AbstractFloat, FixedPointNumbers.FixedPoint{T, f} where f where T<:Integer} instead.
┌ Warning: backend `GR` is not installed.
└ @ Plots ~/.julia/packages/Plots/ju9dp/src/backends.jl:43

GC: pause 88.96ms. collected 324.103730MB. incr 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, vnc, minimal, eglfs, minimalegl, offscreen, vkkhrdisplay, linuxfb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine FILLAREA

GC: pause 70.75ms. collected 342.784054MB. incr 
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine FILLAREA
...
[ goes on for pages and pages ]
...
```

Should this happen? Is this maybe due an example that only works interactively? Should we then either disable it here, or adjust it so it works non-interactively? Or what else is going on?

BTW, the actual error that failed the log then seems to be a network issues, so hopefully intermittent, and can hopefully be ignored:
```
+ ERROR: BSONError: domain=15, code=13053, message=No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling hello on 'db.polymake.org:27017']
```

**Comment by benlorenz** [comment]
> First off, this looks as if some files are included multiple times?
> 
> ```
> WARNING: Method definition base_coefficient_rings(Array{var"#s631", 1} where var"#s631"<:(AbstractAlgebra.MPolyRingElem{T} where T)) in module __228 at /tmp/jl_eORcuY/generic_root_count/src/main.jl:4 overwritten on the same line (check for duplicate calls to `include`).
> ....
> ```

We can probably remove the include in the aux file since it is also included in the jlcon itself, this might be because of some previous version. At least at runtime this errors should not cause issues.

> 
> Then this one (this might be relevant for @thofma and @fieker as it seems to be in the number theory chapter?). Notice the "core dumped" in the middle
> 
> ```
> Aborted (core dumped)
> ...
> GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine FILLAREA
> ...
> ```
> 
> Should this happen? Is this maybe due an example that only works interactively? Should we then either disable it here, or adjust it so it works non-interactively? Or what else is going on?

This are plots calls, it does seem to succeed but the plots backends seem to be very unhappy about running in the restricted github environment without any display.
I will try to have another look if we can somehow adjust the plots backend or something similar to keep the calls but avoid all the output.

> BTW, the actual error that failed the log then seems to be a network issues, so hopefully intermittent, and can hopefully be ignored:
> 
> ```
> + ERROR: BSONError: domain=15, code=13053, message=No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling hello on 'db.polymake.org:27017']
> ```

I don't see any issues on the polymake server that would have caused this, this might have been some network issue on the runner.
To avoid this we could use a similar approach as in the Polymake.jl repo. Include an extract of the relevant dataset in the repo and spin up a custom mongodb server to redirect these requests:
https://github.com/oscar-system/Polymake.jl/blob/80daa742cad63b6805be0a39fe8eb9ef1533dbbe/.github/workflows/runtests.yml#L42-L86

**Comment by fingolfin** [comment]
@benlorenz will have a quick look to see if this is OK now and then we can hopefully close this

**Comment by benlorenz** [comment]
Looking at some recent booktest runs, only a few Plots.jl deprecation warnings remain. These calls are somewhere within the plots packages and out of scope of this issue. (A quick search turned up some related issues and there seems to be some progress towards resolving these.)
