### ISSUE TITLE
Center of a blowup

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#3810]
There has been some discussion about what the method `center` of a blowup should return. 
In personal discussion with @HechtiDerLachs  and @paemurru  we came to the following:

- mathematically speaking the center  is a reduced subscheme, there is no canonical non-reduced structure of it.
Thus `center` must return a the reduced subscheme and the inclusion morphism. Since computing the reduced subscheme is impractical, for now we raise a `NotImplementedError`  until in the possibly far future we have a lazy type for reduced subschemes. 

There should be a method 
`center_ideal_sheaf` which returns the lazy radical ideal sheaf defining the center. This data structure exists already. 
Existing code that uses `center` can be redirected to `center_ideal_sheaf`. The method `center_ideal_sheaf` will be exported. 

Let me ping the other stakeholders @afkafkafk13 @HereAround 
Do you have suggestions / opinions on this?

If we all agree, I will ask @paemurru  to implement this.

**Comment by afkafkafk13** [comment]
Sounds fine to me. Please only throw a not-implemented error, if the reduced scheme is not already available. In settings forcing a reduced center, you know what you have.

**Comment by HereAround** [comment]
Sounds good to me too. I am looking forward to the PR.

**Comment by simonbrandhorst** [comment]
@afkafkafk13  Do you have particular settings in mind? Are they implemented already? 

 @paemurru  would you please go ahead and implement the proposal?

**Comment by afkafkafk13** [comment]
@simonbrandhorst : What I had in mind, was the situation where the centers of a blow up sequence have been determined algorithmically and maximal_associated_points has been used in the process (e.g. BEV, CJS). Then the center data stored in the respective blow up is an ideal sheaf which knows about itself being reduced and irreducible (over the base field).

Edit: It is already implemented and merged this way for the curve case as a testing ground for the overall structure.

**Comment by afkafkafk13** [comment]
By the way: When talking to Erik the other day, I also stated that I fully agree with your streamlining of center and center_ideal_sheaf, but would also like to have a streamlined getter for the center data from each BlowUp type returning e.g. the ray for toric blow-ups and the original center ideal sheaf for Proj-constructions. Since the individual blow-ups have different types und for each type the respective data is type-stable, this is type stable and provides data access for the specialists (not necessarily programmers).
