### ISSUE TITLE
wrong symbol in output of roots()?

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#3842]
The following works
```
julia> R, t = QQ["t"]; v = roots(QQBarField(), t^5-1)
5-element Vector{QQBarFieldElem}:
 Root 1.00000 of x - 1
 Root 0.309017 + 0.951057*im of x^4 + x^3 + x^2 + x + 1
 Root 0.309017 - 0.951057*im of x^4 + x^3 + x^2 + x + 1
 Root -0.809017 + 0.587785*im of x^4 + x^3 + x^2 + x + 1
 Root -0.809017 - 0.587785*im of x^4 + x^3 + x^2 + x + 1
```
but the output mentions "x" instead of "t".

Is it possible to change that?

**Comment by thofma** [comment]
No, it is not possible to change that. Everything is printed using `x`.
```
julia> K = algebraic_closure(QQ)
Field of algebraic numbers

julia> sqrt(K(1))
Root 1.00000 of x - 1

julia> sqrt(K(-1))
Root 1.00000*im of x^2 + 1
```
Alternatively, we can ditch the `x` and just print the coefficients:
```
Root 0.309017 + 0.951057*im of [1, 1, 1, 1, 1]
```

**Comment by YueRen** [comment]
One could consider of allowing the user to specify a string of their choice to be used as variable name in lieu of `x`.  Inferring the string from the input of `roots` is difficult as the input need not be consistent:

```
julia> R,t = QQ["t"]; v = roots(QQBarField(), t^5-1) # created with t
5-element Vector{QQBarFieldElem}:
 Root 1.00000 of x - 1
 Root 0.309017 + 0.951057*im of x^4 + x^3 + x^2 + x + 1
 Root 0.309017 - 0.951057*im of x^4 + x^3 + x^2 + x + 1
 Root -0.809017 + 0.587785*im of x^4 + x^3 + x^2 + x + 1
 Root -0.809017 - 0.587785*im of x^4 + x^3 + x^2 + x + 1

julia> S,u = QQ["u"]; w = roots(QQBarField(), u^2-1) # created with u
2-element Vector{QQBarFieldElem}:
 Root 1.00000 of x - 1
 Root -1.00000 of x + 1

julia> v[1]+w[1] # adding both is no problem, but what should the print string use?
Root 2.00000 of x - 2

```

**Comment by thofma** [comment]
Yes, we can allow a string when creating. But there is only one QQBar. So if we allowed it and one does `abelian_closure(QQ, "x")` followed by `abelian_closure(QQ, "y")`, then everything will be printed with `y` afterwards. Which defeat the purpose of having something remember a specific name.

**Comment by micjoswig** [comment]
OK, thanks everybody for their input.  Let's leave it as it is.  

@thofma Maybe add some comment in the doc of roots?

You decide.  Then please close this ticket, perhaps as invalid.

**Comment by micjoswig** [comment]
OK, I thought about this again.  The `roots` function gets the polynomial as its second argument.  That polynomial knows how to print its variable.  Couldn't that information be passed on?

I think it is not an issue with `QQBar` and friends but rather a local problem in this function.

Or am I missing something?

**Comment by micjoswig** [comment]
OK, it's true the first example, adding two different roots, remains unanswered by my suggestion.  So, let's close this.
