### ISSUE TITLE
Documentation still suggest `PolyRing` constructors instead of the snake_case ones

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#3843]
The two places that I noticed are at the end of the subsection https://docs.oscar-system.org/stable/AbstractAlgebra/polynomial/#Polynomial-ring-constructors with `PolyRing`, but I suppose there are many more

**Comment by joschmitt** [comment]
The `PolyRing` seems to be correct-ish to me. The snake case version would be `polynomial_ring_only` which is not exported, `PolyRing` is exported. It's not clear to me what should be done here.

**Comment by fingolfin** [comment]
Yeah `PolyRing` is somewhat special. Not saying it shouldn't be taken care off, though.

@lgoettgens you wrote "many CamelCase constructors" -- can you maybe point out some more?

**Comment by lgoettgens** [comment]
my other case I vaguely remember to be there seems to have changed
