### ISSUE TITLE
Oscar, CyclotomicField throwing error that no constructors are defined

### ISSUE THREAD

**Issue by lizcarlson** [oscar-system/Oscar.jl#3844]
I recently reinstalled my Oscar package in Julia, so now I am using v1.0.3 (which is the latest compatible with my Julia version (1.9.1; unfortunately upgrading my Julia version is not an option)).  The minute I did this, my code (which worked fine for nearly a year on my previous install of Julia and Oscar) broke (see below).  Not sure why this error is being thrown, seems like either a simple compatibility fix or a bug.  Any help would be appreciated, thank you.

```
import Oscar
m=6
K, x = Oscar.CyclotomicField(m, "x")
ERROR: MethodError: no constructors have been defined for CyclotomicField
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```

**Comment by fieker** [comment]
On Tue, Jun 11, 2024 at 07:09:19PM -0700, lizcarlson wrote:
> I recently reinstalled my Oscar package in Julia, so now I am using v1.0.3 (which is the latest compatible with my Julia version (1.9.1; unfortunately upgrading my Julia version is not an option)).  The minute I did this, my code (which worked fine for nearly a year on my previous install of Julia and Oscar) broke (see below).  Not sure why this error is being thrown, seems like either a simple compatibility fix or a bug.  Any help would be appreciated, thank you.
> 
> ```
> import Oscar
> m=6
> K, x = Oscar.CyclotomicField(m, "x")
> ERROR: MethodError: no constructors have been defined for CyclotomicField
> Stacktrace:
>  [1] top-level scope
>    @ REPL[4]:1
> ```

Not sure about the why, but 
Oscar.cyclotomic_field(m, "x")
should work.
My guess is that CyclotomicField was never a constructor, there never
was a type CyclotomicField. A function used to exist in naming analogy
to NumberField and similar, but was deprecated and swapped to the julia
prefered snake-case version: cyclotomic_field.
The error could be better.
Sorry
 Claus

**Comment by fingolfin** [comment]
To be clear, going from 0.x to 1.0 we remove many aliases for old function names in CamelCase that kept them working, but we've switch to `snake_case` function names already some time ago. So be prepared to change more of your code in this vein.

**Comment by lizcarlson** [comment]
This gave me a chuckle, because in documentation for a different Julia package I use more frequently they use ```snake_case``` for their examples, but only the analogous commands of the form ```CamelCase``` I was using would work without error (and hence why I defaulted to using that for Oscar commands as well, long ago).  Thank you for the clarification, this works just fine now.
