### ISSUE TITLE
Regression in GAP code: missing `regen_doc.g`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3875]
We are seeing this now in some CI logs:
```
ERROR: LoadError: InitError: Error thrown by GAP: Error, file "regen_doc.g" must exist and be readable at /Users/aaruni/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/files.gi:208 called from
<function "Read string">( <arguments> )
 called from read-eval loop at stream:24
```
This is due to a bug in the GAP PackageManager. @ThomasBreuer and me are aware and working on a fix, but since it may cause lots of PRs to report some errors at least on the RPTU runners, I wanted to log it here as a place I can point people to.

**Comment by fingolfin** [comment]
See e.g. [this log](https://github.com/oscar-system/Oscar.jl/actions/runs/9580003339/job/26413691162?pr=3869) -- to explain what is going on: in PR #3874 Thomas is adding some code which uses `git clone` to install a custom version of the GAP package `recog` (we can replace this with installing a fixed tarball later, but for quick iteration it is useful to do this for now). The clone ends up in a place like `~/.gap/pkg/recog` or so.

But the RPTU runners seem to re-use the full environment -- including user home directories. So this git clone stays around "forever", and in particular now affects the RPTU CI jobs for all other PRs.

We will resolve this for now. And in a sense this was useful because it also highlighted some issues regular users will have.

But I think overall this behavior of the runners is a bit problematic. We might accumulate all kinds of things, intentionally or accidentally (or even maliciously?)

@aaruni96 can we implement a bit more isolation for the RPTU runners? E.g. perhaps each PR run can use an overlayfs to make sure any changes are only temporary? (Of course then we need to worry about updating the depot or maybe the depot would be excluded from the overlay or whatever... I am thinking just in rough outlines here, I'll leave the nitty gritty details to you)

**Comment by fingolfin** [comment]
I believe this is resolved now.


But there is a new issue: several people are getting this error with OSCAR 1.1.0 (probably also master, but definitely with 1.1.0 on a completely clean fresh system), including @aaruni96 and @jankoboehm :
```
ERROR: InitError: cannot load the GAP package recog
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] __init__()
    @ Oscar ~/.julia/packages/Oscar/CR7DH/src/Oscar.jl:125
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1134
 ...
```
@aaruni96 figured out why, at least in his setup:
> the install steps for recog somewhere along the line tried to download and untar something, which fails in the runtime [he is using]

So I think `GAP.Packages.install("recog", "1.4.2", ...)` is the culprit: `recog 1.4.2` is already present (as part of the GAP package distribution installed via `GAP_pkg_jll`). But apparently PackageManager nevertheless tries to download and install it anew? Perhaps we can change this to first check if recog 1.4.2 is already installed (or even already loaded) ? @ThomasBreuer ?

**Comment by ThomasBreuer** [comment]
To be precise: The problem should be fixed with #3890, which got merged yesterday.

Currently I cannot reproduce the problem, but avoiding downloads if possible is a real improvement: When a version is specified in the `GAP.Packages.install` call then check whether this version is already installed and available before trying to download something. (The first file that gets downloaded is the package information file. This is not necessary if we have already the required version.)

For the moment, we can do this in Oscar.jl; I will provide a pull request for that.
A better place will be GAP.jl, and eventually GAP's PackageManager should be changed accordingly.

**Comment by benlorenz** [comment]
I would really like to understand more about the failure, I could not reproduce this with a fresh depot and Oscar 1.1.0 so far. What is the state of `.julia/gaproot/v4.12/pkg/` in that situation? Are there layered or readonly depots involved?

And I don't see how #3890 would fix something that seems to happen with 1.1 (on a fresh system that has never seen a master checkout?) since that PR is mostly a revert of a PR that is **not** in 1.1.

**Comment by ThomasBreuer** [comment]
@benlorenz The question is how "fresh" the Julia installation is. Both Oscar 1.1 and the Oscar master branch use the same underlying GAP.
If a dev Oscar has installed some GAP package in `.julia/gaproot/v4.12/pkg/` (perhaps only partially) then this package can influence Oscar 1.1.

**Comment by benlorenz** [comment]
I found someone here who also ran into this error, with current Oscar master on a completely fresh laptop. In this case the root cause was a missing C compiler, which causes the installation of the gap package `io` to fail and this seems to break the explicit loading of `recog` (which indirectly? depends on `io`).

So by manually breaking the io package in the gaproot (deleting the compiled files and adding an error in the configure script) I can trigger the recog error (also with 1.1.0):
```julia
julia> using Oscar
  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.0
ERROR: InitError: cannot load the GAP package recog
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] __init__()
    @ Oscar /tmp/freshdepot/packages/Oscar/CR7DH/src/Oscar.jl:118
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1134
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1122
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1067
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1581
  [7] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1938
  [8] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1812
  [9] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [10] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [11] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1803
 [12] macro expansion
    @ ./loading.jl:1790 [inlined]
 [13] macro expansion
    @ ./lock.jl:267 [inlined]
 [14] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1753
 [15] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [16] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [17] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1746
during initialization of module Oscar
```

**Comment by fingolfin** [comment]
@benlorenz yeah, so (at least) three different things can cause the exact same error: 
- networking failures
- failure to extract the tarball
- missing or broken dependencies


All of this would be resolved by having `GAP_pkg_recog`, etc.. A ton of other issues also would be resolved by that. So here is my plan for that:
1. get the Begehung behind us
2. finish teaching  (26. July!)
3. debug and resolve GAP 4.13 issues so we can finally upgrade to it resp. to GAP.jl to 0.11.x (week 29.7. - 2.8. ?)
4. vacation 
5. work on GAP.jl 0.12.0 which will not use the GAP package distro anymore, but instead use `GAP_pkg_*` mechanism (first week of September? maybe before, but no promises)

**Comment by ThomasBreuer** [comment]
@benlorenz With this recipe, I can also reproduce the problem. Thanks.

Independent of @fingolfin's plan, I think that we can improve the messages about failures to install/load GAP packages.
For the networking problems, this should be done in the PackageManager package.
For problems with the dependencies, this requires an extension of `LoadPackage` in GAP itself and then of `Packages.load` inside GAP.jl.

**Comment by fingolfin** [comment]
I believe this is resolved
