### ISSUE TITLE
Constructors for polyhedral objects

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#388]
After discussion with @fingolfin we decided to introduce a struct `Point` such that Polyhedra can be built from collections of these. Now this could entail the need for several other structs and we should talk about what constructors we want in the end. 

For polyhedra there are two sides:
- The vertex side, the ultimate constructor looks like `Polyhedron(Points, Rays, LinealityGenerators)`
- The halfspace side: `Polyhedron(Inequalities, Equations)`, one could also say `Polyhedron(Halfspaces, Hyperplanes)`.

This is the affine situation, for the non-affine case this also suffices. Maybe we need to drop in an `Affine*` for the affine situation to make this clear.

So in the end we might have `Point, Ray, LinealityGenerator, Halfspace, Hyperplane, AffineHalfspace, AffineHyperplane`. Do you have other/better proposals?

I think once we have decided this it automatically extends to fans and polyhedral complexes and to several other functions as well.

**Comment by fieker** [comment]
On Mon, Mar 29, 2021 at 05:17:58AM -0700, Lars Kastner wrote:
> After discussion with @fingolfin we decided to introduce a struct `Point` such that Polyhedra can be built from collections of these. Now this could entail the need for several other structs and we should talk about what constructors we want in the end. For polyhedra there are two sides:
> - The vertex side, the ultimate constructor looks like `Polyhedron(Points, Rays, LinealityGenerators)`
> - The halfspace side: `Polyhedron(Inequalities, Equations)`, one could also say `Polyhedron(Halfspaces, Hyperplanes)`.
> This is the affine situation, for the non-affine case this also suffices. Maybe we need to drop in an `Affine*` for the affine situation to make this clear.
> So in the end we might have `Point, Ray, LinealityGenerator, Halfspace, Hyperplane, AffineHalfspace, AffineHyperplane`. Do you have other/better proposals?
> I think once we have decided this it automatically extends to fans and polyhedral complexes and to several other functions as well.
> 

Will there be different `Point`s for algebraic and polyhedral geometry?

**Comment by lkastner** [comment]
I don't know and I don't think that I am the right person to answer that question. I will go ahead with this suggestion and while it is not merged it is still easy to change those names to something else. Then you can decide the naming issue in parallel somewhere else. Do you have other objections / suggestions?

**Comment by lkastner** [comment]
Actually it is even worse and `Point` already exists somewhere else. So I will use `Combinatorial*` as a prefix and we can always search replace later.

**Comment by fieker** [comment]
On Thu, Apr 01, 2021 at 07:07:36AM -0700, Lars Kastner wrote:
> Actually it is even worse and `Point` already exists somewhere else. So I will use `Combinatorial*` as a prefix and we can always search replace later.
> 
Why not use the Point?

**Comment by lkastner** [comment]
It is in the `experimental` folder and marked as a first attempt, this to me sounds like it would be a bad idea to rely on it. Furthermore it requires its entries to come from a field and I suspect that this might not be implemented for everything we want to plug into it. It can always be unified later.

**Comment by lkastner** [comment]
Ok, so I made a version with `CombinatorialPoint`. Please have a look. Maybe we can merge the two different points. https://github.com/oscar-system/Oscar.jl/compare/enh/Polytopes/Point

**Comment by fingolfin** [comment]
Can you perhaps open this as a draft PR? That way, we can inline comment on the code and discuss details.

**Comment by fingolfin** [comment]
Although I guess it is short enough to not need that :-). In principle this seems fine to me. All things I can think of right now are mostly about polish. The general idea, however, seems exactly like what I had in mind. Well, I didn't have `CombinatorialPoint` in mind, but as you correctly say, it is fine to use that for now, and we can think about whether we can/want to unify this with other point types later.

**Comment by lkastner** [comment]
Alexej dealt with this in https://github.com/oscar-system/Oscar.jl/pull/578
