### ISSUE TITLE
broken on julia nightly due to `names` changes

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3882]
There were some changes to `names`, which broke things in all packages doing the `import/export` reexport shenanigans. Trying to fix this for Nemo here: https://github.com/Nemocas/Nemo.jl/pull/1800. (edit: reported upstream in https://github.com/JuliaLang/julia/issues/54885)

**Comment by lgoettgens** [comment]
The julia commit has been reverted in https://github.com/JuliaLang/julia/pull/54959, so Nemo should work again once the next nightly is available (next few hours).
