### ISSUE TITLE
Add warning for outdated docs

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3907]
Julia docs show a big red banner "This documentation is not for the latest version. [Go to the latest documentation](https://docs.julialang.org/en/v1.10)." on pages like https://docs.julialang.org/en/v1.7/

We should do the same for the OSCAR docs (and ideally also AA, Nemo, Hecke, etc.)

@thofma pointed out on Slack that https://github.com/JuliaDocs/Documenter.jl/pull/1577 is relevant and that there is a script to add it to old documentation.

@lgoettgens added that on newer outdated pages like https://docs.oscar-system.org/v1.0/ the banner is already there. So it just remains to run `DocumenterTools.OutdatedWarning.generate` once per repository on the `gh-pages` branch

It remains for someone to tackle this -- perhaps @aaruni96 can have a look.

**Comment by lgoettgens** [comment]
I now added PRs to all of our repositories with the script changes, apart from Hecke. The script does not like the current Vitepress site there and is thus unable to determine the point in time when the warning was added already at release. This would need some more manual work.

**Comment by fingolfin** [comment]
Very nice, thank you @lgoettgens !

**Comment by lgoettgens** [comment]
Closing in favor of https://github.com/thofma/Hecke.jl/issues/1590, since this issue is no longer relevant for Oscar.
