### ISSUE TITLE
Pkg.add fails to install Oscar without also running Pkg.update

### ISSUE THREAD

**Issue by Tracque** [oscar-system/Oscar.jl#3940]
**Describe the bug**
On a fresh Julia install, the command Pkg.add causes a broken install of Oscar. Running Pkg.update() fixes this error.

**To Reproduce**

On a fresh install:
```
using Pkg
Pkg.add(Oscar)
...
    Building LoadFlint → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/4b2aa705eb750c14005dbdd1a6c1ef89d96fb5a2/build.log`
    Building CMake ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/50a8b41d2c562fccd9ab841085fc7d1e2706da82/build.log`
    Building Nemo ─────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/93ffb6356a4f41e04859b3ef821cb3f5048574da/build.log`
    Building Singular ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/fb08d41ebe865cd8405b1cde521e1bbfcb439d72/build.log`
ERROR: Error building `Singular`: 
ERROR: LoadError: InitError: could not load library "/home/tristan/.julia/artifacts/d54a2909808f0f05123ef98f8eef4fcde1073e52/lib/libcxxwrap_julia_stl.so"
libjulia.so.1: cannot open shared object file: No such file or directory
```
This behavior is remedied by running Pkg.update(). I have checked on multiple systems that this behavior persists.

**Expected behavior**
From README:

"In principle it can be installed and used like any other Julia package; doing so will take a couple of minutes:"

```
julia> using Pkg
julia> Pkg.add("Oscar")
julia> using Oscar
```

**System:**
I'm running on Ubuntu 24.04 LTS.

After running Pkg.update() to fix the install:
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.0.4
  combining:
    AbstractAlgebra.jl   v0.40.9
    GAP.jl               v0.10.4
    Hecke.jl             v0.30.12
    Nemo.jl              v0.43.3
    Polymake.jl          v0.11.17
    Singular.jl          v0.22.6
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.9+0
    GAP_jll                 v400.1200.200+9
    Singular_jll            v403.216.1602+0
    libpolymake_julia_jll   v0.11.4+0
    libsingular_julia_jll   v0.44.2+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake-avx512)
Threads: 1 default, 0 interactive, 1 GC (on 24 virtual cores)
Official https://julialang.org/ release
```

**Additional context**
I'm unsure of the relevancy, but my use case is that I have been using the package PLD.jl, which depends on Oscar. For some reason, my Oscar install has had a tendency to break (just gets stuck without error on the "using Oscar" command) so I have reinstalled a few times. That was how I encountered this bug.

With regards to the breaking install, I believe it may be a problem on my end although I cannot be sure. If anyone has encountered similar issues I am happy to also create a report for that and upload a working and non-working .julia folder along with the results of the diff command.

**Comment by lgoettgens** [comment]
This sounds like your local copy of the general registry being very outdated. How did you install julia on these "multiple systems" that this issue occurred for you?

**Comment by Tracque** [comment]
I installed according to the instructions on the julialang website:
```
curl -fsSL https://install.julialang.org | sh
```
(curl 8.5.0)

**Comment by fingolfin** [comment]
When you say "fresh install", does that include deleting the `~/.julia` directory?

What is the output of `Pkg.update()` when it "fixes" the issue you are seeing?

**Comment by benlorenz** [comment]
The reason is probably that the `PLD_code.zip` package contains a full manifest which uses a very old Oscar version (0.10.0) that is not compatible with a current julia version.

If you want to use the package versions from that manifest you should try with julia 1.8.5.
Otherwise you need to run update or remove the `Manifest.toml` file.

**Comment by Tracque** [comment]
The source of the issue seems to be that the package manager is fetching an incredibly old (v0.4.0) version of Oscar. This isn't even the version that PLD used though so I'm not sure where this behaviour came from. I also tossed out the manifest and project files from the PLD code to try again but still get the same results.

The package manager also knows without running update that the version of Oscar is old as it is marked as upgradeable when running Pkg.status()...

(As an aside, my understanding was that rm -rf .julia was sufficient for a clean install. If that's not the case then I stand corrected)

**Comment by aaruni96** [comment]
The behaviour of julia's package resolver can depend on many things (where `~/.julia` is just the default depot). If you have some package installed, it can affect which versions of other packages will be fetched, or if there's a stray `Project.toml` or `Manifest.toml` in the current working directory, or if you've set `JULIA_PROJECT` or `JULIA_DEPOT_PATH` in your shell's rc file and forgotten about it, it might be getting confusing information from there.

To try out a completely "fresh" experience, create a new directory and cd into it.  then run `JULIA_DEPOT_PATH=$(pwd)/.julia julia --project=$(pwd)`, and then the first thing you do is try to do `using Pkg; Pkg.add("Oscar")`

**Comment by Tracque** [comment]
That did the trick. For some reason, I configured the path to point to a directory that didn't exist. (Probably from a previous project that I've since gotten rid of, given that it was that way on both machines I tested)

Thanks for the help!
