### ISSUE TITLE
Rings/solving.jl: Tests getting stuck / taking very long

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#3956]
Since this afternoon I have seen several cases of the `short` test group getting stuck for up to two hours and then being cancelled.
The last test file that is run is: 
```
Starting tests for /home/runner/work/Oscar.jl/Oscar.jl/test/Rings/solving.jl
```

It happens across julia versions:
- 1.6, ubuntu: https://github.com/oscar-system/Oscar.jl/actions/runs/10011330202/job/27674510038#step:9:1480
- 1.10, ubuntu: https://github.com/oscar-system/Oscar.jl/actions/runs/10011647460/job/27676040035?pr=3819#step:9:2125
- 1.10, ubuntu: https://github.com/oscar-system/Oscar.jl/actions/runs/10009331751/job/27668001340
- nightly, ubuntu: https://github.com/oscar-system/Oscar.jl/actions/runs/10011330202/job/27674512650

Haven't seen this on macos but this might be due to most tests running on ubuntu.
For >= 1.10 one might need to open the raw log to find the last `Starting tests` line since the github UI gets overwhelmed with 2 hours of GC logging ....

The first case I have noticed seems to be 16:02.

There are also cases where it did succeed but it took very long, e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/10010715115/attempts/1#summary-27672516893:

|                                                        Filename | Runtime in s | + Compilation | + Recompilation | Allocations in MB |
|-----------------------------------------------------------------|--------------|---------------|-----------------|-------------------|
|                                           test/Rings/solving.jl |      4088.61 |       3.97133 |             0.0 |         2.37796e6 |

```
-> Testing test/Rings/solving.jl took: runtime 4088.613 seconds + compilation 3.971 seconds
 + recompilation 0.0 seconds, 2.268 TiB
```
That is quite a bit of allocations ... usually the elliptic surface file has the most allocations with something like `134.462 GiB`.

Might be related to AlgebraicSolving or msolve updates? @ederc

**Comment by ederc** [comment]
Seems to come from the new `msolve` version, I will make a short fix disabling the test for issue #1743 until we have a fix in `msolve` ready.
