### ISSUE TITLE
Create experimental PR using GroupsCore.jl 

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#399]
There's been some talk on a unified interface for groups, done in https://github.com/kalmarek/GroupsCore.jl -- thanks to @kalmarek for kicking it off, and to @albinahlback and @ThomasBreuer for contributing to the discussion, and for @thofma for sharing his thoughts as well -- more input welcome (and sorry if I forgot some).

Anyway, in order to move forward, I think it would be useful to start an experimental PR to Oscar.jl which uses GroupsCore, and changes Oscar.jl to use it properly, and to also use the "conformance tests" it provides. This way, we'll hopefully more quickly converge with the interface and integration.

I call it "experimental" because we may end up moving GroupsCore into AbstractAlgebra, or something like that; but then still >95% of that PR would hopefully remain usable, so it would not be a waste.

**Comment by fieker** [comment]
On Wed, Apr 07, 2021 at 05:12:31AM -0700, Max Horn wrote:
> There's been some talk on a unified interface for groups, done in https://github.com/kalmarek/GroupsCore.jl -- thanks to @kalmarek for kicking it off, and to @albinahlback and @ThomasBreuer for contributing to the discussion, and for @thofma for sharing his thoughts as well -- more input welcome (and sorry if I forgot some).
> 
> Anyway, in order to move forward, I think it would be useful to start an experimental PR to Oscar.jl which uses GroupsCore, and changes Oscar.jl to use it properly, and to also use the "conformance tests" it provides. This way, we'll hopefully more quickly converge with the interface and integration.
> 
> I call it "experimental" because we may end up moving GroupsCore into AbstractAlgebra, or something like that; but then still >95% of that PR would hopefully remain usable, so it would not be a waste.
> 

Just be careful to not get caught in the discussion about MutableAlgebra
- which we do not want at this point I think

**Comment by ThomasBreuer** [comment]
I am working on such an experiment. (See kalmarek/GroupsCore.jl/issues/24.)

**Comment by kalmarek** [comment]
@ThomasBreuer great to hear! I just merged recent developments into master, and I'm waiting for registration pull to merge

EDIT: It's done now
