### ISSUE TITLE
Crashes with empty ideals in Singular

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#3992]
To reproduce:
```julia
P, (x, y) = QQ[:x, :y]
I = ideal(P, elem_type(P)[])
radical_membership(x, I) # Boom!
```
~Fixed in #3988 .~ Fixed in #3995.

It might be worthwhile to investigate this nevertheless. The crash looked really bad with memory access issues in the singular kernel. Maybe something else should also be fixed on another level? (ping @hannes14 )

**Comment by fingolfin** [comment]
Resolved now but @HechtiDerLachs wanted to talked with @hannes14 to see if there is more problems with zero ideals ...

@afkafkafk13 points out that having an empty list of generators might be a problem for Singular. So maybe the code which translates our ideals into Singular ideals should also be adjusted to work with ideals with empty generators?

@hannes14 will take a look

**Comment by thofma** [comment]
From triage: The original issue is fixed. If we find a new error due to "empty ideals", a new issue should be created.
