### ISSUE TITLE
StackOverflowError when computing `roots` of a polynomial over `algebraic_closure(QQ)`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#4007]
I am getting a StackOverflowError when computing `roots` of a polynomial over `algebraic_closure(QQ)`:

```
julia> K = algebraic_closure(QQ)
Field of algebraic numbers

julia> R,x = K["x"]
(Univariate polynomial ring in x over QQBar, x)

julia> f = x-1
x + Root -1.00000 of x + 1

julia> roots(f)
ERROR: StackOverflowError:
Stacktrace:
     [1] factor(a::AbstractAlgebra.Generic.Poly{QQBarFieldElem})
       @ Hecke ~/.julia/packages/Hecke/gMNzj/src/Misc/Integer.jl:179
     [2] factor(x::AbstractAlgebra.Generic.Poly{QQBarFieldElem})
       @ Hecke ~/.julia/packages/Hecke/gMNzj/src/Hecke.jl:202
     [3] factor(a::AbstractAlgebra.Generic.Poly{QQBarFieldElem}; b::@Kwargs{})
       @ Hecke ~/.julia/packages/Hecke/gMNzj/src/Misc/Integer.jl:179
--- the last 2 lines are repeated 26659 more times ---
 [53322] factor(x::AbstractAlgebra.Generic.Poly{QQBarFieldElem})
       @ Hecke ~/.julia/packages/Hecke/gMNzj/src/Hecke.jl:202
```

I don't think computing roots of polynomials over `QQBarField()` is currently supported in flint.  If it isn't, can we return a more verbose error than StackOverflowError? E.g., something that states that this operation is currently not supported.

**Comment by thofma** [comment]
We added `factor` last month (https://github.com/thofma/Hecke.jl/pull/1559), which is basically root finding. I will add the `roots` function.

**Comment by thofma** [comment]
Will be added in https://github.com/thofma/Hecke.jl/pull/1575

**Comment by thofma** [comment]
Should be fixed on master (after `]up`).

**Comment by YueRen** [comment]
Can confirm that it works, thanks!
