### ISSUE TITLE
Wrong links in documentation

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#4009]
Working on  https://github.com/oscar-system/Oscar.jl/pull/3923, I realized that some references in the docu consistently link to the wrong function with the same name.  Take for example the documentation on polyhedral complexes:
https://docs.oscar-system.org/dev/PolyhedralGeometry/polyhedral_complexes/

1. ``[`lineality_space`](@ref)`` keeps referring to the same-named function for polyhedra (see [this](https://docs.oscar-system.org/dev/PolyhedralGeometry/polyhedral_complexes/#rays_modulo_lineality-Union{Tuple{PolyhedralComplex{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20FieldElem}) docu entry)
2. ``[`rays`](@ref)`` keeps referring to the same-named function for K3 surfaces (see [this](https://docs.oscar-system.org/dev/PolyhedralGeometry/polyhedral_complexes/#rays_modulo_lineality-Union{Tuple{PolyhedralComplex{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20FieldElem}) docu entry)
3. ``[`rays_modulo_lineality`](@ref)`` keeps referring to the same-named function for polyhedra (see [this](https://docs.oscar-system.org/dev/PolyhedralGeometry/polyhedral_complexes/#rays-Union{Tuple{PolyhedralComplex{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20FieldElem}) docu entry)
4. ``[`vertices`](@ref)`` links to the same-named function for FTheory (see [this](https://docs.oscar-system.org/dev/PolyhedralGeometry/polyhedral_complexes/#rays-Union{Tuple{PolyhedralComplex{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20FieldElem}) docu entry)

(``[`minimal_faces`](@ref)`` suffers from the same problem, it links to the same-named function for polyhedra)

In all three cases, I have tried specifying the input type like ``[`rays(::PolyhedralComplex)`](@ref)``, with mixed results (worked for `vertices`, does not work for others).  Is this a bug in julia's documentation system or am I using it wrong?

**Comment by thofma** [comment]
Doing the ``[`rays(::PolyhedralComplex)`](@ref)`` dance should work according to https://github.com/JuliaDocs/Documenter.jl/issues/569. Does `rays(::PolyhedralComplex)` do the right thing inside a `@docs` block?

**Comment by YueRen** [comment]
No it doesn't.  Is there a way for you to see the docu of https://github.com/oscar-system/Oscar.jl/pull/3923 without building it yourself?  If yes, you can check the Tropical Geometry -> Tropical Varieties docu.  Tropical varieties inherit several functions from polyhedral complexes and I've tried linking to them in the @docs blocks with mixed results.

**Comment by thofma** [comment]
Yes, everyone can see it. There is a preview build (click the details link on the last item of the CI list).

**Comment by YueRen** [comment]
I think we have to be super precise with what we write in the first line of \@doc. For example, I had to do the following changes in order to fix the documentation for vertices: https://github.com/oscar-system/Oscar.jl/pull/3923/commits/7b5e03493703dc29fe5623dca74776f19278b51d

Compare that to the current documentation of polyhedral complexes where
- [the vertices entry](https://docs.oscar-system.org/stable/PolyhedralGeometry/polyhedral_complexes/#vertices-Tuple{PolyhedralComplex}) is listing the wrong vertices function
- [the vertices reference in the rays entry](https://docs.oscar-system.org/stable/PolyhedralGeometry/polyhedral_complexes/#rays-Union{Tuple{PolyhedralComplex{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20FieldElem}) refers to FTheoryTools

The only problem is, while ``[`vertices(as::Type{PointVector{T}}, PC::PolyhedralComplex{T}) where {T<:scalar_types}`](@ref)`` makes the link work, it looks somewhat ugly in the manual.

**Comment by lgoettgens** [comment]
The first line of `@doc` is completely irrelevant for the documentation generation. What's important is, is that the line in the markdown file to include the docstring or, similarly, to reference another docstring, matches exactly the signature of the method with the wished for docstring. It is not important that the signature of the method is equivalent to the first line of the `@doc` block (that can e.g. be adapted to be more human-readable, as the previous version of https://github.com/oscar-system/Oscar.jl/commit/7b5e03493703dc29fe5623dca74776f19278b51d#r145394738 did)

**Comment by thofma** [comment]
I don't think it has to match it exactly, see https://github.com/JuliaDocs/Documenter.jl/issues/839. Apparently I found out, that 6 years ago one could do `Documenter.DocSystem.getdocs(Documenter.DocSystem.binding(Main, :foo), Tuple{A{T} where {T}})` to find out what `@docs foo(A{T}) where {T}` will include. Not sure if this is still working, but might come in handy if it still does.

**Comment by YueRen** [comment]
Is there a systematic way of fixing this issue?  If not, I will try to fix whatever I can in polyhedral geometry + tropical geometry by going through the docu manually in https://github.com/oscar-system/Oscar.jl/pull/3923

**Comment by thofma** [comment]
I don't think there is an issue. Using `[rays]@(ref)` is ambiguous, so one has to specify which method/docstring should be included (I have not figured out which method is used if none is specified, but it is rarely the one you want). To get the right docstring, one has to provide the same thing as in the `@docs` block. Then one runs into the annoying bugs associated with this, which makes this so painful if there are plenty of methods for the same function.

One option would be to have a `@betterref` version, which has the same input, but which removes the signature in the output.

**Comment by thofma** [comment]
OK, forget about `@betterref`. Just use
```
[`vertices`](@ref vertices(as::Type{PointVector{T}}, PC::PolyhedralComplex{T}) where {T<:scalar_types})
```
One can specify the target of the reference, see https://documenter.juliadocs.org/stable/man/syntax/#Named-@refs.

**Comment by YueRen** [comment]
> OK, forget about `@betterref`. Just use
> 
> ```
> [`vertices`](@ref vertices(as::Type{PointVector{T}}, PC::PolyhedralComplex{T}) where {T<:scalar_types})
> ```
> 
> One can specify the target of the reference, see https://documenter.juliadocs.org/stable/man/syntax/#Named-@refs.

Does that work?  I remember trying exactly that yesterday evening and the link was created but led to a page that did not exist.

**Comment by YueRen** [comment]
I will be closing this, as I have fixed the passages that I noticed.  For future reference, please use the following tool to find the right thing to add after `@ref`: https://github.com/thofma/WhereIsMyDocstring.jl/
