### ISSUE TITLE
Streamline `FreeAssAlgebra` and `Hecke.AssociativeAlgebraElem`

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#4043]
At the Friday meeting today it was discussed that while @Sequenzer works on associative algebras in Oscar, we can use the opportunity to streamline the already existing things in AbstractAlgebra and Hecke (both naming and interface).
From a first look, there seems to be:
- `AbstractAlgebra.FreeAssAlgebra`
- `AbstractAlgebra.FreeAssAlgElem`
- `Hecke.AbstractAssociativeAlgebraElem`
- `Hecke.AssociativeAlgebraElem`

I haven't checked what all of them offer, what the differences are, possibilities, etc. This issue exists just to have some place for discussions.

cc @Sequenzer @thofma @micjoswig @fieker

**Comment by thofma** [comment]
I think we can just rename `FreeAssAlgebra` to `FreeAssociativeAlgebra` and similar for the element. They have nothing else in common that would warrant an "interface".

**Comment by fieker** [comment]
@lgoettgens is promising a resolution by this afternoon... hold thumbs
(it just a renaming)

**Comment by lgoettgens** [comment]
The renaming of the two AA types is done in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1779.

What remains is to rename `FreeAssAlgIdeal` to `FreeAssociativeAlgebraIdeal`. Since this would create a hell of a lot of conflicts with https://github.com/oscar-system/Oscar.jl/pull/4035, I would ask @Sequenzer to include this change in https://github.com/oscar-system/Oscar.jl/pull/4035. It should be a simple search-and-replace and adding `Base.@deprecate_binding FreeAssAlgIdeal FreeAssociativeAlgebraIdeal` to the bottom of `deprecations.jl`.

**Comment by micjoswig** [comment]
Indeed, @Sequenzer please do as proposed.

> What remains is to rename `FreeAssAlgIdeal` to `FreeAssociativeAlgebraIdeal`. Since this would create a hell of a lot of conflicts with #4035, I would ask @Sequenzer to include this change in #4035. It should be a simple search-and-replace and adding `Base.@deprecate_binding FreeAssAlgIdeal FreeAssociativeAlgebraIdeal` to the bottom of `deprecations.jl`.

**Comment by Sequenzer** [comment]
I would wait for the changes in AbstractAlgebra to propagate to OSCAR. But then I will do it.

**Comment by lgoettgens** [comment]
It's already available as AA 0.42.3. You just need to update the compat entry in Oscar's Project.toml.
