### ISSUE TITLE
`small_generating_set` for matrix groups benefits from computing the order?

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#4063]
I was very excited to find `small_generating_set` for groups. However, for matrix groups it seems to work better (better := produce a smaller set), if one first computes the order.

Without computing the order, one gets basically the generators back:
```
julia> K, a = cyclotomic_field(5, "a");

julia> G = matrix_group([matrix(K, [-1 0 0 0; -a^3-a^2 1 0 0; 0 0 1 0; 0 0 0 1]),
                         matrix(K, [1 -a^3-a^2 0 0; 0 -1 0 0; 0 1 1 0; 0 0 0 1]),
                         matrix(K, [1 0 0 0; 0 1 1 0; 0 0 -1 0; 0 0 1 1]), 
                         matrix(K, [1 0 0 0; 0 1 0 0; 0 0 1 1; 0 0 0 -1])])
Matrix group of degree 4
  over cyclotomic field of order 5

julia> small_generating_set(G)
4-element Vector{MatrixGroupElem{AbsSimpleNumFieldElem, AbstractAlgebra.Generic.MatSpaceElem{AbsSimpleNumFieldElem}}}:
 [-1 0 0 0; -a^3-a^2 1 0 0; 0 0 1 0; 0 0 0 1]
 [1 0 0 0; 0 1 0 0; 0 0 1 1; 0 0 0 -1]
 [1 0 0 0; 0 1 1 0; 0 0 -1 0; 0 0 1 1]
 [1 -a^3-a^2 0 0; 0 -1 0 0; 0 1 1 0; 0 0 0 1]
```
If one first triggers the order computation, the set is smaller:
```
julia> G = matrix_group([matrix(K, [-1 0 0 0; -a^3-a^2 1 0 0; 0 0 1 0; 0 0 0 1]),
                         matrix(K, [1 -a^3-a^2 0 0; 0 -1 0 0; 0 1 1 0; 0 0 0 1]),
                         matrix(K, [1 0 0 0; 0 1 1 0; 0 0 -1 0; 0 0 1 1]), 
                         matrix(K, [1 0 0 0; 0 1 0 0; 0 0 1 1; 0 0 0 -1])])
Matrix group of degree 4
  over cyclotomic field of order 5

julia> order(G)
14400

julia> small_generating_set(G)
2-element Vector{MatrixGroupElem{AbsSimpleNumFieldElem, AbstractAlgebra.Generic.MatSpaceElem{AbsSimpleNumFieldElem}}}:
 [-a^3-a^2+1 -a^3-a^2+1 1 0; 2*a^3+2*a^2-1 2*a^3+2*a^2-1 a^3+a^2-1 -1; 0 -1 0 0; -2*a^3-2*a^2+2 -3*a^3-3*a^2+2 -2*a^3-2*a^2+1 -a^3-a^2+1]
 [0 -1 0 0; a^3+a^2-1 a^3+a^2-1 a^3+a^2-1 -1; -2*a^3-2*a^2+2 -3*a^3-3*a^2+2 -2*a^3-2*a^2+2 -a^3-a^2+1; 2*a^3+2*a^2-1 2*a^3+2*a^2-2 a^3+a^2-2 a^3+a^2-1]
```
This is of course just one example. Would it be reasonable to always trigger an order computation on the OSCAR side for matrix groups?
CC @ThomasBreuer @fingolfin

**Comment by lgoettgens** [comment]
We already do this in `describe` in https://github.com/oscar-system/Oscar.jl/blob/0fc7ce71c90545a534290625c227be5328971abf/src/Groups/GAPGroups.jl#L2412-L2415 (x-ref https://github.com/oscar-system/Oscar.jl/issues/2050).

**Comment by ThomasBreuer** [comment]
In fact, one needs "only" the information that the group is finite in order to get the better `small_generating_set` result.
There are several functions for matrix groups that work better when one knows that the group is finite.

Still, one difference between `small_generating_set` and `describe` is that the former wants to be cheap, whereas the latter is known to be expensive (in general).
Thus I am not sure that we want to force a finiteness (or even order) computation in `small_generating_set`.

Perhaps it is better to suggest that if one works with matrix groups over infinite base rings and if one knows (or suspects) that these groups are finite, then one should set the finiteness flag (or ask whether the group is indeed finite) in the beginning.

**Comment by joschmitt** [comment]
> Still, one difference between `small_generating_set` and `describe` is that the former wants to be cheap, whereas the latter is known to be expensive (in general). Thus I am not sure that we want to force a finiteness (or even order) computation in `small_generating_set`.

That sounds reasonable, I didn't know that `small_generating_set` is designed to be cheap.

> Perhaps it is better to suggest that if one works with matrix groups over infinite base rings and if one knows (or suspects) that these groups are finite, then one should set the finiteness flag (or ask whether the group is indeed finite) in the beginning.

The question is just *where* to suggest this... If, as you say, several functions benefit from knowing whether the group is finite, then the only meaningful place would be somewhere in the general documentation on matrix groups. But there, nobody will find it...

**Comment by ThomasBreuer** [comment]
@fingolfin and I have discussed the situation today. The point seems to be that for matrix groups over infinite base domains, the check for finiteness can be regarded as not too expensive in Oscar. This means that it makes sense to add a finiteness check to `small_generating_set` before delegating to GAP, similar to the situation in `describe`.
I will create a pull request for this change.

The same argument holds for other functions dealing with matrix groups, but there seems to be no good place for a general treatment.
