### ISSUE TITLE
Iterator for minors of a matrix

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#4169]
I quite often find myself needing to go through the minors of large symbolic matrices for search for one minor that has a certain property. In this scenario, it's usually not a great idea to use the `minors` command, since this computes a vector of _all_ minors, which can take up a lot of time and memory.

Instead, I usually construct an own iterator in the following way:

```
function minors_iterator(M::MatElem, k::Int)
    row_indices = AbstractAlgebra.combinations(nrows(M), k)
    col_indices = AbstractAlgebra.combinations(ncols(M), k)
    return ( det(M[rows,cols]) for rows in row_indices for cols in col_indices )
end
```

Is there a built-in way of doing this? 

If not, could it make sense to add something like the function above in `AbtractAlgebra.jl`?

**Comment by lgoettgens** [comment]
I cannot see any reason why this shouldn't be useful, so please go ahead, thanks!
You could then even replace the existing `minors` function in AA by `collect(minors_iteraotr(A, k))`
