### ISSUE TITLE
Iterator over rows / columns of a matrix

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#4175]
I often find myself wanting to iterate over all rows or columns of a matrix. For matrices of type `AbstractMatrix`, there are commands `eachrow` and `eachcol` in native Julia that can be used for this. 

Is there something similar in AbstractAlgebra/Oscar? 

And if not, could it make sense to just add something, for instance something along the following lines?

```julia
rows(A::MatElem) = (A[i, :] for i in 1:nrows(A))
cols(A::MatElem) = (A[:, i] for i in 1:ncols(A))
```

**Comment by joschmitt** [comment]
If we want this, then I would say that we should use `view(A, i, :)` and not `A[i, :]` (similar to what Julia seems to do for `eachrow`). A first test seems to confirm that we even could use Julia's `Slices` object for this and literally do the same as `eachrow`.

**Comment by oskarhenriksson** [comment]
If implementing something completely analogous to `eachrow` and `eachcol` is doable, that would be great! (I got a bit confused about how the `Slices` object works, so I wasn't sure.)

**Comment by thofma** [comment]
It seems `eachrow(::Matrix)` does not return an iterator anymore? At least the docstring claims that. I would prefer a proper iterator if we implement `eachrow/eachcol` for Oscar matrices.

**Comment by joschmitt** [comment]
Yes, it returns such a `Slices` object which is iterable.
Our `eachrow` could look like
```
Base.eachrow(a::MatrixElem) = Slices(a, (1, :), (axes(a, 1),))
```
if we simply want to hijack `Slices`.

**Comment by thofma** [comment]
I misunderstand something before. I think the wording in the documentation for `eachrow` is unfortunate. It is still a (lazy) iterator, but before it was a generator. Also the printing of the `Slice` object is done via the array printing and thus gives the impression that all "rows" are already created (which they are not).

To summarize, I am happy to use `Slices`, but unfortunately this won't work on 1.6.
