### ISSUE TITLE
All right or left inverses of matrix

### ISSUE THREAD

**Issue by albinahlback** [oscar-system/Oscar.jl#4179]
Currently, [`is_invertible_with_inverse`](https://docs.oscar-system.org/dev/AbstractAlgebra/matrix/#is_invertible_with_inverse-Union{Tuple{MatrixElem{T}},%20Tuple{T}}%20where%20T%3C:RingElement) can give one left/right inverse of an $m \times n$ matrix. However, it would be nice if it could give *all* left/right inverses of a an unbalanced matrix.

**Comment by fieker** [comment]
On Sun, Oct 06, 2024 at 01:44:04PM -0700, Albin Ahlbäck wrote:
> Currently, [`is_invertible_with_inverse`](https://docs.oscar-system.org/dev/AbstractAlgebra/matrix/#is_invertible_with_inverse-Union{Tuple{MatrixElem{T}},%20Tuple{T}}%20where%20T%3C:RingElement) can give one left/right inverse of an $m \times n$ matrix. However, it would be nice if it could give *all* left/right inverses of a an unbalanced matrix.
> 
This could be intersting, but not under this name - it would be
type-unstable. How would you parametrize all possibilities? Ie. what do
you see the return value to be?

**Comment by albinahlback** [comment]
With my specific case in mind (matrices over the fraction field of multivariate polynomials, base ring integers), one could represent every inverse with:
- *One* matrix with new variables introduced (might get messy, however), or
- *Multiple* matrices $m_{1}, \ldots, m_{k}$, where any inverse is on the form $\lambda_{1} m_{1} + \cdots + \lambda_{k} m_{k}$ for $\lambda_{1} + \cdots + \lambda_{k} = 1$.

**Comment by fingolfin** [comment]
If $m_i, m_j$ are both (right/left) inverses of `A`, then `m_i-m_j` is in the (right/left) kernel / nullspace of `A`. Doesn't that take care of the issue?

**Comment by albinahlback** [comment]
Sure, would just be nice with some builtin functionality for this.

**Comment by albinahlback** [comment]
Hmm, I changed my mind; I agree with Max. As my suggestion would be very complex and messy, I think the best solution is to alter the docstring to give a hint to the user on how to get all inverses, given that one inverse.

**Comment by fingolfin** [comment]
Just to add, if a matrix $A$ over a field $K$ has size $m\times n$, and if $d := m - n >0$, then the nullspace $N:=\{v \in k^m : Av = 0\}$ has rank $d$. But the nullspace $U$ we are looking for is among $m \times m$ matrices, and it has rank $md$, and quickly becomes rather unwieldy. I think in practice it is often possible to work with $N$ instead of $U$ (but of course it depends on your concrete application).
