### ISSUE TITLE
Rename `minimal_generating_set` for groups to e.g. `minimum_generating_set` or `minimal_size_generating_set`?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4181]
... for some more clarify on what it does (though we should retain the old name, too, for backwards compatibility)

**Comment by afkafkafk13** [comment]
I am opposed to this:  `minimal_generating_set` is used with different signatures in different parts of Oscar. For instance also for ideals in local or graded rings.

**Comment by lgoettgens** [comment]
> I am opposed to this: `minimal_generating_set` is used with different signatures in different parts of Oscar. For instance also for ideals in local or graded rings.

Do these other examples that come to your mind return a minimal generating set w.r.t. cardinality or w.r.t. subset-relation?

**Comment by afkafkafk13** [comment]
w.r.t. cardinality -- it need not be contained in the input set of generators, it only needs to generate the same ideal.

**Comment by lgoettgens** [comment]
in this case I think that @fingolfin 's proposal to change the name (with deprecations) would extend to these versions as well. In the precise mathematical terms I learned (and it seems @fingolfin as well), `minimal` always refers to subset-relation while `minimum` and `minimal-size` to cardinality. Thus I agree with the suggestion

**Comment by thofma** [comment]
I am not a group theorist by training, but in the group theory papers that I encountered a minimal generating set always meant a generating set which is minimal in the sense of subset-relation. 

Edit: Also in the title it mentions only the method for groups.

**Comment by wdecker** [comment]
In the cases mentioned by Anne we have Nakayama's lemma which implies that a set of generators is minimal w.r.t. subset-relation iff  it is minimal w.r.t. cardinality.

In the group case, as far as I understand, we think of minimal w.r.t. inclusion. We can then speak of the minimal cardinality of a minimal generating set and for some classes of groups such sets can be reasonably computed. So one question here is what the GAP command refers to: Computing a minimal generating set or computing a `minimal_generating_set_of_minimal_cardinality`. @fingolfin Does this depend on the class of groups under consideration?

**Comment by fingolfin** [comment]
The function `minimal_generating_set` *for groups* (that's the only one I am talking about here) always computes (if it terminates...) a generating set of globally minimal cardinality. I.e. it does more than just finding a subset of the initial generating set. 

So e.g. if I take the additive group generated by 2 and 3, this is $\mathbb{Z}$, then `minimal_generating_set ` would return either $\{1\}$ or $\{-1\}$.

But I think this is contrary to the usual interpretation of "minimal" which is "minimal by inclusion (and similar for "maximal"). That is, for some kind of object "FOO" we usually mean by "$A$ is a minimal FOO" that $A$ is a FOO but no subset also is FOO. E.g. "minimal ideal" (well, I guess strictly speaking that should be "minimal non-trivial ideal", but people are used to this kind of minor impreciseness, also for e.g. "maximal subgroup" etc.)

Anyway, I bring this up because on the GAP side this has frequently lead to confusion in the past when people expected that "minimal generating set" means "minimal with respect to inclusion" (which is much cheaper than finding a minimum generating set)

**Comment by fingolfin** [comment]
Just talked with @wdecker and we agreed that `minimal_size_generating_set` is suitable: not too long and we feel most people will understand it correctly.

**Comment by thofma** [comment]
I think for groups in the literature this is called "minimum generating set". So I would throw `minimum_generating_set` in the ring.

**Comment by ThomasBreuer** [comment]
Since the question is about avoiding misunderstandings, `minimal_size_generating_set` is good from my point of view.

I do not think that there is a general consensus in the literature about the subtle difference between "minimum generating set" and "minimal generating set". As far as I see, the papers dealing with this topic define the notion they use.

(I would call a generating set that is minimal w.r.t. taking subsets irredundant.)
