### ISSUE TITLE
Documentation for elliptic curves missing.

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#4187]
I was notified that the documentation for elliptic curves is missing/hard to find in Oscar.  
There seems to be at least a little something in Hecke. Could we add that to our docs?
@JHanselman @fieker

**Comment by fingolfin** [comment]
Strictly speaking the files are there, but they are not hooked up in the navigation.

@thofma suggest to put them under "number theory".

@aaruni96 will look into that.

**Comment by fingolfin** [comment]
@aaruni96 any news on this?

**Comment by aaruni96** [comment]
Its on the to-do list for after the mardi annual workshop (18th through 20th Nov)

**Comment by aaruni96** [comment]
> There seems to be at least a little something in Hecke. Could we add that to our docs?

I think I added the right things in #4338 . Can someone confirm ?

**Comment by simonbrandhorst** [comment]
Thank you!
