### ISSUE TITLE
Upgrade to CxxWrap.jl 0.16

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4198]
What needs to be update
- [x] `libsingular_julia_jll` -- https://github.com/JuliaPackaging/Yggdrasil/pull/9610
- [ ] `Singular.jl` -- https://github.com/oscar-system/Singular.jl/pull/837
- [x] `libpolymake_julia_jll`
- [x] `polymake_oscarnumber`
- [x] `Polymake.jl`

_Originally posted by @fingolfin in https://github.com/oscar-system/Oscar.jl/issues/3904#issuecomment-2205950676_

**Comment by benlorenz** [comment]
The polymake related binaries are done, the current Polymake.jl 0.11.22 works with CxxWrap 0.14 (using older binaries) and 0.16 (with newer binaries).

**Comment by fingolfin** [comment]
Excellent. And I just made https://github.com/JuliaPackaging/Yggdrasil/pull/9610

**Comment by lgoettgens** [comment]
`] up` on the Oscar master now resolves to some combination that uses CxxWrap 0.16. So I think this is done, right?

**Comment by fingolfin** [comment]
Yes
