### ISSUE TITLE
Make a new OSCAR release?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4211]

**Comment by fingolfin** [comment]
No objections in triage, but @jankoboehm suggested we might wait for the "final" parts of module quotients to land (CC @wdecker) which is apparently due any day this week?!

**Comment by wdecker** [comment]
Module quotients have already landed, but I could add module saturations as well. I will look into ths asap.

**Comment by thofma** [comment]
Since saturations have landed, can we have a new release?

**Comment by wdecker** [comment]
> Since saturations have landed, can we have a new release?

Fine with me.

**Comment by fingolfin** [comment]
Yes
