### ISSUE TITLE
`diagonal_matrix` gives error for empty vectors

### ISSUE THREAD

**Issue by oskarhenriksson** [oscar-system/Oscar.jl#4222]
A small issue that I've had to deal with a couple of times is that I want to apply the `diagonal_matrix` command to vectors that sometimes happen to be empty, which causes the following error:

```
julia> v = QQFieldElem[]
QQFieldElem[]

julia> diagonal_matrix(v)
ERROR: BoundsError: attempt to access 0-element Vector{QQFieldElem} at index [1]
Stacktrace:
 [1] getindex
   @ ./essentials.jl:13 [inlined]
 [2] diagonal_matrix(x::Vector{QQFieldElem})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/QjFtH/src/Matrix.jl:6656
 [3] top-level scope
   @ REPL[35]:1
```

Intuitively (at least for the applications I have in mind), it would make more sense if returned a zero-by-zero matrix. Could this make sense to implement?

**Comment by joschmitt** [comment]
Unfortunately, this can't work in general because there is no way to infer the base ring just from the type of elements. For `QQFieldElem`, this would work because there is only one field of rational numbers, but for example for `FqFieldElem` or `QQMPolyRingElem`, there are many options.
However, there is
```
diagonal_matrix(R::NCRing, x::Vector{T}) where T <: NCRingElement -> MatElem{T}
```
and this does what you want:
```
julia> diagonal_matrix(QQ, QQFieldElem[])
0 by 0 empty matrix
```

**Comment by fingolfin** [comment]
However we could display a more helpful error message...

**Comment by oskarhenriksson** [comment]
Thanks!  The `diagonal_matrix(R::NCRing, x::Vector{T}) where T <: NCRingElement -> MatElem{T}` function is a great solution!

**Comment by oskarhenriksson** [comment]
Sorry, accidentally clicked close. I agree that the error message could be clarified.
