### ISSUE TITLE
Package for intersection theory

### ISSUE THREAD

**Issue by jieaosong** [oscar-system/Oscar.jl#426]
Hi!

As an effort to learn both the Julia/Oscar language, and some of the underlying details in computations of intersection theory, I wrote a new [package](https://github.com/8d1h/IntersectionTheory) in Julia. It is heavily "inspired" by the Macaulay2 package Schubert2, and also partly the Sage libraries Chow and Schubert3, although some of the more specialized stuffs are not there (yet). It certainly merits its existence since the performance is vastly improved in almost all use cases.

I originally started with Oscar, but there were too many random segfaults so I ended up minimizing the dependency to just Nemo and Singular.jl. Also since it is still in an early stage, I haven't documented it yet. But [here](https://github.com/8d1h/8d1h.github.io/blob/master/IntersectionTheory/IntersectionTheory.ipynb) is a notebook showcasing some of the usages.

This is more or less just an announcement of the package. Since I just started Julia and I've never developed/distributed a math package before, any recommendations / suggestions / harsh criticisms would be genuinely appreciated. Thanks!

**Comment by wdecker** [comment]
Hi, I am very much interested in discussing this project. How about using skype or some such. Best, Wolfram

**Comment by thofma** [comment]
In addition to that, it would be very interesting to see those "random segfaults". Do you still have a version of your package where this happend?

**Comment by jieaosong** [comment]
Wow, thanks for the feedback! Yes I would be glad to discuss in video.

I added the Oscar version to a separated branch [here](https://github.com/8d1h/IntersectionTheory/tree/oscar/oscar), which already contains most of the features except blowup.

To be honest, there are still segfaults with just Singular.jl, which I think are due to garbage collecting (it works sometime by using `GC.enable(false)`, but then it will easily crash for large examples). But Oscar's loading time after each crash is way too long, making the development really frustrating (also I tried the debug version of julia, but then Oscar simply won't build, so I just gave up).

**Comment by thofma** [comment]
Thanks. What are the commands to reproduce the segfault(s)?

**Comment by wdecker** [comment]
So, who precisely are you, in which time zone are you, and when do we talk?

**Comment by jieaosong** [comment]
> Thanks. What are the commands to reproduce the segfault(s)?

I couldn't really track it down. Sometimes even tab completion can trigger a segfault. Here is a simple command that can usually trigger it
```julia
P2 = proj(2); P5 = proj(5); h = P2.O1; v = hom(P2, P5, [2h]); v.pushforward(h)
```
If the segfault doesn't happen right away, then try quitting julia will probably do it.

**Comment by thofma** [comment]
I can reproduce it, thanks. I will have a look.

**Comment by jieaosong** [comment]
Thanks!

BTW, I just recalled something that I noticed in Oscar: the word "homogeneous" is spelled as "homogenous" in Oscar's graded ring code. In particular there are two functions `ishomogeneous` and `ishomogenous`, which might be something worth standardized...

**Comment by tthsqe12** [comment]
The random crashes in
```
P2 = proj(2); P5 = proj(5); h = P2.O1; v = hom(P2, P5, [2h]); v.pushforward(h)
```
 are probably fixed by https://github.com/oscar-system/Singular.jl/pull/421

**Comment by fingolfin** [comment]
@8d1h thanks, we should indeed be consistent about how we spell homogeneous / homogenous (even though both spellings are correct). We face similar issues with other words like `normalizer` vs. `normaliser` or `center` vs `centre` etc.

**Comment by jieaosong** [comment]
Hi! Here is an update of the project.

I tested the latest updates in Singular.jl, and they are great! All the previous crashes are gone now, and the fancy orderings work very well. I have added some [documentations](https://8d1h.github.io/IntersectionTheory/dev/) and tests for the package.

There is another thing that I noticed: in quotient rings, when to do reductions appears to have a huge impact on the overall performance. By this I mean whether we reduce the result each time we do an addition / multiplication / etc. I looked at the Oscar source code and I think currently no reduction is done at all. On the other hand, I think in Macaulay2 (probably Sage too), the result is always reduced. I don't know if there exist some good solutions already, but perform reductions only for multiplications and powers seems to be a good balance point. I made a comparison of timings [here](https://8d1h.github.io/IntersectionTheory/dev/dev/#Quotient-rings) (you can see that the difference is huge).

**Comment by fieker** [comment]
On Sat, May 15, 2021 at 02:28:41PM -0700, 8d1h wrote:
> Hi! Here is an update of the project.
> 
> I tested the latest updates in Singular.jl, and they are great! All the previous crashes are gone now, and the fancy orderings work very well. I have added some [documentations](https://8d1h.github.io/IntersectionTheory/dev/) and tests for the package.
> 
> There is another thing that I noticed: in quotient rings, when to do
> reductions appears to have a huge impact on the overall performance.
> By this I mean whether we reduce the result each time we do an
> addition / multiplication / etc. I looked at the Oscar source code and
> I think currently no reduction is done at all. On the other hand, I
> think in Macaulay2 (probably Sage too), the result is always reduced.
> I don't know if there exist some good solutions already, but perform
> reductions only for multiplications and powers seems to be a good
> balance point. I made a comparison of timings
> [here](https://8d1h.github.io/IntersectionTheory/dev/dev/#Quotient-rings)
> (you can see that the difference is huge).
> 
In general, for quotient structure, the best general compromise seem to
reduce prior to a multiplication/ division but not before/ after a sum.
Don't know if this is true in the multivaraite setting

**Comment by wdecker** [comment]
Hi,

with regard to the arithmetic in Oscar/Singular quotient fields: I agree that we should include appropriate reductions here. Well-suited series of test examples would be very helpful. Can you provide a convenient test-suite based on Chow ring examples which can become "arbitrarily large"?

Best,
Wolfram

**Comment by jieaosong** [comment]
The [old version](https://github.com/8d1h/IntersectionTheory/tree/oscar/oscar) of the package uses Oscar's `MPolyQuo`, so it can already be used as a test set. I can update it, and maybe extract just the relevant part. To get arbitrarily large example, maybe we can just use larger Grassmannians? (But there might be different quotient ring use cases that are not covered)

BTW the `homogenous_components` (before its renaming) seems to be quite slow. Here are the timings in Oscar's version, the first timing is just one call of `homogenous_components`
```julia
julia> @time grassmannian(7,14);
```
```julia
# no reduction
  7.414826 seconds (10.86 M allocations: 2.459 GiB, 3.29% gc time)
 28.588924 seconds (48.59 M allocations: 3.530 GiB, 1.68% gc time)
# Reduction after `*` and `^`
  7.332084 seconds (10.86 M allocations: 2.459 GiB, 3.58% gc time)
 12.226159 seconds (12.02 M allocations: 2.503 GiB, 2.14% gc time)
```
And here's Singular.jl-only version for comparison
```julia
# No reduction
  0.093097 seconds (818.67 k allocations: 46.213 MiB, 17.55% gc time)
 17.631392 seconds (33.44 M allocations: 812.869 MiB, 0.25% gc time)
# Reduction after `*` and `^`
  0.091750 seconds (819.07 k allocations: 46.219 MiB, 18.36% gc time)
  4.534995 seconds (1.27 M allocations: 51.637 MiB, 0.37% gc time)
```
(And I haven't tested using reduction *before* `*`. But clearly it's necessary before a division (and `==`), since otherwise the result might be wrong.)

**Comment by wdecker** [comment]
> I can update it, and maybe extract just the relevant part. To get arbitrarily large example, maybe we can just use larger Grassmannians?

That sounds good!

**Comment by wdecker** [comment]
Hi,

I am currently reading the documention --  which is actually already quite nice -- and have two quick remarks:

1)  You write:  

     and a kkk-class is an equivalent class of cycles modulo a certain equivalence.

At this point, the reader does not realize that details will be explained later. So how about writing something like

     and a kkk-class is an equivalence class of cycles modulo numerical equivalence (see below).
    
For the convenience of the beginner, could you then in the explanation  add a sentence for which application(s) precisely you need numerical equivalence (if that is not too complicated) and something in the spirit of the following taken from Eisenbud/Harris:

The class of smooth projective varieties for which the theories coincide includes any variety with an affine stratification, and in particular all products of projective spaces and Grassmannians; it includes all homogeneous spaces for affine algebraic groups; it includes any projective bundle over a variety of this class, and all blow-ups of varieties in this class along subvarieties in this class. 

2) Occasionally I found that more explicit examples might be helpful. For example, just by very quick reading, I found it hard to understand how to define specific morphisms like the one in the classical 3264 example below:

P2 = ProjectiveSpace(2)
P5 = ProjectiveSpace(5)
h = P2.hyperplane()
H = P5.hyperplane()
f = Morphism(P2,P5,[2*h])
B = Blowup(f)
E = B.exceptional_divor()
B.integral((6*H-2*E)^5)

How does this read in your package?

Best, Wolfram

**Comment by jieaosong** [comment]
Thank you very much for the suggestions!
1. Yes, I just wrote down some remarks without much consistency. This should be rewritten with the readers in mind. I will add these explanations.
2. Yes, I plan to add more basic usage examples. The 3264 example can be done as follows.
```julia
P2 = proj(2)
P5 = proj(5)
v = hom(P2, P5, [2P2.O1])
Bl, E = blowup(v)
h = pullback(Bl → P5, P5.O1)
e = pushforward(E → Bl, E(1))
integral((6h - 2e)^5)
```
I couldn't quite decide how to handle the exceptional divisor class. There could be varieties that are blowups with several steps (e.g., a del Pezzo surface), so maybe it makes more sense to apply `exceptional_divisor` to morphisms rather than varieties? Right now `blowup` returns the divisor as a variety, and its class in the blowup is obtained by pushing forward 1.

**Comment by thofma** [comment]
> BTW the `homogenous_components` (before its renaming) seems to be quite slow. Here are the timings in Oscar's version, the first timing is just one call of `homogenous_components`
> 
> ```julia
> julia> @time grassmannian(7,14);
> ```
> 
> ```julia
> # no reduction
>   7.414826 seconds (10.86 M allocations: 2.459 GiB, 3.29% gc time)
>  28.588924 seconds (48.59 M allocations: 3.530 GiB, 1.68% gc time)
> # Reduction after `*` and `^`
>   7.332084 seconds (10.86 M allocations: 2.459 GiB, 3.58% gc time)
>  12.226159 seconds (12.02 M allocations: 2.503 GiB, 2.14% gc time)
> ```
> 
> And here's Singular.jl-only version for comparison
> 
> ```julia
> # No reduction
>   0.093097 seconds (818.67 k allocations: 46.213 MiB, 17.55% gc time)
>  17.631392 seconds (33.44 M allocations: 812.869 MiB, 0.25% gc time)
> # Reduction after `*` and `^`
>   0.091750 seconds (819.07 k allocations: 46.219 MiB, 18.36% gc time)
>   4.534995 seconds (1.27 M allocations: 51.637 MiB, 0.37% gc time)
> ```
> 
> (And I haven't tested using reduction _before_ `*`. But clearly it's necessary before a division (and `==`), since otherwise the result might be wrong.)

How can I reproduce those timings (I mainly interested in the Singular.jl only vs Oscar.jl difference)?

**Comment by jieaosong** [comment]
> How can I reproduce those timings (I mainly interested in the Singular.jl only vs Oscar.jl difference)?

I added the minimal working example [here](https://github.com/8d1h/IntersectionTheory/blob/oscar/oscar/Test.jl) (which could be used as the test set). The two instances of `homogenous_components` are taking up most of the computation time... And it will be even slower if I had used `homogenous_component` for individual components...

For the reduction, I changed these two lines
https://github.com/oscar-system/Oscar.jl/blob/5fe6e4e1a628fc2ca29791f4e30fc4a92c22ab3a/src/Rings/MPolyQuo.jl#L230
to
```julia
*(a::MPolyQuoElem, b::MPolyQuoElem) = check_parent(a, b) && simplify(MPolyQuoElem(a.f*b.f, a.P))
^(a::MPolyQuoElem, b::Base.Integer) = simplify(MPolyQuoElem(Base.power_by_squaring(a.f, b), a.P))
```

**Comment by thofma** [comment]
I just optimized the `homogenous_component` a bit and now get:
```julia
julia> @time grassmannian(7,14);
  0.081963 seconds (1.51 M allocations: 59.460 MiB)
  0.000204 seconds (1.23 k allocations: 29.195 KiB)
  2.050352 seconds (13.28 M allocations: 463.830 MiB, 8.75% gc time)
```
Using in addition reduction after multiplication and powering I get:
```julia
julia> @time grassmannian(7,14);
  0.104065 seconds (1.51 M allocations: 59.460 MiB)
  0.000217 seconds (1.23 k allocations: 29.195 KiB)
  1.268494 seconds (15.97 M allocations: 366.457 MiB, 10.46% gc time)
```

P.S.: My original timings were
```julia
julia> @time grassmannian(7,14);
  3.772582 seconds (10.81 M allocations: 2.458 GiB, 5.61% gc time)
  2.085722 seconds (20.89 k allocations: 507.914 KiB)
 16.354187 seconds (48.19 M allocations: 3.522 GiB, 4.74% gc time)
```

How can I reproduce those Singular.jl only timings?

**Comment by jieaosong** [comment]
Nice! For Singular.jl, maybe just try `@time grassmannian(7,14);`?

The two instances of homogeneous components are here if you want
https://github.com/8d1h/IntersectionTheory/blob/f9b1f84e95688dbcd137eef39cc27a01d43bab2c/src/Main.jl#L793
https://github.com/8d1h/IntersectionTheory/blob/f9b1f84e95688dbcd137eef39cc27a01d43bab2c/src/Main.jl#L1071

**Comment by thofma** [comment]
For the Singular version I get
```julia
julia> @time grassmannian(7, 14);
  2.608281 seconds (1.27 M allocations: 51.624 MiB, 0.38% gc time)
```
I will make a PR with my changes.

**Comment by jieaosong** [comment]
> I will make a PR with my changes.

Thanks that would be great!

**Comment by thofma** [comment]
#446

**Comment by tthsqe12** [comment]
Timing these things must be nightmare. We have three different polynomial implementations ...

**Comment by simonbrandhorst** [comment]
Can this be closed? There seems to be a lot of intersection theory code now. @wdecker

**Comment by wdecker** [comment]
@simonbrandhorst Yes, this can be closed.

**Comment by wdecker** [comment]
We are now in a new phase of dealing with the intersection theory package.
