### ISSUE TITLE
move Weyl groups into OSCAR core

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#4263]
There are several places in the project where Weyl groups are needed.  So I would like to suggest to move those functions from Experimental/LieAlgebras into the OSCAR core.

Please spell out any conventions explicitly in the docs.  Either confirm that these agree with GAP, or state otherwise.

At that opportunity we could also make good use of the weak order (or did I overlook this?).

@lgoettgens @antonydellavecchia @ThomasBreuer @ulthiel

**Comment by lgoettgens** [comment]
I like the idea of moving them. However, there are some things that need to be worked on before moving.

- [x] documentation. there currently is basically nothing. Docstrings for Weyl groups and root systems (they are cyclically defined, so must be moved together) need to be collected on a documentation page, and enriched with some additional information and conventions (e.g. affine types not supported yet).
- [x] action direction. Currently Weyl groups operate from the left (e.g. on roots, weights, etc.), while the rest of OSCAR uses right actions. https://github.com/oscar-system/Oscar.jl/pull/4271
- [ ] Dynkin diagrams. If I recall correctly, they are also intertwined with the definition of Weyl groups and root systems. I would need to look again at them if they are already in the shape to be moved, or if they could be left in experimental for the time being.
- [ ] (after talking to @felix-roehrich): some parts of `WeylGroup.jl` and `RootSystem.jl` are not in the shape/interface yet that we want to keep forever (e.g. the docstring of `character` even says that it will change). We need to go through the files and split them into "core functionality" (that can be moved) and "other things" (that are still experimental, but not needed for the core things).
- [x] a pending discussion with @felix-roehrich about some type internals of roots and weights. https://github.com/oscar-system/Oscar.jl/pull/4271
- [x] printing. Currently, Cartan matrices are always printed, the type is missing. OSCAR's 3 modes need to be implemented. https://github.com/oscar-system/Oscar.jl/pull/4271

additionally pinging @felix-roehrich @fingolfin

**Comment by fingolfin** [comment]
I would love to talk to you (Lars) a little bit about this, though ideally in a video call and not on a GitHub issue. Perhaps we can find some time tomorrow or Friday? we can try coordinate on Slack.

Just a general comment: it doesn't have to be perfect to be moved, e.g. docs, printing and "more features" could also be taken care of after a move, too. But of course central things like "from where to act" need to be settled before we bake it in.

**Comment by micjoswig** [comment]
pinging @antonydellavecchia @flenzen because the changes here could be relevant for algebraic shifting

**Comment by lgoettgens** [comment]
I, finally, opened a PR for moving most of Weyl groups and root systems from experimental to src. Please see the description of https://github.com/oscar-system/Oscar.jl/pull/4399 for a list of moved / non-moved features and my proposed timeline.
