### ISSUE TITLE
Release Oscar 1.2.1

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4291]
@thofma point out that we fixed at least one regression since 1.2.0 which should be quickly released. Fine by me. I think the process will be to cherry-pick it and possible more onto the `release-1.2` branch in close coordination with @benlorenz. I suggested we create a list of PRs here that we'd like to see backported. Please feel free to add issues to this list, or to propose them in the comments.

We can then decide e.g. next Wednesday if the list is complete and we want to release.

- #4277
- https://github.com/oscar-system/Oscar.jl/pull/4270
- https://github.com/oscar-system/Oscar.jl/pull/4282
- https://github.com/oscar-system/Oscar.jl/pull/4299
- https://github.com/oscar-system/Oscar.jl/pull/4257 ?
- https://github.com/oscar-system/Oscar.jl/pull/4279 ?

**Comment by fingolfin** [comment]
I see several PRs were added by @lgoettgens . I assume triage agreed on those.

But was there also a discussion how and when and who will do this? Perhaps "someone" should open a PR for the release-1.2 branch with backports of these PR?

**Comment by lgoettgens** [comment]
> I see several PRs were added by @lgoettgens . I assume triage agreed on those.

No. At triage we only reminded everyone that we are planning a 1.2.1 release. The changes above were just by me looking through the recently merged PRs what I thought would be fine to backport.
Either triage next week or @benlorenz / @aaruni96 would need to decide that these are indeed the ones we want to backport.

> But was there also a discussion how and when and who will do this? Perhaps "someone" should open a PR for the release-1.2 branch with backports of these PR?

@benlorenz wanted to take care of this iirc

**Comment by lgoettgens** [comment]
I think it would be great if we could include https://github.com/oscar-system/Oscar.jl/pull/4321 and [`9140f6d` (#4325)](https://github.com/oscar-system/Oscar.jl/pull/4325/commits/9140f6de3b5c1d90139a11c60f6afd16b0ca1bfd) as well.

**Comment by benlorenz** [comment]
> I think it would be great if we could include #4321 and [`9140f6d` (#4325)](https://github.com/oscar-system/Oscar.jl/pull/4325/commits/9140f6de3b5c1d90139a11c60f6afd16b0ca1bfd) as well.

Done (for the first one only one of the two markers was missing on the release branch).
