### ISSUE TITLE
Missing `eigenvalues` for matrices over integers

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4330]
Just stumbled over this when demoing OSCAR:
```
julia> eigenvalues(identity_matrix(ZZ,3))
ERROR: MethodError: no method matching eigvals(::ZZMatrix)
The function `eigvals` exists, but no method is defined for this combination of argument types.
```

**Comment by lgoettgens** [comment]
We seem to have generic eigenvalue machinery in https://github.com/lgoettgens/Nemo.jl/blob/52ef106a39f4c37830756cb45411401fd8bcdcbc/src/matrix.jl#L206-L293, but this is restricted to `MatElem{<:FieldElem}`.

**Comment by thofma** [comment]
I see no harm widening the signature for the `eigenvalue*` functions to allow `RingElem`.

**Comment by fingolfin** [comment]
Perhaps @JohnAAbbott could look into doing that

**Comment by JohnAAbbott** [comment]
I could add a "one-liner" which simply calls `fraction_field` and then delegates to the existing eigenvalue function(s) which expect matrices over fields.  Is this what you have in mind?  I note that there is already `eigenvalues_with_multiplicities(L::Field, M::MatElem{T}) where T <: RingElem`  according to Julia's `?` operator.
The homonymous function `  eigenvalues_with_multiplicities(M::MatElem{T}) where T <: FieldElem` computes "rational" eigenvalues _i.e._ without making any field extension.
**What type of answer do we expect `eigenvalue` to return for a matrix with `ZZ` entries?**

**Comment by thofma** [comment]
No, it should not delegate to the fraction field. The signature of the functions that take `FieldElem` just needs to be widened to accept `RingElem`.
