### ISSUE TITLE
Problem with issquare_with_square_root

### ISSUE THREAD

**Issue by delphinepol** [oscar-system/Oscar.jl#434]
It seems that there is a problem with the function "issquare_with_square_root", since 5 is not the square of 0 in Z/15Z : 

``` 
julia> R = ResidueRing(ZZ, ZZ(15))
Integers modulo 15

julia> issquare_with_square_root(R(5))
(true, 0)
```

**Comment by fieker** [comment]
On Wed, May 12, 2021 at 07:36:22AM -0700, delphinepol wrote:
> It seems that there is a problem with the function "issquare_with_square_root", since 5 is not the square of 0 in Z/15Z : 
> 
> ``` 
> julia> R = ResidueRing(ZZ, ZZ(15))
> Integers modulo 15
> 
> julia> issquare_with_square_root(R(5))
> (true, 0)
> ``` 
Unfortunately, I believe that this functio never worked in the presence
of zero divisors....
Taking square roots is essentially equivalent to factoring the modulus.

**Comment by thofma** [comment]
I think we can fix it. I think @tthsqe12 provided some root functionality for composite moduli. But it seems it is not properly hooked up.

**Comment by tthsqe12** [comment]
@thofma I thought you already wrapped fmpz_mod_poly_roots_factored. For small n, there is http://flintlib.org/doc/ulong_extras.html#c.n_sqrtmodn but passing the arguments looks horrendous.

**Comment by thofma** [comment]
Yes, is is wrapped (somewhere). The question is now whether we always want to factor the modulus?

**Comment by tthsqe12** [comment]
Eh, what are you going to do. Gotta factor the modulus. maybe the factorization could be cached?

**Comment by thofma** [comment]
We could throw an error and refer to the method `issquare_with_square_root(a::nmod, f::Fac{fmpz})`? I am also happy to cache the factorization.

**Comment by tthsqe12** [comment]
I would cache the factorization.
For nmod, you will have to populate an n_factor_t and then call n_sqrtmodn or nmod_poly_roots_factored. Or, cast to fmpz_mod

For fmpz_mod, populate an fmpz_factor_t and fmpz_mod_poly_roots_factored.

The current function in Hecke is assuming the modulus is prime.

**Comment by fingolfin** [comment]
The equivalent of this nowadays just seems to produce a method not found error?
```
julia> R, _ = residue_ring(ZZ, ZZ(15))
(Integers modulo 15, Map: ZZ -> ZZ/(15))

julia> is_square_with_sqrt(R(5))
ERROR: MethodError: no method matching is_square(::ZZModRingElem)

Closest candidates are:
  is_square(::FqMPolyRingElem)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/flint/fq_default_mpoly.jl:279
  is_square(::FqPolyRepFieldElem)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/flint/fq.jl:385
  is_square(::FpMPolyRingElem)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/flint/fmpz_mod_mpoly.jl:561
  ...

Stacktrace:
 [1] is_square_with_sqrt(a::ZZModRingElem)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/wVuNz/src/Rings.jl:170
 [2] top-level scope
   @ REPL[161]:1
```

**Comment by fingolfin** [comment]
So the wrong result is gone, and now we are just missing an implementation for this case. But if someone needs it, they'll see that error and can request it (or just implement something).
