### ISSUE TITLE
`libsingular_julia.so: undefined symbol` in CI

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#4341]
Since about an hour ago, all CI jobs of Oscar fail with
```
/opt/hostedtoolcache/julia/1.10.6/x64/bin/julia: symbol lookup error: /home/runner/.julia/artifacts/cf0ff4f151918145bd7c13270aae66e73a2cc2d9/lib/libsingular_julia.so: undefined symbol: _Z4kStdP10sip_sidealS0_6tHomogPP6intvecS3_iiS3_PFiP10skStrategyE
Package Oscar errored during testing (exit code: 127)
```
As this error mentions singular, and there has been a release of Singular_jll at about that time, I suspect this to correlate somehow.

ping @hannes14

**Comment by benlorenz** [comment]
That symbol seems to point to the old `intvec` version of `kstd`:
https://github.com/Singular/Singular/commit/fdca75298a0343daa1ccc375fae787b4c2b638e2#diff-e0d539743ed77af80cf62b0c1cb0242fe497fcb6b72bb74e179c68485ee6d91fL41-R42

**Comment by fingolfin** [comment]
`c++filt` says:
```
kStd(sip_sideal*, sip_sideal*, tHomog, intvec**, intvec*, int, int, intvec*, int (*)(skStrategy*))
```

**Comment by benlorenz** [comment]
Similar error again with the new version (Singular_jll v404.0.708) but with a different symbol, 
`_Z8kMin_stdP10sip_sidealS0_6tHomogPP6intvecRS0_S3_ii`:
```
kMin_std(sip_sideal*, sip_sideal*, tHomog, intvec**, sip_sideal*&, intvec*, int, int)
```
https://github.com/oscar-system/Oscar.jl/actions/runs/11973443988/job/33401803885?pr=4286#step:8:527

**Comment by fingolfin** [comment]
@hannes14 made a new release fixing that but now it fails in
```
idElimination(sip_sideal*, spolyrec*, intvec*, GbVariant)
```

**Comment by fingolfin** [comment]
In addition `libsingular-julia` cannot be built against the current `Singular_jll`, the errors (see https://github.com/JuliaPackaging/Yggdrasil/pull/9839) suggest that also `kStd` has a breaking change.

I would suggest that for further changes we stop the whack-a-mole and the new Singular commit is first tested locally. One way how to do this is described in `README.maintainer.md` inside the `Singular.jl` repository, in the final section `Building a custom `Singular_jjl` locally`

**Comment by thofma** [comment]
Can we revert whatever started this to get a working Oscar again?

**Comment by fingolfin** [comment]
Yeah we should yank the last couple bad Singular_jll releases. Unfortunately I can't access a computer right now to do it (maybe later today if nobody beats me to it)

**Comment by hannes14** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/9851 works locally with the tests of Singular.jl and Oscar.jl

**Comment by thofma** [comment]
I think it broke the doctests, so this release of Singular_jll is still breaking Oscar development.

See: https://github.com/oscar-system/Oscar.jl/actions/runs/11983625740/job/33427069919

**Comment by lgoettgens** [comment]
Would it be possible to revert all of these Singular_jll versions from the last days asap? Until this is fixed, we have failures in CI, see https://github.com/oscar-system/Oscar.jl/actions/runs/12002618979/job/33454875472#step:8:944
