### ISSUE TITLE
Problem with sqrtmod with powers of 2

### ISSUE THREAD

**Issue by delphinepol** [oscar-system/Oscar.jl#437]
The function sqrtmod does not find a square root of -7 mod 1024 and throws an error that such a square root does not exist, whereas one can find one (deduced from a square root modulo 512 using the formula given on https://math.stackexchange.com/questions/845486/square-roots-modulo-powers-of-2 ).

```
S = ResidueRing(ZZ, ZZ(1024))
Integers modulo 1024

julia> sqrtmod(ZZ(-7), ZZ(1024))
ERROR: no square root exists
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] sqrtmod(::fmpz, ::fmpz) at /home/pol/.julia/packages/Nemo/BMnm6/src/flint/fmpz.jl:845
 [3] top-level scope at REPL[3]:1

julia> S(75 + 256*11)^2 == S(-7)
true
```

**Comment by fieker** [comment]
On Fri, May 14, 2021 at 04:32:56AM -0700, delphinepol wrote:
>  The function sqrtmod does not find a square root of -7 mod 1024 and throws an error that such a square root does not exist, whereas one can find one (deduced from a square root modulo 512 using the formula given on https://math.stackexchange.com/questions/845486/square-roots-modulo-powers-of-2 ).
> 
-7 = 1 mod 8, thus -7 is a square in Z_2 thus as well in Z/2^1024...
Newton iteration will find it....

**Comment by delphinepol** [comment]
I know that it is supposed to be possible to compute it, but I wanted to point out that the function was not able to compute the square root mod 1024, whereas it was able to compute it mod 512. By the way, is there something for Newton iteration in Oscar ?

**Comment by fieker** [comment]
On Mon, May 17, 2021 at 12:33:09AM -0700, delphinepol wrote:
> I know that it is supposed to be possible to compute it, but I wanted to point out that the function was not able to compute the square root mod 1024, whereas it was able to compute it mod 512. By the way, is there something for Newton iteration in Oscar ?
> 
I've implemented many many newton iterations in Oscar. In your
appliation, the "best" is probably in examples/PerfectPowers.jl

_root_exact(a, n) computes the n-the root of a modulo powers of 2 (for
units)
You cannot use it directly I think, but it contains a Newton iteration
(or more)

**Comment by delphinepol** [comment]
Thank you for the answer !

**Comment by fingolfin** [comment]
I've submitted https://github.com/Nemocas/Nemo.jl/issues/1254 but also had a look at the `sqrtmod` docstring, and it turns out that it only supports prime moduli... Though it doesn't check that.

**Comment by fingolfin** [comment]
Annoyingly this still persists:
```
julia> sqrtmod(ZZ(-7), ZZ(512))
75

julia> sqrtmod(ZZ(-7), ZZ(1024))
ERROR: no square root exists or modulus is not prime
```

**Comment by tthsqe12** [comment]
Sadly, I don't see a resolution for the one-line `sqrtmod` function. Is a two-line solution involving the creation of a polynomial and asking for its roots acceptable?

**Comment by thofma** [comment]
Yes
