### ISSUE TITLE
residue_ring of a residue_ring is very slow

### ISSUE THREAD

**Issue by JohnAAbbott** [oscar-system/Oscar.jl#4410]
**Describe the bug**
The last command below takes a long time -- I did not wait for it to finish.  It can also be reproduced using only `AbstractAlgebra`

**To Reproduce**
Steps to reproduce the behaviour, please provide a code snippet that triggers
the bug.
```
# using Pkg; Pkg.develop(path="/home/zez25zuh/OSCAR/GIT/AbstractAlgebra.jl");
# using AbstractAlgebra
P,(x,y) = polynomial_ring(QQ, ["x", "y"]);
f = x+y+1;
R,phi = residue_ring(P,f);
residue_ring(R, phi(x))
```

**Expected behavior**
A bit faster?

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.3.0-DEV - #master, 409d74e527 -- 2024-12-17 11:22:07 +0100
  combining:
    AbstractAlgebra.jl   v0.44.1 - #master, c10f88063e -- 2024-12-19 18:04:37 +0100
    GAP.jl               v0.12.2
    Hecke.jl             v0.35.0
    Nemo.jl              v0.48.0 - #JAA/is_nilpotent, 0773b2670a -- 2024-12-18 14:46:53 +0100
    Polymake.jl          v0.11.23
    Singular.jl          v0.24.1
  building on:
    FLINT_jll               v300.100.300+0
    GAP_jll                 v400.1300.102+2
    Singular_jll            v404.1.700+0
    libpolymake_julia_jll   v0.13.0+0
    libsingular_julia_jll   v0.46.1+0
    polymake_jll            v400.1300.2+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.5
Commit 6f3fdf7b362 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 20 virtual cores)
Environment:
  JULIA_LOAD_PATH = @:@v#.#:@stdlib:/environments/globalenv
  JULIA_DEPOT_PATH = /home/zez25zuh/.julia:
Official https://julialang.org/ release
```

**Additional context**

**Comment by joschmitt** [comment]
From what I can tell, the issue starts with using `residue_ring` on a multivariate polynomial ring. The method returns a `EuclideanRingResidueRing`, but the ring wasn't euclidean to start with. (I don't know what exact properties of the ring are required in the implementation.)
Maybe `residue_ring` should redirect to `quo(::Ring, ::Ideal)` in this case?

**Comment by fieker** [comment]
On Fri, Dec 20, 2024 at 01:59:22AM -0800, JohnAAbbott wrote:
> **Describe the bug**
> The last command below takes a long time -- I did not wait for it to finish.  It can also be reproduced using only `AbstractAlgebra`
> 
> **To Reproduce**
> Steps to reproduce the behaviour, please provide a code snippet that triggers
> the bug.
> ```
> # using Pkg; Pkg.develop(path="/home/zez25zuh/OSCAR/GIT/AbstractAlgebra.jl");
> # using AbstractAlgebra
> P,(x,y) = polynomial_ring(QQ, ["x", "y"]);
> f = x+y+1;
> R,phi = residue_ring(P,f);
> residue_ring(R, phi(x))
> ```
> 
> **Expected behavior**
> A bit faster?

kind of user error... Q[x,y] is not euclidean but you (well the system)
is calling a function for euclidean rings....
it dies trying to invert elements using euclids algorithm

**Comment by fieker** [comment]
On Fri, Dec 20, 2024 at 01:59:22AM -0800, JohnAAbbott wrote:
> **Describe the bug**
> The last command below takes a long time -- I did not wait for it to finish.  It can also be reproduced using only `AbstractAlgebra`
> 
> **To Reproduce**
> Steps to reproduce the behaviour, please provide a code snippet that triggers
> the bug.
> ```
> # using Pkg; Pkg.develop(path="/home/zez25zuh/OSCAR/GIT/AbstractAlgebra.jl");
> # using AbstractAlgebra
> P,(x,y) = polynomial_ring(QQ, ["x", "y"]);
> f = x+y+1;
> R,phi = residue_ring(P,f);
> residue_ring(R, phi(x))
> ```
> 
> **Expected behavior**
> A bit faster?

julia> quo(P, [f])
(Quotient of multivariate polynomial ring by ideal (x + y + 1), Map: P
-> quotient of multivariate polynomial ring)

**Comment by joschmitt** [comment]
Funnily enough, if I do
```
R, phi = quo(R, f);
quo(R, phi(x));
```
I still get a `EuclideanRingResidueRing` in the end.

P.S.: `quo(R, ideal(phi(x)))` works correctly.

**Comment by JohnAAbbott** [comment]
The original context was trying to create a test case in `AbstractAlgebra` to achieve better code coverage; I think it is not worth investing more time in trying to construct such an input.
In any case, it is not good that `residue_ring` returns a `EuclideanRingResidueRing` when the result clearly is not -- it should either produce an error or give a correct result.  I did not see anything in the documentation about restrictions on arguments for `residue_ring`.

**Comment by joschmitt** [comment]
I created #4412 for the problems with `residue_ring` vs. `quo`.

I close this issue in favour of #4412.
