### ISSUE TITLE
OSCAR website should link to docs

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#443]
https://oscar.computeralgebra.de/documentation/ is missing a link to the Oscar.jl documentation

**Comment by fingolfin** [comment]
@ThomasBreuer could you also take care of this, please?

**Comment by wdecker** [comment]
We should decide on how far we make the docu public and how often we update it. So far I can only see integers and rationals. Or am I missing something?

**Comment by thofma** [comment]
The link is wrong. I will fix it.

**Comment by thofma** [comment]
https://github.com/oscar-system/oscar-website/pull/172

**Comment by fieker** [comment]
On Thu, Jun 10, 2021 at 02:10:41AM -0700, thofma wrote:
> https://github.com/oscar-system/oscar-website/pull/172

When is latest updated?

**Comment by thofma** [comment]
Latest is not a thing anymore. It was renamed to "dev" quite a while ago.
