### ISSUE TITLE
Don't forget to fix singular_ring(::NmodRing)

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Oscar.jl#444]
I don't have time to fix this now and would like to remember to fix this later.

https://github.com/oscar-system/Oscar.jl/blob/89b97d59d246addea8f9192f1185db1720e90462/src/Rings/mpoly.jl#L525-L526

This might break
https://github.com/oscar-system/Oscar.jl/blob/89b97d59d246addea8f9192f1185db1720e90462/examples/TranslateBinomial2.jl#L35-L44

**Comment by thofma** [comment]
Don't we have `gfp_mpoly` now?
