### ISSUE TITLE
Oscar doesn't precompile with Julia 1.7.0-beta2

### ISSUE THREAD

**Issue by matthias314** [oscar-system/Oscar.jl#504]
You might be interested in the following observation: When trying to install Oscar 0.5.2 with the current beta2 version of the upcoming Julia release 1.7.0, the packages CxxWrap, GAP, Polymake, Singular and Oscar produce errors during precompilation. Installation with Julia 1.6.1 works fine.
```
Julia Version 1.7.0-beta2
Commit b570546b68 (2021-06-20 06:31 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2430 0 @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, sandybridge)
```
EDIT: Maybe this is related: JuliaInterop/CxxWrap.jl#291

**Comment by fingolfin** [comment]
Yes we are aware. That's because Julia 1.7 breaks CxxWrap, and updating it is ... tricky...

**Comment by fingolfin** [comment]
See also https://github.com/JuliaPackaging/Yggdrasil/pull/3214 (plus discussions on the Julia Slack, which I can't link to).
