### ISSUE TITLE
docs: collapse all top-level entries in the navigation by default

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#512]
... if this is possible with Documenter.jl at all.

Suggested by @micjoswig during out weekly meeting; @thofma wanted to have a look. 

I thought we could do this using [`hide()`](https://juliadocs.github.io/Documenter.jl/dev/lib/public/#Documenter.hide) but that seems to completely remove things from the navbar unless the page is active, which is *not* what we want.

**Comment by fingolfin** [comment]
I asked on the Julia Slack and was told: Pass
`format = Documenter.HTML(collapselevel = 1)`
to makedocs.

**Comment by thofma** [comment]
I will make a PR.
