### ISSUE TITLE
docs: weirdness in navbar with docs included from Hecke

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#513]
Something weird is going on in the navbar for these pages:
- https://oscar-system.github.io/Oscar.jl/dev/Hecke/docs/src/number_fields/intro/
- https://oscar-system.github.io/Oscar.jl/dev/Hecke/docs/src/number_fields/basics/
- https://oscar-system.github.io/Oscar.jl/dev/Hecke/docs/src/number_fields/elements/

Here is a screenshot

<img width="290" alt="Screenshot 2021-07-02 at 15 26 47" src="https://user-images.githubusercontent.com/241512/124281348-ebcb5900-db49-11eb-9ff2-a3ccb6832858.png">

**Comment by thofma** [comment]
Will have a look.

**Comment by fingolfin** [comment]
Got fixed at some point
