### ISSUE TITLE
docs: why do some filenames have a prefix like `ca_`, `pg_`, `it_`?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#514]
I think @wdecker started this and the the Polymake group took over the convention.

But this seems redundant: instead of `CommutativeAlgebra/ca_binomial_ideals.md` why not use `CommutativeAlgebra/binomial_ideals.md` -- or even `CommutativeAlgebra/BinomialIdeals.md`.

Also, during our meeting today we kinda agreed that all chapters should start with an introduction page; right now that's e.g. `CommutativeAlgebra/ca.md` -- I would suggest to give these start pages a uniform name, e.g. `index.md` or `intro.md`. That then also makes it easy to "find" these entry points.

**Comment by micjoswig** [comment]
"pg" was just copied from "ca". So, no reason by itself.

**Comment by wdecker** [comment]
The only reason for starting with ca was that at that time, the  relevant files where in a different, more general folder. Having a more refined folder structure now, there is no reason for such things except: Are their conflicts with having files in different folders with the same name (such as intro.md)?

**Comment by thofma** [comment]
No, there will be no conflict.

**Comment by micjoswig** [comment]
Do you want to keep it like this, or do we make one global change (after the 0.6.0 release)?

@fingolfin : Please decide, take action if need be, and close this ticket.
