### ISSUE TITLE
docs: "introduction" vs "interface"

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#515]
Start each top level section with a page "Introduction".  That is supposed to describe the key mathematical concepts, with references to standard text books.

Possibly we might create a uniform style for this later.

**Comment by wbhart** [comment]
I have created Introduction sections for each chapter of the AbstractAlgebra documentation, which would make some contribution to this if those were slurped in (once merged).

I tried not to mention AbstractAlgebra directly in the Introductions for all the sections that seem like they'd work as introductions for Oscar as well.

**Comment by micjoswig** [comment]
It's much improved now (all over the place).  Thanks to everybody!

@ThomasBreuer : please pick books to cite in the intros of "Rings" and "Fields".  Consult with @fieker if need be.  Then close this ticket.
