### ISSUE TITLE
Missing functionality for quotients of graded rings

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#526]
* [x] `homogeneous_components` when used on a quotient element returns elements in the ambient ring
```julia
julia> R, (x, y) = grade(PolynomialRing(QQ, ["x", "y"])[1]);

julia> Q = quo(R, ideal([x^2, y]))[1];

julia> homogeneous_components(Q[1])
Dict{GrpAbFinGenElem, MPolyElem_dec{fmpq, fmpq_mpoly}} with 1 entry:
  [1] => x
```
* [x] No function to retrieve the degrees of the generators of R or Q, so one must use `R.d` or `Q.R.d`.
* [x] The gradings are not very easy to use. In particular since the abelian group used in the gradings is not cached, one must retrieve it using `R.D` or `Q.R.D`.
```julia
julia> Z = abelian_group([0])
GrpAb: Z

julia> R.D
GrpAb: Z

julia> R.D == Z
false

julia> homogeneous_component(x, Z([1]))
ERROR: Elements must belong to the same group
```
* [x] If one works with the underlying non-graded ring, elements cannot be coerced into Q directly (easy to fix).
```julia
julia> R.R[1]
x

julia> R(R.R[1])
x

julia> Q(R.R[1])
ERROR: AssertionError: parent(a) == Q.R
```

- [x] Evaluation.
- [x] Promotion.

_Originally posted by @8d1h in https://github.com/oscar-system/Oscar.jl/issues/520#issuecomment-873575112_

**Comment by fieker** [comment]
So there are functions missing
 - one to compute the degree of the generators. Suggestions for the name?
 - one to get the decorating group. Suggestions for the name?
 - a missing coercion 
 - a wrong return type
The last 2 are easy - as are the first - provided someone comes up with a good name

**Comment by thofma** [comment]
I will work on it.

**Comment by jieaosong** [comment]
Some more missing functionalities
* Evaluation
```julia
julia> R, (x,y) = grade(PolynomialRing(QQ, ["x", "y"])[1]);

julia> evaluate(x, [x,y])
x

julia> x(x,y)
ERROR: MethodError: objects of type MPolyElem_dec{fmpq, fmpq_mpoly} are not callable
```
* Promotion
```julia
julia> x + 1//2
ERROR: MethodError: no method matching (::MPolyRing_dec{fmpq, FmpqMPolyRing})(::Rational{Int64})

julia> x + QQ(1//2)
ERROR: type MPolyElem_dec has no field poly
```
And ditto for `MPolyQuoElem` (even non-graded ones).
