### ISSUE TITLE
Nemo bug?

### ISSUE THREAD

**Issue by asbuch** [oscar-system/Oscar.jl#54]
The last line of the following causes an error, I think this must be a bug::

```julia
using Nemo
R, (a, b) = PolynomialRing(ZZ, ["a", "b"])
T, x = PolynomialRing(R, "x")
divexact(x, one(T))
U, (y,) = PolynomialRing(R, ["y"])
divexact(y, one(U))
```

I believe I used the latest version of Nemo (installed with ]dev Nemo).

Anders

**Comment by wbhart** [comment]
Yes, that is a bug. The Nemo repository is here though:

https://github.com/Nemocas/Nemo.jl

**Comment by wbhart** [comment]
@asbuch Did you open this as a ticket on the official Nemo repository?

**Comment by asbuch** [comment]
I did not, I can do so if you wish, but I don't know if you want the same bug reported multiple times?

I initially followed the instructions on this page about how to report problems:
https://oscar.computeralgebra.de/community/

The "GitHub" link on that page gives a lists of several sub-projects within Oscar.  Maybe it would be useful to have a link to Nemo on that list?

**Comment by wbhart** [comment]
Yes, please. No one will see it here except me, as this is just my personal fork.

**Comment by wbhart** [comment]
By the way, Nemo is on the list on the page you mentioned.
