### ISSUE TITLE
Wishlist for groups interface

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#541]
For various pieces of code in Oscar (invariant theory, cohomology, ...) we need wrappers for the following GAP functions. Feel free to edit this issue and add your own / add comments with additional requests.

- [ ] `GeneratorsOfMonoid` (and probably more monoid related stuff)
- [ ] `InverseGeneralMapping`
- [ ] `IsomorphismFpGroupByGenerators`
- [ ] `MappedWord`
- [ ] `RelatorsOfFpGroup`
- [ ] `RelationsOfFpMonoid`
- [ ] ...

**Comment by fieker** [comment]
some of them exist in the Cohomology module and need to be "approved" and moved out of examples. Similar with the group stuff in GaloisGrp....

**Comment by fingolfin** [comment]
Looking at that code is part of the source for this list. However, I don't think these "exist" there so much as that the code you reference is *calling* them -- but it doesn't e.g. provide a standalone wrapper for `RelationsOfFpMonoid` (which is fine, it's not your job to write those).

I mainly wrote these issue to collect things together we need, and to be able to show people who ask for things where they can log them, and then hopefully to give @ThomasBreuer and me some impetus to finally get some more of these done... Stay tuned
