### ISSUE TITLE
Determinants of matrices with polynomial entries

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#545]
I got the following error

ERROR: MethodError: no method matching one(::Type{fmpq_mpoly})

running this code 

R, A = PolynomialRing(QQ, "a" => (1:3,1:3))
det(A)

As it seems, some methods for the computation of determinants are not yet implemented here.

**Comment by fieker** [comment]
On Fri, Jul 09, 2021 at 02:33:54AM -0700, HechtiDerLachs wrote:
> I got the following error
> 
> ERROR: MethodError: no method matching one(::Type{fmpq_mpoly})
> 
> running this code 
> 
> R, A = PolynomialRing(QQ, "a" => (1:3,1:3))
> det(A)
> 
> As it seems, some methods for the computation of determinants are not yet implemented here.

No, det is fine, but it cannot work for Arrays only for matrices:

det(matrix(A))

works.

det(A) is calling julia's base and this cannot support our types
det(matrix(A)) is calling us

**Comment by HechtiDerLachs** [comment]
Ah, OK. Thanks.
