### ISSUE TITLE
Printing roots of unity

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#552]
Writing elements of the abelian closure of QQ looks horrible:
```
julia> binomial_primary_decomposition(I)
3-element Array{Tuple{MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}},MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}}},1}:
 (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + -z_3 in Q(z_3), x1 + -z_3 in Q(z_3), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + -z_3 in Q(z_3), x3)
 (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + (z_3 + 1 in Q(z_3)), x1 + (z_3 + 1 in Q(z_3)), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + (z_3 + 1 in Q(z_3)), x3)
 (ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1), ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1))
```
Two questions to start a discussion:
1. Isn't -1 in Q(z_1) just -1?
2. Can I print (z_3 + 1 in Q(z_3)) by introducing a greek letter such as \zeta_3: (\zeta_3+1)

**Comment by fieker** [comment]
On Fri, Jul 09, 2021 at 09:30:30AM -0700, Wolfram Decker wrote:
> Writing elements of the abelian closure of QQ looks horrible:
> 
> julia> binomial_primary_decomposition(I)
> 3-element Array{Tuple{MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}},MPolyIdeal{AbstractAlgebra.Generic.MPoly{Oscar.QabModule.QabElem}}},1}:
>  (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + -z_3 in Q(z_3), x1 + -z_3 in Q(z_3), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + -z_3 in Q(z_3), x3)
>  (ideal generated by: x1 + -1 in Q(z_1)*x2, x1^3 + -1 in Q(z_1), x2^2*x3 + -1 in Q(z_1)*x3, x3, x2 + (z_3 + 1 in Q(z_3)), x1 + (z_3 + 1 in Q(z_3)), ideal generated by: x1*x2^2 + -1 in Q(z_1), x2 + (z_3 + 1 in Q(z_3)), x3)
>  (ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1), ideal generated by: x2 + -1 in Q(z_1), x1 + -1 in Q(z_1), x1*x2 + -1 in Q(z_1))
> 
> Two questions to start a discussion:
> 1) Isn't -1 in Q(z_1) just -1?
Yes (and no):
 mathematically it is -1
 Juliawise it is not fmpz, nor fmpq, but a QabElem (or so)
> 2) Can I print (z_3 + 1 in Q(z_3)) by introducing a greek letter such as \zeta_3: (\zeta_3+1)
 Yes (and no):
 we've decided to not use anyhting but normal (ancient) 7-bit ascii in
 our programming - to have maximal flexibility in tools (and not run
 into wierd codeoage problems when s.o. is using the wrong editor/ tool)
 Bu it would be easy to print greek.
 Question: z_9^3: should this magically become z_3 in printing?
