### ISSUE TITLE
Wishlist for documentation

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#559]
A random collection of ideas for improving the Oscar.jl documentation, based on real world experiences and discussions on Slack :-)

- there seems to be no docstring for `hom` between multivariate polynomial rings
- I had a hard time finding any information about how to create homomorphisms between rings
  - perhaps there could be a section "Ring homomorphisms"; we already have sections "Group homomorphisms" and "Module homomorphisms"
  - I think we could liberally link to that; I tend to search on web pages for terms like "homomorphism" and had zero hits on the pages ["Ring interface"](https://oscar-system.github.io/Oscar.jl/dev/AbstractAlgebra/rings/) and ["TODO"](https://oscar-system.github.io/Oscar.jl/dev/AbstractAlgebra/mpolynomial_rings/) which I found surprising
- ...

**Comment by wdecker** [comment]
The docu for commutative algebra says:

Creating Polynomial Rings

Referring to the corrresponding section of the ring chapter for details, we recall how to create multivariate polynomial rings. Then we show how to assign gradings to these rings and how to set up maps between them.

The functionality for the latter is in the making (@Dan), the docu will follow (@wdecker).

**Comment by lkastner** [comment]
Is this done? I found
https://docs.oscar-system.org/dev/CommutativeAlgebra/rings/#hom-Tuple{MPolyRing,%20AbstractAlgebra.NCRing,%20Any,%20Vector{T}%20where%20T}

**Comment by wdecker** [comment]
In addition, there are:
https://docs.oscar-system.org/dev/CommutativeAlgebra/affine_algebras/#Homomorphisms-From-Affine-Algebras
https://docs.oscar-system.org/dev/CommutativeAlgebra/localizations/#Homomorphisms-from-Localized-Rings
So that is settled.
