### ISSUE TITLE
Homomorphisms from polynomial rings into "arbitrary" rings

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#560]
I tried to define a homomorphism from a polynomial ring into its coefficient field, but failed. This is what I tried:
```
julia> F = GF(5)
Galois field with characteristic 5

julia> R, (x,y) = PolynomialRing(F, [:x,:y])
(Multivariate Polynomial Ring in x, y over Galois field with characteristic 5, gfp_mpoly[x, y])

julia> hom(R, F, [one(F), zero(F)])
ERROR: MethodError: no method matching hom(::GFPMPolyRing, ::Nemo.GaloisField, ::Array{gfp_elem,1})
Closest candidates are:
  hom(::Oscar.FreeModule_dec{T}, ::Any, ::Any) where T at /Users/mhorn/Projekte/OSCAR/Oscar.jl/src/Modules/FreeModules-graded.jl:425
  hom(::S, ::T, ::Any...; inverse, check, compute_inverse) where {S<:NumField, T<:NumField} at /Users/mhorn/.julia/packages/Hecke/p8znJ/src/Map/NumField.jl:140
  hom(::FinField, ::FinField, ::FinFieldElem; check) at /Users/mhorn/.julia/packages/Hecke/p8znJ/src/Map/FiniteField.jl:17
  ...
Stacktrace:
 [1] top-level scope at REPL[14]:1

```

I realize that for unrestricted domain & codomain pairings, the resulting homomorphisms may be of limited use (e.g. preimages may not be computable), but if the domain is a polynomial ring over a coefficient ring `K`, and the codomain is a K-algebra in a natural way, then at least images normally can be computed efficiently, no?

Can we support something like this?

I guess one can extend this and consider other domains, too. E.g. the reverse to the above, embedding the coefficient ring into a polynomial ring.

**Comment by thofma** [comment]
Yes, when we overhaul the morphisms this will also be possible.

**Comment by HechtiDerLachs** [comment]
Could you add a check to the AlgebraHomomorphism routine which throws an error if the entries in the vector of images of the generators do not belong to the target ring? 

The error messages which I got were rather cryptic.

**Comment by thofma** [comment]
Sure.

**Comment by simonbrandhorst** [comment]
Seems to work now. Can this be closed?
