### ISSUE TITLE
Schemes

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#561]
This page is meant as a place for discussion about what schemes in Oscar should be. 
Please write what you expect from schemes and which features you need. 

(Edit) Moved the Wiki part to:
https://github.com/Singular/Singular/wiki/Singular-Development-Roadmap

**Comment by fingolfin** [comment]
Indeed. @AlexD97 and @jankoboehm are working on this, PR #461 is part of work towards this, as far as I understand.

**Comment by wdecker** [comment]
@simonbrandhorst: Is this meant to start a discussion? Or?

**Comment by simonbrandhorst** [comment]
(Edit) Yes :-).
