### ISSUE TITLE
singular_ring not working for finite prime fields

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#564]
```julia
julia> Fx, = GF(fmpz(3))["x", "y"]
(Multivariate Polynomial Ring in x, y over Galois field with characteristic 3, AbstractAlgebra.Generic.MPoly{gfp_fmpz_elem}[x, y])

julia> Oscar.singular_ring(Fx)
ERROR: pointer_from_objref cannot be used on immutable objects
Stacktrace:
  [1] error(s::String)
[...]
```
@tthsqe12

**Comment by tthsqe12** [comment]
Well, you can't use n_unknown on immutables.
This is a well-known fact. :)
https://github.com/oscar-system/Oscar.jl/blob/c4eca1ee2c7b309d8bf5fa6cdc7ffab4eaaaf949/experimental/Rings/QabAndPChars.jl#L23-L25

Unfortunately, singular offers no native analogue of gfp_fmpz_elem, so either we make gfp_fmpz_elem mutable, or make a mutable wrapper of it?

**Comment by thofma** [comment]
How about not creating an `n_unkown`? Or is there no corresponding Singular type?

**Comment by tthsqe12** [comment]
> Unfortunately, singular offers no native analogue of gfp_fmpz_elem

**Comment by thofma** [comment]
What about the `ResidueRing` trick from here: https://github.com/oscar-system/Oscar.jl/pull/528/?

**Comment by tthsqe12** [comment]
No - then Singular doesn't know it is a field.

**Comment by tthsqe12** [comment]
This is now fixed as:
```julia
julia> Fx, = GF(fmpz(3))["x", "y"]
(Multivariate Polynomial Ring in x, y over Galois field with characteristic 3, AbstractAlgebra.Generic.MPoly{gfp_fmpz_elem}[x, y])

julia> Oscar.singular_ring(Fx)
Singular Polynomial Ring (Coeffs(17)),(x,y),(lp(2),C)

julia> typeof(gen(ans, 1))
Singular.spoly{Singular.n_FieldElem{Singular.FieldElemWrapper{Nemo.GaloisFmpzField, gfp_fmpz_elem}}}
```
