### ISSUE TITLE
No singular_ring for finite fields

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#566]
```julia
julia> F, = FiniteField(3, 1, "a")
(Finite field of degree 1 over F_3, 2)

julia> singular_ring(F)
Singular coefficient ring over Finite field of degree 1 over F_3

julia> typeof(ans)
Singular.CoefficientRing{fq_nmod}

julia> Fx, x = PolynomialRing(F, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Finite field of degree 1 over F_3, fq_nmod_mpoly[x, y])


julia> M = Singular.Matrix(singular_ring(Fx), [1 0; 0 1])
[1, 0
0, 1]

julia> Singular.LibFinvar.primary_invariants(M)

signal (11): Speicherzugriffsfehler
in expression starting at REPL[9]:1
unknown function (ip: (nil))
Allocations: 32341043 (Pool: 32306422; Big: 34621); GC: 14
[1]    27100 segmentation fault (core dumped)  julia
```
@tthsqe12

**Comment by tthsqe12** [comment]
Another difficult situation: Singular only offers finite fields of characteristic less thatn about 2^30, so does singular_ring(::FqNmodFiniteField):
 1. return n_unknown (as it currently does), or
 2. try to create the native singular version and possibly throw, or
 3. create a type-unstable combination of the above two

?

**Comment by thofma** [comment]
I guess there is no chance of making Singular itself play nice with `n_unkown`?

**Comment by tthsqe12** [comment]
I highly doubt it, but let's ask @hannes14 .

**Comment by hannes14** [comment]
- extending Singulars limit for  finite fields to 2^62 is possible
- n_unknown misses all functionality related to factorize, gcd, extgcd due to missing support in factory
