### ISSUE TITLE
geometric_genus(C::ProjectivePlaneCurve{S}) is wildy type unstable

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Oscar.jl#572]
I was looking over #466, and as far as I can see, it actually returns `Int` or `fmpq` (!!), but the compiler infers `Any` for the return type (calls to the singular library are necessarily unpredictable).

<ins> I hope for a return type of `fmpz` and the compiler should be able to infer it </ins>

Cause of fmpq return type is related to #573

**Comment by fingolfin** [comment]
@delphinepol can you take a look at this?

**Comment by delphinepol** [comment]
OK, I will have a look !

**Comment by tthsqe12** [comment]
I learned of a good way to catch this from other parts of oscar test code (the parentheses are need here):
```julia
@testset "genus" begin
    S, (x, y, z) = PolynomialRing(QQ, ["x", "y", "z"])
    T, _ = grade(S)
    C = Oscar.ProjPlaneCurve(T(y^2 * z - x^3 - x * z^2))
    @test (@inferred Oscar.arithmetic_genus(C)) == 1
    @test (@inferred Oscar.geometric_genus(C)) == 1
    R, (a, b) = PolynomialRing(GF(7), ["a", "b"])
    D = Oscar.AffinePlaneCurve(b^9 - a^2 * (a - 1)^9)
    @test (@inferred Oscar.arithmetic_genus(D)) == 45
    @test (@inferred Oscar.geometric_genus(D)) == 0
end
```
If would be great to have more of these kinds of checks in the test code.

**Comment by delphinepol** [comment]
What do you mean by "inferred" ? I can turn the output of the functions as fmpz, but the test is not going through... What does this test check in fact ? How does the compiler infers something ? I have no clue on how to influence it...

**Comment by tthsqe12** [comment]
So, keep the @inferred in your test code. It turns out the whole of oscar is too type unstable to do this very cleanly. But, you can try to get `fmpz` as the inferred return type for the genus as follows.

----
`arithmetic_genus`: you can see the current status as follows. The bad parts here should be shown in red, and the summary of the bad situation is in `Body::Any`, which is the inferred return type.
```julia
julia> code_warntype(Oscar.arithmetic_genus, (Oscar.ProjPlaneCurve,))
Variables
  #self#::Core.Const(Oscar.PlaneCurveModule.arithmetic_genus)
  C::Oscar.PlaneCurveModule.ProjPlaneCurve
  H::Any
  A::Any
  I::Any
  S::MPolyRing_dec{_A, _B} where {_A, _B}
  F::MPolyElem_dec{S, S1} where {S, S1}

Body::Any
1 ─       (F = Base.getproperty(C, :eq))
│         (S = Oscar.PlaneCurveModule.parent(F))
│   %3  = S::MPolyRing_dec{_A, _B} where {_A, _B}
│   %4  = Base.vect(F)::Vector{_A} where _A
│         (I = Oscar.PlaneCurveModule.ideal(%3, %4))
│         (A = Oscar.PlaneCurveModule.quo(S, I))
│   %7  = Base.getindex(A, 1)::Any
│         (H = Oscar.PlaneCurveModule.hilbert_polynomial(%7))
│   %9  = Oscar.PlaneCurveModule.coeff(H, 0)::Any
│   %10 = -%9::Any
│   %11 = (%10 + 1)::Any
└──       return %11
```
Basically, the compiler infers nothing, as it has `::Any` everywhere.

To start, we need the following type assertion on `hilbert_polynomial` in `mpoly-affine-algebras.jl` line 131. The type unstability of hilbert_polynomial is a separate issue, but this works for our purposes now.
```julia
function hilbert_polynomial(A::MPolyQuo)::fmpq_poly
```

Then, you can do
```julia
function arithmetic_genus(C::ProjectivePlaneCurve)
  F = C.eq
  S = parent(F)
  I = ideal(S, [F])
  A = quo(S, I)
  H = hilbert_polynomial(A[1])
  return -ZZ(coeff(H, 0)) + 1
end
```
and voila:
```julia
julia> code_warntype(Oscar.arithmetic_genus, (Oscar.ProjPlaneCurve,))
Variables
  #self#::Core.Const(Oscar.PlaneCurveModule.arithmetic_genus)
  C::Oscar.PlaneCurveModule.ProjPlaneCurve
  H::fmpq_poly
  A::Any
  I::Any
  S::MPolyRing_dec{_A, _B} where {_A, _B}
  F::MPolyElem_dec{S, S1} where {S, S1}

Body::fmpz
1 ─       (F = Base.getproperty(C, :eq))
│         (S = Oscar.PlaneCurveModule.parent(F))
│   %3  = S::MPolyRing_dec{_A, _B} where {_A, _B}
│   %4  = Base.vect(F)::Vector{_A} where _A
│         (I = Oscar.PlaneCurveModule.ideal(%3, %4))
│         (A = Oscar.PlaneCurveModule.quo(S, I))
│   %7  = Base.getindex(A, 1)::Any
│         (H = Oscar.PlaneCurveModule.hilbert_polynomial(%7))
│   %9  = Oscar.PlaneCurveModule.coeff(H, 0)::fmpq
│   %10 = Oscar.PlaneCurveModule.ZZ(%9)::fmpz
│   %11 = -%10::fmpz
│   %12 = (%11 + 1)::fmpz
└──       return %12
```

----
`geometric_genus`:  Here is the current code.
In the first branch, any call to Singular.Lib... is going to be completely uninferrable.
In the second branch, the return is `pa+1`. What is the type of `pa`? It starts out as `0`, which is an `Int`, but if the loop runs (the compiler doesn't know if the loop runs), then it gets promoted to whatever `coeff(H, 0)` returns, which is an `fmpq`.

```julia
function geometric_genus(C::ProjectivePlaneCurve{S}) where S <: FieldElem
   F = defining_equation(C)
   R = parent(F)
   I = ideal(R, [F])
   if S == fmpq
      singular_assure(I)
      return Singular.LibNormal.genus(I.gens.S)
   else
      A = quo(R, I)
      L = normalization(A[1])
      m = length(L)
      pa = 0
      for i in 1:m
         J = L[i][1].I
         T, _ = grade(parent(J[1]))
         V = T.(gens(J))
         JJ = ideal(T, V)
         B = quo(T, JJ)
         H = hilbert_polynomial(B[1])
         pa = pa - coeff(H, 0)
      end
      return pa + 1
   end
end
```

The following reasonable modifications, when combined with the type assertion
`function hilbert_polynomial(A::MPolyQuo)::fmpq_poly`
from above produce passing test code. The compiler now knows that `coeff(H, 0)` is an `fmpq` and `ZZ(::fmpq)` will throw if the rational is not integral.
Also, if Singular.LibNormal.genus returns something other that an `Int`, we will find out and learn something!.

```julia
function geometric_genus(C::ProjectivePlaneCurve{S}) where S <: FieldElem
...
      return ZZ(Singular.LibNormal.genus(I.gens.S)::Int)
   else
...
      pa = zero(ZZ)
      for i in 1:m
...
         H = hilbert_polynomial(B[1])
         pa = pa - ZZ(coeff(H, 0))
      end
      return pa + 1
   end
end

```

**Comment by delphinepol** [comment]
@tthsqe12 Thank you very much for your help, it works !
