### ISSUE TITLE
New binaries with flint 2.8

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#589]
Just an issue to keep track of the progress:
- [x] flint, arb, antic, calcium, Singular
- [x] libsingular_julia (@tthsqe12)
- [x] normaliz (@benlorenz)
- [x] polymake (@benlorenz)
- [x] libpolymake_julia (@benlorenz)
- [x] Polymake release (@benlorenz)
- [x] LoadFlint (https://github.com/oscar-system/LoadFlint.jl/pull/23)
- [x] Generate `build_*` for arb, antic, calcium for Nemo (@thofma)
- [x] Hecke release compatible with Nemo 0.26
- [x] Singular release compatible with libsingular_julia 0.16 + Nemo 0.26 + AA 0.21
- [ ] Oscar release with updated compat

**Comment by benlorenz** [comment]
I added some more bullet points to keep track of what is (as far as I can tell) currently missing to be able to use the new binaries in a new Oscar release.

**Comment by thofma** [comment]
@tthsqe12 Could you take care of the Singular.jl release?
