### ISSUE TITLE
GF(p,1) does not work if `p` is large (i.e., and fmpz)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#590]
Note this:
```
julia> p = next_prime(fmpz(2)^64)
18446744073709551629

julia> GF(p)
Galois field with characteristic 18446744073709551629

julia> GF(p, 1)
ERROR: MethodError: no method matching GF(::fmpz, ::Int64)
Closest candidates are:
  GF(::fmpz; cached) at /Users/mhorn/.julia/packages/Nemo/BksOQ/src/flint/gfp_fmpz_elem.jl:399
  GF(::Int64, ::Int64) at /Users/mhorn/.julia/packages/Hecke/ysVZL/src/Misc/FiniteField.jl:18
  GF(::Int64, ::Int64, ::AbstractString; cached) at /Users/mhorn/.julia/packages/Hecke/ysVZL/src/Misc/FiniteField.jl:18
Stacktrace:
 [1] top-level scope
   @ REPL[23]:1
```

I would expect `GF(p, 1)` to work identical to `GF(p)`.

(Ideally, I'd also like to have `GF(p, 2)`, but that's a separate concern)

**Comment by fingolfin** [comment]
In contrast, this works:
```
julia> F, a = FiniteField(next_prime(fmpz(2)^64), 1, "a")
(Finite field of degree 1 over F_18446744073709551629, 756194802194484695)

julia> F, a = FiniteField(next_prime(fmpz(2)^64), 2, "a")
(Finite field of degree 2 over F_18446744073709551629, a)
```

**Comment by fieker** [comment]
My fault, FiniteField does work. The original proposal was to have GF(p)
only for prime fields. In Hecke I wanted a uniform interface...

The current plan
 GF(p,k), GF(p) -> only the field, tpe depending on arguments
 FiniteField()  -> field and "generator"

currently, GF(a,b) = FiniteField(a,b) (plus me choosing a name)

**Comment by fingolfin** [comment]
I agree with this plan, esp. as I just now run into this and got myself greatly confused 🤣 

Can we also support `GF(p^k)` alternatively to `GL(p,k)` ? As a GAP user, I am very used to it. Of course one may counter it with "this is inefficient"... Also fine by me, but then I'd like to suggest that we improve the error message: instead of
```
julia> GF(4)
ERROR: DomainError with 4:
Characteristic must be prime
```
how about this:
```
julia> GF(4)
ERROR: DomainError with 4:
Characteristic must be prime, use GF(p,d) to create fields with prime power order
```

**Comment by fieker** [comment]
On Thu, Sep 02, 2021 at 02:24:21AM -0700, Max Horn wrote:
> I agree with this plan, esp. as I just now run into this and got myself greatly confused 🤣 
> 
> Can we also support `GF(p^k)` alternatively to `GL(p,k)` ? As a GAP user, I am very used to it. Of course one may counter it with "this is inefficient"... Also fine by me, but then I'd like to suggest that we improve the error message: instead of
Perfect power testing is fast, clearny not as fast as not doing it, but
fast enough (softly linear I think)

**Comment by fingolfin** [comment]
This has been resolved, `GF(next_prime(fmpz(2)^64),1)` now works just fine
