### ISSUE TITLE
Importing Oscar breaks display of Vectors in Pluto notebooks

### ISSUE THREAD

**Issue by iimog** [oscar-system/Oscar.jl#597]
When importing Oscar in a Pluto notebook and then trying to display any Vector (even if it has nothing to do with Oscar, e.g. a Vector of Strings) the output is broken and produces an error message:
```julia
# first cell
import Oscar
# second cell
["a","b"]
```
Error message:
```
Failed to show value:
MethodError: no method matching show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::String)
Closest candidates are:
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.QabModule.QabElem) at /home/markus/.julia/packages/Oscar/u2chq/experimental/Rings/QabAndPChars.jl:54
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.QabModule.QabField) at /home/markus/.julia/packages/Oscar/u2chq/experimental/Rings/QabAndPChars.jl:30
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.MPolyIdealLoc) at /home/markus/.julia/packages/Oscar/u2chq/src/Rings/mpoly-local.jl:215

...

    show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::Vector{String})@IJulia.jl:325
    show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:654
    var"#sprint_withreturned#28"(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Vector{String})@PlutoRunner.jl:591
    format_output_default(::Any, ::Any)@PlutoRunner.jl:515
    #format_output#17@PlutoRunner.jl:532[inlined]
    formatted_result_of(::Base.UUID, ::Bool, ::Nothing, ::Module)@PlutoRunner.jl:448
    top-level scope@none:1
```

Here is a screenshot of the expected output (before importing Oscar)
![Screenshot_without_Oscar](https://user-images.githubusercontent.com/7403236/127671594-63daa996-d2d5-4c12-a74f-e4bb2b182570.png)

this is the output with Oscar imported
![Screenshot_with_Oscar](https://user-images.githubusercontent.com/7403236/127671609-2fd28034-a115-4a50-aaf3-93f1e6426a98.png)

I initially reported this issue to Pluto https://github.com/fonsp/Pluto.jl/issues/1346
However, it seems to be caused by overloads of `Base.show` and `Base.showable` through `Oscar` or one of its dependencies. Any help would be appreciated as I would love to use the power of Oscar within the nice computing environment of Pluto.

**Comment by thofma** [comment]
Thanks for the report. I am working on a fix.

**Comment by thofma** [comment]
Can you do a `Pkg.update()` and try again?

**Comment by iimog** [comment]
Thanks @thofma for working on this issue so quickly! After `Pkg.update()` the issue remained. But after digging a little deeper I realized that `Oscar` depends on `Hecke` 0.10.5 so after importing `Oscar` into the notebook `Hecke` is downgraded from 0.10.15. When I just import the most current version of `Hecke` the error is gone.

**Comment by thofma** [comment]
Ah, yes, the latest official Oscar release is `0.5.3` which pins the dependencies to some old version. I guess you are using this. We have not done a new Oscar release in a while and I don't know when the next one will be done. To get something working now, you could do `]dev Oscar` or `]add Oscar#master` to get the latest development version, which should fix the problem.

**Comment by iimog** [comment]
Exactly. By default Pluto uses a specific version [(latest stable if not otherwise specified)](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management). If I force it to use my locally installed dev version of Oscar everything works as expected. Thank you so much for fixing this!

![Screenshot from 2021-08-02 10-18-08](https://user-images.githubusercontent.com/7403236/127828570-7d9ab25a-0766-401b-afc2-7ad78483bba3.png)
