### ISSUE TITLE
AlgebraHomomorphism doesn't seem to copy its own list of generators

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#655]
When I create an instance f of an AlgebraHomomorphism, and I pass a vector v with the images of the generators to it, then altering v a posteriori will also alter f. 

See the following code:

```julia
using Oscar

R, vars = QQ["x","y"]
x = vars[1]
y = vars[2]
f = AlgebraHomomorphism( R, R, vars )
push!( vars, x )
f(x)
```

That's not the way that it's supposed to be, is it?

**Comment by thofma** [comment]
Yeah, we should probably fix this.

**Comment by thofma** [comment]
@HechtiDerLachs Did this give you a wrong result? (I am just looking for a good way to test this).

**Comment by HechtiDerLachs** [comment]
Yes. On my machine the above code crashed with an error message which was complaining that the number of elements in the vars vector (the *internal* one of the AlgebraHomomorphism f) does not match the number of variables of R anymore. But in general, it should, of course, be impossible to change f by changing the vector vars *after* f has been defined.

**Comment by thofma** [comment]
Hm, did you try in a fresh session? It does not error for me.

**Comment by HechtiDerLachs** [comment]
Yes. It throws despite a fresh session.

```
ERROR: Incorrect number of values in evaluation
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] evaluate(a::fmpq_mpoly, vals::Vector{fmpq_mpoly})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/PirHd/src/MPoly.jl:693
 [3] #556
   @ ~/Kaiserslautern/neuer_Oscar_Klon/Oscar.jl/src/Rings/affine-algebra-homs.jl:118 [inlined]
 [4] (::Hecke.var"#47#50"{Oscar.var"#556#559"{Vector{fmpq_mpoly}}})(x::fmpq_mpoly)
   @ Hecke ~/.julia/packages/Hecke/NoVd0/src/Map/MapType.jl:193
 [5] image(M::MapFromFunc{FmpqMPolyRing, FmpqMPolyRing}, a::fmpq_mpoly)
   @ Hecke ~/.julia/packages/Hecke/NoVd0/src/Map/Map.jl:39
 [6] (::MapFromFunc{FmpqMPolyRing, FmpqMPolyRing})(a::fmpq_mpoly)
   @ Hecke ~/.julia/packages/Hecke/NoVd0/src/Hecke.jl:722
 [7] map_poly(F::Oscar.AlgHom{fmpq}, p::fmpq_mpoly)
   @ Oscar ~/Kaiserslautern/neuer_Oscar_Klon/Oscar.jl/src/Rings/affine-algebra-homs.jl:233
 [8] (::Oscar.AlgHom{fmpq})(p::fmpq_mpoly)
   @ Oscar ~/Kaiserslautern/neuer_Oscar_Klon/Oscar.jl/src/Rings/affine-algebra-homs.jl:242
 [9] top-level scope
   @ REPL[7]:1
```
