### ISSUE TITLE
Polymake lattice_points not in the documentation?

### ISSUE THREAD

**Issue by DonDriguez** [oscar-system/Oscar.jl#663]
It seems like the Polymake function lattice_points(P::Polyhedron) exists but is not mentioned in the documentation. Is that on purpose? It would be nice if this could be added.

**Comment by lkastner** [comment]
https://github.com/oscar-system/Oscar.jl/pull/644/commits/e7c0b323fe6ba0ab48893cf4a423f595093878ab
