### ISSUE TITLE
isisomorphic cannot compare all groups

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#664]
During the summer school, I wanted to check if an automorphism group of a galois extension is the wanted group `C_2`.
```julia
Qx, x = QQ["x"]
f = x^2 - 2
K, _ = number_field(f)
grp, _ = automorphism_group(K)
isisomorphic(grp, cyclic_group(2))
```

However, the last line gives the following error.
```julia
ERROR: MethodError: no method matching isisomorphic(::GrpGen, ::PcGroup)
Closest candidates are:
  isisomorphic(::GrpGen, ::GrpGen) at /home/lgoe/.julia/packages/Hecke/iuS2D/src/Grp/Morphisms.jl:396
  isisomorphic(::Oscar.GAPGroup, ::Oscar.GAPGroup) at /home/lgoe/.julia/packages/Oscar/Bh1Um/src/Groups/homomorphisms.jl:312
```

**Comment by fingolfin** [comment]
See also issue #161

**Comment by fingolfin** [comment]
This could be done by interpreting the rows (or columns) of the multiplication table in `GrpGen` instances as permutations, and use that to just write down an isomorphic PermGroup. (For real work, one will want to reduce the number of resulting generators, though).

**Comment by thofma** [comment]
Another idea I had was making `automorphism_group` return a `PermGroup` in case Oscar is loaded.

**Comment by lgoettgens** [comment]
@fieker mentioned a fix already contained in an oscar example, i.e. one can give `automorphism_group` a return type

**Comment by fingolfin** [comment]
Yeah, so with `grp, _ = automorphism_group(PermGroup, K)` everything works.

The question is: should we still bother to also support `GrpGen`?
