### ISSUE TITLE
`subgroup` and `sub`

### ISSUE THREAD

**Issue by FriedrichRober** [oscar-system/Oscar.jl#667]
It's a bit confusing that there are two commands `sub` and `subgroup`.

**Comment by fieker** [comment]
On Wed, Sep 08, 2021 at 01:18:05AM -0700, FriedrichRober wrote:
> It's a bit confusing that there are two commands `sub` and `subgroup`.
> 
sub works for "all" structures, ie. modules, number fields, ...

subgroup, by choice of name, only for groups.

**Comment by thofma** [comment]
`subgroup` is only used in Hecke for one specific type of group. We should just rename it.

**Comment by FriedrichRober** [comment]
The problem I had was that `subgroup` does not work for all groups. For example:

```
julia> G = symmetric_group(5)
Sym( [ 1 .. 5 ] )

julia> x = perm(G, [2,3,1,5,4])
(1,2,3)(4,5)

julia> H, iota = subgroup(G, [x])
ERROR: MethodError: no method matching subgroup(::PermGroup, ::Vector{PermGroupElem})
Stacktrace:
 [1] top-level scope
   @ REPL[8]:1

julia> H, iota = sub(G, [x])
(Group([ (1,2,3)(4,5) ]), Group homomorphism from 
Group([ (1,2,3)(4,5) ])
to
Sym( [ 1 .. 5 ] ))
```

**Comment by thofma** [comment]
Will be fixed by https://github.com/thofma/Hecke.jl/pull/396.

**Comment by thofma** [comment]
Let's keep it open until the changes made it to Oscar.

**Comment by fingolfin** [comment]
There was an Oscar release in the meantime and I think this is really resolved now
