### ISSUE TITLE
Some functionality missing for rings

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#672]
Try the following code in julia:

```julia
using Oscar

R, vars = QQ["x","y"]
v = typeof(R)[]
prod(v)
```

This complains about `one(::Type{FmpqMPolyRing})` not being implemented. If, on the contrary, one was doing 

```julia
v = Int[]
prod(v)
```
that works just fine. 

I would even like to try to fix this myself and provide a pull request for that. But since this would be my first time, I would be very happy if someone could assist me with that.

**Comment by fieker** [comment]
On Thu, Sep 09, 2021 at 06:06:41AM -0700, HechtiDerLachs wrote:
> Try the following code in julia:
> 
> ```julia
> using Oscar
> 
> R, vars = QQ["x","y"]
> v = typeof(R)[]
> prod(v)
> ```
> 
> This complains about `one(::Type{FmpqMPolyRing})` not being implemented. If, on the contrary, one was doing 
> 
> ```julia
> v = Int[]
> prod(v)
> ```
> that works just fine. 
> 
> I would even like to try to fix this myself and provide a pull request for that. But since this would be my first time, I would be very happy if someone could assist me with that.

Cannot be fixed, sorry. Just knowing the type I do not know the
variables and cannot re-create the ring. You can try
reduce(*, v, init = one(R))

**Comment by thofma** [comment]
This cannot be fixed. It works for `Int` because there is a unique `one(Int)` determined by the type.

**Comment by thofma** [comment]
You can also just do `prod(v, init = one(R))`.

**Comment by HechtiDerLachs** [comment]
Ok, that makes sense... Thanks

**Comment by fieker** [comment]
On Thu, Sep 09, 2021 at 06:15:57AM -0700, Tommy Hofmann wrote:
> You can also just do `prod(v, init = one(R))`.
> 
... since julia 1.6
