### ISSUE TITLE
A few number theory commands in Oscar

### ISSUE THREAD

**Issue by Asconik** [oscar-system/Oscar.jl#674]
1) The ramified_primes command does not work on its own, only by entering Hecke.ramified_primes:
https://oscar-system.github.io/Oscar.jl/stable/Hecke/orders/orders/#ramified_primes-Tuple{NfOrd}

2) Same issue for isprincipal_fac_elem, gotta enter Hecke.isprincipal_fac_elem:
https://oscar-system.github.io/Oscar.jl/stable/Hecke/orders/ideals/#isprincipal_fac_elem-Tuple{NfOrdIdl}

3) The documentation for the Order method 
https://oscar-system.github.io/Oscar.jl/stable/Hecke/orders/orders/#Order-Tuple{AnticNumberField,%20Vector{nf_elem}}
is incorrect:
- It needs the number field as first argument before all the rest
- The command includes the keyword "cached", but the description says "isbasis" (but "isbasis" is also a keyword? Are there actually three keywords in all?)

4) In the following ideal method
https://oscar-system.github.io/Oscar.jl/stable/Hecke/orders/ideals/#ideal-Tuple{NfOrd,%20fmpz_mat}
why are "check" and "x_in_hnf" not keywords? Like in the Order method in 3)

**Comment by thofma** [comment]
Thanks for the report.
