### ISSUE TITLE
Docs: add `G(vecint)` to manual, where `G` is a permutation group

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#676]
At least I couldn't find it under https://oscar-system.github.io/Oscar.jl/dev/Groups/permgroup/

Inspired by Summer school feedback

**Comment by lgoettgens** [comment]
It is visible there as part of `perm`

![2024-08-30_15-57](https://github.com/user-attachments/assets/bc2277ef-8b5f-4547-9c0c-080c5f50e1d3)
