### ISSUE TITLE
Add `IntegerUnion = Union{Integer, fmpz}` somewhere

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#679]

**Comment by fingolfin** [comment]
I would suggest to add this in Nemo, so we can also use it in Singular and Hecke

**Comment by tthsqe12** [comment]
What about RationalUnion?

**Comment by thofma** [comment]
There does not seem to be a high demand for that.

**Comment by tthsqe12** [comment]
There is a significant amount of documentation that needs to change in src/Rings/integer.md with this change.

**Comment by fingolfin** [comment]
@tthsqe12 why, exactly, though? I mean it sure would be nice to mention `IntegerUnion`, but why does this require lots of changes? Could you elaborate a bit?

Also, are you referring to that file in Oscar.jl or the one in Nemo? Or even both? (Or AA? but that shouldn't have to refer to `fmpz` ever, should it?)

**Comment by fingolfin** [comment]
Ohh, or perhaps you are referring to the fact that PR #668 did in fact *not* "pure Oscar.Integer" as it title claimed, but rather left all references to `Oscar.Integer` in the manual, specifically in these files:
- `docs/src/Rings/integer.md`
- `docs/src/Rings/rational.md`
- `docs/src/img/IntegerTypes.svg`

**Comment by tthsqe12** [comment]
Yes, I am refering to the Oscar/docs/src/Rings/integer.md

**Comment by fingolfin** [comment]
OK, but I don't see how that's a blocker for adding `IntegerUnion` to Nemo.jl? To get this moving, I added https://github.com/Nemocas/Nemo.jl/pull/1175, looking forward to feedback there :-)

**Comment by fingolfin** [comment]
Also https://github.com/thofma/Hecke.jl/pull/403 and https://github.com/oscar-system/Oscar.jl/pull/686

**Comment by fingolfin** [comment]
Done now
