### ISSUE TITLE
singular_module

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#682]
https://github.com/oscar-system/Oscar.jl/blob/091c198aa418a56171e6c8f33ed60cbe913efe2c/src/Modules/UngradedModules.jl#L552

this needs to be

` Sx = singular_ring(base_ring(F), keep_ordering = false)`

otherwise the singular ring will be `lp` ordered and the computation not terminate.

**Comment by fingolfin** [comment]
This has been resolved at some point.
