### ISSUE TITLE
docs: remove reference to Oscar.Integer, Oscar.Rational; update or remove `IntegerTypes.svg` and `RationalTypes.svg`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#688]
Some time ago, `Oscar.Integer` was removed, but the Oscar manual still refers to it in `docs/src/Rings/integer.md` and `docs/src/Rings/rational.md` as well as in `docs/src/img/IntegerTypes.svg`.

Likewise, `Oscar.Rational` is currently identical to `Base.Rational`, but `docs/src/Rings/rational.md` and `docs/src/img/RationalTypes.svg` instead claim that it is a type that represents "Oscar rational numbers" resp. `fmpq`.

This should be corrected.

**Comment by thofma** [comment]
We should mention that `fmpz/ZZ` is a replacement for arithmetic with integers, but `Int` should be used for "control flow,  book-keeping, array-shuffling, and combinatorics.".

CC: @ulthiel
