### ISSUE TITLE
Require Julia >= 1.6 ?!

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#716]
We already agreed that once (if) Julia 1.6 becomes LTS, it is OK for us to require it as minimal version for Oscar and our various packages (including AbstractAlgebra, Nemo).

But upon rethinking this, I don't see why we couldn't require Julia 1.6 in `Oscar.jl` *right now*. Then of course any of our other packages can choose separately if they want to follow or stay with their current Julia compat range.

But as long as Oscar.jl doesn't do this, none of our other packages can really change their compat range; they are locked in by Oscar.jl

Motivation: we will have to rebuild a bunch of JLLs soon for Flint, Polymake, GAP, ... and this is a pain right now. Supporting only Julia >= 1.6 will cut down on the required work considerably (although there'll still be a bunch).

So, what do people think? Downside is of course that we leave some people behind; but actually I'd prefer if more users were on Julia 1.6 (it's faster; less variation in Julia versions means fewer bugs that only crop up with old Julia; etc.)

**Comment by tthsqe12** [comment]
Sounds good to me. It looks like 1.6 is where things finally started to come together, like WeakRef :).

**Comment by lkastner** [comment]
I am all in favour, since it will greatly reduce workload of those involved with the more technical issues.

**Comment by thofma** [comment]
Sounds good to me.

**Comment by benlorenz** [comment]
I am also in favor of this!

**Comment by fingolfin** [comment]
@wdecker @micjoswig @fieker any concerns about this?

**Comment by micjoswig** [comment]
> @wdecker @micjoswig @fieker any concerns about this?

Nope. Fine with me.

**Comment by fingolfin** [comment]
Wolfram and Claus also agreed when I talked to them about it. PR #720 implements this.
