### ISSUE TITLE
Inner or outer normals for inequality description?

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#730]
The main question of this issue is how we want the H-description of a polyhedron or cone to look like. As a reminder; The H-description is the description of a cone or polyhedron as a finite intersection of (affine) halfspaces. So:
- Should a cone be the set of all `x` such that `Ax>=0` or `Ax<=0`?
- Should a polyhedron be the set of all `x` such that `Ax>=b` or `Ax<=b`?
- Do these need to be "consistent", i.e. would choosing `Ax<=b` for polyhedra mean that we have to choose `Ax<=0`?

Here of course `A` denotes a suitable matrix and `b` a suitable vector.

There are several books we follow within Oscar, and I will mainly talk about
- Joswig, Theobald: Polyhedral and Algebraic Methods in Computational Geometry (JT); and
- Cox, Little, Schenck: Toric varieties (CLS)

JT: Currently we use the beginning of Section 4.1  as a definition for the H-description of a polyhedron `P`, i.e. `Ax<=b`, i.e. outer normals. So if we take a row `a_i` of `A`, we have that `P` is contained in the set `{x | <a_i,x>-b_i<=0}`. This I would characterize as the negative affine halfspace induced by `(a_i,b_i)`. However, Theorem 3.9 gives the H-description as the intersection of positive halfspaces, togehter with 2.3.1 "Orientation of hyperplanes". Example 4.3 also seems to use the positive side. So there is probably some linear programming convention here interfering with some discrete geometry convention? There is also Def. 5.3 being explicit about using inner normals. The same is true for cones.

Now for CLS: 7.1 uses inner normals for both polyhedra and cones. There is also Def. 1.2.3 "dual cone" and (2.2.1) "inward-pointing facet normal".

So the suggestions / questions I have are:
- What are the conventions other Oscar developers use?
- Use inner normals for cones, i.e. change `cone_from_inequalities`,
- Write a documentation page about different conventions from different areas of mathematics. Especially also elaborate on the conventions used in `polymake` vs Oscar.
- Someone already suggested that `Cone` should be the constructor for a cone from inequalities. This made me feel uneasy, but considering that we already have the analogue `Polyhedron`, it makes sense to change this. So change the convention for `cone_from_inequalities`, and turn this into the `Cone` constructor. `positive_hull` is then the analogue of `convex_hull`.
- Would it make sense to introduce a template parameter for which normals to use? We already do something similar for the LP to decide whether we want to find the maximum and minimum. And for sure we will have to do something similar for tropical varieties.

**Comment by fieker** [comment]
I think I'd rather fix either <= or >= for all constructors - it's not
that the translation is hard. If you want to be fancy, you could provide
a boolean to auto-flip, but on the whole, I'd choose one (the lesser
work) and fix it and document it.

Different conventions from different groups in different areas make it
impossible for the "outsider" to get anyhting done....

As to cones via inequalities: the cones that occur (so far) "naturally"
for me come this way.... my applications have possibly nothing to do
with your intended applications, but that is the power of Oscar. (or wil
be)

**Comment by thofma** [comment]
As a non-expert I would value consistency rather high.

P.S.: I added a `min/max` parameter for the tropical ring toy implementation, which one only ever sees once, namely when constructing the semi ring (with some arbitrary default). Afterwards one just uses `+` and one can forget about `min/max`. (Not sure about the variety stuff. I had hoped that it would not matter that much either).

**Comment by lkastner** [comment]
@alexej-jordan I just want to make you aware of this issue. At this point I have gathered enough information, so let's talk at some point.
