### ISSUE TITLE
Computation of kernels of module homomorphism doesn't finish in due time

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#732]
I try to compute the tangent vector fields to an A_2-singularity using this code:
```julia
using Oscar

R, var = QQ["x","y","z"]
n = length(var)
f = var[1]^2 + var[2]^2 + var[3]^3
Tn = FreeModule(R, n)
Df = jacobi_matrix(f)
On = FreeModule(R, 1)
I, i = sub(On, [On([f])])
OX, p = quo(On, I)
phi = ModuleHomomorphism( Tn, OX, Df )
K = kernel(phi)
```
But this code doesn't seem to finish. I've waited several minutes, which I think is a fair amount of time for this particular small problem. In `Singular` the code would be this: 
```C
ring R = 0,(x,y,z),dp;
poly f = x^2+y^2+z^3;
matrix Df = matrix(jacob(f));
ideal I = f;
module K = modulo(Df, I);
print(K);
```
and it doesn't take the fractions of a second to finish. 

Interestingly, the methods printed by the stacktrace from aborting the Oscar-command don't seem to use any Singular backend.

**Comment by thofma** [comment]
My reply from slack: It is calling the wrong function. The modul homorphisms for free modules over affine algebras are not hooked up with Singular. There is a catchall implementation for kernels of matrices which assumes that the ring is a PID. Obviously this makes no sense here and it will never finish.

**Comment by jankoboehm** [comment]
You can give it a try with the code in the Modules pull request.

**Comment by HechtiDerLachs** [comment]
Alright, thanks for the replies!

@jankoboehm I think this time I can wait for the modules to be officially merged. This example can be done in Singular for now. I was just curious to find out what the Oscar implementation would look like.

Let's get back to this, once the catchall has become obsolete.

**Comment by fingolfin** [comment]
What is the status of this issue?

**Comment by fingolfin** [comment]
@HechtiDerLachs please verify if this is still an issue

**Comment by HechtiDerLachs** [comment]
```julia
R, var = QQ["x","y","z"]
n = length(var)
f = var[1]^2 + var[2]^2 + var[3]^3
Tn = FreeModule(R, n)
Df = jacobi_matrix(f)
On = FreeModule(R, 1)
I, i = sub(On, [On([f])])
OX, p = quo(On, I)
phi = hom( Tn, OX, Df )
K = kernel(phi)
```
now works.
