### ISSUE TITLE
Document how to run parts of the test suite

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#756]
Since @HereAround asked about it...

Apparently `Oscar.test_module()` can be used for that, but it comes with no documentation? Also, when I tried to use it in the past, I run into all kinds of issues, e.g.
- it was broken in some of our packages (IIRC in AA? I think I've submitted a PR back then...);
- it launches a separate Julia, so it doesn't benefit from `using Revise`
- that subjulia doesn't get all arguments; IIRC I had trouble using it when working with Julia projects

But perhaps all of that can be overcome. For starters, though, having at least a minimal comment explaining how it is *supposed* to be used, along with a few examples, would be great. Perhaps the people who wrote it resp. at least know about it, could add some? I am hoping that would be @fieker and @thofma 

An alternative would be to use `ReTest.jl`, which @rfourquet developed explicitly for us back then (see <https://github.com/JuliaTesting/ReTest.jl> and https://github.com/Nemocas/AbstractAlgebra.jl/pull/686).

**Comment by fieker** [comment]
On Mon, Oct 25, 2021 at 01:17:45AM -0700, Max Horn wrote:
> Since @HereAround asked about it...
> 
> Apparently `Oscar.test_module()` can be used for that, but it comes with no documentation? Also, when I tried to use it in the past, I run into all kinds of issues, e.g.
> - it was broken in some of our packages (IIRC in AA? I think I've submitted a PR back then...);
> - it launches a separate Julia, so it doesn't benefit from `using Revise`
You need to call `Oscar.test_module("all", false)` - the false will not
start a new julia

**Comment by lkastner** [comment]
`test_module` has documentation and @lgoettgens just added `test_experimental_module` with docs as well, so I hope this is fine now.
https://docs.oscar-system.org/dev/DeveloperDocumentation/new_developers/
