### ISSUE TITLE
Logical implications for toric varieties

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#771]
Support logical implications, e.g. that every projective toric variety is complete. Or that an affine one is not complete...

**Comment by lkastner** [comment]
In the background this is already happening on the polymake side via its rules, e.g.
```
   rule AFFINE : N_MAXIMAL_CONES{
      $this->AFFINE = ($this->N_MAXIMAL_CONES == 1);
   }
 
   rule DEGENERATE : LINEALITY_DIM {
      $this->DEGENERATE = $this->LINEALITY_DIM > 0;
   }
```
and there are many more like this, but they live with the underlying fan instead.

So for many properties this is not necessary on the Oscar side, as only the access to these properties in polymake needs to be done.

I'd like to avoid setting too many attributes manually, but if something pops up that isn't offered by polymake, please let me know.
