### ISSUE TITLE
Missing constructors for Fans and other polyhedral stuff

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#772]
There is an mismatch between the types accepted by e.g. the `PolyhedralFan` constructor(s), and the types returned by property accessor functions like `rays`. E.g. consider this:
```juliarepl
julia> Rays = [1 0; 0 1; -1 0; 0 -1];

julia> Cones = IncidenceMatrix([[1, 2], [1, 4], [3, 2], [3, 4]]);

julia> PF = PolyhedralFan(Rays, Cones)
A polyhedral fan in ambient dimension 2

julia> rs = rays(PF)
4-element VectorIterator{RayVector{Polymake.Rational}}:
 [1, 0]
 [0, 1]
 [0, -1]
 [-1, 0]

julia> cs = maximal_cones(PF)
Oscar.MaximalConeIterator(A polyhedral fan in ambient dimension 2)

julia> PolyhedralFan(rs, cs)
ERROR: MethodError: no method matching PolyhedralFan(::VectorIterator{RayVector{Polymake.Rational}}, ::Oscar.MaximalConeIterator)
Closest candidates are:
  PolyhedralFan(::Any) at /Users/mhorn/Projekte/OSCAR/Oscar.jl/src/Polytopes/PolyhedralFan/constructors.jl:87
Stacktrace:
 [1] top-level scope
   @ REPL[17]:1
```

So I need one kind of type to describe "rays" to construct a fan, but I get a different type when I ask a fan for its rays and the two are incompatible.

**Comment by YueRen** [comment]
I don't think this warrants its own issue, so I'll just add it to here:  It is a bit inconsistent that `PolyhedralFan` wants the `IncidenceMatrix` last while `PolyhedralComplex` requires it first.

**Comment by YueRen** [comment]
Can this ticket be closed? Everything seems to work flawlessly now:

```
PF = PolyhedralFan([1 0; 0 1; -1 0; 0 -1], IncidenceMatrix([[1, 2, 3], [3, 4, 1]]))
PolyhedralFan(maximal_cones(PF)) # works
PolyhedralFan(rays(PF),lineality_space(PF),IncidenceMatrix([[1,2]])) # works as well
```

**Comment by lkastner** [comment]
I think so. If something is missing, we can just make a new one. Thanks for pinging @YueRen

**Comment by benlorenz** [comment]
On more remark, to get back to the original style of input one can use `ray_indices`:
```
julia> cs = maximal_cones(PF)
4-element SubObjectIterator{Cone{QQFieldElem}}:
 Polyhedral cone in ambient dimension 2
 Polyhedral cone in ambient dimension 2
 Polyhedral cone in ambient dimension 2
 Polyhedral cone in ambient dimension 2

julia> PolyhedralFan(rs, ray_indices(cs))
Polyhedral fan in ambient dimension 3
```
This will convert the cones in the list of maximal cones to an IncidenceMatrix first which encodes the maximal cones in terms of the rays.

(Also note that `cs` now shows as a list of polyhedral cones which should make it more clear)
