### ISSUE TITLE
Implementation of the ring interface

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#790]
I've encountered the following issues when implementing the ring interface: 

 * It seems that `divexact `is a mandatory functionality for Oscar's ring interface and it is tested in the tests. @tthsqe12 explained to me via email that the idea behind this fact is that if one has an *exact domain*, then one should be able to perform the `divexact` operation. Indeed, it depends on what is returned by the `isdomain_type` and `isexact_type` routines what is being tested. I think that all these considerations should also be reflected in the documentation of the interface.
 * The signature of the `deepcopy_internal` routine has changed from `ObjectIdDict` to `IdDict`.
 * It should be better documented which module the functions belong to. For instance, one has to extend `Base.deepcopy_internal`, but `AbstractAlgebra.promote_rule`. I think, it wouldn't hurt, if the qualifiers were consistently used throughout the whole documentation.

**Comment by thofma** [comment]
Thanks @HechtiDerLachs for the feedback.

Regarding the first point, I would also like to make it optional instead of mandatory. I see two options.
1. Just mark it as mandatory and do a `hasmethod` in the `test_Ring_interface`. Then will get `MethodError` whenever it is invoked.
2. Add the fallback
    ```
    divexact(x::T, y::T) where {T <: RingElem} = NotImplementedError("divexact not implemented for $T")
    ```
    Then we have a nice error message whenever `divexact` is invoked, but then we cannot handle the optional aspect in the 
    `test_Ring_interface` using `hasmethod`. We could just catch for `NotImplementedError` instead.

Thoughts, @tthsqe12?

**Comment by tthsqe12** [comment]
I like option 2. Not sure what you getting at with hasmethod in option 1.

**Comment by thofma** [comment]
The `test_Ring_interface` should test the `divexact`method in case it exists. One can use `if hasmethod(divexact, Tuple{T, T})` to check the existent of the method one wants to check.

**Comment by thofma** [comment]
I also prefer option 2. Lots of things won't work if `divexact` is missing, but who cares. A lot of things will still be working and we will get some useful error message.

**Comment by fingolfin** [comment]
@HechtiDerLachs can you please check if anything needs to be done here (in particular we think the fallback error is now there) and then either close this, or formulate what in your view is missing.

**Comment by HechtiDerLachs** [comment]
I think this can be closed then. Thanks to everyone working on this!
