### ISSUE TITLE
HomotopContinuation.jl/OSCAR compatibility issue

### ISSUE THREAD

**Issue by PBrdng** [oscar-system/Oscar.jl#792]
Hello everyone,

since the latest version of OSCAR (0.6.0) it is not possible anymore to have both the most recent versions of OSCAR (0.6.0) and HomotopyContinuation.jl (2.5.6). Either OSCAR-0.6.0+HC-1.4.4 or OSCAR-0.5.2+HC-2.5.6. Any ideas what could be the problem?

**Comment by thofma** [comment]
What does `]add Oscar@0.6.0` (or was it `pin`?) say. It should print the dependency which is holding back the update.

**Comment by PBrdng** [comment]
I just tried with a new environment: Julia simply downgrades HC.jl when I install Oscar.

**Comment by thofma** [comment]
What is the output of the commands I posted?

**Comment by thofma** [comment]
What is the output of the commands I posted?

**Comment by thofma** [comment]
One of the dependencies of HomotopyContinuation.jl (Arblib.jl) requires an old version of `Arb_jll`, which is then holding everything back. There is nothing we can do to fix this in Oscar.
