### ISSUE TITLE
gap_to_julia

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#794]
currently, I think in the generic case: ```function gap_to_julia(x::GapObj; recursive::Bool = true)```

the `Matrix{Any}` case cannot be trached as `IsList` is coming first...

**Comment by fingolfin** [comment]
`IsMatrixObj` stands for the "new type" matrices in GAP; a plain list-of-lists is not an `IsMatrixObj`, it is `IsMatrix` (yes, that's confusing, but we have no alternative w/o breaking backwards compatibility.

In any case, I recommend *not* using `gap_to_julia` if possible, we've been working on changing code away from it. Instead, if you want a `Matrix{Any}`, then write `Matrix{Any}(gapobj)`. Example:
```
julia> gapobj = @gap [[1,2],[3,4]]
GAP: [ [ 1, 2 ], [ 3, 4 ] ]

julia> Matrix{Any}(gapobj)
2×2 Matrix{Any}:
 1  2
 3  4
```

**Comment by fingolfin** [comment]
So this is about the following code in GAP.jl:
```
function gap_to_julia(x::GapObj; recursive::Bool = true)
...
    Wrappers.IsList(x) && return gap_to_julia(Vector{Any}, x; recursive)
    Wrappers.IsMatrixObj(x) && return gap_to_julia(Matrix{Any}, x; recursive)
...
```
The point is: there are "old-style" GAP matrices (which are still predominant), which are indeed lists, and thus the first case deals with them. And then there are "new-style" matrices, which are *not* lists but are `IsMatrixObj`. The second case deals with them.

It is true that this function does never convert an "old-style" GAP matrix into a `Matrix{Any}`. We *could* work on that, but it'd still be a hack, and you could find further corner cases. In the end, it is as I said: it is far preferable to specify the desired output type, and then use a constructor, or pass that type to `gap_to_julia`.
