### ISSUE TITLE
supported Julia versions

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#80]
I think this is a good time to decide which platforms and which Julia versions we currently support.

Here is my suggestion:
- we support Julia 1.3 and we try to get ready a.s.a.p. for the upcoming Julia 1.4
- target platforms: x86_64-linux-gnu, x86_64-apple-darwin14
- CxxWrap 0.9.0
- travis: distribution ubuntu bionic

Some explanations:
- Julia 1.0 is the latest LTS version, but it seems unlikely that GAP (with its garbage collection) can ever be supported
- Julia 1.1 and 1.2 do not receive any back ports any more
- Windows support only through WSL (i.e., this is covered by x86_64-linux-gnu)
- The travis configuration is important for building CxxWrap; otherwise the compiler is too old.

Unless there are immediate objections, this should be posted on
https://github.com/oscar-system/Oscar.jl/blob/master/README.md

Of course, this is a moving target.  So it will require frequent (?) updates.

**Comment by fieker** [comment]
On Wed, Mar 11, 2020 at 02:03:43AM -0700, Michael Joswig wrote:
> I think this is a good time to decide which platforms and which Julia versions we currently support.
I fear that there is no decision:
 we cannot support 1.0 due to infrastructure requirements.
 As much as it hurts to have to drop 1.0, we cannot do this.

 Similarly, CxxWrap requiring a modern c++ compiler means that Debian
 16.04 is out as well. Given that this is LTS until 2024, this is also
 going to hurt people on older equipment.

**Comment by fingolfin** [comment]
I agree. Julia 1.0 is out, my suggestion to backport the GC changes was rejected (and I can totally understand); the primary argument was that Julia 1.5 or 1.6 is likely to be the next LTS (see https://github.com/JuliaLang/julia/pull/34644 for details)

**Comment by ThomasBreuer** [comment]
What is the status of Oscar.jl's  `README.md`, compared to the [OSCAR homepage](https://oscar.computeralgebra.de/)?
Concerning the installation, Oscar.jl is not yet a registered Julia package (thus `Pkg.add("Oscar")` does not work), `Project.toml` states that the Julia versions 1.0 to 1.2 are supported, and no dependencies on GAP.jl and Singular.jl are listed.

**Comment by fieker** [comment]
On Mon, Mar 16, 2020 at 06:29:58AM -0700, ThomasBreuer wrote:
> What is the status of Oscar.jl's  `README.md`, compared to the [OSCAR homepage](https://oscar.computeralgebra.de/)?
> Concerning the installation, Oscar.jl is not yet a registered Julia package (thus `Pkg.add("Oscar")` does not work), `Project.toml` states that the Julia versions 1.0 to 1.2 are supported, and no dependencies on GAP.jl and Singular.jl are listed.
> 
> 
I assumed it was registered already, but aparently not...
So: nothing has changed so far, the README is lying...

Supported Julia versions will only be 1.3 onwards I'm afraid: Gap and
Polymake...

**Comment by wbhart** [comment]
It's not registered because until recently it has not passed its tests for any versions of Julia and there is no working release. For registration you want: README + docs + passing tests + passing CI + OS support (OSX + Linux for us).

**Comment by wbhart** [comment]
Why won't 1.1 and 1.2 be supported? (I understand why 1.0 is not).

**Comment by fieker** [comment]
On Mon, Mar 16, 2020 at 07:02:51AM -0700, wbhart wrote:
> Why won't 1.1 and 1.2 be supported? (I understand why 1.0 is not).
I understood polymake probs, but maybe not.
There is the BIG problem of multiple libflint and the resulting
non-passing of tests

**Comment by ThomasBreuer** [comment]
GAP.jl now requires Julia 1.3, see https://github.com/oscar-system/GAP.jl/pull/309

**Comment by wbhart** [comment]
Oh, I see. Thanks Thomas.

**Comment by fieker** [comment]
There is still the problem with the multiple libflint. Benjamin and I are close to a solution, but it still needs to be deployed. It will, tomake life more interesting, require a Nemo and Polymake release...
(The idea is to add a new package LoadFlint or similar as a dependency to both that will do exactly what the name says: load libflint.so into the process)

**Comment by wbhart** [comment]
Could a solution like @rfourquet's fix for the banners work instead?

**Comment by fieker** [comment]
On Tue, Mar 17, 2020 at 05:24:46AM -0700, wbhart wrote:
> Could a solution like @rfourquet's fix for the banners work instead?
Not really...
libflint needs to be loaded before polymake, so outside of __init__ I
think
But maybe it would work...

**Comment by micjoswig** [comment]
I don't quite understand. 

Sascha added the dependence on Nemo directly into
https://github.com/oscar-system/Polymake.jl/blob/master/src/Polymake.jl

Doesn't this solve the problem?

On 17.03.20 13:34, Claus Fieker wrote:
> On Tue, Mar 17, 2020 at 05:24:46AM -0700, wbhart wrote:
>> Could a solution like @rfourquet's fix for the banners work instead?
> Not really...
> libflint needs to be loaded before polymake, so outside of __init__ I
> think
> But maybe it would work...
>>
>> -- 
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/oscar-system/Oscar.jl/issues/80#issuecomment-600042034
> 
> 

-- 
Prof. Dr. Michael Joswig           <joswig@math.tu-berlin.de>
Technische Universitaet      Institut fuer Mathematik, MA 6-2
Str. des 17. Juni 136                 D-10623 Berlin, Germany
phone +49 (30) 314-75904               fax +49 (30) 314-25047

**Comment by fieker** [comment]
On Tue, Mar 17, 2020 at 06:17:45AM -0700, Michael Joswig wrote:
> I don't quite understand. 
> 
> Sascha added the dependence on Nemo directly into
> https://github.com/oscar-system/Polymake.jl/blob/master/src/Polymake.jl
> 
> Doesn't this solve the problem?

That would probably solve this problem, but longer term, you don't want
to have Nemo in, That what Benjamin and I have been playing with:
basically put a dependency on libflint in, not on Nemo.

**Comment by fieker** [comment]
Only after this is fixed can be proceed to update Oscar and the instructions...

in oscar-systems I've added LoadFlint

**Comment by fingolfin** [comment]
I believe this can be closed now: 
- Oscar.jl now depends on Julia >= 1.3 and we state so in `README.md` and on the homepage. 
- We use CxxWrap 0.9 in all comp (although... they just released 0.10, and we may want to switch to that as it is expected to resolve issues with Julia nightly builds... *sigh* but so far it looks less painful than the 0.8 -> 0.9 migration)
- Regarding Windows support, we only discuss this in terms of using WSL on the website; for Ubuntu we focus on 18.04 "Bionic" (although we also give more complicated instructions for 16.04 "Xenial")
- Travis uses bionic
- the flint related issues are resolved by LoadFlint.jl

OK, so the only thing from @micjoswig original list not quite explicitly addressed is the target platform x86_64-apple-darwin14 (so macOS >= 10.10); I think it's OK for now to not state this explicitly as a requirement anywhere, as few people will be on older systems; and if anybody there complaints, we'll just deal with it as it comes up (i.e. either by saying it's a requirement, or by resolving whatever the reported issue is).

**Comment by fingolfin** [comment]
So we need CxxWrap 0.10.1 for Singular.jl, because there are crashes with 0.9.

In the spirit of this issue, I suggest that we adapt the plan @micjoswig suggested, by replacing CxxWrap 0.9 with 0.10 (resp. 0.10.1) as the CxxWrap version we standardize on. And in the future, if we need a newer one, we will coordinate Polymake.jl and Singular.jl to use the same version.

Just to spell it out (it was discussed orally before): The motivation for standardizing on a single (major) version is that trying to support multiple major CxxWrap versions simultaneously does not provide any visible benefits, but introduces complications and so is not worth the both for us and for our users.

Agreed?

**Comment by fieker** [comment]
On Tue, Apr 21, 2020 at 07:51:58AM -0700, Max Horn wrote:
> So we need CxxWrap 0.10.1 for Singular.jl, because there are crashes with 0.9.
> 
> In the spirit of this issue, I suggest that we adapt the plan @micjoswig suggested, by replacing CxxWrap 0.9 with 0.10 (resp. 0.10.1) as the CxxWrap version we standardize on. And in the future, if we need a newer one, we will coordinate Polymake.jl and Singular.jl to use the same version.
> 
> Just to spell it out (it was discussed orally before): The motivation for standardizing on a single (major) version is that trying to support multiple major CxxWrap versions simultaneously does not provide any visible benefits, but introduces complications and so is not worth the both for us and for our users.
> 
> Agreed?
> 
I'm happy with simplification

**Comment by mohamed-barakat** [comment]
Agreed.

**Comment by fingolfin** [comment]
This is now up to 1.6
