### ISSUE TITLE
zsolve problems on macOS

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#801]
I am running julia 1.6 on Apple silicon using the x86 intel binaries and get the following error:
```julia
sh: line 1: 19725 Abort trap: 6           zsolve -q /var/folders/vw/fn8vgctd5bv0llw3_fnmrdz00000gn/T//poly19690Taaaa0005 > /dev/null 2>&1
   polymake:  WARNING: rule _4ti2.hilbert, _4ti2.integer_points: HILBERT_BASIS_GENERATORS : CONE_AMBIENT_DIM , FACETS | INEQUALITIES failed: couldn't run 4ti2: zsolve -q /var/folders/vw/fn8vgctd5bv0llw3_fnmrdz00000gn/T//poly19690Taaaa0005
```
@benlorenz If you think that we should just wait for native Apple silicon binaries (and if this is the problem), just close this issue.

**Comment by benlorenz** [comment]
Native binaries won't make a difference for that, these were wrong wrappers and this should be fixed (https://github.com/oscar-system/Singular.jl/issues/502 + https://github.com/oscar-system/Singular.jl/pull/506) on the Singular.jl master (and in the next release).

**Comment by thofma** [comment]
Ah, great!
