### ISSUE TITLE
New Oscar release

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#802]
We should make a new Oscar.jl release soon. The current 0.6.0 is quite far behind by now. Dunno if the new release should be 0.6.1 or 0.7.0, feel free to comment with your opinion.

What do we want to have before doing it, though? Some thoughts (feel free to suggest more):
- [x] new Singular.jl release with the fix for https://github.com/oscar-system/Oscar.jl/issues/801 (cc @tthsqe12 )
- [x] new GAP.jl release with a couple fixes and improvements (hopefully tomorrow)
- [x] new Hecke.jl
- [x] merge msolve PR #781
- ... ?

I'd also do it before any big type renaming.

**Comment by ederc** [comment]
If possible I would like to have #781 in it.

**Comment by fingolfin** [comment]
@wdecker just told me that he'd love to make some more documentation improvements. We could postpone the release till Monday then, he said he should be ready by then.

Independently, we've discovered that GAP.jl 0.7 seems to cause the Julia kernel for IJulia / Jupyter to crash, see https://github.com/oscar-system/GAP.jl/issues/760 -- this also causes Oscar to crash, and that's kind of a show stopper for a release. I'll investigate ASAP.

**Comment by fingolfin** [comment]
To be clear the crash in IJulia only happens *sometimes*, making it a tad difficult to debug

**Comment by fingolfin** [comment]
0.7.0 is out
