### ISSUE TITLE
Deal with Set and Dict in doctest

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#809]
From @maxhorn:

So this leaves the following solutions:
1. turn the `jldoctest` into a plain example, i.e., `julia-repl` -- drawback is that it won't be tested this way, and so it'll risk diverging from reality more and more
2. add a hack where we install a custom `show` method for `Dict` in the setup code for the doctests; that custom show could order the keys in certain fixed order; seems quite complicated, though...
3. add a doctest filter to filter out the dict content so it doesn't cause a diff -- we may want to look into that if we persistently get more of these kinds of failures, but for now I think we can just
4. ... adjust the test to the new order. Easy, since `Oscar.build_doc(doctest=:fix)` does it automatically for us. I did that in PR #804.

Of course we may get fluctuating tests at some point (i.e., with real randomness, we may need to go back to one of the other options.

Filter by @lkastner:
```
```jldoctest; filter = r".*"
```

**Comment by fingolfin** [comment]
I don't know if anyone ever tried to do 3?  Also, for 4 I think it is important to note that we agreed that all tests should be for Julia 1.6 for the time being, and `Oscar.build_doc(doctest=:fix)` enforces this now

**Comment by fingolfin** [comment]
Is there anything to be done here these days? I've not had issues with Set or Dict output fluctuating in a long time, probably because we either avoid those in outputs or have ways to deal with them, or maybe they are just more stable these days...

Close it?
