### ISSUE TITLE
Implement simplicial complexes

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#829]
Wrap the corresponding `polymake` type and give input for the refactoring within polymake.

**Comment by micjoswig** [comment]
[(Very incomplete) first draft](https://github.com/oscar-system/Oscar.jl/tree/mj/SimplicialComplexes).

Next steps:
- integral (co-)homology
- minimal non-faces; Stanley-Reisner ideals/rings 

Please give feedback concerning design decisions, and you may request functionality (X-mas is near!).
