### ISSUE TITLE
PolynomialRing fails on print when trivial

### ISSUE THREAD

**Issue by FGlazov** [oscar-system/Oscar.jl#834]
I'm working on a decomposition of a specific polynomial ring into smaller rings, and sometimes some terms inside the decomposition are the trivial ring. Of course, it would be possible to skip creating these terms in the decomposition and sidestep the following issue.

The edge case of a trivial ```PolynomialRing``` seems to mostly work alright, however there is a small issue when attempting to print it out. In particular, the following code executed in the Julia shell causes an error:

```julia
julia> using Oscar
julia> variable_names = Array{String}(undef, 0);
julia> R, x = PolynomialRing(QQ, variable_names);
julia> R
```
The last line causes the following exception:

```
ERROR: BoundsError: attempt to access 0-element Vector{Symbol} at index [0]
Stacktrace:
  [1] getindex
    @ ./array.jl:801 [inlined]
  [2] show(io::IOContext{Base.TTY}, p::FmpqMPolyRing)
    @ Nemo ~/.julia/packages/Nemo/EXnlj/src/flint/fmpq_mpoly.jl:316
  [3] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, x::FmpqMPolyRing)
    @ Base.Multimedia ./multimedia.jl:47
  [4] (::REPL.var"#38#39"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
  [.....]
  [14] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
  [.....]
```
I would either expect an output like "Multivariate Polynomial Ring in  over Rational Field" / "Trivial Multivariate Polynomial Ring" when printing ```R```, or alternatively an error when constructing a ```PolynomialRing``` with an empty list of variables saying that the trivial ring is unsupported.

**Comment by thofma** [comment]
Thanks for the report. @tthsqe12 didn't we just fix this?

**Comment by FGlazov** [comment]
Ah, you're right, I've just updated to 0.7.0 and the constructor for PolynomialRing now outputs ```need at least one indeterminate``` instead of causing problems later on. Thanks :+1:

**Comment by tthsqe12** [comment]
You will be able to use no variables next year.
