### ISSUE TITLE
Internal stackoverflow julia master + MacOS

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#842]
On julia master and MacOS: https://github.com/oscar-system/Oscar.jl/runs/4352506233?check_suite_focus=true#step:5:426
I restarted it, but it is still there.

Have not tried to reproduce locally.

**Comment by thofma** [comment]
Can reproduce it locally, will report upstream.

**Comment by fingolfin** [comment]
Apparently reported at https://github.com/JuliaLang/julia/issues/43254 with proposed fix https://github.com/JuliaLang/julia/pull/43265

**Comment by thofma** [comment]
Fixed upstream.
