### ISSUE TITLE
Rename, document and advertise `@declare_other` and `set_special/get_special`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#843]
We ought to (a) rename `@declare_other` and `set_special/get_special` to something more consistent and sensible, (b) document it and then (c) advertise it to all our devs and beyond

_Originally posted by @fingolfin in https://github.com/oscar-system/Oscar.jl/issues/839#issuecomment-982536876_

**Comment by fingolfin** [comment]
Here is a suggestion:
- `@declare_other` -> `@attributes`
-   ... and instead of adding a member `other::Dict{Symbol,Any}` it adds a dict `_attribute::Dict{Symbol,Any}` with the leading `underscore to avoid clashes with "regular" members
- `set_special` -> `setattribute` or `setattr`
- `get_special` -> `getattribute` or `getattr`
- `hasspecial` -> `hasattribute` or `hasattr`

Thoughts?

**Comment by thofma** [comment]
What is the problem with the underscores? I would suggest  `set_attribute` and `get_attribute`.

**Comment by fingolfin** [comment]
No problem from my POV (although the Julia convention would forego them, but ... *shrug*)

**Comment by fingolfin** [comment]
@thofma Just for completeness, I assume you would also suggest `has_attribute` instead of `hasspecial`, right?

Separately from this, from looking at Julia, perhaps the `set` command should have a trailing `!`, e.g. `set_attribute!`, to parallel `setfield!`, `setindex!`, `setproperty!`

**Comment by fingolfin** [comment]
See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1065 where this is implemented in AA; once that is merged and there is a new AA release, we can make use of it everywhere

**Comment by fingolfin** [comment]
Done
