### ISSUE TITLE
Support symbols resp. strings in `GF` and `FiniteField` the same way as in `PolynomialRing`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#862]
The variables in `PolynomialRing` can be specified either as symbol(s) or as string(s):
```
julia> PolynomialRing(QQ, :x)
(Univariate Polynomial Ring in x over Rational Field, x)

julia> PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)
```

But for `GF` and `FiniteField` that does not seem to be the case:
```
julia> GF(5, 2, "t")
(Finite field of degree 2 over F_5, t)

julia> GF(5, 2, :t)
ERROR: MethodError: no method matching GF(::Int64, ::Int64, ::Symbol)
...
```

That's IMHO confusing. Either they should all support both strings and symbols; or they should all only support one of the two. Since there is already code using string and other code using symbols, I think the only option right now is to add support for symbols to `GF` and `FiniteField`

CC @fieker as he is working on tweaking `GF` anyway

**Comment by fieker** [comment]
Internally only symbols are stored, however the interface is hit and miss.
An old open problem...
Same for power series, q-adics, number fields, free modules....

**Comment by lgoettgens** [comment]
This has been partially resolved by thofma/Hecke.jl#574.
Furthermore, thofma/Hecke.jl#1062 will allow `Char`s as well.
