### ISSUE TITLE
Allow `FiniteField(fmpz(5),2)` and `GF(fmpz(5), 2)` and `GF(fmpz(5), 2, "t")`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#863]
These all work with `5` instead of `fmpz(5)`.

UPDATE: just to clarify, what I am looking for is "symmetry" here in what kind of calls are allowed, not necessarily that they return the "same" thing or even something of the same type. In that vein, these all work:
- `GF(5)`, `FiniteField(5)` -- produce a `Nemo.GaloisField`
- `GF(5,2)`, `FiniteField(5,2)` -- produce a `FqNmodFiniteField`
- `GF(fmpz(5))`, `FiniteField(fmpz(5))` -- produce a `Nemo.GaloisFmpzField`
- `FiniteField(fmpz(5), 2, "t")` -- produces a `FqFiniteField`

But these don't:
- `FiniteField(fmpz(5),2)` and `GF(fmpz(5), 2)` and `GF(fmpz(5), 2, "t")` -- all ought to produce the same field like `FiniteField(fmpz(5), 2, "t")`, so type `FqFiniteField`

**Comment by fieker** [comment]
...but return a different type...

**Comment by fingolfin** [comment]
Of course

**Comment by fingolfin** [comment]
Good news is that `GF(fmpz(5), 2)` and `GF(fmpz(5), 2, "t")` now work!

But not yet `FiniteField(fmpz(5),2)`. I also think that it'd be nice to also allow for symbols instead of strings to match what we allow for polynomial rings. I'll look into writing a PR for Nemo.
