### ISSUE TITLE
Docstring for `FiniteField` describes `FlintFiniteField` instead

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#864]
That's not terribly bad but at least confusing. It comes from this line of code:
```
src/Nemo.jl:470:const FiniteField = FlintFiniteField
```
So perhaps this should be an issue in the Nemo.jl repository instead...?

**Comment by fingolfin** [comment]
Maybe one solution is to rename `FlintFiniteField` to `FiniteField` and just not import `AA.FiniteField` into `Nemo`? Is there any reason not to do that?

**Comment by fieker** [comment]
On Thu, Mar 09, 2023 at 03:19:53AM -0800, Max Horn wrote:
> Maybe one solution is to rename `FlintFiniteField` to `FiniteField` and just not import `AA.FiniteField` into `Nemo`? Is there any reason not to do that?
Remeber Tommy is currently working on "the" finite fields, the generic
version...
So I would not work on that
