### ISSUE TITLE
funny spelling of function names in toric geometry section

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#877]
Function names like isbasepoint_free and  isvery_ample look a bit funny, no?  Is this inttentional?
I am aware of the design rule that there should be no underscore after "is".  But here, either we should make an exception, or we should call it, e.g., "isbasepointfree".

**Comment by fieker** [comment]
On Thu, Dec 09, 2021 at 07:15:26AM -0800, Michael Joswig wrote:
> Function names like isbasepoint_free and  isvery_ample look a bit funny, no?  Is this inttentional?
> 
there is com julia "convention" to not use _ to separate "is". By the
looks of it there is only one (exported) mistake: is_equal_with_morphism

**Comment by micjoswig** [comment]
Yes, I am aware of this convention.  And I like conventions, but there are natural limits, when good conventions become stupid.

On 10.12.21 09:20, Claus Fieker wrote:
> On Thu, Dec 09, 2021 at 07:15:26AM -0800, Michael Joswig wrote:
>> Function names like isbasepoint_free and  isvery_ample look a bit funny, no?  Is this inttentional?
>>
> there is com julia "convention" to not use _ to separate "is". By the
> looks of it there is only one (exported) mistake: is_equal_with_morphism
>> -- 
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/oscar-system/Oscar.jl/issues/877
> 
> 

-- 
Prof. Dr. Michael Joswig           ***@***.***>
Technische Universitaet      Institut fuer Mathematik, MA 6-2
Str. des 17. Juni 136                 D-10623 Berlin, Germany
phone +49 (30) 314-75904               fax +49 (30) 314-25047

**Comment by fingolfin** [comment]
We discussed this during our meeting. The [Julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/) is actually super vague about this:
> functions are lowercase (`maximum`, `convert`) and, when readable, with multiple words squashed together (`isequal`, `haskey`). When necessary, use underscores as word separators. Underscores are also used to indicate a combination of concepts (`remotecall_fetch` as a more efficient implementation of `fetch(remotecall(...))`) or as modifiers.

So we could use e.g. `is_basepoint_free`, or `is_very_ample`. Indeed, even Julia itself uses many such function names *internally*.

We discussed a few possible way to make the above more concrete ("always use underscores" or "use underscores if it is more than 1 word/concept/...). We asked @thofma to please come up with a brief text for the Oscar style guide in the user manual.

**Comment by micjoswig** [comment]
We talked about this.  @fingolfin : if you are OK with this, please close this issue.

**Comment by lkastner** [comment]
As far as I see, there is no solution yet in the https://oscar-system.github.io/Oscar.jl/dev/General/styleguide/ . Correct me if I am wrong.

**Comment by micjoswig** [comment]
> As far as I see, there is no solution yet in the https://oscar-system.github.io/Oscar.jl/dev/General/styleguide/ . Correct me if I am wrong.

Please make (modest) adjustments to the style guide to summarize this discussion.  Then close this issue.
