### ISSUE TITLE
Fix `abelian_group` to accept `fmpz`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#884]
`abelian_group` does not accept fmpz:
```

julia> abelian_group(PcGroup, [1, 23])
<pc group of size 23 with 2 generators>

julia> abelian_group(PcGroup, fmpz[1, 23])
ERROR: MethodError: no method matching abelian_group(::Type{PcGroup}, ::Vector{fmpz})

```

_Originally posted by @simonbrandhorst in https://github.com/oscar-system/Oscar.jl/pull/876#discussion_r767553765_

**Comment by simonbrandhorst** [comment]
This issue is solved. Would you please close @fingolfin ?
