### ISSUE TITLE
Make singular_ring remember the grading?

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#886]
Say I have a graded `MPolyRing` and at some point construct the corresponding `singular_ring`. Then this ring will not know about the grading:
```
julia> R, (x, y) = grade(PolynomialRing(QQ, ["x", "y"])[1], [ 2, 3 ])
(Multivariate Polynomial Ring in x, y over Rational Field graded by 
  x -> [2]
  y -> [3], MPolyElem_dec{fmpq, fmpq_mpoly}[x, y])

julia> singular_ring(R)
Singular Polynomial Ring (QQ),(x,y),(dp(2),C)
```
Is this intended? I'm really no expert, but I would expect the Singular ring to come with a weighted ordering matching the grading (wp(2, 3) in the example) or at least that there is an option for this. I think one can assume that the user specified the grading because they want to work with homogeneous polynomials/ideals/... and then it would be important that Singular knows about the grading to speed up computations or even make certain algorithm accessible.
It's perfectly possible that there are problems with, say, negative weights I haven't thought about...

**Comment by tthsqe12** [comment]
~Probably Singular.jl rings, ideals, and polys are going to get the @ attribute treatment soon or later, at which point you can probably store whatever you want wherever you want it.~

**Comment by joschmitt** [comment]
Okay, thanks.
I think one can already give the singular ring the weighted ordering. My question was more in the direction as of whether there is a reason this is not done yet (other than that nobody thought about it).
Just to make my point: I have a homogeneous ideal in a positively graded polynomial ring and would like to compute a minimal generating set using the functionality in `Singular.libSingular.idMinBase` (which is only wrapped for Oscar ideals over local rings yet...). Even if it were wrapped, it would not work because Singular would not know about the grading of the ring, so in general declare the ideal not to be homogeneous.
I guess you could file this under "feature request".

**Comment by thofma** [comment]
Can you elaborate how `@attributes` (or `@ttributes?`) would help @tthsqe12? `singular_ring` needs to create some internal Singular ring with `wp(2, 3)` in the example above, so the actual object returned must be different?

**Comment by tthsqe12** [comment]
Sure, my initial comment was off the mark. Just create the singular_ring with whatever ordering you want.
