### ISSUE TITLE
To do list: Tropical Geometry in Oscar

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#888]
This is a general to do list for the tropical package in branch yr/tropicalGeometry to keep track of all the tasks:

Major:
-------

- add support for multiplicities (via attributes)
- add support for the tropical projective space (via flag in attributes which primarily affects how information is presented to the user)

Minor:
-------

**Hypersurfaces:**
- improve tropical hypersurfaces: cache tropical polynomial via attributes
- improve tropical hypersurfaces: cache algebraic polynomial (if applicable) via attributes
- improve tropical hypersurfaces: cache initial forms via attribute (mainly as exercise to work towards caching initial ideals of tropical varieties)

**Curves:**
- add constructor: embedded tropical curve from edges + vertices 
- add constructor embedded tropical curve from tropical variety (if dim=1)
- add constructor: abstract tropical curve from edges + vertex weights

**Linear Spaces:**
- add constructor: tropical linear space from Pluecker vector
- add constructor: tropical linear space from tropical / algebraic polynomial (if deg=1)
- add constructor: tropical linear space from tropical / algebraic matrix 
- add constructor: tropical linear space from tropical variety (if deg=1)

**General:**
- improve intersect + stably_intersect: allow as input more than 2 tropical varieties
- add constructor: tropical hypersurface via algebraic polynomial
- improve all tropical: add visualization routines
- improve all tropical: add dual graphs routines
- improve polyhedral fans + complexes: add general support for symmetries (via existing polymake-internal functions)

**Comment by wdecker** [comment]
@YueRen Great! I am looking forward to follow the progress you are going to make! 

With regard to identifiers etc we should coordinate naming with toric geometry and algebraic geometry.

**Comment by YueRen** [comment]
A lot of the things were implemented with https://github.com/oscar-system/Oscar.jl/pull/2832 so I will close this issue.
