### ISSUE TITLE
Missing example in documentation for matrix orderings

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#907]
The documentation lacks an example of how to construct a matrix ordering for a GB computation:
https://oscar-system.github.io/Oscar.jl/dev/CommutativeAlgebra/ideals/#Creating-Matrix-Orderings

I tried passing a Singular matrix ordering to a GB computation, but that was not it. It seems to take symbols only:
```
julia> R, (x1,x2) = PolynomialRing(QQ, "x".*string.(1:2))
(Multivariate Polynomial Ring in x1, x2 over Rational Field, fmpq_mpoly[x1, x2])

julia> I = ideal([x1+x2])
ideal(x1 + x2)

julia> G = groebner_basis(I,ordering=ordering_M([1 0; 0 1]))
ERROR: TypeError: in keyword argument ordering, expected Symbol, got a value of type Singular.sordering
Stacktrace:
 [1] top-level scope
   @ REPL[84]:1`
```

**Comment by fieker** [comment]
On Fri, Dec 17, 2021 at 02:49:29AM -0800, YueRen wrote:
> The documentation lacks an example of how to construct a matrix ordering for a GB computation:
> https://oscar-system.github.io/Oscar.jl/dev/CommutativeAlgebra/ideals/#Creating-Matrix-Orderings
> 
> I tried passing a Singular matrix ordering to a GB computation, but that was not it. It seems to take symbols only:
> ```
> julia> R, (x1,x2) = PolynomialRing(QQ, "x".*string.(1:2))
> (Multivariate Polynomial Ring in x1, x2 over Rational Field, fmpq_mpoly[x1, x2])
> 
> julia> I = ideal([x1+x2])
> ideal(x1 + x2)
> 
> julia> G = groebner_basis(I,ordering=ordering_M([1 0; 0 1]))
> ERROR: TypeError: in keyword argument ordering, expected Symbol, got a value of type Singular.sordering
> Stacktrace:
>  [1] top-level scope
>    @ REPL[84]:1`
> ```
> 
Thats what I meant: we can define them in Oscar - in a way that Singular
could use. However, the interface to singular is at this point,
deficient...

**Comment by joschmitt** [comment]
This has been fixed/became obsolete by the 'new' monomial orderings. The matrix orderings are documented here (with an example): https://docs.oscar-system.org/dev/CommutativeAlgebra/GroebnerBases/orderings/#Matrix-Orderings .
