### ISSUE TITLE
allow coefficient_ring for ideals

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#911]
I suggest to allow `coefficient_ring` for ideals, unless there is a reason that I'm currently not seeing:

```
Kt, t = RationalFunctionField(QQ,"t")
Ktx, (x1,x2,x3,x4,x5) = PolynomialRing(Kt,5)
I = ideal([x1+x2,x2+x3,x3+x4,x4+x5])
coefficient_ring(I[1]) # works
coefficient_ring(I) # does not work
```

As far as I can see, `coefficient_ring` for ideals can be problematic for two reasons, both of which currently cannot occur in Oscar:

- the ideal has no generators
- the generators of the ideal belong to different polynomial rings

**Comment by wdecker** [comment]
@YueRen 
```
julia> base_ring(base_ring(I))
Rational Field

julia> Kt, t = RationalFunctionField(QQ,"t")
(Rational function field over Rational Field, t)

julia> Ktx, (x1,x2,x3,x4,x5) = PolynomialRing(Kt,5)
(Multivariate Polynomial Ring in x1, x2, x3, x4, x5 over Rational function field over Rational Field, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Rat{fmpq}}[x1, x2, x3, x4, x5])

julia> I = ideal([x1+x2,x2+x3,x3+x4,x4+x5])
ideal(x1 + x2, x2 + x3, x3 + x4, x4 + x5)

julia> base_ring(base_ring(I))
Rational function field over Rational Field

julia> coefficient_ring(I[1])
Rational function field over Rational Field
```

**Comment by thofma** [comment]
I don't see the problem of defining
```julia
coefficient_ring(I::MPolyIdeal) = coefficient_ring(base_ring(I))
```
to get the `K` in `K[x]` given an ideal. Is this what you are after? Or are you after the `K[x]` given an ideal?

**Comment by fingolfin** [comment]
@YueRen is what @thofma suggested that what you are after? Then of course we could add it, though then perhaps we should also have it for other types of ideals and carefully document that "the coefficient ring of a polynomial ideal is the coefficient ring of the polynomial ring containing the ideal" or so.

**Comment by YueRen** [comment]
@fingolfin Yes, @thofma suggestion is very reasonable.
