### ISSUE TITLE
vertex-facet incidences for polyhedra (maybe others, too) unnecessarily expensive

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#915]
This refers [this source code](https://github.com/oscar-system/Oscar.jl/blob/master/src/PolyhedralGeometry/Polyhedron/properties.jl).

The following function, to determine the vertex-facet incidences of a polytope, is used internally:
```
function _vertex_incidences(::Val{_face_polyhedron}, P::Polymake.BigObject; f_dim = -1, f_ind::Vector{Int64} = Vector{Int64}())
    return IncidenceMatrix(collect.(Polymake.to_one_based_indexing(Polymake.polytope.faces_of_dim(P, f_dim)[f_ind])))[:, _vertex_indices(P)]
end
```
Yet, `faces_of_dim` is potentially costly.  At any rate, the correct way is to take the `VERTICES_IN_FACETS` property and convert it directly.

It may be possible that, at the time of writing this code polymake's small object type `IncidenceMatrix` was not directly convertible to Julia.  But that is fixed by now.

**Comment by lkastner** [comment]
Are you only talking about facets right now or is there a way to get the lower dim faces too from the `VERTICES_IN_FACETS`?

**Comment by micjoswig** [comment]
That code calls the polymake user function `faces_of_dim`, which requires to compute the entire `HASSE_DIAGRAM`, even if you only ask for the facets; check polymake rule basis.  Moreover, the vertex-facet incidence matrix is needed at any rate.

**Comment by lkastner** [comment]
I understand, but what I was asking is if you want us to make a special case for facets only or is there some other way to bypass `faces_of_dim` entirely?

**Comment by micjoswig** [comment]
We already have a number of versions of `facets`. We need another one, which is just the list of vertex indices (corresponding to one row of VERTICES_IN_FACETS).  We also need the entire vertex-facet matrix as a separate function.  Of course these should share some code.  Also put a mild warning to the `faces` function, just saying that it is expensive.

Of course, there is the usual split between vertices and rays in Oscar, which we do not need in polymake.

**Comment by benlorenz** [comment]
So I think we could do the following things (or at least some of those):
- fix `{vertex,ray}_incidences(facets(c))`, which currently throws an `ArgumentError`. This should return the vertex/ray indices for all facets as an IncidenceMatrix (fetching it directly from VIF).
- maybe add a special case for `faces(c,dim(c)-1)` to use `facets(c)`, or add a special case for that in `_vertex_incidences`
- rename those `*_incidences` to `*_indices` as this would better describe the data
- improve `faces_of_dim` in _polymake_ to use VIF for codim 1 faces

**Comment by micjoswig** [comment]
Sounds good.  I think these two should be prioritized (and these are also the most easy to do):
>     * fix `{vertex,ray}_incidences(facets(c))`, which currently throws an `ArgumentError`. This should return the vertex/ray indices for all facets as an IncidenceMatrix (fetching it directly from VIF).
>     * improve `faces_of_dim` in _polymake_ to use VIF for codim 1 faces
