### ISSUE TITLE
What to do for object clashes?

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#922]
This discussion already popped up a while ago and is also reflected in #769 as an example. The problem is the following: Some mathematical objects appear in different corners of Oscar, so who gets this object? Does anyone?

For example: Many mathematical disciplines know a `projective_space`, for example algebraic geometry and toric geometry. These lead to two different descriptions. So what should happen if someone writes `projective_space(n)`? Currently this is solved very awkwardly with `toric_projective_space`.

Another new example is `torus(...)`.

I don't think introducing a super object capturing all the aspects will solve this. Maybe a module solution could work, as I think that we can at least expect the user to know what kind of mathematics they want to do. Nevertheless if you arrive at another solution, even the superobject, I will happy that you arrived at a solution.

**Comment by micjoswig** [comment]
I see essentially two ways of resolving this.  Either such a function gets a traits class as an optional argument, similar to, e.g.,
```
facets(as::Type{T} = AffineHalfspace, P::Polyhedron)
```
Or we introduce modules for separation:
```
SimplicialComplexes.torus()
AlgebraicGroups.torus(QQ, 3)
```
Don't be fooled here that you could tell these apart by their signatures. First, there are other examples (like the projective spaces that Lars mentioned).  Second, this would be totally intuitive for the user. I would consider this very bad style.

I am slightly leaning toward the modules.  To me this looks like the cleaner solution.

**Comment by micjoswig** [comment]
Of course, there is a third solution:
```
torus_as_simplicial_complex()
torus_as_algebraic_group(QQ, 3)
```
But I don't see any advantage here.  So that would be my least favored.

**Comment by fieker** [comment]
On Wed, Dec 22, 2021 at 04:49:30AM -0800, Michael Joswig wrote:
> I see essentially two ways of resolving this.  Either such a function gets a traits class as an optional argument, similar to, e.g.,
> ```
> facets(as::Type{T} = AffineHalfspace, P::Polyhedron)
> ```
We're using this version in several places already, julia does it e.g.
for ceil, round, floor, ...
ceil(x) has the same type as x
ceil(Int, x) yields an Int
...
We're using this e.g. for cylotomic_field...

Here, as above, we do not have any decent module to associate with.

> Or we introduce modules for separation:
> ```
> SimplicialComplexes.torus()
> AlgebraicGroups.torus(QQ, 3)
> ```
For BinomialIdeals this is happening. Supposed to be happening or so.

> Don't be fooled here that you could tell these apart by their signatures. First, there are other examples (like the projective spaces that Lars mentioned).  Second, this would be totally intuitive for the user. I would consider this very bad style.
> 
> I am slightly leaning toward the modules.  To me this looks like the cleaner solution.
> 
As I said, you don't have proper modules in all cases that would make
sense, so for the time being I'd say use modules where this makes sense,
use additional types in other situations and in general, maybe, do both.
In this example, as a user I might be able to do 
  ?torus
and get information about the different possibilities. I won't be able
to guess the modules.

The actual signature btw. would be
 torus(::Type{AffineHalfspace}, P::Polyhedron)

then the dispatch on
 torus(AffineHalfspace, P)
can be done automatically. And methods(torus) would help, e.g.

julia> methods(cyclotomic_field)
# 4 methods for generic function "cyclotomic_field":
[1] cyclotomic_field(::Type{ClassField}, n::Integer) in Hecke at
/home/fieker/.julia/dev/Hecke/src/RCF/cyclo.jl:488
[2] cyclotomic_field(::Type{NonSimpleNumField}, n::Int64; cached) in
Hecke at
/home/fieker/.julia/dev/Hecke/src/NumField/NfAbs/NonSimple.jl:1039
[3] cyclotomic_field(::Type{ClassField}, n::fmpz) in Hecke at
/home/fieker/.julia/dev/Hecke/src/RCF/cyclo.jl:492
[4] cyclotomic_field(n::Int64; cached) in Hecke at
/home/fieker/.julia/dev/Hecke/src/NumField/NfAbs/NfAbs.jl:90

We were slightly too lazy, but even ? is then partially helpful:

help?> cyclotomic_field
search: cyclotomic_field cyclotomic_extension

  cyclotomic_field(n::Int) -> AnticNumberField, nf_elem

  The cyclotomic field defined by the n-th cyclotomic polynomial.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> cyclotomic_field(10)
  (Cyclotomic field of order 10, z_10)

  ────────────────────────────────────────────────────────────────────────────

  cyclotomic_field(::Type{ClassField}, n::Int) -> ClassField

  The n-th cyclotomic field as a ray_class_field

**Comment by micjoswig** [comment]
OK.  Looks like a decision to me.

@fingolfin @thofma : please complain now, or we will proceed with type traits.

**Comment by thofma** [comment]
No complaint from my side. I am happy with the type traits and/or the module prefix in case it makes sense.
