### ISSUE TITLE
Computation of kernels for Algebra Homomorphisms of graded rings

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#926]
The following code fails, probably due to a faulty translation between the `Oscar` and the `Singular` side:
```julia
R, (x,y,z) = QQ["x", "y", "z"]
R_ext, _ = PolynomialRing(R, ["u", "v", "w"])
S, (u,v,w) = grade(R_ext, [1,1,1])
f = AlgebraHomomorphism(S, S, [u*v^2, u*w^2, u*v*w])
K = kernel(f)
```
Interestingly, if one writes `[u^2, v^2, w^2]` in the map definition, it nevertheless outputs the correct kernel.

**Comment by thofma** [comment]
Yes, I think this is also #975 and #976 :-(

**Comment by fingolfin** [comment]
`AlgebraHomomorphism` is no more, but if I use `hom` this seems to work now?
```
julia> f = hom(S, S, [u*v^2, u*w^2, u*v*w])
Map with following data
Domain:
=======
S
Codomain:
=========
S

julia> kernel(f)
ideal(u*v - w^2)
```
