### ISSUE TITLE
Promotion for finite fields

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#960]
This has been an issue at some point before, but the solution finally didn't make its way into Oscar/AbstractAlgebra:

Could someone please add the lines 
```
  AbstractAlgebra.promote_rule(::Type{gfp_mpoly}, ::Type{fmpz}) = gfp_mpoly
  AbstractAlgebra.promote_rule(::Type{gfp_elem}, ::Type{fmpz}) = gfp_elem
``` 
in the appropriate places?

**Comment by HechtiDerLachs** [comment]
This had been part of some PR of mine before, with the idea of the code to be moved eventually. But then it ended up in the tests and never became part of Oscar.

**Comment by HechtiDerLachs** [comment]
Also this line seems to be required:
```
AbstractAlgebra.promote_rule(::Type{gfp_elem}, ::Type{AbstractAlgebra.Generic.Frac{gfp_mpoly}}) = AbstractAlgebra.Generic.Frac{gfp_mpoly}
```

**Comment by simonbrandhorst** [comment]
Seems like 
https://github.com/Nemocas/AbstractAlgebra.jl
is the appropriate place for this issue.

**Comment by fingolfin** [comment]
Indeed. @HechtiDerLachs you should open an issue there -- or even better, a PR.
