### ISSUE TITLE
WARNING: import of Hecke.example into Oscar conflicts with an existing identifier; ignored.

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#97]
This warning is shown when precompiling a freshly installed Oscar.jl 0.3.0:
```
WARNING: import of Hecke.example into Oscar conflicts with an existing identifier; ignored.
```

**Comment by fingolfin** [comment]
Hmm, in another instance, I saw this instead (not sure what triggered the difference, and no time/energy/interest in figuring it our right now):
```
WARNING: could not import Hecke.number_of_small_groups into Oscar
WARNING: could not import Hecke.small_groups_limit into Oscar
```
Of course those functions should perhaps also eventually be replaced by code calling into GAP.jl resp. the Oscar Groups API, but that's another issue.

**Comment by fieker** [comment]
On Mon, Apr 27, 2020 at 01:56:07PM -0700, Max Horn wrote:
> Hmm, in another instance, I saw this instead (not sure what triggered the difference, and no time/energy/interest in figuring it our right now):
> ```
> WARNING: could not import Hecke.number_of_small_groups into Oscar
> WARNING: could not import Hecke.small_groups_limit into Oscar
> ```
> Of course those functions should perhaps also eventually be replaced by code calling into GAP.jl resp. the Oscar Groups API, but that's another issue.
> 
I'll look into this. hopefully the example prob has been dealt with by
updating Hecke to 0.8.1 which happend about the time you mentioned it.
I check, but I suspect the number_of_small_groups does not exist any
more, hence it cannot be imported. One of the ci/ several repos and
julia quirks problems:
 - you can, in Hecke or elsewhere export non-existing functions (export
   blah)
 - you cannot import (automatically) such functions as they don't exist. 
   Oscar goes through a list of all exported symbols and re-exports
   them, this fails...

**Comment by fieker** [comment]
On Mon, Apr 27, 2020 at 01:56:07PM -0700, Max Horn wrote:
> Hmm, in another instance, I saw this instead (not sure what triggered the difference, and no time/energy/interest in figuring it our right now):
> ```
> WARNING: could not import Hecke.number_of_small_groups into Oscar
> WARNING: could not import Hecke.small_groups_limit into Oscar
> ```
> Of course those functions should perhaps also eventually be replaced by code calling into GAP.jl resp. the Oscar Groups API, but that's another issue.

Someone was writing an interface to Gaps small groups, but got
sidetracked. The declarations and export statements are there, the code
not...
