### ISSUE TITLE
Singular ring coercion riddle

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#975]
@tthsqe12 
```julia
julia> A, t = PolynomialRing(QQ, ["t"])
(Multivariate Polynomial Ring in t over Rational Field, fmpq_mpoly[t])

julia> R, (x,y,z) = PolynomialRing(A, ["x", "y", "z"])
(Multivariate Polynomial Ring in x, y, z over Multivariate Polynomial Ring in t over Rational Field, AbstractAlgebra.Generic.MPoly{fmpq_mpoly}[x, y, z])

julia> I = ideal(R, [x]); x in I
ERROR: TypeError: in typeassert, expected fmpq_mpoly, got a value of type Singular.spoly{Singular.n_Q}
Stacktrace:
 [1] Ring
   @ ~/.julia/dev/Oscar/src/Rings/mpoly.jl:723 [inlined]
 [2] (::AbstractAlgebra.Generic.MPolyRing{fmpq_mpoly})(f::Singular.spoly{Singular.n_RingElem{Singular.spoly{Singular.n_Q}}})
```
(Because of caching(?) the command `x in I` will succeed when called again. One has to recreate `I` to encounter the error.)

I think the problem is that since `A`, the base ring of `R`, is an `MPolyRing`, we recurse
https://github.com/oscar-system/Oscar.jl/blob/af90aae4743389fa07914ff3ca4717b744547e79/src/Rings/mpoly.jl#L649
which leads to hickups in the coercion.

1. Should we just disallow this? Does it even make sense to create `Singular.PolynomialRing(singular_ring(A))` in this case? This means wrapping an `spoly` again in an `n_RingElem`?! Do you think it makes more sense to just do `Singular.PolynomialRing(A)`? Do we need a `singular_coefficient_ring`? 😢 
2. Is there a way to fix this without 1.?

**Comment by tthsqe12** [comment]
We need a singular_coefficient_ring function since there is no point (and it is unexpected) to recursively translate the coefficient ring.

**Comment by fingolfin** [comment]
This seems to work now. Close it? Or is something still to be done (what?)
