### ISSUE TITLE
missing `ordering` function for graded rings

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#989]
This is to bring the Oscar-people's attention to the following issue: 

https://github.com/Nemocas/AbstractAlgebra.jl/issues/1105

It was discussed there that this might be more of a problem in Oscar.

**Comment by fieker** [comment]
Pure Oscar. The intrduction of orderings as 1st level Objetcs is not finished yet, so this is causing problems in many places. The person working on it is/was sick. The changes are not complete, and this is simply a case of a missing function. The easier approach is to just add them as all the other trivial missing functions.
