### ISSUE TITLE
Polynomial build complex does not throw out of bounds error

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#991]
```
julia> R, (x, y) = PolynomialRing(QQ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Rational Field, fmpq_mpoly[x, y])

julia> B = MPolyBuildCtx(R)
Builder for an element of Multivariate Polynomial Ring in x, y over Rational Field

julia> for i = 1:5 push_term!(B, QQ(i), [i]) end

julia> finish(B::MPolyBuildCtx)
5*x^5*y^4294967296 + 4*x^4*y^4294967296 + 3*x^3*y^4294967296 + 2*x^2*y^4559012384 + x*y^4294967296
```

**Comment by tthsqe12** [comment]
This is not an out of bounds error per say, it is the fact that the vector `[i]` is expected to have length 2.

**Comment by tthsqe12** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1106 However, since it is a ! function, isn't it supposed to skip the input sanitisation?

**Comment by thofma** [comment]
No, it just means that we mutate the first argument.

**Comment by tthsqe12** [comment]
alright, our code is getting more and more unpredictable branches to error messages.

**Comment by fieker** [comment]
On Tue, Jan 18, 2022 at 07:40:15AM -0800, dan wrote:
> alright, our code is getting more and more unpredictable branches to error messages.
> 
I am confused. What is more and more unpredictable here?

**Comment by tthsqe12** [comment]
well, I am not sure if the branches are getting predicted, but I can be sure that there is a lot more input that could be sanitized. For example, is set_exponent_vector! also supposed to sanitize?

**Comment by fingolfin** [comment]
If `set_exponent_vector!` is a public function: yes it should sanitize.

That said, in the AA code it says this:
```julia
# set the exponent vector of the underlying polynomial (used internally)
function set_exponent_vector!(a::AbsMSeries, i::Int64, v::Vector{Int64})
```
Fine by me. But main problem is that it is hard to guess if a given function is supposed tobe "internal" or "for public consumption". My personal rule is: unsafe, internal function have `_` as prefix, so I would call this function `_set_exponent_vector!`. Perhaps this is something we should consider as a general rule? Of course I am also open to other ways to do this.

**Comment by fieker** [comment]
On Wed, Jan 19, 2022 at 09:50:07AM -0800, Max Horn wrote:
Use the @inbounds ... mechanism?

**Comment by tthsqe12** [comment]
This issue is not exactly one of inbounds/outofbounds. Here we just want the length of the supplied exponent vector to match the number of variables. Not sure it abusing the @inbounds macro is a good idea. Or, maybe, we can create our own macro ~@we_know_what_we_are_doing~ @weknow_what_we_are_doing and use it in the internal code?

**Comment by tthsqe12** [comment]
I think we do need two separate functions `_set_exponent_vector!` and `set_exponent_vector!` since `@weknow_what_we_are_doing` would be useless unless it got inlined (like @inbounds).
