### ISSUE TITLE
Which properties should be cached where?

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#997]
The toric varieties have several properties computed by polymake: projective, smooth, fano, Gorenstein, simplicial, complete, etc. These are also cached by polymake, but now they are additionally cached by the attribute system. Do we want this? Sure, these are light-weight, but there will be larger properties in the future, so this is a general question. I can see the advantage, that one can the just use `has_attribute` and does not have to go via polymakes equivalent, but maybe there would be a way to redirect?

**Comment by HereAround** [comment]
Question in return - how can I know which properties `Polymake` caches? Is there a complete list? Are changes anticipated?

As of now, I would indeed prefer a uniform attribute caching for all properties/attributes in `OSCAR`. (The only exception is `isnormal` at this point, as this always return `true`).

**Comment by benlorenz** [comment]
Basically all polymake properties are cached, i.e. everything that is accessed like `pm_object(tv).SOMETHING` will be stored in the polymake object inside `tv`. Whether it already exists can be tested with `Polymake.exists(pm_object(tv), "SOMETHING")`.

**Comment by HereAround** [comment]
Thank you for elaborating. I need to think about this. (And hear what you all think about this, of course.)

I am torn between the following:
1. It is inefficient to cache multiple times/in different places. (Probably not too bad for boolean attributes, but for properties such as the mapping from Weil divisors to divisor classes, this is different.)
2. A uniform `OSCAR`-code which makes it clear/obvious what is being cached and how. (From the `OSCAR` code, the caching in `Polymake` is somewhat hidden.)

I would expect that thus far this double-caching is relatively cheap. This is why I am currently leaning towards 2.

**Comment by lkastner** [comment]
At some point I will discuss writing a wrapper to avoid double caching, but this issue can be closed now.
